import sys
sys.path.insert(0, ".")
from layer3_write import append_results


def L(lead_id, domain, business_name, primary, confidence, summary,
      conv, cart, eng, followup, ci, ev_conv, ev_cart, ev_eng, ev_followup,
      open_gap_count, secondary=None, disqualifier=None):
    return (lead_id, domain, business_name, primary, secondary, confidence, summary,
            conv, cart, eng, followup, ci, ev_conv, ev_cart, ev_eng, ev_followup,
            open_gap_count, disqualifier)


RESULTS = [
L(1354, "telefonsounds.ai", "Telefonsounds", primary="Cart Recovery Opportunity", secondary="Follow-up Opportunity", confidence="low",
  summary="AI phone-announcement digital-product store with reviews already live but no ESP.",
  conv=40, cart=55, eng=40, followup=45, ci=30,
  ev_conv="has_cart=True, no ESP", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="reviews present, active promo code", ev_followup="no email capture form detected",
  open_gap_count=2),
L(1355, "ummaexperiencia.com", "Ummaexperiencia", primary="Cart Recovery Opportunity", secondary="Customer Engagement Opportunity", confidence="low",
  summary="Photography/portfolio site with an attached shop, product_count_visible=4, no ESP or capture form.",
  conv=35, cart=50, eng=25, followup=30, ci=25,
  ev_conv="has_cart=True, no ESP; page is mostly a gallery/portfolio theme", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="no chat/reviews/popup", ev_followup="no email capture form detected",
  open_gap_count=2),
L(1356, "monnidamour.fr", "Monnidamour", primary="Not a Good Fit", confidence="medium",
  summary="French hotel-amenities products store already running Omnisend ESP with both email and contact forms.",
  conv=25, cart=20, eng=25, followup=20, ci=30,
  ev_conv="Omnisend ESP already live", ev_cart="has_esp_tag=omnisend",
  ev_eng="no chat/reviews", ev_followup="email capture and ESP already wired together",
  open_gap_count=1, disqualifier="already has ESP in place"),
L(1357, "itherstel.nl", "Itherstel", primary="Follow-up Opportunity", secondary="Cart Recovery Opportunity", confidence="low",
  summary="Dutch computer-repair and gaming-PC shop, product_count_visible=0 suggests thin page fetched, no ESP.",
  conv=40, cart=45, eng=30, followup=45, ci=30,
  ev_conv="has_cart=True but this is primarily a repair services business with a shop", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="no chat/reviews/popup", ev_followup="no email capture form detected",
  open_gap_count=2),
L(1358, "leleklink.hu", "Leleklink", primary="Insufficient Data", confidence="high",
  summary="Page served an obfuscated JS-based verification wall — no real content retrievable.",
  conv=50, cart=50, eng=50, followup=50, ci=50,
  ev_conv="bot-check/obfuscated verification page", ev_cart="has_cart=False (undetermined)",
  ev_eng="no signals extractable — verification wall", ev_followup="no signals extractable — verification wall",
  open_gap_count=0, disqualifier="anti-bot verification page — cannot assess real content"),
L(1359, "cambridgexamschool.com", "Cambridgexamschool", primary="Follow-up Opportunity", confidence="low",
  summary="Spanish Cambridge exam-prep school with WhatsApp chat but no lead-capture form or ESP.",
  conv=40, cart=20, eng=40, followup=50, ci=30,
  ev_conv="platform=unknown, has_cart=False", ev_cart="has_cart=False",
  ev_eng="WhatsApp chat already present", ev_followup="has_email_form=True but no ESP automation for enrollment leads",
  open_gap_count=1),
L(1360, "pjamlaw.co.uk", "Pjamlaw", primary="Follow-up Opportunity", confidence="low",
  summary="UK law firm with no lead-capture form or ESP.",
  conv=40, cart=20, eng=30, followup=50, ci=30,
  ev_conv="has_cart=True likely false-positive for a law firm", ev_cart="product_count_visible=0",
  ev_eng="generic popup only, cta_count_above_fold=2", ev_followup="no email or contact form detected",
  open_gap_count=1),
L(1361, "findhouzez.com", "Findhouzez", primary="Follow-up Opportunity", confidence="low",
  summary="Real-estate listings platform with an email form but no ESP.",
  conv=40, cart=20, eng=30, followup=50, ci=30,
  ev_conv="has_cart=False — listings platform, not e-commerce", ev_cart="has_cart=False",
  ev_eng="generic popup only, cta_count_above_fold=2", ev_followup="has_email_form=True but no ESP automation",
  open_gap_count=1),
L(1362, "tmssmedicalcenter.com", "Tmssmedicalcenter", primary="Insufficient Data", confidence="high",
  summary="Page served an obfuscated JS-based verification wall — no real content retrievable.",
  conv=50, cart=50, eng=50, followup=50, ci=50,
  ev_conv="bot-check/obfuscated verification page", ev_cart="has_cart=False (undetermined)",
  ev_eng="no signals extractable — verification wall", ev_followup="no signals extractable — verification wall",
  open_gap_count=0, disqualifier="anti-bot verification page — cannot assess real content"),
L(1363, "rushbd.com", "Rushbd", primary="Cart Recovery Opportunity", secondary="Follow-up Opportunity", confidence="low",
  summary="Bangladeshi WooCommerce store, product_count_visible=1 suggests thin catalog, no ESP.",
  conv=35, cart=50, eng=30, followup=45, ci=25,
  ev_conv="has_cart=True, no ESP", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="no chat/reviews/popup, cta_count_above_fold=6", ev_followup="has_email_form=True but no ESP automation",
  open_gap_count=2),
L(1364, "giftstudio.ro", "Giftstudio", primary="Insufficient Data", confidence="high",
  summary="Page served an obfuscated JS-based verification wall — no real content retrievable.",
  conv=50, cart=50, eng=50, followup=50, ci=50,
  ev_conv="bot-check/obfuscated verification page", ev_cart="has_cart=False (undetermined)",
  ev_eng="no signals extractable — verification wall", ev_followup="no signals extractable — verification wall",
  open_gap_count=0, disqualifier="anti-bot verification page — cannot assess real content"),
L(1365, "luxuryvacationrent.com", "Luxuryvacationrent", primary="Follow-up Opportunity", confidence="low",
  summary="Vacation-rental properties business (Maui, Bass Lake) with no lead-capture form or ESP.",
  conv=40, cart=25, eng=30, followup=50, ci=30,
  ev_conv="has_cart=True likely false-positive for a vacation-rental booking business", ev_cart="product_count_visible=3 (property listings, not physical cart)",
  ev_eng="no chat/reviews/popup", ev_followup="no email or contact form detected for high-value rental inquiries",
  open_gap_count=1),
L(1366, "kbslrecords.com", "Kbslrecords", primary="Insufficient Data", confidence="low",
  summary="Domain resolved but page_text is empty and platform is unknown.",
  conv=50, cart=50, eng=50, followup=50, ci=50,
  ev_conv="page_text empty", ev_cart="has_cart=False (undetermined)",
  ev_eng="no signals extractable", ev_followup="no signals extractable",
  open_gap_count=0, disqualifier="empty/undetermined signals — cannot assess"),
L(1367, "ilysh.com", "Ilysh", primary="Insufficient Data", confidence="high",
  summary="Gateway/upstream connection-timeout error — no content retrievable.",
  conv=50, cart=50, eng=50, followup=50, ci=50,
  ev_conv="upstream connection timeout", ev_cart="has_cart=False (undetermined)",
  ev_eng="no signals extractable — gateway error", ev_followup="no signals extractable — gateway error",
  open_gap_count=0, disqualifier="upstream gateway error — cannot assess"),
L(1368, "ashanti.com.pl", "Ashanti", primary="Follow-up Opportunity", confidence="low",
  summary="Polish psychology/sexology therapy practice with reviews already live but no lead-capture form or ESP.",
  conv=40, cart=20, eng=40, followup=50, ci=30,
  ev_conv="has_cart=False — booking-driven therapy practice", ev_cart="has_cart=False",
  ev_eng="reviews present", ev_followup="no email or contact form detected for session-booking leads",
  open_gap_count=1),
L(1369, "motosikletkiralama.com", "Motosikletkiralama", primary="Insufficient Data", confidence="high",
  summary="Page served an obfuscated JS-based verification wall — no real content retrievable.",
  conv=50, cart=50, eng=50, followup=50, ci=50,
  ev_conv="bot-check/obfuscated verification page", ev_cart="has_cart=False (undetermined)",
  ev_eng="no signals extractable — verification wall", ev_followup="no signals extractable — verification wall",
  open_gap_count=0, disqualifier="anti-bot verification page — cannot assess real content"),
L(1370, "viridigital.co.za", "Viridigital", primary="Follow-up Opportunity", confidence="medium",
  summary="South African printing/branding B2B service with WhatsApp chat and booking already live, but no ESP.",
  conv=45, cart=20, eng=50, followup=55, ci=35,
  ev_conv="has_cart=False — B2B print/branding services", ev_cart="has_cart=False",
  ev_eng="WhatsApp chat and booking already present, cta_count_above_fold=1", ev_followup="has_email_form=True but no ESP automation",
  open_gap_count=1),
L(1371, "ledini.com.pl", "Ledini", primary="Cart Recovery Opportunity", secondary="Follow-up Opportunity", confidence="low",
  summary="Polish LED-neon-signs WooCommerce store, product_count_visible=0 suggests thin page fetched.",
  conv=40, cart=55, eng=30, followup=45, ci=30,
  ev_conv="has_cart=True, no ESP", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="generic popup only, no chat/reviews", ev_followup="has_email_form=True but no ESP automation",
  open_gap_count=2),
L(1372, "updaty.be", "Updaty", primary="Follow-up Opportunity", confidence="low",
  summary="Belgian web/app-development B2B agency with no lead-capture form or ESP.",
  conv=35, cart=20, eng=30, followup=45, ci=25,
  ev_conv="has_cart=True likely false-positive for a B2B dev agency", ev_cart="product_count_visible=0",
  ev_eng="no chat/reviews/popup", ev_followup="no email or contact form detected",
  open_gap_count=1),
L(1373, "carewithusagency.com", "Carewithusagency", primary="Insufficient Data", confidence="low",
  summary="Domain resolved but page_text is empty and platform is unknown.",
  conv=50, cart=50, eng=50, followup=50, ci=50,
  ev_conv="page_text empty", ev_cart="has_cart=False (undetermined)",
  ev_eng="no signals extractable", ev_followup="no signals extractable",
  open_gap_count=0, disqualifier="empty/undetermined signals — cannot assess"),
L(1374, "jbarrowfirewood.co.uk", "Jbarrowfirewood", primary="Cart Recovery Opportunity", secondary="Customer Engagement Opportunity", confidence="medium",
  summary="UK small firewood-delivery WooCommerce store (4 products) with no capture form or ESP.",
  conv=40, cart=60, eng=35, followup=35, ci=30,
  ev_conv="has_cart=True, no ESP", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="generic popup only, no chat/reviews, cta_count_above_fold=3", ev_followup="no email capture form detected",
  open_gap_count=2),
L(1375, "woww.ee", "Woww", primary="Not a Good Fit", confidence="medium",
  summary="Estonian travel-deals site already running Klaviyo ESP.",
  conv=25, cart=20, eng=25, followup=20, ci=30,
  ev_conv="has_cart=True likely false-positive for a travel-packages business", ev_cart="has_esp_tag=klaviyo",
  ev_eng="no chat/reviews", ev_followup="email capture and Klaviyo ESP already wired together",
  open_gap_count=1, disqualifier="already has ESP in place"),
L(1376, "legendsdata.com", "Legendsdata", primary="Insufficient Data", confidence="low",
  summary="Domain resolved but page_text is empty and platform is unknown.",
  conv=50, cart=50, eng=50, followup=50, ci=50,
  ev_conv="page_text empty", ev_cart="has_cart=False (undetermined)",
  ev_eng="no signals extractable", ev_followup="no signals extractable",
  open_gap_count=0, disqualifier="empty/undetermined signals — cannot assess"),
L(1377, "bmw-elitemotors.rs", "Bmw-Elitemotors", primary="Follow-up Opportunity", confidence="low",
  summary="Serbian BMW/MINI dealer with no lead-capture form or ESP.",
  conv=40, cart=20, eng=30, followup=50, ci=30,
  ev_conv="has_cart=True likely false-positive for an auto dealership", ev_cart="product_count_visible=0",
  ev_eng="no chat/reviews/popup despite test-drive/service booking CTAs", ev_followup="no email or contact form detected",
  open_gap_count=1),
L(1378, "perfectcircle.nz", "Perfectcircle", primary="Cart Recovery Opportunity", secondary="Customer Engagement Opportunity", confidence="low",
  summary="New Zealand B2B auto-parts supplier WooCommerce store (2 products) with no ESP.",
  conv=35, cart=50, eng=25, followup=30, ci=25,
  ev_conv="has_cart=True, no ESP", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="no chat/reviews/popup", ev_followup="no email capture form detected",
  open_gap_count=2),
L(1379, "dlpconnex.co.uk", "Dlpconnex", primary="Follow-up Opportunity", confidence="medium",
  summary="UK telecom/WiFi-repeater B2B solutions provider with both email and contact forms but no ESP.",
  conv=45, cart=20, eng=35, followup=55, ci=35,
  ev_conv="has_cart=True likely false-positive for a B2B telecom-solutions business", ev_cart="product_count_visible=0",
  ev_eng="cta_count_above_fold=4", ev_followup="has_email_form=True and has_contact_form=True but no ESP automation",
  open_gap_count=1),
L(1381, "conchwindows.com", "Conchwindows", primary="Follow-up Opportunity", confidence="medium",
  summary="US commercial/residential window manufacturer B2B with both email and contact forms but no ESP.",
  conv=45, cart=20, eng=35, followup=55, ci=35,
  ev_conv="has_cart=True likely false-positive for a B2B window manufacturer", ev_cart="product_count_visible=0",
  ev_eng="no chat/reviews/popup", ev_followup="has_email_form=True and has_contact_form=True but no ESP automation",
  open_gap_count=1),
L(1382, "miereamilena.ro", "Miereamilena", primary="Cart Recovery Opportunity", secondary="Customer Engagement Opportunity", confidence="low",
  summary="Romanian honey WooCommerce store (5 products) with no capture form or ESP.",
  conv=35, cart=50, eng=25, followup=30, ci=25,
  ev_conv="has_cart=True, no ESP", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="no chat/reviews/popup", ev_followup="no email capture form detected",
  open_gap_count=2),
L(1383, "estelaalba.com", "Estelaalba", primary="Cart Recovery Opportunity", secondary="Follow-up Opportunity", confidence="low",
  summary="Spanish artist's shop and services site (12+ years experience), product_count_visible=0 suggests thin page fetched, no ESP.",
  conv=35, cart=50, eng=30, followup=40, ci=25,
  ev_conv="has_cart=True, no ESP", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="generic popup only, no chat/reviews", ev_followup="no email capture form detected",
  open_gap_count=2),
L(1384, "vanlithvoorzetramen.nl", "Vanlithvoorzetramen", primary="Cart Recovery Opportunity", secondary="Follow-up Opportunity", confidence="medium",
  summary="Dutch secondary-glazing/window-inserts WooCommerce store (3 products) with both email and contact forms but no ESP.",
  conv=45, cart=60, eng=30, followup=55, ci=35,
  ev_conv="has_cart=True, no ESP", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="no chat/reviews/popup", ev_followup="has_email_form=True and has_contact_form=True but no ESP automation",
  open_gap_count=2),
L(1385, "forbelle.com.mx", "Forbelle", primary="Insufficient Data", confidence="high",
  summary="Page served an obfuscated JS-based verification wall — no real content retrievable.",
  conv=50, cart=50, eng=50, followup=50, ci=50,
  ev_conv="bot-check/obfuscated verification page", ev_cart="has_cart=False (undetermined)",
  ev_eng="no signals extractable — verification wall", ev_followup="no signals extractable — verification wall",
  open_gap_count=0, disqualifier="anti-bot verification page — cannot assess real content"),
L(1386, "datameesterschap.nl", "Datameesterschap", primary="Follow-up Opportunity", confidence="low",
  summary="Dutch AI/data-strategy B2B consulting business with no lead-capture form or ESP.",
  conv=35, cart=20, eng=30, followup=45, ci=25,
  ev_conv="has_cart=True likely false-positive for a B2B consulting business", ev_cart="product_count_visible=0",
  ev_eng="no chat/reviews/popup", ev_followup="no email or contact form detected",
  open_gap_count=1),
L(1387, "byminmobiliaria.mx", "Byminmobiliaria", primary="Follow-up Opportunity", confidence="low",
  summary="Mexican real-estate agency with WhatsApp chat but no email-capture form or ESP.",
  conv=40, cart=20, eng=40, followup=50, ci=30,
  ev_conv="has_cart=True likely false-positive for a real-estate agency", ev_cart="product_count_visible=0",
  ev_eng="WhatsApp chat already present", ev_followup="no email capture form detected despite active chat channel",
  open_gap_count=1),
L(1388, "eclatservice.com", "Eclatservice", primary="Follow-up Opportunity", confidence="medium",
  summary="US data-abstracting/outsourcing B2B service with both email and contact forms and booking already offered, but no ESP.",
  conv=45, cart=20, eng=45, followup=55, ci=35,
  ev_conv="has_cart=True likely false-positive for a B2B outsourcing service", ev_cart="product_count_visible=0",
  ev_eng="booking already offered, cta_count_above_fold=3", ev_followup="has_email_form=True and has_contact_form=True but no ESP automation",
  open_gap_count=1),
L(1389, "mipartner.hu", "Mipartner", primary="Follow-up Opportunity", confidence="low",
  summary="Hungarian AI-automation B2B consulting business with no lead-capture form or ESP.",
  conv=35, cart=20, eng=30, followup=45, ci=25,
  ev_conv="has_cart=False — B2B AI-consulting firm", ev_cart="has_cart=False",
  ev_eng="no chat/reviews/popup", ev_followup="no email or contact form detected",
  open_gap_count=1),
L(1390, "padelpass.co.uk", "Padelpass", primary="Insufficient Data", confidence="low",
  summary="Domain resolved but page_text is empty and platform is unknown.",
  conv=50, cart=50, eng=50, followup=50, ci=50,
  ev_conv="page_text empty", ev_cart="has_cart=False (undetermined)",
  ev_eng="no signals extractable", ev_followup="no signals extractable",
  open_gap_count=0, disqualifier="empty/undetermined signals — cannot assess"),
L(1391, "thewhiskyriver.co.uk", "Thewhiskyriver", primary="Insufficient Data", confidence="low",
  summary="Domain resolved but page_text is empty and platform is unknown.",
  conv=50, cart=50, eng=50, followup=50, ci=50,
  ev_conv="page_text empty", ev_cart="has_cart=False (undetermined)",
  ev_eng="no signals extractable", ev_followup="no signals extractable",
  open_gap_count=0, disqualifier="empty/undetermined signals — cannot assess"),
L(1392, "hospitalityplusplus.com", "Hospitalityplusplus", primary="Insufficient Data", confidence="low",
  summary="Domain resolved but page_text is empty and platform is unknown.",
  conv=50, cart=50, eng=50, followup=50, ci=50,
  ev_conv="page_text empty", ev_cart="has_cart=False (undetermined)",
  ev_eng="no signals extractable", ev_followup="no signals extractable",
  open_gap_count=0, disqualifier="empty/undetermined signals — cannot assess"),
L(1393, "studyworks.sg", "Studyworks", primary="Follow-up Opportunity", secondary="Cart Recovery Opportunity", confidence="low",
  summary="Singapore exam-booking service with an attached shop (3 products) but no capture form or ESP.",
  conv=40, cart=40, eng=35, followup=50, ci=30,
  ev_conv="has_cart=True but this is a booking-driven exam-services business", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="booking already offered", ev_followup="no email capture form detected despite active booking flow",
  open_gap_count=2),
L(1394, "malotraktorybalogh.sk", "Malotraktorybalogh", primary="Cart Recovery Opportunity", secondary="Follow-up Opportunity", confidence="medium",
  summary="Slovak mini-tractor dealer (8 products, 7 brands) with both email and contact forms and reviews already live, but no ESP.",
  conv=45, cart=60, eng=45, followup=55, ci=35,
  ev_conv="has_cart=True, no ESP", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="reviews present", ev_followup="has_email_form=True and has_contact_form=True but no ESP automation",
  open_gap_count=2),
L(1395, "farmauchytilovi.cz", "Farmauchytilovi", primary="Insufficient Data", confidence="high",
  summary="Origin server returns HTTP 502 (WEDOS.protection detects misconfiguration) — no content retrievable.",
  conv=50, cart=50, eng=50, followup=50, ci=50,
  ev_conv="502 origin server error", ev_cart="has_cart=False (undetermined)",
  ev_eng="no signals extractable — origin error", ev_followup="no signals extractable — origin error",
  open_gap_count=0, disqualifier="origin server returns 502 — cannot assess"),
L(1396, "truedamagecare.com", "Truedamagecare", primary="Follow-up Opportunity", confidence="low",
  summary="Consulting/insurance-like 'Plans' services business with an email form but no ESP.",
  conv=35, cart=25, eng=30, followup=45, ci=25,
  ev_conv="has_cart=True likely false-positive for a services/plans business", ev_cart="product_count_visible=0",
  ev_eng="generic popup only, cta_count_above_fold=4", ev_followup="has_email_form=True but no ESP automation",
  open_gap_count=1),
L(1397, "smartscoop.hu", "Smartscoop", primary="Cart Recovery Opportunity", secondary="Customer Engagement Opportunity", confidence="low",
  summary="Hungarian smart ice-cream-scoop gadget product site, product_count_visible=0 suggests thin page fetched, no ESP.",
  conv=35, cart=50, eng=25, followup=30, ci=25,
  ev_conv="has_cart=True, no ESP", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="no chat/reviews/popup", ev_followup="no email capture form detected",
  open_gap_count=2),
L(1398, "ziptrack.in", "Ziptrack", primary="Cart Recovery Opportunity", secondary="Customer Engagement Opportunity", confidence="medium",
  summary="Indian GPS vehicle-tracking B2B/B2C WooCommerce store (8 products) with a high above-fold CTA count (8) but no capture form or ESP.",
  conv=40, cart=60, eng=40, followup=35, ci=30,
  ev_conv="has_cart=True, no ESP, cta_count_above_fold=8", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="generic popup only, no chat/reviews despite high above-fold CTA count", ev_followup="no email capture form detected",
  open_gap_count=2),
L(1399, "bumbum.mn", "Bumbum", primary="Cart Recovery Opportunity", secondary="Follow-up Opportunity", confidence="medium",
  summary="Mongolian security/safety business with an attached shop (6 products), reviews, and a high above-fold CTA count (9), but no ESP.",
  conv=45, cart=60, eng=45, followup=55, ci=35,
  ev_conv="has_cart=True, no ESP, cta_count_above_fold=9", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="reviews present", ev_followup="has_email_form=True but no ESP automation",
  open_gap_count=2),
L(1400, "hydrogel.rs", "Hydrogel", primary="Not a Good Fit", confidence="medium",
  summary="Serbian plant-hydrogel product store already running Mailchimp ESP with reviews.",
  conv=25, cart=20, eng=25, followup=20, ci=30,
  ev_conv="Mailchimp ESP already live", ev_cart="has_esp_tag=mailchimp",
  ev_eng="reviews present, cta_count_above_fold=1", ev_followup="email capture and ESP already wired together",
  open_gap_count=1, disqualifier="already has ESP + reviews stack in place"),
L(1401, "ktktrading.com", "Ktktrading", primary="Follow-up Opportunity", confidence="low",
  summary="French forex-trading education/signals service with booking and reviews already live, but no ESP behind an email form.",
  conv=40, cart=20, eng=40, followup=50, ci=30,
  ev_conv="has_cart=True likely false-positive for a trading-education service", ev_cart="product_count_visible=0",
  ev_eng="booking and reviews already present", ev_followup="no email capture form detected for course-signup leads",
  open_gap_count=1),
L(1402, "academylinknetwork.com", "Academylinknetwork", primary="Follow-up Opportunity", confidence="low",
  summary="Education/membership platform with booking already offered but no ESP.",
  conv=40, cart=20, eng=35, followup=50, ci=30,
  ev_conv="has_cart=True likely false-positive for a membership education platform", ev_cart="product_count_visible=0",
  ev_eng="booking already offered, cta_count_above_fold=4", ev_followup="has_email_form=True but no ESP automation",
  open_gap_count=1),
L(1403, "uniksolutions.in", "Uniksolutions", primary="Follow-up Opportunity", confidence="low",
  summary="Indian WhatsApp business-automation/CRM B2B service (ironically) with WhatsApp chat but no visible lead-capture form or ESP.",
  conv=35, cart=20, eng=35, followup=45, ci=25,
  ev_conv="has_cart=False — B2B automation-services provider", ev_cart="has_cart=False",
  ev_eng="WhatsApp chat already present, cta_count_above_fold=4", ev_followup="no email or contact form detected despite active chat channel",
  open_gap_count=1),
L(1404, "leader-plaque.fr", "Leader-Plaque", primary="Cart Recovery Opportunity", secondary="Follow-up Opportunity", confidence="low",
  summary="French funeral-industry B2B supplier (memorial plaques) with both email and contact forms and reviews already live, but no ESP.",
  conv=40, cart=55, eng=40, followup=50, ci=30,
  ev_conv="has_cart=True, no ESP", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="reviews present", ev_followup="has_email_form=True and has_contact_form=True but no ESP automation",
  open_gap_count=2),
L(1405, "bloomandsavour.com", "Bloomandsavour", primary="Insufficient Data", confidence="low",
  summary="Domain resolved but page_text is empty and platform is unknown.",
  conv=50, cart=50, eng=50, followup=50, ci=50,
  ev_conv="page_text empty", ev_cart="has_cart=False (undetermined)",
  ev_eng="no signals extractable", ev_followup="no signals extractable",
  open_gap_count=0, disqualifier="empty/undetermined signals — cannot assess"),
L(1406, "enshaa.me", "Enshaa", primary="Follow-up Opportunity", confidence="low",
  summary="Saudi real-estate developer with an email form but no ESP.",
  conv=40, cart=20, eng=30, followup=50, ci=30,
  ev_conv="has_cart=True likely false-positive for a real-estate developer", ev_cart="product_count_visible=0",
  ev_eng="generic popup only, cta_count_above_fold=1", ev_followup="has_email_form=True but no ESP automation for high-value property leads",
  open_gap_count=1),
L(1407, "alfaaprime.com", "Alfaaprime", primary="Not a Good Fit", confidence="medium",
  summary="Business already running Mailchimp ESP with cta_count_above_fold=3.",
  conv=25, cart=20, eng=30, followup=20, ci=30,
  ev_conv="Mailchimp ESP already live", ev_cart="has_esp_tag=mailchimp",
  ev_eng="cta_count_above_fold=3", ev_followup="email capture and ESP already wired together",
  open_gap_count=1, disqualifier="already has ESP in place"),
L(1408, "sundeus.ai", "Sundeus", primary="Follow-up Opportunity", confidence="low",
  summary="AI company with reviews and a very high above-fold CTA count (14), with a Mailchimp ESP tag detected but no visible email-capture form to feed it.",
  conv=40, cart=30, eng=45, followup=40, ci=35,
  ev_conv="has_cart=True, has_esp_tag=mailchimp but has_email_form=False — ESP underused", ev_cart="has_esp_tag=mailchimp, has_email_form=False",
  ev_eng="reviews present, cta_count_above_fold=14 (very high)", ev_followup="ESP present but no capture mechanism visibly wired to it",
  open_gap_count=1),
L(1409, "neronobilis.it", "Neronobilis", primary="Cart Recovery Opportunity", secondary="Follow-up Opportunity", confidence="low",
  summary="Italian truffle-products WooCommerce store, product_count_visible=0 suggests thin page fetched, no ESP.",
  conv=40, cart=55, eng=30, followup=45, ci=30,
  ev_conv="has_cart=True, no ESP", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="generic popup only, no chat/reviews", ev_followup="has_email_form=True but no ESP automation",
  open_gap_count=2),
]

n = append_results(RESULTS)
print(f"appended {n} rows (chunk_014)")
