import sys
sys.path.insert(0, ".")
from layer3_write import append_results


def L(lead_id, domain, business_name, primary, confidence, summary,
      conv, cart, eng, followup, ci, ev_conv, ev_cart, ev_eng, ev_followup,
      open_gap_count, secondary=None, disqualifier=None):
    return (lead_id, domain, business_name, primary, secondary, confidence, summary,
            conv, cart, eng, followup, ci, ev_conv, ev_cart, ev_eng, ev_followup,
            open_gap_count, disqualifier)


RESULTS = [
L(1584, "goodfindmarine.com", "Goodfindmarine", primary="Cart Recovery Opportunity", secondary="Follow-up Opportunity", confidence="low",
  summary="Indian marine-equipment B2B business with a newsletter signup but no ESP.",
  conv=35, cart=50, eng=30, followup=40, ci=25,
  ev_conv="has_cart=True, no ESP, cta_count_above_fold=2", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="no chat/reviews/popup", ev_followup="has_email_form=True (newsletter signup) but no ESP automation",
  open_gap_count=2),
L(1585, "infolinklabsinc.com", "Infolinklabsinc", primary="Cart Recovery Opportunity", secondary="Follow-up Opportunity", confidence="low",
  summary="Philippine CCTV/security-equipment B2B distributor with both email and contact forms and reviews already live, but no ESP.",
  conv=40, cart=55, eng=35, followup=45, ci=30,
  ev_conv="has_cart=True, no ESP", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="reviews present but no chat", ev_followup="has_email_form=True and has_contact_form=True but no ESP automation",
  open_gap_count=2),
L(1586, "dmeventsolutions.nl", "Dmeventsolutions", primary="Not a Good Fit", confidence="medium",
  summary="Dutch event-equipment rental B2B business already running Klaviyo ESP with WhatsApp chat and reviews.",
  conv=25, cart=15, eng=30, followup=20, ci=30,
  ev_conv="has_cart=True likely false-positive for an equipment-rental business", ev_cart="has_esp_tag=klaviyo",
  ev_eng="WhatsApp chat and reviews already present", ev_followup="email capture and Klaviyo ESP already wired together",
  open_gap_count=1, disqualifier="already has ESP + chat + reviews stack in place"),
L(1587, "bagsfactori.com", "Bagsfactori", primary="Follow-up Opportunity", confidence="low",
  summary="Custom delivery-bags B2B manufacturer with both email and contact forms (WhatsApp quote-request popup) but no ESP.",
  conv=35, cart=20, eng=30, followup=45, ci=25,
  ev_conv="has_cart=False — B2B manufacturer, quote-request model", ev_cart="has_cart=False",
  ev_eng="cta_count_above_fold=1", ev_followup="has_email_form=True and has_contact_form=True but no ESP automation",
  open_gap_count=1),
L(1588, "limradesigns.in", "Limradesigns", primary="Cart Recovery Opportunity", secondary="Customer Engagement Opportunity", confidence="low",
  summary="Indian home-decor/window-dressings retailer WooCommerce store with a high above-fold CTA count (5) but no capture form or ESP.",
  conv=35, cart=50, eng=30, followup=25, ci=25,
  ev_conv="has_cart=True, no ESP, cta_count_above_fold=5", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="no chat/reviews/popup", ev_followup="no email capture form detected",
  open_gap_count=2),
L(1589, "yes-cable.uz", "Yes-Cable", primary="Follow-up Opportunity", confidence="low",
  summary="Uzbek cable B2B manufacturer with no lead-capture form or ESP.",
  conv=35, cart=20, eng=25, followup=40, ci=25,
  ev_conv="has_cart=True likely false-positive for a B2B cable manufacturer", ev_cart="product_count_visible=0",
  ev_eng="no chat/reviews/popup", ev_followup="no email or contact form detected",
  open_gap_count=1),
L(1590, "dtee.in", "Dtee", primary="Cart Recovery Opportunity", secondary="Follow-up Opportunity", confidence="low",
  summary="Indian industrial-valves B2B manufacturer WooCommerce store with reviews already live but no ESP.",
  conv=35, cart=50, eng=35, followup=40, ci=25,
  ev_conv="has_cart=True, no ESP", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="reviews present but no chat", ev_followup="no email capture form detected",
  open_gap_count=2),
L(1591, "emiratesrefineryltd.com", "Emiratesrefineryltd", primary="Cart Recovery Opportunity", secondary="Follow-up Opportunity", confidence="low",
  summary="UAE refinery-equipment B2B business with booking and reviews already live, but page copy includes obfuscated/encoded script content, no ESP.",
  conv=35, cart=45, eng=35, followup=40, ci=25,
  ev_conv="has_cart=True, no ESP; page content includes obfuscated encoded script", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="booking and reviews already present, cta_count_above_fold=3", ev_followup="has_email_form=True but no ESP automation",
  open_gap_count=2),
L(1592, "bamel.sk", "Bamel", primary="Follow-up Opportunity", confidence="low",
  summary="Slovak machine-repair B2B services business with no lead-capture form or ESP.",
  conv=35, cart=20, eng=25, followup=40, ci=25,
  ev_conv="has_cart=True likely false-positive for a B2B repair services business", ev_cart="product_count_visible=0",
  ev_eng="no chat/reviews/popup", ev_followup="no email or contact form detected",
  open_gap_count=1),
L(1593, "aynifoods.com", "Aynifoods", primary="Insufficient Data", confidence="low",
  summary="Domain resolved but page_text is empty and platform is unknown.",
  conv=50, cart=50, eng=50, followup=50, ci=50,
  ev_conv="page_text empty", ev_cart="has_cart=False (undetermined)",
  ev_eng="no signals extractable", ev_followup="no signals extractable",
  open_gap_count=0, disqualifier="empty/undetermined signals — cannot assess"),
L(1594, "meptech.ma", "Meptech", primary="Not a Good Fit", confidence="medium",
  summary="Moroccan industrial-equipment B2B business already running Omnisend ESP with reviews.",
  conv=25, cart=20, eng=30, followup=20, ci=30,
  ev_conv="Omnisend ESP already live", ev_cart="has_esp_tag=omnisend",
  ev_eng="reviews present", ev_followup="email capture and ESP already wired together",
  open_gap_count=1, disqualifier="already has ESP + reviews stack in place"),
L(1595, "hairlossrehab.ie", "Hairlossrehab", primary="Follow-up Opportunity", confidence="medium",
  summary="Irish hair-loss treatment business currently running a pre-launch waiting-list campaign, with booking, reviews, and a very high above-fold CTA count (11), but no ESP.",
  conv=45, cart=30, eng=50, followup=50, ci=35,
  ev_conv="has_cart=True but business is in a pre-launch waiting-list phase", ev_cart="product_count_visible=1",
  ev_eng="booking and reviews already present, cta_count_above_fold=11 (very high)", ev_followup="waiting-list signup present but no ESP automation confirmed",
  open_gap_count=2),
L(1596, "thesecondaddress.com", "Thesecondaddress", primary="Follow-up Opportunity", confidence="low",
  summary="European fractional vacation-home ownership business with booking already offered but no email-capture form or ESP.",
  conv=40, cart=25, eng=35, followup=50, ci=30,
  ev_conv="has_cart=True likely false-positive for a fractional real-estate business", ev_cart="product_count_visible=3",
  ev_eng="booking already offered ('schedule a meeting'), cta_count_above_fold=6", ev_followup="no email capture form detected for high-value property inquiries",
  open_gap_count=1),
L(1597, "sinaghabezah.com", "Sinaghabezah", primary="Cart Recovery Opportunity", secondary="Follow-up Opportunity", confidence="low",
  summary="Turkish oil-and-gas equipment B2B manufacturer with a high above-fold CTA count (7) but no ESP.",
  conv=40, cart=50, eng=35, followup=45, ci=30,
  ev_conv="has_cart=True, no ESP, cta_count_above_fold=7", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="generic popup only, no chat/reviews", ev_followup="has_email_form=True but no ESP automation",
  open_gap_count=2),
L(1598, "seedoosports.com", "Seedoosports", primary="Cart Recovery Opportunity", secondary="Customer Engagement Opportunity", confidence="low",
  summary="Custom gym-equipment/boxing-rings B2B manufacturer, product_count_visible=1 suggests thin catalog, no ESP.",
  conv=35, cart=50, eng=25, followup=25, ci=25,
  ev_conv="has_cart=True, no ESP", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="generic popup only, no chat/reviews", ev_followup="no email capture form detected",
  open_gap_count=2),
L(1599, "kitsrecycling.se", "Kitsrecycling", primary="Cart Recovery Opportunity", secondary="Follow-up Opportunity", confidence="low",
  summary="Swedish recycling-equipment B2B business, product_count_visible=0 suggests thin page fetched, no ESP.",
  conv=35, cart=50, eng=25, followup=40, ci=25,
  ev_conv="has_cart=True, no ESP", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="generic popup only, no chat/reviews", ev_followup="has_email_form=True but no ESP automation",
  open_gap_count=2),
L(1600, "carolinapatiofurniture.com", "Carolinapatiofurniture", primary="Cart Recovery Opportunity", secondary="Customer Engagement Opportunity", confidence="low",
  summary="US patio-furniture retailer WooCommerce store (16 products) with reviews already live but no capture form or ESP.",
  conv=40, cart=55, eng=35, followup=30, ci=25,
  ev_conv="has_cart=True, no ESP", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="reviews present but no chat/popup", ev_followup="no email capture form detected",
  open_gap_count=2),
L(1601, "izo-tim.rs", "Izo-Tim", primary="Cart Recovery Opportunity", secondary="Customer Engagement Opportunity", confidence="low",
  summary="Serbian construction-materials B2B retailer, product_count_visible=1 suggests thin catalog, no ESP.",
  conv=30, cart=45, eng=25, followup=25, ci=20,
  ev_conv="has_cart=True, no ESP", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="no chat/reviews/popup", ev_followup="no email capture form detected",
  open_gap_count=2),
L(1602, "laffausa.com", "Laffausa", primary="Cart Recovery Opportunity", secondary="Follow-up Opportunity", confidence="low",
  summary="US artisan food-products manufacturer WooCommerce store (7 products) with both email and contact forms but no ESP.",
  conv=40, cart=55, eng=30, followup=45, ci=30,
  ev_conv="has_cart=True, no ESP", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="no chat/reviews/popup, cta_count_above_fold=2", ev_followup="has_email_form=True and has_contact_form=True but no ESP automation",
  open_gap_count=2),
L(1603, "jetradingab.com", "Jetradingab", primary="Cart Recovery Opportunity", secondary="Customer Engagement Opportunity", confidence="low",
  summary="Swedish trading company B2B WooCommerce store (26 products) with a high above-fold CTA count (8) but no capture form or ESP.",
  conv=40, cart=55, eng=40, followup=30, ci=30,
  ev_conv="has_cart=True, no ESP, cta_count_above_fold=8", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="no chat/reviews despite high above-fold CTA count", ev_followup="no email capture form detected",
  open_gap_count=2),
L(1604, "nitusharoosh.com", "Nitusharoosh", primary="Cart Recovery Opportunity", secondary="Follow-up Opportunity", confidence="low",
  summary="Fashion-brand WooCommerce store whose fetched copy is mostly unrendered slider-plugin script, no ESP.",
  conv=35, cart=50, eng=25, followup=40, ci=25,
  ev_conv="has_cart=True, no ESP; page content largely unrendered slider-plugin boilerplate", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="cta_count_above_fold=3", ev_followup="has_email_form=True but no ESP automation",
  open_gap_count=2),
L(1605, "egtmea.com", "Egtmea", primary="Cart Recovery Opportunity", secondary="Follow-up Opportunity", confidence="low",
  summary="UAE speech-recognition/healthcare-IT B2B reseller (25 products) with both email and contact forms but no ESP.",
  conv=40, cart=50, eng=30, followup=45, ci=30,
  ev_conv="has_cart=True, no ESP", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="no chat/reviews/popup, cta_count_above_fold=1", ev_followup="has_email_form=True and has_contact_form=True but no ESP automation",
  open_gap_count=2),
L(1606, "isasolutions.net", "Isasolutions", primary="Cart Recovery Opportunity", secondary="Follow-up Opportunity", confidence="low",
  summary="Australian fire-fighting-systems B2B business (since 2010) with both email and contact forms but no ESP.",
  conv=40, cart=50, eng=25, followup=45, ci=30,
  ev_conv="has_cart=True, no ESP", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="no chat/reviews/popup", ev_followup="has_email_form=True and has_contact_form=True but no ESP automation",
  open_gap_count=2),
L(1607, "stelex.co.in", "Stelex", primary="Cart Recovery Opportunity", secondary="Follow-up Opportunity", confidence="low",
  summary="Indian grease-guns/oil-cans B2B manufacturer with reviews already live but no ESP.",
  conv=40, cart=55, eng=35, followup=45, ci=30,
  ev_conv="has_cart=True, no ESP", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="reviews present, cta_count_above_fold=2", ev_followup="has_email_form=True but no ESP automation",
  open_gap_count=2),
L(1608, "www.testsod.com", "Testsod", primary="Cart Recovery Opportunity", secondary="Follow-up Opportunity", confidence="low",
  summary="US NetSuite audit-compliance software B2B product with a moderate above-fold CTA count (4) but no ESP.",
  conv=35, cart=50, eng=30, followup=40, ci=25,
  ev_conv="has_cart=True, no ESP, cta_count_above_fold=4", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="generic popup only, no chat/reviews", ev_followup="no email capture form detected",
  open_gap_count=2),
L(1609, "bagwaninursery.com", "Bagwaninursery", primary="Cart Recovery Opportunity", secondary="Follow-up Opportunity", confidence="low",
  summary="Indian wholesale plant-nursery B2B business (17 products) with WhatsApp chat but no ESP.",
  conv=35, cart=50, eng=35, followup=40, ci=25,
  ev_conv="has_cart=True, no ESP", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="WhatsApp chat already present, cta_count_above_fold=1", ev_followup="no email capture form detected despite active chat",
  open_gap_count=2),
L(1610, "manchesterseals.com", "Manchesterseals", primary="Cart Recovery Opportunity", secondary="Customer Engagement Opportunity", confidence="low",
  summary="UK industrial-seals B2B business, product_count_visible=0 suggests thin page fetched, no ESP.",
  conv=35, cart=50, eng=25, followup=30, ci=25,
  ev_conv="has_cart=True, no ESP, cta_count_above_fold=5", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="no chat/reviews/popup", ev_followup="no email capture form detected",
  open_gap_count=2),
L(1611, "unison-doors.com", "Unison-Doors", primary="Cart Recovery Opportunity", secondary="Follow-up Opportunity", confidence="low",
  summary="Bulgarian entrance-doors B2B manufacturer, product_count_visible=0 suggests thin page fetched, no ESP.",
  conv=35, cart=50, eng=25, followup=40, ci=25,
  ev_conv="has_cart=True, no ESP", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="generic popup only, no chat/reviews", ev_followup="has_email_form=True but no ESP automation",
  open_gap_count=2),
L(1612, "arshadtech.com", "Arshadtech", primary="Insufficient Data", confidence="high",
  summary="Gateway/upstream connection-timeout error — no content retrievable.",
  conv=50, cart=50, eng=50, followup=50, ci=50,
  ev_conv="upstream connection timeout", ev_cart="has_cart=False (undetermined)",
  ev_eng="no signals extractable — gateway error", ev_followup="no signals extractable — gateway error",
  open_gap_count=0, disqualifier="upstream gateway error — cannot assess"),
L(1613, "girorigin.com", "Girorigin", primary="Cart Recovery Opportunity", secondary="Follow-up Opportunity", confidence="low",
  summary="WooCommerce store (7 products) whose fetched copy is mostly unrendered font-loader JS boilerplate, no ESP.",
  conv=35, cart=50, eng=25, followup=40, ci=25,
  ev_conv="has_cart=True, no ESP; page content largely unrendered JS boilerplate", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="cta_count_above_fold=2", ev_followup="has_email_form=True and has_contact_form=True but no ESP automation",
  open_gap_count=2),
L(1615, "equipement-bureaux.com", "Equipement-Bureaux", primary="Cart Recovery Opportunity", secondary="Follow-up Opportunity", confidence="low",
  summary="French office-furniture B2B business (16 products) with WhatsApp chat but no ESP.",
  conv=35, cart=50, eng=35, followup=40, ci=25,
  ev_conv="has_cart=True, no ESP", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="WhatsApp chat already present", ev_followup="no email capture form detected despite active chat",
  open_gap_count=2),
L(1616, "mocks.dsracademy.uk", "Dsracademy", primary="Insufficient Data", confidence="high",
  summary="Site explicitly states 'Coming Soon — New WordPress website is being built' — not yet live.",
  conv=50, cart=50, eng=50, followup=50, ci=50,
  ev_conv="site explicitly not yet launched", ev_cart="has_cart=False, site inactive",
  ev_eng="no real content to evaluate — placeholder page", ev_followup="no real content to evaluate — placeholder page",
  open_gap_count=0, disqualifier="site not live — 'coming soon' placeholder"),
L(1617, "tuojueautoparts.com", "Tuojueautoparts", primary="Insufficient Data", confidence="low",
  summary="Domain resolved but page_text is empty and platform is unknown.",
  conv=50, cart=50, eng=50, followup=50, ci=50,
  ev_conv="page_text empty", ev_cart="has_cart=False (undetermined)",
  ev_eng="no signals extractable", ev_followup="no signals extractable",
  open_gap_count=0, disqualifier="empty/undetermined signals — cannot assess"),
L(1618, "wewellhome.com", "Wewellhome", primary="Insufficient Data", confidence="high",
  summary="Gateway/upstream connection-timeout error — no content retrievable.",
  conv=50, cart=50, eng=50, followup=50, ci=50,
  ev_conv="upstream connection timeout", ev_cart="has_cart=False (undetermined)",
  ev_eng="no signals extractable — gateway error", ev_followup="no signals extractable — gateway error",
  open_gap_count=0, disqualifier="upstream gateway error — cannot assess"),
L(1619, "decarthomes.com", "Decarthomes", primary="Not a Good Fit", confidence="medium",
  summary="Home-decor/furniture B2B/B2C retailer (33 brands) already running Mailchimp ESP with both email and contact forms.",
  conv=25, cart=20, eng=30, followup=20, ci=30,
  ev_conv="Mailchimp ESP already live", ev_cart="has_esp_tag=mailchimp",
  ev_eng="33 brands carried, active promo offers", ev_followup="email capture and ESP already wired together",
  open_gap_count=1, disqualifier="already has ESP in place"),
L(1620, "samargallery.com", "Samargallery", primary="Insufficient Data", confidence="high",
  summary="Gateway/upstream connection-timeout error — no content retrievable.",
  conv=50, cart=50, eng=50, followup=50, ci=50,
  ev_conv="upstream connection timeout", ev_cart="has_cart=False (undetermined)",
  ev_eng="no signals extractable — gateway error", ev_followup="no signals extractable — gateway error",
  open_gap_count=0, disqualifier="upstream gateway error — cannot assess"),
L(1621, "sallyteam.com", "Sallyteam", primary="Cart Recovery Opportunity", secondary="Follow-up Opportunity", confidence="low",
  summary="Armenian food-products B2B distributor with WhatsApp chat but no ESP.",
  conv=35, cart=50, eng=35, followup=40, ci=25,
  ev_conv="has_cart=True, no ESP", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="WhatsApp chat already present", ev_followup="has_email_form=True but no ESP automation",
  open_gap_count=2),
L(1623, "gmbeautydevice.com", "Gmbeautydevice", primary="Insufficient Data", confidence="low",
  summary="Domain resolved but page_text is empty and platform is unknown.",
  conv=50, cart=50, eng=50, followup=50, ci=50,
  ev_conv="page_text empty", ev_cart="has_cart=False (undetermined)",
  ev_eng="no signals extractable", ev_followup="no signals extractable",
  open_gap_count=0, disqualifier="empty/undetermined signals — cannot assess"),
L(1624, "inkcolorful.com", "Inkcolorful", primary="Insufficient Data", confidence="low",
  summary="Domain resolved but page_text is empty and platform is unknown.",
  conv=50, cart=50, eng=50, followup=50, ci=50,
  ev_conv="page_text empty", ev_cart="has_cart=False (undetermined)",
  ev_eng="no signals extractable", ev_followup="no signals extractable",
  open_gap_count=0, disqualifier="empty/undetermined signals — cannot assess"),
L(1625, "twelvestoneshse.org", "Twelvestoneshse", primary="Insufficient Data", confidence="low",
  summary="Domain resolved but page_text is empty and platform is unknown.",
  conv=50, cart=50, eng=50, followup=50, ci=50,
  ev_conv="page_text empty", ev_cart="has_cart=False (undetermined)",
  ev_eng="no signals extractable", ev_followup="no signals extractable",
  open_gap_count=0, disqualifier="empty/undetermined signals — cannot assess"),
L(1626, "gnantinbynini.com", "Gnantinbynini", primary="Insufficient Data", confidence="low",
  summary="Domain resolved but page_text is empty and platform is unknown.",
  conv=50, cart=50, eng=50, followup=50, ci=50,
  ev_conv="page_text empty", ev_cart="has_cart=False (undetermined)",
  ev_eng="no signals extractable", ev_followup="no signals extractable",
  open_gap_count=0, disqualifier="empty/undetermined signals — cannot assess"),
L(1627, "digigalaxyco.com", "Digigalaxyco", primary="Insufficient Data", confidence="high",
  summary="Gateway/upstream connection-termination error — no content retrievable.",
  conv=50, cart=50, eng=50, followup=50, ci=50,
  ev_conv="upstream connection termination error", ev_cart="has_cart=False (undetermined)",
  ev_eng="no signals extractable — gateway error", ev_followup="no signals extractable — gateway error",
  open_gap_count=0, disqualifier="upstream gateway error — cannot assess"),
L(1628, "manata.co", "Manata", primary="Insufficient Data", confidence="high",
  summary="Gateway/upstream connection-timeout error — no content retrievable.",
  conv=50, cart=50, eng=50, followup=50, ci=50,
  ev_conv="upstream connection timeout", ev_cart="has_cart=False (undetermined)",
  ev_eng="no signals extractable — gateway error", ev_followup="no signals extractable — gateway error",
  open_gap_count=0, disqualifier="upstream gateway error — cannot assess"),
L(1629, "cr-iskierka.pl", "Cr-Iskierka", primary="Follow-up Opportunity", confidence="low",
  summary="Polish child-therapy/biofeedback clinic (appointment-booking model) with no lead-capture form or ESP.",
  conv=35, cart=20, eng=30, followup=45, ci=25,
  ev_conv="has_cart=True likely false-positive for a clinical/therapy practice", ev_cart="product_count_visible=0",
  ev_eng="no chat/reviews/popup", ev_followup="no email or contact form detected for appointment-booking leads",
  open_gap_count=1),
L(1630, "albatlamakina.com", "Albatlamakina", primary="Cart Recovery Opportunity", secondary="Follow-up Opportunity", confidence="low",
  summary="Turkish HVAC-compressor-components B2B distributor (10 products) with no ESP.",
  conv=35, cart=50, eng=25, followup=40, ci=25,
  ev_conv="has_cart=True, no ESP", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="no chat/reviews/popup", ev_followup="has_email_form=True but no ESP automation",
  open_gap_count=2),
L(1631, "davethan.tech", "Davethan", primary="Not a Good Fit", confidence="medium",
  summary="Tech business (3 products) already running Mailchimp ESP with tawk chat and a high above-fold CTA count (7).",
  conv=25, cart=20, eng=30, followup=20, ci=30,
  ev_conv="Mailchimp ESP already live", ev_cart="has_esp_tag=mailchimp",
  ev_eng="tawk chat already present, cta_count_above_fold=7", ev_followup="email capture and ESP already wired together",
  open_gap_count=1, disqualifier="already has ESP + chat + strong CTA presence in place"),
L(1632, "misijaplus.rs", "Misijaplus", primary="Cart Recovery Opportunity", secondary="Follow-up Opportunity", confidence="low",
  summary="Serbian UV-printer manufacturer/reseller B2B (3 products) with WhatsApp chat but no ESP.",
  conv=35, cart=50, eng=35, followup=40, ci=25,
  ev_conv="has_cart=True, no ESP", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="WhatsApp chat already present", ev_followup="no email capture form detected despite active chat",
  open_gap_count=2),
L(1633, "safarinortherntour.com", "Safarinortherntour", primary="Follow-up Opportunity", confidence="low",
  summary="Tanzanian safari-tour operator with an email form but no ESP.",
  conv=40, cart=20, eng=25, followup=50, ci=30,
  ev_conv="has_cart=True likely false-positive for a tour-package business", ev_cart="product_count_visible=0",
  ev_eng="cta_count_above_fold=1", ev_followup="has_email_form=True but no ESP automation for high-value tour inquiries",
  open_gap_count=1),
L(1634, "chasingsmiles.org", "Chasingsmiles", primary="Not a Good Fit", confidence="medium",
  summary="South African children's charity already running Mailchimp ESP.",
  conv=20, cart=15, eng=25, followup=15, ci=25,
  ev_conv="has_cart=True likely false-positive for a donation-driven charity", ev_cart="has_esp_tag=mailchimp",
  ev_eng="cta_count_above_fold=3", ev_followup="email capture and ESP already wired together",
  open_gap_count=1, disqualifier="already has ESP in place"),
L(1635, "envy-surfboards.com", "Envy-Surfboards", primary="Cart Recovery Opportunity", secondary="Customer Engagement Opportunity", confidence="low",
  summary="Custom surfboard manufacturer, product_count_visible=0 suggests thin page fetched, no ESP.",
  conv=35, cart=50, eng=25, followup=25, ci=25,
  ev_conv="has_cart=True, no ESP", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="generic popup only, no chat/reviews", ev_followup="no email capture form detected",
  open_gap_count=2),
L(1636, "yersontech.cn", "Yersontech", primary="Cart Recovery Opportunity", secondary="Customer Engagement Opportunity", confidence="low",
  summary="Chinese RF/microwave-components B2B manufacturer WooCommerce store (6 products) with no capture form or ESP.",
  conv=35, cart=50, eng=25, followup=25, ci=25,
  ev_conv="has_cart=True, no ESP", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="generic popup only, no chat/reviews", ev_followup="no email capture form detected",
  open_gap_count=2),
L(1637, "sabzfalaholive.com", "Sabzfalaholive", primary="Insufficient Data", confidence="high",
  summary="Gateway/upstream connection-timeout error — no content retrievable.",
  conv=50, cart=50, eng=50, followup=50, ci=50,
  ev_conv="upstream connection timeout", ev_cart="has_cart=False (undetermined)",
  ev_eng="no signals extractable — gateway error", ev_followup="no signals extractable — gateway error",
  open_gap_count=0, disqualifier="upstream gateway error — cannot assess"),
L(1638, "petrapremium.com", "Petrapremium", primary="Follow-up Opportunity", secondary="Cart Recovery Opportunity", confidence="low",
  summary="Jordanian luxury hotel (near Petra) with reviews already live and an online booking widget, but no ESP.",
  conv=40, cart=25, eng=40, followup=45, ci=30,
  ev_conv="has_cart=True but this is a hotel-booking business", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="reviews present, cta_count_above_fold=1", ev_followup="has_email_form=True but no ESP automation for booking leads",
  open_gap_count=2),
L(1639, "oasisdemontagne.com", "Oasisdemontagne", primary="Follow-up Opportunity", confidence="low",
  summary="Tunisian desert/oasis accommodation tourism business with an email form but no ESP.",
  conv=35, cart=20, eng=25, followup=45, ci=25,
  ev_conv="has_cart=True likely false-positive for a tourism-accommodation business", ev_cart="product_count_visible=0",
  ev_eng="generic popup only, no chat/reviews", ev_followup="has_email_form=True but no ESP automation",
  open_gap_count=1),
L(1640, "angelscurls.com", "Angelscurls", primary="Insufficient Data", confidence="low",
  summary="Domain resolved but page_text is empty and platform is unknown.",
  conv=50, cart=50, eng=50, followup=50, ci=50,
  ev_conv="page_text empty", ev_cart="has_cart=False (undetermined)",
  ev_eng="no signals extractable", ev_followup="no signals extractable",
  open_gap_count=0, disqualifier="empty/undetermined signals — cannot assess"),
]

n = append_results(RESULTS)
print(f"appended {n} rows (chunk_018)")
