import sys
sys.path.insert(0, ".")
from layer3_write import append_results

RESULTS = [
("739","hyrla.pl","Hyrla","Follow-up Opportunity",None,"Medium",
 "Polish charcoal and gas grill (BBQ) e-commerce brand.",
 35,40,35,60,50,
 "cta_count_above_fold is 0; Polish 'Kup teraz' likely present but not matched.","A popup script is present but has_esp_tag is none.",
 "has_chat_widget is none on a moderate grill/accessory catalog.",
 "has_email_form is false, has_contact_form is false, has_esp_tag is none -- no capture mechanism.",1,None),
("740","selectopts.com","Selectopts","Follow-up Opportunity",None,"Medium",
 "Nigerian shoes and watches e-commerce brand (Lagos).",
 40,40,45,60,50,
 "cta_count_above_fold is 0 despite an active discount promo.","A popup script is present but has_esp_tag is none.",
 "has_chat_widget is none across shoe types and watch offerings.",
 "has_email_form is false, has_contact_form is false, has_esp_tag is none -- no capture mechanism.",1,None),
("741","inergy-byestella.com","Inergy Byestella","Follow-up Opportunity",None,"Low",
 "German healing-crystal jewelry brand (handcrafted).",
 35,35,20,55,50,
 "cta_count_above_fold is 0.","A popup script is present but has_esp_tag is none.",
 "WhatsApp chat widget is present.",
 "has_email_form is false, has_contact_form is false, has_esp_tag is none -- no capture mechanism.",1,None),
("742","thefootballdream.com","Thefootballdream","Follow-up Opportunity",None,"Low",
 "Spanish youth football summer camp (Real Sporting affiliated).",
 40,15,35,55,50,
 "cta_count_above_fold is 0.","Not a real retail cart (camp registration).",
 "has_chat_widget is none across several camp locations.",
 "has_email_form is false, has_contact_form is false, has_esp_tag is none -- no capture mechanism.",1,None),
("743","zelenodomacinstvo.com","Zelenodomacinstvo","Customer Engagement Opportunity",None,"High",
 "Serbian organic/local food e-commerce brand (Uzice).",
 35,40,70,20,50,
 "cta_count_above_fold is 0; Serbian detector miss likely.","A popup script is present but has_esp_tag is none.",
 "has_chat_widget is none across a very wide grocery catalog (produce, dairy, juices, jams, honey, meat, fish, alcohol, frozen goods, bread, natural medicine).",
 "has_email_form is true (evidence: 'Email') -- a capture mechanism exists.",0,None),
("744","thealphathings.com","Thealphathings","Cart Recovery Opportunity",None,"Low",
 "Indian skincare e-commerce brand.",
 15,35,30,20,50,
 "8 CTAs above the fold give a clear path.","A popup script is present but has_esp_tag is none, on a 9-product catalog.",
 "has_chat_widget is none on a narrow catalog.","has_email_form is true -- a capture mechanism exists.",0,None),
("745","charmiqjewellery.com","Charmiqjewellery","Cart Recovery Opportunity",None,"Low",
 "Indian jewelry e-commerce brand.",
 40,40,40,20,50,
 "cta_count_above_fold is 0.","A popup script is present but has_esp_tag is none.",
 "has_chat_widget is none across earrings, necklaces, and bracelet categories by occasion.",
 "has_email_form is true -- a capture mechanism exists.",0,None),
("746","divian.lt","Divian","Cart Recovery Opportunity",None,"Low",
 "Lithuanian women's fashion e-commerce brand.",
 35,30,40,15,50,
 "cta_count_above_fold is 0; Lithuanian detector miss likely.","An Omnisend ESP tag and popup are present.",
 "has_chat_widget is none across several fashion collections.",
 "has_email_form is true with an Omnisend ESP tag -- a capture mechanism exists.",0,None),
("747","ozmedbeauty.lt","Ozmedbeauty","Customer Engagement Opportunity",None,"Medium",
 "Lithuanian aesthetic-medicine and beauty clinic.",
 40,30,60,20,50,
 "cta_count_above_fold is 0.","A popup script is present but has_esp_tag is none.",
 "has_chat_widget is none across a wide range of aesthetic-medicine procedures (dermatology, injections, permanent makeup, laser hair removal, HIFU, RF).",
 "has_email_form is true (evidence: 'El. pastas') -- a capture mechanism exists.",0,None),
("748","natureclean.in","Natureclean","Customer Engagement Opportunity",None,"Low",
 "Indian eco-friendly cleaning-products e-commerce brand.",
 40,40,45,15,50,
 "cta_count_above_fold is 0 despite an active promo.","A popup script is present but has_esp_tag is none, on a real 17-product catalog.",
 "has_chat_widget is none across floor, kitchen, fabric, and bathroom cleaner categories.",
 "has_email_form is true and has_contact_form is true (evidence: data-consent checkbox) -- a capture mechanism exists.",0,None),
("749","bestbuy4all.com","Bestbuy4All","Cart Recovery Opportunity",None,"Low",
 "General-merchandise e-commerce store (automotive, electronics, home goods).",
 40,40,20,20,50,
 "cta_count_above_fold is 0 despite a real 53-product catalog.","A popup script is present but has_esp_tag is none.",
 "WhatsApp chat widget is present despite a wide catalog, closing this gap per the signal.",
 "has_email_form is true (evidence: 'Email') -- a capture mechanism exists.",0,None),
("750","www.hesterpro.ee","Hesterpro","Conversion Opportunity",None,"Low",
 "Estonian window-cleaning-robot e-commerce brand.",
 40,30,20,15,50,
 "cta_count_above_fold is 0; 'Osta' (buy) is a real CTA not counted.","An Omnisend ESP tag and popup are present.",
 "has_chat_widget is none on a single-product-focus catalog.",
 "has_email_form is true with an Omnisend ESP tag -- a capture mechanism exists.",0,None),
("751","www.fairytrees.ie","Fairytrees","Follow-up Opportunity",None,"Medium",
 "Irish winery producing French-Irish heritage wines.",
 40,40,25,60,50,
 "cta_count_above_fold is 0.","A popup script is present but has_esp_tag is none, on a real 6-wine catalog.",
 "has_chat_widget is none on a narrow catalog.",
 "has_email_form is false, has_contact_form is false, has_esp_tag is none -- no capture mechanism.",1,None),
("752","truckamuck.com","Truckamuck","Customer Engagement Opportunity",None,"Medium",
 "US trucker lifestyle/merchandise marketplace (apparel, electronics, legal, PPE, parts).",
 40,55,70,20,50,
 "2 CTAs above the fold.","has_popup_script is false and has_esp_tag is none on a real merchandise catalog -- no recovery mechanism.",
 "has_chat_widget is none across an unusually wide range of unrelated categories (apparel, electronics, legal services, truck parts, PPE, pet products).",
 "has_email_form is true (evidence: 'Email') -- a capture mechanism exists.",1,None),
("753","all-in-one-concierge.com","All In One Concierge","Conversion Opportunity",None,"Low",
 "Egyptian travel concierge service (hotels, real estate, limo, airport transfers).",
 40,20,20,15,50,
 "cta_count_above_fold is 0.","Not a real retail cart (concierge/booking business).",
 "WhatsApp chat widget is present despite a wide service range.",
 "has_email_form is true with a Mailchimp ESP tag -- a capture mechanism exists.",0,None),
("754","valordoor.com","Valordoor","Insufficient Data",None,"Low",
 "Not determinable -- the fetched page returned no visible text content.",
 50,50,50,50,50,
 "not determinable from available signals","not determinable from available signals","not determinable from available signals","not determinable from available signals",0,None),
("755","www.mystic-cacao.com","Mystic Cacao","Follow-up Opportunity",None,"Medium",
 "Dutch ceremonial cacao and spiritual-accessories e-commerce brand.",
 40,30,30,50,50,
 "cta_count_above_fold is 0.","An OptinMonster popup is present but has_esp_tag is none.",
 "has_chat_widget is none on a narrow niche catalog.",
 "has_email_form is false -- no capture form was confirmed in the static markup, though an OptinMonster popup is active, suggesting one may exist dynamically.",0,None),
("756","vastranis.com","Vastranis","Follow-up Opportunity",None,"Medium",
 "Ethnic-wear (sarees, lehengas, suits) e-commerce brand.",
 15,55,40,60,50,
 "8 CTAs above the fold give a clear path.","has_popup_script is false and has_esp_tag is none -- no recovery mechanism.",
 "has_chat_widget is none across a moderate range of ethnic-wear categories.",
 "has_email_form is false, has_contact_form is false, has_esp_tag is none -- no capture mechanism.",1,None),
("757","maisondesforestiblesabbaye.com","Maisondesforestiblesabbaye","Customer Engagement Opportunity",None,"Low",
 "French foraging/mushroom-experience business (Abbaye).",
 40,20,55,15,50,
 "cta_count_above_fold is 0.","Not a real retail cart (experience business).",
 "has_chat_widget is none across a wide range of foraging/nature activity types (winter, gourmet, herbalism, mushrooms).",
 "has_email_form is true with a Mailchimp ESP tag -- a capture mechanism exists.",0,None),
("758","duragreenlighting.co.uk","Duragreenlighting","Customer Engagement Opportunity",None,"High",
 "UK commercial LED lighting B2B supplier.",
 40,25,70,15,50,
 "cta_count_above_fold is 0.","A Mailchimp ESP tag and popup are present.",
 "has_chat_widget is none across a very wide, technical lighting catalog (downlights, spotlights, track lights, floor/table lamps, LED strip, lighting control systems).",
 "has_email_form is true with a Mailchimp ESP tag -- a capture mechanism exists.",0,None),
("759","simiobasan.ca","Simiobasan","Follow-up Opportunity",None,"Low",
 "Canadian lawyer, author, and city councillor personal brand (book sales, legal practice).",
 40,15,20,55,50,
 "4 CTAs above the fold give a clear path.","has_cart is false -- not a retail cart business.",
 "Personal brand isn't a catalog; low relevance.",
 "has_email_form is false, has_contact_form is false, has_esp_tag is none -- no capture mechanism.",1,None),
("760","balilifespa.pl","Balilifespa","Customer Engagement Opportunity",None,"Medium",
 "Polish Balinese-style massage spa (Rumia and Gdynia locations).",
 40,25,60,55,50,
 "cta_count_above_fold is 0.","A popup script is present but has_esp_tag is none.",
 "has_chat_widget is none across a very wide massage-service menu (Thai, Balinese, hot stone, Shiatsu, Lomi Lomi, prenatal, sports).",
 "has_email_form is false, has_contact_form is false, has_esp_tag is none -- no capture mechanism.",1,None),
("761","christianroyalty.co.za","Christianroyalty","Cart Recovery Opportunity",None,"Low",
 "South African Christian lifestyle magazine and shop.",
 15,30,40,15,50,
 "8 CTAs above the fold give a clear path.","A Mailchimp ESP tag and popup are present.",
 "has_chat_widget is none across magazine, business directory, and shop offerings.",
 "has_email_form is true with a Mailchimp ESP tag -- a capture mechanism exists.",0,None),
("762","fermentmag.pl","Fermentmag","Customer Engagement Opportunity",None,"Low",
 "Polish wine and fermentation culture magazine with an attached shop.",
 40,35,55,20,50,
 "cta_count_above_fold is 0.","A popup script is present but has_esp_tag is none, on a small 3-product shop.",
 "has_chat_widget is none across a wide magazine content range (travel, science, wine, fermentation, books, events).",
 "has_email_form is true (evidence: data-consent text) -- a capture mechanism exists.",0,None),
("763","drivematecarrentals.com","Drivematecarrentals","Insufficient Data",None,"Low",
 "Not determinable -- the fetched page returned no visible text content.",
 50,50,50,50,50,
 "not determinable from available signals","not determinable from available signals","not determinable from available signals","not determinable from available signals",0,None),
("764","somnushaven.com","Somnushaven","Follow-up Opportunity",None,"Medium",
 "US mattress and bedding e-commerce brand.",
 40,40,20,65,50,
 "cta_count_above_fold is 0 despite an active 20%-off sitewide promo.","A popup script is present but has_esp_tag is none, on a real 29-product catalog.",
 "A Tawk chat widget is present.",
 "has_email_form is false, has_contact_form is false, has_esp_tag is none -- no capture mechanism on high-ticket mattress purchases.",1,None),
("765","peptideminds.com","Peptideminds","Customer Engagement Opportunity",None,"Medium",
 "US peptide/research-chemical e-commerce brand.",
 40,25,65,15,50,
 "Only 1 CTA above the fold.","A Klaviyo ESP tag and popup are present.",
 "has_chat_widget is none across a wide, technical 36-product peptide catalog.",
 "has_email_form is true with a Klaviyo ESP tag -- a capture mechanism exists.",0,None),
("766","equilibratucamino.com","Equilibratucamino","Follow-up Opportunity",None,"Medium",
 "Spanish gambling-addiction treatment center (ETC method).",
 40,25,20,50,50,
 "cta_count_above_fold is 0; 'RESERVA HOY' is a real CTA not counted.","An OptinMonster popup and Brevo ESP tag are present.",
 "WhatsApp chat widget is present.",
 "has_email_form is false -- no capture form was confirmed in the static markup, though a Brevo ESP tag and active popup are present, suggesting one may exist dynamically.",0,None),
("767","uniqueeventsgroup.co.uk","Uniqueeventsgroup","Follow-up Opportunity",None,"Low",
 "UK event entertainment and theatre production company.",
 20,15,20,55,50,
 "4 CTAs above the fold give a clear path.","Not a real retail cart (events business).",
 "WhatsApp chat widget is present.",
 "has_email_form is false, has_contact_form is false, has_esp_tag is none -- no capture mechanism.",1,None),
("768","expertisecenter.org","Expertisecenter","Customer Engagement Opportunity",None,"Low",
 "Egyptian training and consultation center.",
 15,25,40,20,50,
 "6 CTAs above the fold give a clear path.","Not a real retail cart (training center).",
 "has_chat_widget is none across training and consultation program offerings.",
 "has_email_form is true -- a capture mechanism exists.",0,None),
("770","houseofbeans.co","Houseofbeans","Follow-up Opportunity",None,"Low",
 "Sierra Leone premium coffee brand (with a physical location).",
 40,50,20,55,50,
 "2 CTAs above the fold.","has_popup_script is false and has_esp_tag is none on a small 8-product catalog.",
 "has_chat_widget is none on a narrow coffee-focused catalog.",
 "has_email_form is false, has_contact_form is false, has_esp_tag is none -- no capture mechanism.",1,None),
("771","debesumedziotojai.lt","Debesumedziotojai","Follow-up Opportunity",None,"Low",
 "Lithuanian paragliding tourism experience business.",
 35,15,20,55,50,
 "cta_count_above_fold is 0 despite a real booking calendar.","Not a real retail cart (experience business).",
 "has_chat_widget is none on a single-experience-type offering.",
 "has_email_form is false, has_contact_form is false, has_esp_tag is none -- no capture mechanism.",1,None),
("772","smartmarteg.com","Smartmarteg","Follow-up Opportunity","Customer Engagement Opportunity","High",
 "Egyptian home-goods and gadgets e-commerce store.",
 40,40,65,65,50,
 "cta_count_above_fold is 0; Arabic detector miss likely.","A popup script is present but has_esp_tag is none.",
 "has_chat_widget is none across a very wide catalog (small appliances, kitchen tools, sports gear, toys, lighting, cleaning, personal care, car accessories).",
 "has_email_form is false, has_contact_form is false, has_esp_tag is none -- no capture mechanism.",2,None),
("773","conexionforrajera.com","Conexionforrajera","Follow-up Opportunity",None,"Low",
 "Argentine B2B hay/forage trading marketplace.",
 40,15,20,55,50,
 "cta_count_above_fold is 0; 'Quiero comprar/vender' are real CTAs not counted.",
 "Not a real retail cart (trading marketplace).","WhatsApp chat widget is present.",
 "has_email_form is false, has_contact_form is false, has_esp_tag is none -- no capture mechanism.",1,None),
("774","hemp-angels.hu","Hemp Angels","Insufficient Data",None,"Low",
 "Not determinable -- the fetched page returned no visible text content.",
 50,50,50,50,50,
 "not determinable from available signals","not determinable from available signals","not determinable from available signals","not determinable from available signals",0,None),
("775","churchsecurity-101.com","Churchsecurity 101","Insufficient Data",None,"Low",
 "Not determinable -- the fetched page returned no visible text content.",
 50,50,50,50,50,
 "not determinable from available signals","not determinable from available signals","not determinable from available signals","not determinable from available signals",0,None),
("776","perdelesidraperiibycrina.ro","Perdelesidraperiibycrina","Follow-up Opportunity",None,"Medium",
 "Romanian curtains and drapery e-commerce brand.",
 40,40,25,60,50,
 "cta_count_above_fold is 0; Romanian detector miss likely.","A popup script is present but has_esp_tag is none.",
 "WhatsApp chat widget is present.",
 "has_email_form is false, has_contact_form is false, has_esp_tag is none -- no capture mechanism.",1,None),
("777","butforthem.com","Butforthem","Customer Engagement Opportunity",None,"Low",
 "US life-insurance agency (Babcock Ranch, FL).",
 20,20,40,20,50,
 "3 CTAs above the fold give a clear path.","Not a real retail cart (insurance agency).",
 "has_chat_widget is none across several insurance-policy types.",
 "has_email_form is true (evidence: 'Email *') -- a capture mechanism exists.",0,None),
("778","riseathletic.ma","Riseathletic","Follow-up Opportunity",None,"Low",
 "Moroccan boutique fitness studio (Casablanca).",
 40,15,20,45,50,
 "cta_count_above_fold is 0; 'COMMENT RESERVER' is a real CTA not counted.","Not a real retail cart (fitness studio).",
 "A Crisp chat widget is present.",
 "has_email_form is false -- no capture form was confirmed in the static markup, though a Mailchimp tag is loaded, suggesting one may exist dynamically.",0,None),
("779","luvaluaccessories.com","Luvaluaccessories","Customer Engagement Opportunity","Follow-up Opportunity","High",
 "Handcrafted jewelry e-commerce brand (Luvalu Accessories).",
 40,40,75,65,50,
 "Only 1 CTA above the fold despite an active discount code.","A popup script is present but has_esp_tag is none.",
 "has_chat_widget is none despite the page text showing a much larger real catalog (Bracelets 61, Necklaces 89, Earrings 23, Rings 8) than the structurally counted 20 products.",
 "has_email_form is false, has_contact_form is false, has_esp_tag is none -- no capture mechanism.",2,None),
("780","yovansudha.com","Yovansudha","Cart Recovery Opportunity",None,"Low",
 "Indian Ayurvedic men's wellness e-commerce brand.",
 15,35,20,15,50,
 "7 CTAs above the fold plus an active promo bar give a clear path.","A popup script is present but has_esp_tag is none, on a real 13-product catalog.",
 "WhatsApp chat widget is present.","has_email_form is true and has_contact_form is true (evidence: 'Your name') -- a capture mechanism exists.",0,None),
("782","www.4uviplogo.com","4Uviplogo","Not a Good Fit",None,"High",
 "Not determinable as a real business -- the page shows a visible PHP warning and generic Latin filler text, suggesting an unfinished WordPress theme demo.",
 50,50,50,50,50,
 "not determinable from available signals","not determinable from available signals","not determinable from available signals","not determinable from available signals",
 0,"Site shows a visible PHP warning ('Warning: Undefined array key...') and generic Latin filler copy -- appears to be an unfinished WordPress theme demo, not a live business."),
("783","colorblendco.com","Colorblendco","Conversion Opportunity",None,"Low",
 "Canadian art-studio cafe (paint-and-sip experiences, Kitchener).",
 40,20,35,10,50,
 "cta_count_above_fold is 0.","Not a real retail cart (studio-cafe hybrid).",
 "has_chat_widget is none across a moderate range of event types (sip & nib, private events, drop-in paints).",
 "has_email_form is true and has_contact_form is true with a Mailchimp ESP tag -- a capture mechanism exists.",0,None),
("784","natureenzo.com","Natureenzo","Customer Engagement Opportunity",None,"Low",
 "Indian luxury bath and body-care e-commerce brand.",
 15,30,55,50,50,
 "4 CTAs above the fold give a clear path.","A Mailchimp ESP tag and popup are present.",
 "has_chat_widget is none across a wide 33-product bath/body catalog.",
 "has_email_form is false -- no capture form was confirmed in the static markup, though a Mailchimp tag is loaded, suggesting one may exist dynamically.",0,None),
("785","www.thistleandcloth.com","Thistleandcloth","Cart Recovery Opportunity",None,"Low",
 "Scottish kilt and tartan dressmaker.",
 15,35,20,20,50,
 "5 CTAs above the fold give a clear path.","A popup script is present but has_esp_tag is none, on a small 3-product catalog.",
 "has_chat_widget is none on a narrow niche catalog.","has_email_form is true (evidence: 'Email Address') -- a capture mechanism exists.",0,None),
("786","freshhome.hu","Freshhome","Customer Engagement Opportunity","Follow-up Opportunity","High",
 "Hungarian ventilation/HVAC equipment e-commerce brand (B2B).",
 40,55,65,60,50,
 "cta_count_above_fold is 0; Hungarian detector miss likely.","has_popup_script is false and has_esp_tag is none -- no recovery mechanism.",
 "has_chat_widget is none across a wide, technical HVAC catalog (heat-recovery units, axial/centrifugal fans, filters, controllers).",
 "has_email_form is false, has_contact_form is false, has_esp_tag is none -- no capture mechanism.",2,None),
("787","dreamongallery.com","Dreamongallery","Cart Recovery Opportunity",None,"Medium",
 "US wall-art/canvas-print e-commerce brand (NYC-themed).",
 40,55,40,20,50,
 "2 CTAs above the fold.","has_popup_script is false and has_esp_tag is none on a real, decent-ticket ($299-439) art-print catalog -- no recovery mechanism.",
 "has_chat_widget is none across several art-theme categories.","has_email_form is true -- a capture mechanism exists.",0,None),
("788","aubouquets.ca","Aubouquets","Customer Engagement Opportunity",None,"Low",
 "Quebec florist.",
 40,40,55,20,50,
 "cta_count_above_fold is 0.","A popup script is present but has_esp_tag is none.",
 "has_chat_widget is none across a wide range of occasion/season categories.",
 "has_email_form is true (evidence: 'Email') -- a capture mechanism exists.",0,None),
("789","leafandiron.com","Leafandiron","Customer Engagement Opportunity",None,"Low",
 "US e-commerce brand (page text was dominated by Elementor builder CSS, obscuring the actual business content).",
 10,25,35,15,50,
 "14 CTAs above the fold, though the page text quality made them hard to verify in context.",
 "A Mailchimp ESP tag and popup are present.",
 "has_chat_widget is none; catalog width unclear due to CSS-polluted page text.",
 "has_email_form is true with a Mailchimp ESP tag -- a capture mechanism exists.",0,None),
("790","acasoulmusic.com","Acasoulmusic","Conversion Opportunity",None,"Low",
 "Gospel/soul music label and artist roster.",
 40,20,35,10,50,
 "2 CTAs above the fold.","Not a real retail cart (music label).",
 "has_chat_widget is none across an artist roster; moderate relevance.",
 "has_email_form is true and has_contact_form is true with a Mailchimp ESP tag -- a capture mechanism exists.",0,None),
("791","tintdizajn.hr","Tintdizajn","Follow-up Opportunity",None,"Low",
 "Croatian car window-tinting shop (page text was dominated by a login-form widget, obscuring the actual service content).",
 40,15,20,55,50,
 "cta_count_above_fold is 0; page content is mostly a login-form widget.","Not a real retail cart (tinting service).",
 "Service business, not a catalog; low relevance.",
 "has_email_form is false, has_contact_form is false, has_esp_tag is none -- no capture mechanism, though page text quality limits confidence.",1,None),
("792","serwissejfow.pl","Serwissejfow","Customer Engagement Opportunity",None,"Low",
 "Polish safe and vault repair/service business.",
 40,20,40,20,50,
 "cta_count_above_fold is 0.","Not a real retail cart (repair service).",
 "has_chat_widget is none across several service types (repair, emergency opening, lock replacement).",
 "has_email_form is true (evidence: 'Adres e-mail') -- a capture mechanism exists.",0,None),
("793","srederi.com","Srederi","Customer Engagement Opportunity",None,"Medium",
 "Balkan paper-shredder e-commerce brand (Dahle, HSM, Fellowes, Olympia).",
 40,40,60,20,50,
 "Only 1 CTA above the fold.","A popup script is present but has_esp_tag is none.",
 "has_chat_widget is none across 4 shredder brands spanning compact, office, and industrial models.",
 "has_email_form is true -- a capture mechanism exists.",0,None),
("794","ayoshin.com","Ayoshin","Insufficient Data",None,"Low",
 "Not determinable -- the fetched page is a gateway/proxy error ('upstream connect error'), not real business content.",
 50,50,50,50,50,
 "not determinable from available signals","not determinable from available signals","not determinable from available signals","not determinable from available signals",0,None),
("795","mobilityonthemove.co.uk","Mobilityonthemove","Insufficient Data",None,"Low",
 "Not determinable -- the fetched page returned no visible text content.",
 50,50,50,50,50,
 "not determinable from available signals","not determinable from available signals","not determinable from available signals","not determinable from available signals",0,None),
]

n = append_results(RESULTS)
print(f"appended {n} rows (chunk_004)")
