import sys
sys.path.insert(0, ".")
from layer3_write import append_results


def L(lead_id, domain, business_name, primary, confidence, summary,
      conv, cart, eng, followup, ci, ev_conv, ev_cart, ev_eng, ev_followup,
      open_gap_count, secondary=None, disqualifier=None):
    return (lead_id, domain, business_name, primary, secondary, confidence, summary,
            conv, cart, eng, followup, ci, ev_conv, ev_cart, ev_eng, ev_followup,
            open_gap_count, disqualifier)


RESULTS = [
L(911, "decopierrenature.com", "Decopierrenature", primary="Cart Recovery Opportunity", secondary="Follow-up Opportunity", confidence="medium",
  summary="French decorative stone/home-decor WooCommerce store (31 products, 6 brands).",
  conv=45, cart=65, eng=45, followup=55, ci=35,
  ev_conv="has_cart=True, no ESP", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="generic popup only, no chat/reviews", ev_followup="has_email_form=True but no ESP automation",
  open_gap_count=2),
L(912, "petiteminiaturepaws.com", "Petiteminiaturepaws", primary="Insufficient Data", confidence="low",
  summary="Domain resolved but page_text is empty and platform is unknown.",
  conv=50, cart=50, eng=50, followup=50, ci=50,
  ev_conv="page_text empty", ev_cart="has_cart=False (undetermined)",
  ev_eng="no signals extractable", ev_followup="no signals extractable",
  open_gap_count=0, disqualifier="empty/undetermined signals — cannot assess"),
L(913, "raquelholisticcoaching.com", "Raquelholisticcoaching", primary="Follow-up Opportunity", confidence="low",
  summary="Spanish holistic-coaching service with a small attached shop, but no lead-capture form or ESP.",
  conv=40, cart=30, eng=40, followup=55, ci=35,
  ev_conv="has_cart=True but small side-shop on a service-led coaching site", ev_cart="product_count_visible=6",
  ev_eng="no chat, no reviews", ev_followup="no email capture form detected for a coaching/consultation service",
  open_gap_count=2),
L(914, "osskaters.com", "Osskaters", primary="Cart Recovery Opportunity", secondary="Follow-up Opportunity", confidence="medium",
  summary="Vintage skateboarding-culture WooCommerce shop with no ESP.",
  conv=45, cart=65, eng=40, followup=55, ci=35,
  ev_conv="has_cart=True, no ESP", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="generic popup only, no chat/reviews", ev_followup="has_email_form=True but no ESP automation",
  open_gap_count=2),
L(915, "carrepertoire.com", "Carrepertoire", primary="Follow-up Opportunity", confidence="low",
  summary="US car-marketing/curating agency (B2B services, cart flag likely false-positive) with no lead-capture form.",
  conv=40, cart=20, eng=40, followup=55, ci=30,
  ev_conv="has_cart likely false-positive for a B2B marketing agency", ev_cart="product_count_visible=0",
  ev_eng="no chat, no reviews, cta_count_above_fold=4", ev_followup="no email or contact form detected",
  open_gap_count=1),
L(916, "timstoursnyc.com", "Timstoursnyc", primary="Cart Recovery Opportunity", secondary="Follow-up Opportunity", confidence="medium",
  summary="NYC walking-tour and taxi-booking WooCommerce site with booking and reviews already live.",
  conv=50, cart=60, eng=55, followup=60, ci=40,
  ev_conv="has_cart=True, no ESP", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="booking and reviews already present", ev_followup="has_email_form=True but no ESP automation",
  open_gap_count=2),
L(917, "am-devices.com", "Am-Devices", primary="Cart Recovery Opportunity", secondary="Follow-up Opportunity", confidence="medium",
  summary="Electronics/devices WooCommerce store with both email and contact forms but no ESP.",
  conv=45, cart=65, eng=40, followup=55, ci=35,
  ev_conv="has_cart=True, no ESP", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="generic popup only, no chat/reviews", ev_followup="has_email_form=True and has_contact_form=True but no ESP automation",
  open_gap_count=2),
L(919, "sandyrosesportcollections.com", "Sandyrosesportcollections", primary="Insufficient Data", confidence="low",
  summary="Domain resolved but page_text is empty and platform is unknown.",
  conv=50, cart=50, eng=50, followup=50, ci=50,
  ev_conv="page_text empty", ev_cart="has_cart=False (undetermined)",
  ev_eng="no signals extractable", ev_followup="no signals extractable",
  open_gap_count=0, disqualifier="empty/undetermined signals — cannot assess"),
L(920, "aacharyskitchen.com", "Aacharyskitchen", primary="Cart Recovery Opportunity", secondary="Follow-up Opportunity", confidence="medium",
  summary="Sri Lankan restaurant with online table reservation, reviews already live, but no ESP.",
  conv=50, cart=60, eng=55, followup=55, ci=40,
  ev_conv="has_cart=True, no ESP", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="reviews present, cta_count_above_fold=4, table-reservation flow in copy", ev_followup="has_email_form=True but no ESP automation",
  open_gap_count=2),
L(921, "morbistore.in", "Morbistore", primary="Cart Recovery Opportunity", secondary="Customer Engagement Opportunity", confidence="medium",
  summary="Indian grocery/household-goods WooCommerce marketplace with a large catalog (46 products) and active promo, but no capture form or ESP.",
  conv=45, cart=70, eng=50, followup=40, ci=35,
  ev_conv="has_cart=True, has_promo_bar=True, no ESP, 46 products", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="generic popup only, no chat/reviews", ev_followup="no email capture form detected despite active promo",
  open_gap_count=2),
L(922, "alassalicare.com", "Alassalicare", primary="Insufficient Data", confidence="medium",
  summary="Store launch is explicitly 'coming soon' (Arabic: preparing to launch) — not a live storefront.",
  conv=50, cart=50, eng=50, followup=50, ci=50,
  ev_conv="site not live (store launching soon)", ev_cart="has_cart=False, site inactive",
  ev_eng="no real content to evaluate engagement", ev_followup="no signals extractable — placeholder page",
  open_gap_count=0, disqualifier="site not live — 'coming soon' placeholder"),
L(923, "altheaagewell.com", "Altheaagewell", primary="Insufficient Data", confidence="low",
  summary="Domain resolved but page_text is empty and platform is unknown.",
  conv=50, cart=50, eng=50, followup=50, ci=50,
  ev_conv="page_text empty", ev_cart="has_cart=False (undetermined)",
  ev_eng="no signals extractable", ev_followup="no signals extractable",
  open_gap_count=0, disqualifier="empty/undetermined signals — cannot assess"),
L(924, "www.canadatradesupply.com", "Canadatradesupply", primary="Cart Recovery Opportunity", secondary="Follow-up Opportunity", confidence="medium",
  summary="Canadian industrial equipment distributor (22 brands) with WhatsApp chat and both email and contact forms, no ESP.",
  conv=50, cart=60, eng=50, followup=60, ci=40,
  ev_conv="has_cart=True, no ESP", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="WhatsApp chat present but no reviews", ev_followup="has_email_form=True and has_contact_form=True but no ESP automation",
  open_gap_count=2),
L(925, "hlcbrokers.com", "Hlcbrokers", primary="Follow-up Opportunity", confidence="medium",
  summary="Forex/CFD brokerage service (Kabul-based) with an email form but no ESP.",
  conv=45, cart=20, eng=40, followup=60, ci=40,
  ev_conv="has_cart=True likely false-positive for a financial brokerage service", ev_cart="product_count_visible=0",
  ev_eng="cta_count_above_fold=6", ev_followup="has_email_form=True but no ESP automation for high-value trading leads",
  open_gap_count=1),
L(926, "northernproxy.com", "Northernproxy", primary="Insufficient Data", confidence="high",
  summary="Page served an anti-bot verification challenge ('Verifying that you are not a robot') — no real content retrievable.",
  conv=50, cart=50, eng=50, followup=50, ci=50,
  ev_conv="bot-check page, no real content", ev_cart="has_cart=False (undetermined)",
  ev_eng="no signals extractable — verification wall", ev_followup="no signals extractable — verification wall",
  open_gap_count=0, disqualifier="anti-bot verification page — cannot assess real content"),
L(927, "customfoodtruck.org", "Customfoodtruck", primary="Not a Good Fit", confidence="medium",
  summary="Custom food-truck manufacturer already running Omnisend ESP, tawk chat, and reviews.",
  conv=20, cart=20, eng=30, followup=15, ci=25,
  ev_conv="Omnisend ESP + tawk chat already live", ev_cart="has_esp_tag=omnisend",
  ev_eng="chat widget and reviews already present", ev_followup="email capture and ESP already wired together",
  open_gap_count=1, disqualifier="already has ESP + chat + reviews stack in place"),
L(928, "notableservicegroup.com", "Notableservicegroup", primary="Follow-up Opportunity", confidence="medium",
  summary="US notary/administrative services firm with appointment booking and reviews already live, but no email-capture form.",
  conv=45, cart=25, eng=50, followup=55, ci=40,
  ev_conv="has_cart=True likely false-positive for a notary services firm", ev_cart="product_count_visible=0",
  ev_eng="booking and reviews already present, cta_count_above_fold=3", ev_followup="no email or contact form detected despite active booking flow",
  open_gap_count=1),
L(929, "taiceglobalservices.com", "Taiceglobalservices", primary="Follow-up Opportunity", confidence="medium",
  summary="Nigerian education/travel/business-services conglomerate with reviews already live but no ESP.",
  conv=45, cart=25, eng=45, followup=60, ci=40,
  ev_conv="has_cart=True likely false-positive for a multi-service business", ev_cart="product_count_visible=0",
  ev_eng="reviews present, cta_count_above_fold=3", ev_followup="has_email_form=True and has_contact_form=True but no ESP automation",
  open_gap_count=1),
L(930, "talariaebikeshop.com", "Talariaebikeshop", primary="Not a Good Fit", confidence="medium",
  summary="Electric-bike retailer already running Mailchimp ESP with reviews, active promo, and cta_count_above_fold=12.",
  conv=20, cart=20, eng=25, followup=15, ci=25,
  ev_conv="Mailchimp ESP already live, very high above-fold CTA count (12)", ev_cart="has_esp_tag=mailchimp",
  ev_eng="reviews and promo already present", ev_followup="email capture and ESP already wired together",
  open_gap_count=1, disqualifier="already has ESP + reviews + promo + strong CTA presence in place"),
L(931, "gunavibes.com", "Gunavibes", primary="Follow-up Opportunity", secondary="Cart Recovery Opportunity", confidence="low",
  summary="Panama (San Blas) tour-transport service with a Mailchimp ESP tag but no visible email-capture form to feed it.",
  conv=40, cart=40, eng=45, followup=45, ci=35,
  ev_conv="has_cart=True, has_esp_tag=mailchimp but has_email_form=False — ESP underused", ev_cart="has_esp_tag=mailchimp, has_email_form=False",
  ev_eng="cta_count_above_fold=6", ev_followup="ESP present but no capture mechanism visibly wired to it",
  open_gap_count=2),
L(932, "rb-community.com", "Rb-Community", primary="Follow-up Opportunity", confidence="medium",
  summary="US 55+ residential community/real-estate site (cart flag likely false-positive) with no email capture or ESP.",
  conv=40, cart=20, eng=40, followup=55, ci=35,
  ev_conv="has_cart=True likely false-positive for a real-estate community site", ev_cart="product_count_visible=0",
  ev_eng="no chat, no reviews", ev_followup="no email capture form detected for high-value property inquiries",
  open_gap_count=1),
L(933, "mstechnologies.us", "Mstechnologies", primary="Follow-up Opportunity", confidence="medium",
  summary="US IT/cybersecurity consulting B2B firm with no lead-capture form or ESP.",
  conv=40, cart=20, eng=40, followup=55, ci=35,
  ev_conv="has_cart=True likely false-positive for a B2B IT consulting firm", ev_cart="product_count_visible=0",
  ev_eng="no chat, no reviews, cta_count_above_fold=2", ev_followup="no email or contact form detected",
  open_gap_count=1),
L(934, "egmdistro.com", "Egmdistro", primary="Insufficient Data", confidence="low",
  summary="Domain resolved but page_text is empty and platform is unknown.",
  conv=50, cart=50, eng=50, followup=50, ci=50,
  ev_conv="page_text empty", ev_cart="has_cart=False (undetermined)",
  ev_eng="no signals extractable", ev_followup="no signals extractable",
  open_gap_count=0, disqualifier="empty/undetermined signals — cannot assess"),
L(935, "passionhealthcc.com", "Passionhealthcc", primary="Follow-up Opportunity", confidence="low",
  summary="US healthcare consultation service with no lead-capture form or ESP.",
  conv=40, cart=20, eng=40, followup=55, ci=35,
  ev_conv="has_cart=True likely false-positive for a healthcare consultation service", ev_cart="product_count_visible=0",
  ev_eng="generic popup only, cta_count_above_fold=1", ev_followup="no email or contact form detected",
  open_gap_count=1),
L(936, "carmelinasrestaurant.com", "Carmelinasrestaurant", primary="Not a Good Fit", confidence="medium",
  summary="Restaurant already running Mailchimp ESP with table booking and reviews already live.",
  conv=20, cart=20, eng=30, followup=15, ci=25,
  ev_conv="Mailchimp ESP already live", ev_cart="has_esp_tag=mailchimp",
  ev_eng="booking and reviews already present, multilingual site", ev_followup="email capture and ESP already wired together",
  open_gap_count=1, disqualifier="already has ESP + booking + reviews stack in place"),
L(937, "nigdevinc.net", "Nigdevinc", primary="Follow-up Opportunity", confidence="low",
  summary="Turkish crane/manlift rental B2B service with no lead-capture form or ESP.",
  conv=40, cart=20, eng=35, followup=55, ci=30,
  ev_conv="has_cart=True likely false-positive for a crane-rental service", ev_cart="product_count_visible=0",
  ev_eng="no chat, no reviews", ev_followup="no email or contact form detected",
  open_gap_count=1),
L(938, "onlybhutantour.com", "Onlybhutantour", primary="Insufficient Data", confidence="low",
  summary="Domain resolved but page_text is empty and platform is unknown.",
  conv=50, cart=50, eng=50, followup=50, ci=50,
  ev_conv="page_text empty", ev_cart="has_cart=False (undetermined)",
  ev_eng="no signals extractable", ev_followup="no signals extractable",
  open_gap_count=0, disqualifier="empty/undetermined signals — cannot assess"),
L(939, "luxvitta.com", "Luxvitta", primary="Insufficient Data", confidence="low",
  summary="Page fetched only raw JS framework boilerplate (Astro runtime code) — no readable business content extracted.",
  conv=50, cart=50, eng=50, followup=50, ci=50,
  ev_conv="page_text is JS boilerplate, no readable content", ev_cart="has_cart=False (undetermined)",
  ev_eng="no signals extractable from rendered content", ev_followup="no signals extractable from rendered content",
  open_gap_count=0, disqualifier="page content is unrendered JS boilerplate — cannot assess"),
L(940, "marasparlatemizlik.com", "Marasparlatemizlik", primary="Follow-up Opportunity", confidence="medium",
  summary="Turkish professional cleaning-services business with both email and contact forms but no ESP.",
  conv=45, cart=20, eng=40, followup=60, ci=35,
  ev_conv="has_cart=True likely false-positive for a cleaning services business", ev_cart="product_count_visible=0",
  ev_eng="generic popup only, no chat/reviews", ev_followup="has_email_form=True and has_contact_form=True but no ESP automation",
  open_gap_count=1),
L(941, "sitcomsa.com", "Sitcomsa", primary="Cart Recovery Opportunity", secondary="Follow-up Opportunity", confidence="medium",
  summary="Nicaraguan networking-equipment reseller (Mikrotik/Ubiquiti) WooCommerce store with both email and contact forms, no ESP.",
  conv=45, cart=60, eng=40, followup=55, ci=35,
  ev_conv="has_cart=True, no ESP", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="generic popup only, no chat/reviews", ev_followup="has_email_form=True and has_contact_form=True but no ESP automation",
  open_gap_count=2),
L(942, "comanprotecsas.com", "Comanprotecsas", primary="Follow-up Opportunity", confidence="low",
  summary="Engineering/infrastructure company site whose fetched copy includes filler/placeholder text, suggesting an unfinished build; email form present but no ESP.",
  conv=35, cart=20, eng=35, followup=45, ci=25,
  ev_conv="has_cart=True likely false-positive; page content includes apparent placeholder filler text", ev_cart="product_count_visible=0",
  ev_eng="reviews present but page content otherwise appears unfinished", ev_followup="has_email_form=True but no ESP automation",
  open_gap_count=1),
L(943, "innosolvesolutions.com", "Innosolvesolutions", primary="Follow-up Opportunity", confidence="medium",
  summary="US accounting/IT/digital-marketing B2B services firm with WhatsApp chat and reviews already live, but no ESP.",
  conv=45, cart=25, eng=50, followup=60, ci=40,
  ev_conv="has_cart=True likely false-positive for a B2B services firm", ev_cart="product_count_visible=0",
  ev_eng="WhatsApp chat and reviews already present, cta_count_above_fold=2", ev_followup="has_email_form=True and has_contact_form=True but no ESP automation",
  open_gap_count=1),
L(944, "blueridgemeds.com", "Blueridgemeds", primary="Insufficient Data", confidence="low",
  summary="Domain resolved but page_text is empty and platform is unknown.",
  conv=50, cart=50, eng=50, followup=50, ci=50,
  ev_conv="page_text empty", ev_cart="has_cart=False (undetermined)",
  ev_eng="no signals extractable", ev_followup="no signals extractable",
  open_gap_count=0, disqualifier="empty/undetermined signals — cannot assess"),
L(945, "vision-mosaique.com", "Vision-Mosaique", primary="Follow-up Opportunity", confidence="low",
  summary="French visual-content/video strategy agency (B2B services) with no lead-capture form or ESP.",
  conv=40, cart=20, eng=35, followup=50, ci=30,
  ev_conv="has_cart=True likely false-positive for a B2B creative agency", ev_cart="product_count_visible=0",
  ev_eng="no chat, no reviews", ev_followup="no email or contact form detected",
  open_gap_count=1),
L(947, "aacprofessionals.com", "Aacprofessionals", primary="Not a Good Fit", confidence="medium",
  summary="UK national accountancy firm already running Mailchimp ESP with cta_count_above_fold=7.",
  conv=20, cart=20, eng=30, followup=15, ci=25,
  ev_conv="Mailchimp ESP already live", ev_cart="has_esp_tag=mailchimp",
  ev_eng="cta_count_above_fold=7", ev_followup="email capture and ESP already wired together",
  open_gap_count=1, disqualifier="already has ESP + strong CTA presence in place"),
L(948, "tranquilstress.net", "Tranquilstress", primary="Cart Recovery Opportunity", secondary="Follow-up Opportunity", confidence="medium",
  summary="Online pharmacy with reviews already live and cta_count_above_fold=7, but no capture form or ESP.",
  conv=50, cart=65, eng=50, followup=45, ci=40,
  ev_conv="has_cart=True, no ESP", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="reviews present, cta_count_above_fold=7", ev_followup="no email capture form detected despite high engagement surface",
  open_gap_count=2),
L(949, "gunandamor.com", "Gunandamor", primary="Multi-Opportunity", confidence="medium",
  summary="Firearms/ammunition e-commerce store (20 products) with Tidio chat, reviews, promo bar, and high above-fold CTA count (11), but no capture form or ESP.",
  conv=55, cart=65, eng=55, followup=55, ci=45,
  ev_conv="has_cart=True, no ESP despite substantial engagement infrastructure", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="Tidio chat, reviews, promo bar, and cta_count_above_fold=11 already present", ev_followup="no email capture form detected despite strong engagement surface",
  open_gap_count=2),
L(950, "infengshui.com", "Infengshui", primary="Cart Recovery Opportunity", secondary="Follow-up Opportunity", confidence="medium",
  summary="Feng shui bracelets/products WooCommerce store with an active discount offer but no ESP.",
  conv=45, cart=65, eng=45, followup=55, ci=35,
  ev_conv="has_cart=True, no ESP", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="generic popup only, no chat/reviews, cta_count_above_fold=3", ev_followup="has_email_form=True but no ESP automation",
  open_gap_count=2),
L(951, "madebylalawatts.com", "Madebylalawatts", primary="Cart Recovery Opportunity", secondary="Follow-up Opportunity", confidence="medium",
  summary="Custom embroidered/graphic apparel WooCommerce store (17 products) with no ESP.",
  conv=45, cart=65, eng=40, followup=55, ci=35,
  ev_conv="has_cart=True, no ESP", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="no chat, no reviews, cta_count_above_fold=4", ev_followup="has_email_form=True but no ESP automation",
  open_gap_count=2),
L(952, "www.good4ulabs.com", "Good4Ulabs", primary="Follow-up Opportunity", confidence="medium",
  summary="US occupational health screening/DOT physical clinic with appointment booking already live but no ESP.",
  conv=45, cart=20, eng=45, followup=60, ci=40,
  ev_conv="has_cart=True likely false-positive for a clinical services provider", ev_cart="product_count_visible=0",
  ev_eng="booking already offered, cta_count_above_fold=1", ev_followup="has_email_form=True but no ESP automation for patient/employer leads",
  open_gap_count=1),
L(953, "thestellarcart.com", "Thestellarcart", primary="Cart Recovery Opportunity", secondary="Customer Engagement Opportunity", confidence="medium",
  summary="General-merchandise WooCommerce marketplace with a broad catalog (38 products) but no capture form or ESP.",
  conv=45, cart=70, eng=45, followup=35, ci=35,
  ev_conv="has_cart=True, no ESP, 38 products", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="generic popup only, no chat/reviews, cta_count_above_fold=3", ev_followup="no email capture form detected",
  open_gap_count=2),
L(954, "wahltonsaus.com", "Wahltonsaus", primary="Cart Recovery Opportunity", secondary="Customer Engagement Opportunity", confidence="medium",
  summary="Artisanal hot-sauce WooCommerce store with reviews already live but no capture form or ESP.",
  conv=45, cart=65, eng=45, followup=35, ci=35,
  ev_conv="has_cart=True, no ESP", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="reviews present, cta_count_above_fold=6", ev_followup="no email capture form detected",
  open_gap_count=2),
L(955, "kingscourtlocal.com", "Kingscourtlocal", primary="Follow-up Opportunity", confidence="low",
  summary="Local-business networking/subscription community platform with an email form but no ESP.",
  conv=40, cart=25, eng=40, followup=55, ci=35,
  ev_conv="has_cart=True likely false-positive for a membership community platform", ev_cart="product_count_visible=0",
  ev_eng="cta_count_above_fold=2", ev_followup="has_email_form=True but no ESP automation",
  open_gap_count=1),
L(956, "wildernesssmokehaus.com", "Wildernesssmokehaus", primary="Multi-Opportunity", confidence="medium",
  summary="Artisanal sausage/smoked-meats WooCommerce store with a very high above-fold CTA count (17), recently under new ownership, but no ESP.",
  conv=50, cart=65, eng=55, followup=55, ci=40,
  ev_conv="has_cart=True, no ESP, cta_count_above_fold=17", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="generic popup only, no reviews, but very strong above-fold CTA presence (17)", ev_followup="has_email_form=True but no ESP automation",
  open_gap_count=3),
L(958, "jobsiteshield.com", "Jobsiteshield", primary="Cart Recovery Opportunity", secondary="Follow-up Opportunity", confidence="medium",
  summary="Job-site security/monitoring equipment B2B WooCommerce store with tawk chat but no ESP.",
  conv=45, cart=60, eng=50, followup=55, ci=35,
  ev_conv="has_cart=True, no ESP", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="tawk chat present, cta_count_above_fold=2", ev_followup="has_email_form=True but no ESP automation",
  open_gap_count=2),
L(959, "ridetulum.com", "Ridetulum", primary="Not a Good Fit", confidence="medium",
  summary="Tulum jeep/scooter rental business already running Mailchimp ESP with both email and contact forms.",
  conv=25, cart=25, eng=30, followup=20, ci=30,
  ev_conv="Mailchimp ESP already live", ev_cart="has_esp_tag=mailchimp",
  ev_eng="generic popup capture already present", ev_followup="email capture and ESP already wired together",
  open_gap_count=1, disqualifier="already has ESP + capture forms in place"),
L(960, "newageceiling.in", "Newageceiling", primary="Cart Recovery Opportunity", secondary="Follow-up Opportunity", confidence="medium",
  summary="Indian ceiling-products B2B/quote-driven business with reviews already live but no ESP.",
  conv=45, cart=55, eng=45, followup=55, ci=35,
  ev_conv="has_cart=True, no ESP, thin catalog (1 product visible)", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="reviews present, cta_count_above_fold=2", ev_followup="has_email_form=True but no ESP automation",
  open_gap_count=2),
L(961, "kalyan-spirit.ru", "Kalyan-Spirit", primary="Cart Recovery Opportunity", secondary="Follow-up Opportunity", confidence="medium",
  summary="Russian hookah manufacturer/wholesaler WooCommerce store with WhatsApp chat but no ESP.",
  conv=45, cart=65, eng=50, followup=55, ci=35,
  ev_conv="has_cart=True, no ESP", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="WhatsApp chat present, active wholesale discount messaging", ev_followup="has_email_form=True but no ESP automation",
  open_gap_count=2),
L(963, "pompeyka.ru", "Pompeyka", primary="Cart Recovery Opportunity", secondary="Customer Engagement Opportunity", confidence="low",
  summary="Russian pizza restaurant online-ordering WooCommerce site (13 products).",
  conv=40, cart=65, eng=40, followup=35, ci=30,
  ev_conv="has_cart=True, no ESP", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="no chat, no reviews, no popup", ev_followup="no email capture form detected",
  open_gap_count=2),
L(964, "vitagenx.ro", "Vitagenx", primary="Cart Recovery Opportunity", secondary="Follow-up Opportunity", confidence="low",
  summary="Romanian supplements WooCommerce store with WhatsApp chat and reviews but no ESP.",
  conv=45, cart=60, eng=50, followup=55, ci=35,
  ev_conv="has_cart=True, no ESP", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="WhatsApp chat and reviews already present", ev_followup="no email capture form detected despite active chat",
  open_gap_count=2),
L(965, "sortedservice.in", "Sortedservice", primary="Not a Good Fit", confidence="medium",
  summary="Indian IT accessories/services business (computers, CCTV, taxation, SEO) already running Mailchimp ESP.",
  conv=25, cart=25, eng=30, followup=20, ci=30,
  ev_conv="Mailchimp ESP already live", ev_cart="has_esp_tag=mailchimp",
  ev_eng="multi-service business with several categories", ev_followup="email capture and ESP already wired together",
  open_gap_count=1, disqualifier="already has ESP tag present"),
L(966, "www.vivaanlifestyle.com", "Vivaanlifestyle", primary="Not a Good Fit", confidence="medium",
  summary="Lifestyle retailer (31 products) already running Mailchimp ESP with reviews and cta_count_above_fold=4.",
  conv=25, cart=25, eng=30, followup=20, ci=30,
  ev_conv="Mailchimp ESP already live", ev_cart="has_esp_tag=mailchimp",
  ev_eng="reviews present, cta_count_above_fold=4", ev_followup="email capture and ESP already wired together",
  open_gap_count=1, disqualifier="already has ESP + reviews stack in place"),
L(967, "danrelax.com", "Danrelax", primary="Not a Good Fit", confidence="medium",
  summary="Spanish mattress retailer already running Klaviyo ESP.",
  conv=25, cart=25, eng=30, followup=20, ci=30,
  ev_conv="Klaviyo ESP already live", ev_cart="has_esp_tag=klaviyo",
  ev_eng="no chat/reviews but ESP already handling automation", ev_followup="email capture and Klaviyo ESP already wired together",
  open_gap_count=1, disqualifier="already has ESP in place"),
L(968, "ratita-presumida.com", "Ratita-Presumida", primary="Cart Recovery Opportunity", secondary="Customer Engagement Opportunity", confidence="low",
  summary="WooCommerce store, product_count_visible=0 suggests thin page fetched, no ESP.",
  conv=40, cart=60, eng=40, followup=35, ci=30,
  ev_conv="has_cart=True, no ESP", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="generic popup only, no chat/reviews", ev_followup="no email capture form detected",
  open_gap_count=2),
L(969, "duratagroup.com", "Duratagroup", primary="Cart Recovery Opportunity", secondary="Follow-up Opportunity", confidence="medium",
  summary="Sports-nutrition/supplement store with active promo but no ESP.",
  conv=45, cart=65, eng=45, followup=55, ci=35,
  ev_conv="has_cart=True, has_promo_bar=True, no ESP", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="generic popup only, no chat/reviews", ev_followup="has_email_form=True but no ESP automation",
  open_gap_count=2),
]

n = append_results(RESULTS)
print(f"appended {n} rows (chunk_007)")
