import sys
sys.path.insert(0, ".")
from layer3_write import append_results


def L(lead_id, domain, business_name, primary, confidence, summary,
      conv, cart, eng, followup, ci, ev_conv, ev_cart, ev_eng, ev_followup,
      open_gap_count, secondary=None, disqualifier=None):
    return (lead_id, domain, business_name, primary, secondary, confidence, summary,
            conv, cart, eng, followup, ci, ev_conv, ev_cart, ev_eng, ev_followup,
            open_gap_count, disqualifier)


RESULTS = [
L(1171, "nashoutlet.com", "Nashoutlet", primary="Cart Recovery Opportunity", secondary="Follow-up Opportunity", confidence="medium",
  summary="General-merchandise marketplace with reviews and an active promo but no ESP.",
  conv=45, cart=65, eng=50, followup=55, ci=35,
  ev_conv="has_cart=True, no ESP", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="reviews present, active promo", ev_followup="has_email_form=True but no ESP automation",
  open_gap_count=2),
L(1172, "kingkebabish.com", "Kingkebabish", primary="Cart Recovery Opportunity", secondary="Customer Engagement Opportunity", confidence="low",
  summary="Restaurant WooCommerce ordering site, product_count_visible=0 and mostly CSS boilerplate in fetched copy.",
  conv=35, cart=55, eng=35, followup=30, ci=25,
  ev_conv="has_cart=True, no ESP; page content largely unrendered CSS boilerplate", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="cta_count_above_fold=2", ev_followup="no email capture form detected",
  open_gap_count=2),
L(1173, "glitzhair-germany.com", "Glitzhair-Germany", primary="Cart Recovery Opportunity", secondary="Follow-up Opportunity", confidence="medium",
  summary="German hair-extensions WooCommerce store with reviews already live but no ESP.",
  conv=45, cart=65, eng=45, followup=50, ci=35,
  ev_conv="has_cart=True, no ESP", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="reviews present but no chat", ev_followup="no email capture form detected despite reviews present",
  open_gap_count=2),
L(1174, "codeupschool.com", "Codeupschool", primary="Follow-up Opportunity", confidence="medium",
  summary="Coding-bootcamp with both email and contact forms and reviews already live, but no ESP.",
  conv=45, cart=25, eng=50, followup=60, ci=35,
  ev_conv="has_cart=True likely false-positive for an education/bootcamp business", ev_cart="product_count_visible=0",
  ev_eng="reviews present", ev_followup="has_email_form=True and has_contact_form=True but no ESP automation for enrollment leads",
  open_gap_count=1),
L(1175, "www.doorhanvrata.cz", "Doorhanvrata", primary="Cart Recovery Opportunity", secondary="Follow-up Opportunity", confidence="low",
  summary="Czech garage-door retailer WooCommerce store, product_count_visible=0 suggests thin page fetched.",
  conv=40, cart=60, eng=35, followup=50, ci=30,
  ev_conv="has_cart=True, no ESP", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="generic popup only, no chat/reviews", ev_followup="no email capture form detected",
  open_gap_count=2),
L(1176, "holsurub.ro", "Holsurub", primary="Cart Recovery Opportunity", secondary="Customer Engagement Opportunity", confidence="low",
  summary="Romanian WooCommerce store with mostly unrendered CSS boilerplate in fetched copy, no ESP.",
  conv=35, cart=55, eng=30, followup=30, ci=25,
  ev_conv="has_cart=True, no ESP; page content largely unrendered CSS boilerplate", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="no chat/reviews/popup capture confirmed", ev_followup="no email capture form detected",
  open_gap_count=2),
L(1177, "localtoursalicante.com", "Localtoursalicante", primary="Follow-up Opportunity", confidence="medium",
  summary="Spanish tour operator with WhatsApp chat but no email-capture form or ESP.",
  conv=45, cart=25, eng=45, followup=55, ci=35,
  ev_conv="has_cart=True likely false-positive for a tour-package business", ev_cart="product_count_visible=0",
  ev_eng="WhatsApp chat present, cta_count_above_fold=3", ev_followup="no email capture form detected despite active chat channel",
  open_gap_count=1),
L(1178, "decomashogar.cl", "Decomashogar", primary="Cart Recovery Opportunity", secondary="Follow-up Opportunity", confidence="medium",
  summary="Chilean furniture WooCommerce store with WhatsApp chat and an active promo but no ESP.",
  conv=45, cart=65, eng=50, followup=50, ci=35,
  ev_conv="has_cart=True, has_promo_bar=True, no ESP", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="WhatsApp chat present", ev_followup="no email capture form detected despite active chat and promo",
  open_gap_count=2),
L(1179, "lamba-velkoobchod.sk", "Lamba-Velkoobchod", primary="Cart Recovery Opportunity", secondary="Customer Engagement Opportunity", confidence="low",
  summary="Slovak herbal/wholesale products WooCommerce store, product_count_visible=0 suggests thin page fetched.",
  conv=40, cart=60, eng=35, followup=35, ci=30,
  ev_conv="has_cart=True, no ESP", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="no chat/reviews/popup", ev_followup="no email capture form detected",
  open_gap_count=2),
L(1180, "zostangroomerem.pl", "Zostangroomerem", primary="Cart Recovery Opportunity", secondary="Follow-up Opportunity", confidence="medium",
  summary="Polish dog-grooming courses and consulting business with an attached shop and reviews already live, but no ESP.",
  conv=45, cart=55, eng=50, followup=55, ci=35,
  ev_conv="has_cart=True, no ESP", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="reviews present", ev_followup="has_email_form=True but no ESP automation",
  open_gap_count=2),
L(1181, "www.tiendaonlinerives.com", "Tiendaonlinerives", primary="Cart Recovery Opportunity", secondary="Follow-up Opportunity", confidence="medium",
  summary="Spanish general-merchandise marketplace with WhatsApp chat but no ESP.",
  conv=45, cart=65, eng=50, followup=50, ci=35,
  ev_conv="has_cart=True, no ESP", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="WhatsApp chat present but no reviews", ev_followup="no email capture form detected despite active chat",
  open_gap_count=2),
L(1182, "thegoodroom.in", "Thegoodroom", primary="Cart Recovery Opportunity", secondary="Customer Engagement Opportunity", confidence="low",
  summary="Indian WooCommerce store with mostly unrendered CSS boilerplate in fetched copy, no ESP.",
  conv=35, cart=55, eng=30, followup=30, ci=25,
  ev_conv="has_cart=True, no ESP; page content largely unrendered CSS boilerplate", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="cta_count_above_fold=1", ev_followup="no email capture form detected",
  open_gap_count=2),
L(1183, "vibezcoffees.com", "Vibezcoffees", primary="Cart Recovery Opportunity", secondary="Customer Engagement Opportunity", confidence="low",
  summary="Coffee shop with an active promo but page copy includes apparent theme-demo boilerplate ('Home 2 Home 3...'), no ESP.",
  conv=35, cart=55, eng=35, followup=30, ci=25,
  ev_conv="has_cart=True, has_promo_bar=True, no ESP; page content includes apparent theme-demo navigation boilerplate", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="no chat/reviews/popup", ev_followup="no email capture form detected",
  open_gap_count=2),
L(1184, "s3woodworks.com", "S3Woodworks", primary="Insufficient Data", confidence="high",
  summary="Page served an obfuscated JS-based verification wall — no real content retrievable.",
  conv=50, cart=50, eng=50, followup=50, ci=50,
  ev_conv="bot-check/obfuscated verification page", ev_cart="has_cart=False (undetermined)",
  ev_eng="no signals extractable — verification wall", ev_followup="no signals extractable — verification wall",
  open_gap_count=0, disqualifier="anti-bot verification page — cannot assess real content"),
L(1185, "excavatorscheaper.com", "Excavatorscheaper", primary="Insufficient Data", confidence="high",
  summary="Site returns a PHP fatal error (uncaught TypeError in advanced-cache.php) — no usable content retrievable.",
  conv=50, cart=50, eng=50, followup=50, ci=50,
  ev_conv="PHP fatal error page", ev_cart="has_cart=False (undetermined)",
  ev_eng="no signals extractable — site is broken", ev_followup="no signals extractable — site is broken",
  open_gap_count=0, disqualifier="site returns a PHP fatal error — cannot assess"),
L(1186, "bizneshair.pl", "Bizneshair", primary="Follow-up Opportunity", confidence="medium",
  summary="Polish hair/trichology education and consulting business with an email form but no ESP.",
  conv=45, cart=25, eng=40, followup=55, ci=35,
  ev_conv="has_cart=True likely false-positive for an education/consulting business", ev_cart="product_count_visible=0",
  ev_eng="no chat/reviews/popup", ev_followup="has_email_form=True but no ESP automation",
  open_gap_count=1),
L(1187, "mm-baitservice.hu", "Mm-Baitservice", primary="Cart Recovery Opportunity", secondary="Customer Engagement Opportunity", confidence="low",
  summary="Hungarian fishing-bait WooCommerce store, product_count_visible=0 suggests thin page fetched.",
  conv=40, cart=60, eng=35, followup=30, ci=25,
  ev_conv="has_cart=True, no ESP", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="no chat/reviews/popup", ev_followup="no email capture form detected",
  open_gap_count=2),
L(1188, "anuskart.com", "Anuskart", primary="Insufficient Data", confidence="high",
  summary="Page explicitly states 'This is a demo store for testing purposes — no orders shall be fulfilled' — not a real live business.",
  conv=50, cart=50, eng=50, followup=50, ci=50,
  ev_conv="page explicitly labeled as a demo/test store", ev_cart="not a real storefront",
  ev_eng="not a real storefront", ev_followup="not a real storefront",
  open_gap_count=0, disqualifier="site explicitly labeled a demo/test store — not a real business"),
L(1189, "tpmkw.com", "Tpmkw", primary="Not a Good Fit", confidence="medium",
  summary="Kuwaiti plastic-manufacturing B2B company already running Mailchimp ESP.",
  conv=25, cart=20, eng=30, followup=20, ci=30,
  ev_conv="has_cart=True likely false-positive for a manufacturing B2B business", ev_cart="has_esp_tag=mailchimp",
  ev_eng="no chat/reviews", ev_followup="email capture and ESP already wired together",
  open_gap_count=1, disqualifier="already has ESP in place"),
L(1191, "iiptexas.com", "Iiptexas", primary="Cart Recovery Opportunity", secondary="Follow-up Opportunity", confidence="medium",
  summary="Texas insulation-supplies B2B WooCommerce store with no ESP.",
  conv=45, cart=55, eng=35, followup=55, ci=35,
  ev_conv="has_cart=True, no ESP", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="no chat/reviews/popup", ev_followup="has_email_form=True but no ESP automation",
  open_gap_count=2),
L(1193, "dimensionalacademy.in", "Dimensionalacademy", primary="Follow-up Opportunity", confidence="low",
  summary="Indian consulting/coaching academy with both email and contact forms and reviews already live, but no ESP; page copy includes apparent lorem-ipsum filler text.",
  conv=40, cart=25, eng=45, followup=50, ci=30,
  ev_conv="has_cart=True likely false-positive for a coaching/consulting academy", ev_cart="product_count_visible=0",
  ev_eng="reviews present but page content includes apparent placeholder filler text", ev_followup="has_email_form=True and has_contact_form=True but no ESP automation",
  open_gap_count=1),
L(1194, "pescayalgomas.com", "Pescayalgomas", primary="Not a Good Fit", confidence="medium",
  summary="Mexican fishing-gear WooCommerce store already running Brevo ESP.",
  conv=25, cart=20, eng=30, followup=20, ci=30,
  ev_conv="Brevo ESP already live", ev_cart="has_esp_tag=brevo",
  ev_eng="no chat/reviews", ev_followup="email capture and Brevo ESP already wired together",
  open_gap_count=1, disqualifier="already has ESP in place"),
L(1195, "amazontambopatatours.com", "Amazontambopatatours", primary="Follow-up Opportunity", confidence="medium",
  summary="Peruvian Amazon eco-tour operator with no lead-capture form or ESP.",
  conv=40, cart=20, eng=35, followup=55, ci=30,
  ev_conv="has_cart=True likely false-positive for a tour-package business", ev_cart="product_count_visible=0",
  ev_eng="cta_count_above_fold=1", ev_followup="no email or contact form detected for high-value tour inquiries",
  open_gap_count=1),
L(1196, "minipipolis.com", "Minipipolis", primary="Insufficient Data", confidence="low",
  summary="Domain resolved but page_text is empty and platform is unknown.",
  conv=50, cart=50, eng=50, followup=50, ci=50,
  ev_conv="page_text empty", ev_cart="has_cart=False (undetermined)",
  ev_eng="no signals extractable", ev_followup="no signals extractable",
  open_gap_count=0, disqualifier="empty/undetermined signals — cannot assess"),
L(1197, "smprevive.com", "Smprevive", primary="Follow-up Opportunity", confidence="low",
  summary="Japanese tools retailer (25th anniversary brand) with no cart function detected and no lead-capture form or ESP.",
  conv=30, cart=15, eng=30, followup=40, ci=25,
  ev_conv="has_cart=False despite shopify platform — page may be an informational/anniversary landing page", ev_cart="has_cart=False",
  ev_eng="no chat/reviews/popup", ev_followup="no email capture form detected",
  open_gap_count=1),
L(1198, "max-foam.com", "Max-Foam", primary="Cart Recovery Opportunity", secondary="Follow-up Opportunity", confidence="medium",
  summary="UAE foam-manufacturing B2B WooCommerce store with WhatsApp chat but no ESP.",
  conv=45, cart=55, eng=50, followup=50, ci=35,
  ev_conv="has_cart=True, no ESP", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="WhatsApp chat already present, cta_count_above_fold=2", ev_followup="no email capture form detected despite active chat",
  open_gap_count=2),
L(1200, "tyre.com.sg", "Tyre", primary="Insufficient Data", confidence="low",
  summary="Domain resolved but page_text is empty and platform is unknown.",
  conv=50, cart=50, eng=50, followup=50, ci=50,
  ev_conv="page_text empty", ev_cart="has_cart=False (undetermined)",
  ev_eng="no signals extractable", ev_followup="no signals extractable",
  open_gap_count=0, disqualifier="empty/undetermined signals — cannot assess"),
L(1201, "speedysealnotary.com", "Speedysealnotary", primary="Not a Good Fit", confidence="medium",
  summary="Notary services business already running Mailchimp ESP.",
  conv=25, cart=20, eng=30, followup=20, ci=30,
  ev_conv="has_cart=True likely false-positive for a notary services business", ev_cart="has_esp_tag=mailchimp",
  ev_eng="no chat/reviews", ev_followup="email capture and ESP already wired together",
  open_gap_count=1, disqualifier="already has ESP in place"),
L(1202, "redrhinonuts.com", "Redrhinonuts", primary="Cart Recovery Opportunity", secondary="Customer Engagement Opportunity", confidence="medium",
  summary="Specialty pili-nuts WooCommerce store (conservation-cause brand) with no capture form or ESP.",
  conv=40, cart=60, eng=40, followup=35, ci=30,
  ev_conv="has_cart=True, no ESP", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="generic popup only, no chat/reviews, cta_count_above_fold=2", ev_followup="no email capture form detected",
  open_gap_count=2),
L(1203, "mkombelogistics.com", "Mkombelogistics", primary="Insufficient Data", confidence="low",
  summary="Domain resolved but page_text is empty and platform is unknown.",
  conv=50, cart=50, eng=50, followup=50, ci=50,
  ev_conv="page_text empty", ev_cart="has_cart=False (undetermined)",
  ev_eng="no signals extractable", ev_followup="no signals extractable",
  open_gap_count=0, disqualifier="empty/undetermined signals — cannot assess"),
L(1204, "zandeproject.com", "Zandeproject", primary="Cart Recovery Opportunity", secondary="Customer Engagement Opportunity", confidence="low",
  summary="Fashion WooCommerce store (dresses, co-ords), product_count_visible=0 suggests thin page fetched.",
  conv=40, cart=60, eng=35, followup=30, ci=25,
  ev_conv="has_cart=True, no ESP", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="cta_count_above_fold=1, no chat/reviews", ev_followup="no email capture form detected",
  open_gap_count=2),
L(1205, "szolbob.hu", "Szolbob", primary="Cart Recovery Opportunity", secondary="Customer Engagement Opportunity", confidence="low",
  summary="Hungarian doors/windows WooCommerce store, product_count_visible=0 suggests thin page fetched.",
  conv=40, cart=60, eng=35, followup=30, ci=25,
  ev_conv="has_cart=True, no ESP", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="generic popup only, no chat/reviews", ev_followup="no email capture form detected",
  open_gap_count=2),
L(1206, "hmdigisolution.com", "Hmdigisolution", primary="Follow-up Opportunity", confidence="medium",
  summary="SEO/digital-marketing agency B2B with tawk chat and reviews already live, but no ESP.",
  conv=45, cart=25, eng=50, followup=60, ci=35,
  ev_conv="has_cart=True likely false-positive for a B2B marketing agency", ev_cart="product_count_visible=0",
  ev_eng="tawk chat and reviews already present", ev_followup="has_email_form=True but no ESP automation",
  open_gap_count=1),
L(1207, "www.zenvital.si", "Zenvital", primary="Follow-up Opportunity", secondary="Cart Recovery Opportunity", confidence="medium",
  summary="Slovenian Pilates/reformer studio (multi-location) with both email and contact forms but no ESP.",
  conv=45, cart=40, eng=40, followup=55, ci=35,
  ev_conv="has_cart=True but this is a fitness-studio class-booking business", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="no chat/reviews/popup", ev_followup="has_email_form=True and has_contact_form=True but no ESP automation for class-booking leads",
  open_gap_count=2),
L(1208, "theskintist.co.za", "Theskintist", primary="Insufficient Data", confidence="high",
  summary="Page served an anti-bot verification challenge — no real content retrievable.",
  conv=50, cart=50, eng=50, followup=50, ci=50,
  ev_conv="bot-check page, no real content", ev_cart="has_cart=False (undetermined)",
  ev_eng="no signals extractable — verification wall", ev_followup="no signals extractable — verification wall",
  open_gap_count=0, disqualifier="anti-bot verification page — cannot assess real content"),
L(1209, "north-arib.com", "North-Arib", primary="Follow-up Opportunity", confidence="low",
  summary="Saudi IT/smart-city solutions B2B provider with no lead-capture form or ESP.",
  conv=40, cart=20, eng=35, followup=50, ci=30,
  ev_conv="has_cart=True likely false-positive for a B2B IT solutions provider", ev_cart="product_count_visible=0",
  ev_eng="no chat, no reviews", ev_followup="no email or contact form detected",
  open_gap_count=1),
L(1211, "technaxon.com", "Technaxon", primary="Follow-up Opportunity", confidence="medium",
  summary="Pakistani IT/digital-transformation B2B agency with reviews already live but no ESP.",
  conv=45, cart=25, eng=45, followup=60, ci=35,
  ev_conv="has_cart=True likely false-positive for a B2B IT agency", ev_cart="product_count_visible=0",
  ev_eng="reviews present", ev_followup="has_email_form=True and has_contact_form=True but no ESP automation",
  open_gap_count=1),
L(1212, "ceainspection.com", "Ceainspection", primary="Follow-up Opportunity", confidence="medium",
  summary="B2B inspection services provider with a high above-fold CTA count (6) but no lead-capture form or ESP.",
  conv=45, cart=20, eng=45, followup=55, ci=30,
  ev_conv="has_cart=True likely false-positive for a B2B inspection services business", ev_cart="product_count_visible=0",
  ev_eng="cta_count_above_fold=6", ev_followup="no email or contact form detected for a quote-request business",
  open_gap_count=1),
L(1213, "vaziri.club", "Vaziri", primary="Cart Recovery Opportunity", secondary="Follow-up Opportunity", confidence="low",
  summary="Brewery/restaurant with table booking already offered but no email-capture form or ESP.",
  conv=40, cart=40, eng=40, followup=45, ci=30,
  ev_conv="has_cart=True but this is a brewery/restaurant, not physical-goods e-commerce", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="booking already offered, cta_count_above_fold=2", ev_followup="no email capture form detected despite active booking flow",
  open_gap_count=2),
L(1214, "printinventory.co.za", "Printinventory", primary="Insufficient Data", confidence="high",
  summary="Site explicitly states 'Pardon our dust! We're working on something amazing — check back soon!' — not yet live.",
  conv=50, cart=50, eng=50, followup=50, ci=50,
  ev_conv="site explicitly under construction", ev_cart="has_cart=True flagged but site is not live",
  ev_eng="no real content to evaluate — placeholder page", ev_followup="no real content to evaluate — placeholder page",
  open_gap_count=0, disqualifier="site under construction — 'coming soon' placeholder"),
L(1215, "almondgainworld.com", "Almondgainworld", primary="Cart Recovery Opportunity", secondary="Customer Engagement Opportunity", confidence="medium",
  summary="Nigerian men's/women's health supplements WooCommerce store with a high above-fold CTA count (6) but no capture form or ESP.",
  conv=45, cart=65, eng=45, followup=35, ci=35,
  ev_conv="has_cart=True, no ESP, cta_count_above_fold=6", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="generic popup only, no chat/reviews despite high above-fold CTA count", ev_followup="no email capture form detected",
  open_gap_count=2),
L(1216, "loopshop.se", "Loopshop", primary="Insufficient Data", confidence="high",
  summary="Gateway/upstream connection-timeout error — no content retrievable.",
  conv=50, cart=50, eng=50, followup=50, ci=50,
  ev_conv="upstream connection timeout", ev_cart="has_cart=False (undetermined)",
  ev_eng="no signals extractable — gateway error", ev_followup="no signals extractable — gateway error",
  open_gap_count=0, disqualifier="upstream gateway error — cannot assess"),
L(1217, "giter.ie", "Giter", primary="Cart Recovery Opportunity", secondary="Follow-up Opportunity", confidence="medium",
  summary="Irish perfumes/cosmetics WooCommerce store (23 products) with reviews already live but no ESP.",
  conv=45, cart=65, eng=45, followup=55, ci=35,
  ev_conv="has_cart=True, no ESP", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="reviews present, cta_count_above_fold=3", ev_followup="has_email_form=True but no ESP automation",
  open_gap_count=2),
L(1218, "bibiotic.ro", "Bibiotic", primary="Cart Recovery Opportunity", secondary="Customer Engagement Opportunity", confidence="low",
  summary="Romanian WooCommerce store (46 products) with reviews already live, but page copy is mostly unrendered CSS boilerplate, no ESP.",
  conv=40, cart=60, eng=40, followup=30, ci=30,
  ev_conv="has_cart=True, no ESP; page content largely unrendered CSS boilerplate", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="reviews present despite thin readable content", ev_followup="no email capture form detected",
  open_gap_count=2),
L(1219, "bluecompostinvestments.com", "Bluecompostinvestments", primary="Not a Good Fit", confidence="medium",
  summary="South African fertilizer/animal-feed B2B retailer already running Mailchimp ESP with reviews and an active promo.",
  conv=25, cart=20, eng=30, followup=20, ci=30,
  ev_conv="Mailchimp ESP already live", ev_cart="has_esp_tag=mailchimp",
  ev_eng="reviews present, active promo, cta_count_above_fold=2", ev_followup="email capture and ESP already wired together",
  open_gap_count=1, disqualifier="already has ESP + reviews + active promo in place"),
L(1220, "taniaericher.com", "Taniaericher", primary="Cart Recovery Opportunity", secondary="Follow-up Opportunity", confidence="low",
  summary="French artist's online shop (paintings, photography, 5 products) with no ESP.",
  conv=40, cart=55, eng=30, followup=45, ci=30,
  ev_conv="has_cart=True, no ESP", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="no chat/reviews/popup", ev_followup="has_email_form=True but no ESP automation",
  open_gap_count=2),
L(1221, "b2bredsnake.pl", "B2Bredsnake", primary="Cart Recovery Opportunity", secondary="Follow-up Opportunity", confidence="low",
  summary="Polish heating/ventilation B2B WooCommerce store, product_count_visible=0 suggests thin page fetched.",
  conv=40, cart=60, eng=35, followup=50, ci=30,
  ev_conv="has_cart=True, no ESP", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="generic popup only, no chat/reviews", ev_followup="has_email_form=True but no ESP automation",
  open_gap_count=2),
L(1222, "hartechsolutions.com", "Hartechsolutions", primary="Insufficient Data", confidence="low",
  summary="Domain resolved but page_text is empty and platform is unknown.",
  conv=50, cart=50, eng=50, followup=50, ci=50,
  ev_conv="page_text empty", ev_cart="has_cart=False (undetermined)",
  ev_eng="no signals extractable", ev_followup="no signals extractable",
  open_gap_count=0, disqualifier="empty/undetermined signals — cannot assess"),
L(1223, "shriekaa.in", "Shriekaa", primary="Follow-up Opportunity", confidence="low",
  summary="Indian WooCommerce store with reviews already live, but a beehive-pro.com theme-demo author reference in raw code suggests possible template origin; no ESP.",
  conv=40, cart=45, eng=45, followup=50, ci=30,
  ev_conv="has_cart=True, no ESP; page metadata references a beehive-pro.com theme demo domain", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="reviews present, cta_count_above_fold=4", ev_followup="has_email_form=True but no ESP automation; theme-demo origin lowers confidence",
  open_gap_count=2),
L(1224, "neutemu.com", "Neutemu", primary="Insufficient Data", confidence="low",
  summary="Page content is entirely unrendered dark-mode-toggle JS boilerplate — no readable business content extracted.",
  conv=50, cart=50, eng=50, followup=50, ci=50,
  ev_conv="page_text is JS boilerplate, no readable content", ev_cart="has_cart=False",
  ev_eng="no signals extractable from rendered content", ev_followup="no signals extractable from rendered content",
  open_gap_count=0, disqualifier="page content is unrendered JS boilerplate — cannot assess"),
L(1225, "loadcarhauler.com", "Loadcarhauler", primary="Follow-up Opportunity", secondary="Cart Recovery Opportunity", confidence="medium",
  summary="Car-shipping/logistics B2B platform (dealers, brokers, carriers) with both email and contact forms but no ESP.",
  conv=45, cart=40, eng=40, followup=55, ci=35,
  ev_conv="has_cart=True but this is a logistics-services marketplace, not physical goods", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="cta_count_above_fold=1", ev_followup="has_email_form=True and has_contact_form=True but no ESP automation",
  open_gap_count=2),
L(1226, "concretekothon.com", "Concretekothon", primary="Cart Recovery Opportunity", secondary="Follow-up Opportunity", confidence="low",
  summary="Plant-care shop with booking already offered, but page copy includes apparent 'eCommerce WordPress Themes' theme-demo boilerplate; no ESP.",
  conv=35, cart=50, eng=40, followup=40, ci=25,
  ev_conv="has_cart=True, no ESP; page content includes apparent theme-demo boilerplate text", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="booking already offered, cta_count_above_fold=4", ev_followup="no email capture form detected; theme-demo origin lowers confidence",
  open_gap_count=2),
L(1227, "mrmtimbercrafter.ie", "Mrmtimbercrafter", primary="Cart Recovery Opportunity", secondary="Follow-up Opportunity", confidence="medium",
  summary="Irish timber/fencing-products WooCommerce store (21 products) with both email and contact forms but no ESP.",
  conv=45, cart=60, eng=40, followup=55, ci=35,
  ev_conv="has_cart=True, no ESP", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="generic popup only, no chat/reviews", ev_followup="has_email_form=True and has_contact_form=True but no ESP automation",
  open_gap_count=2),
L(1228, "hikanzu.com", "Hikanzu", primary="Cart Recovery Opportunity", secondary="Follow-up Opportunity", confidence="low",
  summary="WooCommerce store (13 products) with both email and contact forms, but fetched copy includes obfuscated JS decode logic mixed into the content; no ESP.",
  conv=40, cart=55, eng=40, followup=50, ci=30,
  ev_conv="has_cart=True, no ESP; page content includes obfuscated JS artifacts", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="cta_count_above_fold=5", ev_followup="has_email_form=True and has_contact_form=True but no ESP automation",
  open_gap_count=2),
L(1229, "consortium1.co", "Consortium1", primary="Not a Good Fit", confidence="medium",
  summary="B2B brand/digital-experience agency already running Mailchimp ESP with booking already offered.",
  conv=25, cart=15, eng=35, followup=20, ci=30,
  ev_conv="has_cart=False — B2B agency, cart recovery not applicable", ev_cart="has_esp_tag=mailchimp",
  ev_eng="booking already offered, cta_count_above_fold=4", ev_followup="email capture and ESP already wired together",
  open_gap_count=1, disqualifier="already has ESP + booking flow in place"),
]

n = append_results(RESULTS)
print(f"appended {n} rows (chunk_011)")
