import sys
sys.path.insert(0, ".")
from layer3_write import append_results


def L(lead_id, domain, business_name, primary, confidence, summary,
      conv, cart, eng, followup, ci, ev_conv, ev_cart, ev_eng, ev_followup,
      open_gap_count, secondary=None, disqualifier=None):
    return (lead_id, domain, business_name, primary, secondary, confidence, summary,
            conv, cart, eng, followup, ci, ev_conv, ev_cart, ev_eng, ev_followup,
            open_gap_count, disqualifier)


RESULTS = [
L(1411, "masseriamarcantonio.com", "Masseriamarcantonio", primary="Follow-up Opportunity", confidence="low",
  summary="Italian Puglia agriturismo/farmhouse stay with no lead-capture form or ESP.",
  conv=40, cart=20, eng=30, followup=50, ci=30,
  ev_conv="has_cart=True likely false-positive for a stay-booking business", ev_cart="product_count_visible=0",
  ev_eng="no chat/reviews/popup", ev_followup="no email or contact form detected for high-value stay inquiries",
  open_gap_count=1),
L(1412, "rewardforadventure.com", "Rewardforadventure", primary="Not a Good Fit", confidence="medium",
  summary="Craft-spirits (gin) retailer already running Mailchimp ESP with reviews.",
  conv=25, cart=20, eng=30, followup=20, ci=30,
  ev_conv="Mailchimp ESP already live", ev_cart="has_esp_tag=mailchimp",
  ev_eng="reviews present", ev_followup="email capture and ESP already wired together",
  open_gap_count=1, disqualifier="already has ESP + reviews stack in place"),
L(1413, "bettinsolishotguns.com", "Bettinsolishotguns", primary="Cart Recovery Opportunity", secondary="Customer Engagement Opportunity", confidence="medium",
  summary="Firearms manufacturer/dealer with a high above-fold CTA count (10) but no capture form or ESP.",
  conv=45, cart=60, eng=40, followup=35, ci=30,
  ev_conv="has_cart=True, no ESP, cta_count_above_fold=10", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="no chat/reviews/popup despite high above-fold CTA count", ev_followup="no email capture form detected",
  open_gap_count=2),
L(1414, "arkedia.co.uk", "Arkedia", primary="Follow-up Opportunity", confidence="low",
  summary="UK digital-studio agency (web/software/AI) with a 'free quote' CTA but no lead-capture form or ESP.",
  conv=40, cart=20, eng=35, followup=50, ci=30,
  ev_conv="has_cart=False — B2B digital agency", ev_cart="has_cart=False",
  ev_eng="cta_count_above_fold=4", ev_followup="no email or contact form detected behind the 'free quote' CTA",
  open_gap_count=1),
L(1415, "nasp.cl", "Nasp", primary="Insufficient Data", confidence="medium",
  summary="Page fetched only a JS bootstrap loader referencing site.json/team.json data files — no readable business content extracted.",
  conv=50, cart=50, eng=50, followup=50, ci=50,
  ev_conv="page_text is JS bootstrap loader, no readable content", ev_cart="has_cart=False",
  ev_eng="no signals extractable from rendered content", ev_followup="no signals extractable from rendered content",
  open_gap_count=0, disqualifier="page content is unrendered JS bootstrap loader — cannot assess"),
L(1416, "taitaiva.com", "Taitaiva", primary="Follow-up Opportunity", confidence="low",
  summary="BPO/virtual-assistant services provider with booking and reviews already live, but no ESP.",
  conv=40, cart=20, eng=40, followup=50, ci=30,
  ev_conv="has_cart=True likely false-positive for a B2B outsourcing service", ev_cart="product_count_visible=0",
  ev_eng="booking and reviews already present, cta_count_above_fold=1", ev_followup="no email capture form detected despite active booking flow",
  open_gap_count=1),
L(1417, "ueluc.com", "Ueluc", primary="Insufficient Data", confidence="high",
  summary="Page served an obfuscated JS-based verification wall — no real content retrievable.",
  conv=50, cart=50, eng=50, followup=50, ci=50,
  ev_conv="bot-check/obfuscated verification page", ev_cart="has_cart=False (undetermined)",
  ev_eng="no signals extractable — verification wall", ev_followup="no signals extractable — verification wall",
  open_gap_count=0, disqualifier="anti-bot verification page — cannot assess real content"),
L(1418, "festivalchai.co.uk", "Festivalchai", primary="Insufficient Data", confidence="low",
  summary="Domain resolved but page_text is empty and platform is unknown.",
  conv=50, cart=50, eng=50, followup=50, ci=50,
  ev_conv="page_text empty", ev_cart="has_cart=False (undetermined)",
  ev_eng="no signals extractable", ev_followup="no signals extractable",
  open_gap_count=0, disqualifier="empty/undetermined signals — cannot assess"),
L(1419, "albertacustom.ca", "Albertacustom", primary="Not a Good Fit", confidence="medium",
  summary="Canadian business already running Omnisend ESP with both email and contact forms.",
  conv=25, cart=20, eng=30, followup=20, ci=30,
  ev_conv="Omnisend ESP already live", ev_cart="has_esp_tag=omnisend",
  ev_eng="no chat/reviews", ev_followup="email capture and ESP already wired together",
  open_gap_count=1, disqualifier="already has ESP in place"),
L(1420, "beardedceejaay.com", "Beardedceejaay", primary="Cart Recovery Opportunity", secondary="Customer Engagement Opportunity", confidence="medium",
  summary="Activewear-apparel WooCommerce store (5 products) with no capture form or ESP.",
  conv=40, cart=60, eng=35, followup=30, ci=30,
  ev_conv="has_cart=True, no ESP", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="generic popup only, no chat/reviews, cta_count_above_fold=2", ev_followup="no email capture form detected",
  open_gap_count=2),
L(1421, "vantveld.be", "Vantveld", primary="Cart Recovery Opportunity", secondary="Follow-up Opportunity", confidence="low",
  summary="Belgian local-produce farm-shop WooCommerce store, product_count_visible=0 suggests thin page fetched.",
  conv=40, cart=55, eng=30, followup=45, ci=30,
  ev_conv="has_cart=True, no ESP", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="generic popup only, no chat/reviews", ev_followup="has_email_form=True but no ESP automation",
  open_gap_count=2),
L(1422, "colwellbrothers.ie", "Colwellbrothers", primary="Insufficient Data", confidence="low",
  summary="Domain resolved but page_text is empty and platform is unknown.",
  conv=50, cart=50, eng=50, followup=50, ci=50,
  ev_conv="page_text empty", ev_cart="has_cart=False (undetermined)",
  ev_eng="no signals extractable", ev_followup="no signals extractable",
  open_gap_count=0, disqualifier="empty/undetermined signals — cannot assess"),
L(1423, "tutifruticl.cl", "Tutifruticl", primary="Follow-up Opportunity", confidence="low",
  summary="Chilean content-creation/social-media B2B agency with both email and contact forms and booking already live, but no ESP.",
  conv=40, cart=20, eng=40, followup=50, ci=30,
  ev_conv="has_cart=True likely false-positive for a B2B creative agency", ev_cart="product_count_visible=0",
  ev_eng="booking already offered, cta_count_above_fold=2", ev_followup="has_email_form=True and has_contact_form=True but no ESP automation",
  open_gap_count=1),
L(1424, "socialflute.com", "Socialflute", primary="Follow-up Opportunity", secondary="Cart Recovery Opportunity", confidence="low",
  summary="Indian social-media services business with an attached shop, WhatsApp chat, and reviews already live, but no ESP.",
  conv=40, cart=35, eng=45, followup=45, ci=30,
  ev_conv="has_cart=True but this is primarily a B2B services business with a small shop", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="WhatsApp chat and reviews already present, cta_count_above_fold=4", ev_followup="no email capture form detected despite active chat",
  open_gap_count=2),
L(1425, "saipetrochem.com", "Saipetrochem", primary="Follow-up Opportunity", confidence="low",
  summary="Indian petrochemical/bitumen B2B manufacturer with no lead-capture form or ESP.",
  conv=35, cart=20, eng=25, followup=45, ci=25,
  ev_conv="has_cart=True likely false-positive for a B2B manufacturer", ev_cart="product_count_visible=1",
  ev_eng="no chat/reviews/popup, cta_count_above_fold=2", ev_followup="no email or contact form detected",
  open_gap_count=1),
L(1426, "kefidata.com", "Kefidata", primary="Insufficient Data", confidence="low",
  summary="Domain resolved but page_text is empty and platform is unknown.",
  conv=50, cart=50, eng=50, followup=50, ci=50,
  ev_conv="page_text empty", ev_cart="has_cart=False (undetermined)",
  ev_eng="no signals extractable", ev_followup="no signals extractable",
  open_gap_count=0, disqualifier="empty/undetermined signals — cannot assess"),
L(1427, "essor.co.ke", "Essor", primary="Multi-Opportunity", confidence="medium",
  summary="Kenyan fashion retailer (15 products) with reviews and a very high above-fold CTA count (11), but no ESP.",
  conv=50, cart=60, eng=50, followup=50, ci=35,
  ev_conv="has_cart=True, no ESP, cta_count_above_fold=11 (very high)", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="reviews present, strong above-fold CTA presence", ev_followup="has_email_form=True but no ESP automation",
  open_gap_count=2),
L(1428, "reimailpros.com", "Reimailpros", primary="Follow-up Opportunity", confidence="low",
  summary="Real-estate direct-mail marketing B2B service with booking already offered and a high above-fold CTA count (7), but no ESP.",
  conv=40, cart=25, eng=35, followup=50, ci=30,
  ev_conv="has_cart=True but this is primarily a B2B direct-mail marketing service", ev_cart="product_count_visible=5",
  ev_eng="booking already offered, cta_count_above_fold=7", ev_followup="no email capture form detected despite active booking flow",
  open_gap_count=1),
L(1429, "ms21studio.com", "Ms21Studio", primary="Follow-up Opportunity", confidence="low",
  summary="Panama/Venezuela architecture and interior-design B2B firm with no lead-capture form or ESP.",
  conv=35, cart=20, eng=25, followup=45, ci=25,
  ev_conv="has_cart=False — B2B design/construction firm", ev_cart="has_cart=False",
  ev_eng="no chat/reviews/popup", ev_followup="no email or contact form detected",
  open_gap_count=1),
L(1431, "r2-collective.com", "R2-Collective", primary="Not a Good Fit", confidence="medium",
  summary="DJ/photography event-services business already running Mailchimp ESP.",
  conv=25, cart=15, eng=30, followup=20, ci=30,
  ev_conv="has_cart=False — event-services business", ev_cart="has_esp_tag=mailchimp",
  ev_eng="cta_count_above_fold=2", ev_followup="email capture and ESP already wired together",
  open_gap_count=1, disqualifier="already has ESP in place"),
L(1432, "huesocabra.com", "Huesocabra", primary="Cart Recovery Opportunity", secondary="Customer Engagement Opportunity", confidence="low",
  summary="WooCommerce store whose fetched copy is mostly unrendered marquee-widget CSS boilerplate, no ESP.",
  conv=35, cart=50, eng=25, followup=25, ci=25,
  ev_conv="has_cart=True, no ESP; page content largely unrendered CSS boilerplate", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="no chat/reviews/popup", ev_followup="no email capture form detected",
  open_gap_count=2),
L(1433, "sgigroup.co.in", "Sgigroup", primary="Follow-up Opportunity", confidence="medium",
  summary="Indian construction/machinery B2B firm with WhatsApp chat and both email and contact forms, but no ESP.",
  conv=45, cart=25, eng=45, followup=55, ci=35,
  ev_conv="has_cart=True likely false-positive for a B2B construction firm", ev_cart="product_count_visible=0",
  ev_eng="WhatsApp chat already present, cta_count_above_fold=6", ev_followup="has_email_form=True and has_contact_form=True but no ESP automation",
  open_gap_count=1),
L(1434, "decancounty.com", "Decancounty", primary="Not a Good Fit", confidence="medium",
  summary="Hotel/suites property near Bangalore airport already running Mailchimp ESP with reviews.",
  conv=25, cart=20, eng=30, followup=20, ci=30,
  ev_conv="has_cart=True likely false-positive for a hospitality property", ev_cart="has_esp_tag=mailchimp",
  ev_eng="reviews present, cta_count_above_fold=5", ev_followup="email capture and ESP already wired together",
  open_gap_count=1, disqualifier="already has ESP + reviews stack in place"),
L(1435, "ssureinsurance.com", "Ssureinsurance", primary="Follow-up Opportunity", confidence="low",
  summary="Insurance agency with WhatsApp chat, booking, and reviews already live, but page copy includes apparent multi-page theme-demo content ('Home 1', 'Home 2'); no ESP.",
  conv=40, cart=20, eng=45, followup=50, ci=30,
  ev_conv="has_cart=True likely false-positive for an insurance agency; page includes theme-demo navigation", ev_cart="product_count_visible=0",
  ev_eng="WhatsApp chat, booking, and reviews already present, cta_count_above_fold=3", ev_followup="has_email_form=True but no ESP automation for insurance-quote leads",
  open_gap_count=1),
L(1436, "focusedleaders.co.uk", "Focusedleaders", primary="Follow-up Opportunity", confidence="low",
  summary="UK leadership-coaching business with no lead-capture form or ESP.",
  conv=35, cart=20, eng=30, followup=45, ci=25,
  ev_conv="has_cart=True likely false-positive for a coaching business", ev_cart="product_count_visible=0",
  ev_eng="no chat/reviews/popup", ev_followup="no email or contact form detected",
  open_gap_count=1),
L(1437, "nnekamarwellness.com", "Nnekamarwellness", primary="Cart Recovery Opportunity", secondary="Follow-up Opportunity", confidence="medium",
  summary="US weight-loss/wellness-programs WooCommerce store (8 products) with reviews and a high above-fold CTA count (8), but no ESP.",
  conv=45, cart=60, eng=45, followup=55, ci=35,
  ev_conv="has_cart=True, no ESP, cta_count_above_fold=8", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="reviews present", ev_followup="has_email_form=True but no ESP automation",
  open_gap_count=2),
L(1438, "sparderm.com", "Sparderm", primary="Follow-up Opportunity", confidence="low",
  summary="Indian dermatology clinic with booking and reviews already live but no ESP.",
  conv=40, cart=20, eng=40, followup=50, ci=30,
  ev_conv="has_cart=True likely false-positive for a dermatology clinic", ev_cart="product_count_visible=0",
  ev_eng="booking and reviews already present, cta_count_above_fold=2", ev_followup="no email capture form detected despite active booking flow",
  open_gap_count=1),
L(1439, "coolerbox.hu", "Coolerbox", primary="Not a Good Fit", confidence="medium",
  summary="Hungarian business already running Mailchimp ESP with booking already offered.",
  conv=25, cart=20, eng=30, followup=20, ci=30,
  ev_conv="Mailchimp ESP already live", ev_cart="has_esp_tag=mailchimp",
  ev_eng="booking already offered", ev_followup="email capture and ESP already wired together",
  open_gap_count=1, disqualifier="already has ESP + booking flow in place"),
L(1440, "simulspheretz.com", "Simulspheretz", primary="Insufficient Data", confidence="high",
  summary="Hosting account suspended — no live site content to evaluate.",
  conv=50, cart=50, eng=50, followup=50, ci=50,
  ev_conv="account suspended", ev_cart="no storefront exists",
  ev_eng="no engagement infrastructure — not a live site", ev_followup="no capture forms — not a live site",
  open_gap_count=0, disqualifier="hosting account suspended, site not live"),
L(1441, "sportvilkius.lt", "Sportvilkius", primary="Follow-up Opportunity", confidence="low",
  summary="Lithuanian personal-training service with both email and contact forms but no ESP.",
  conv=40, cart=20, eng=30, followup=50, ci=30,
  ev_conv="has_cart=True likely false-positive for a personal-training service", ev_cart="product_count_visible=0",
  ev_eng="no chat/reviews/popup", ev_followup="has_email_form=True and has_contact_form=True but no ESP automation",
  open_gap_count=1),
L(1442, "sheikhoil.com", "Sheikhoil", primary="Cart Recovery Opportunity", secondary="Follow-up Opportunity", confidence="low",
  summary="Pakistani cooking-oil manufacturer WooCommerce store, product_count_visible=1 suggests thin catalog, no ESP.",
  conv=35, cart=50, eng=30, followup=45, ci=25,
  ev_conv="has_cart=True, no ESP", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="generic popup only, no chat/reviews, cta_count_above_fold=1", ev_followup="has_email_form=True but no ESP automation",
  open_gap_count=2),
L(1443, "ghncom.com", "Ghncom", primary="Not a Good Fit", confidence="medium",
  summary="Nutrition-supplements retailer (13 products) already running Mailchimp ESP with reviews and cta_count_above_fold=6.",
  conv=25, cart=20, eng=30, followup=20, ci=30,
  ev_conv="Mailchimp ESP already live", ev_cart="has_esp_tag=mailchimp",
  ev_eng="reviews present, cta_count_above_fold=6", ev_followup="email capture and ESP already wired together",
  open_gap_count=1, disqualifier="already has ESP + reviews stack in place"),
L(1444, "helenaessentials.com", "Helenaessentials", primary="Not a Good Fit", confidence="medium",
  summary="Essentials/lifestyle retailer already running Mailchimp ESP with reviews and an active promo.",
  conv=25, cart=20, eng=30, followup=20, ci=30,
  ev_conv="Mailchimp ESP already live, active promo (free shipping over 150€)", ev_cart="has_esp_tag=mailchimp",
  ev_eng="reviews present, cta_count_above_fold=3", ev_followup="email capture and ESP already wired together",
  open_gap_count=1, disqualifier="already has ESP + reviews + promo in place"),
L(1445, "alliancemscinc.com", "Alliancemscinc", primary="Insufficient Data", confidence="low",
  summary="Domain resolved but page_text is empty and platform is unknown.",
  conv=50, cart=50, eng=50, followup=50, ci=50,
  ev_conv="page_text empty", ev_cart="has_cart=False (undetermined)",
  ev_eng="no signals extractable", ev_followup="no signals extractable",
  open_gap_count=0, disqualifier="empty/undetermined signals — cannot assess"),
L(1446, "cadrehospice.com", "Cadrehospice", primary="Not a Good Fit", confidence="medium",
  summary="US hospice-care provider already running Mailchimp ESP with booking and reviews.",
  conv=20, cart=15, eng=30, followup=15, ci=25,
  ev_conv="has_cart=True likely false-positive for a hospice-care provider", ev_cart="has_esp_tag=mailchimp",
  ev_eng="booking and reviews already present, cta_count_above_fold=2", ev_followup="email capture and ESP already wired together",
  open_gap_count=1, disqualifier="already has ESP + booking + reviews stack in place"),
L(1447, "trofeokarting.com", "Trofeokarting", primary="Cart Recovery Opportunity", secondary="Follow-up Opportunity", confidence="low",
  summary="Karting racing club with an attached shop and booking already offered, but no ESP.",
  conv=40, cart=40, eng=35, followup=45, ci=30,
  ev_conv="has_cart=True but this is a club with booking-driven services alongside a shop", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="booking already offered", ev_followup="no email capture form detected despite active booking flow",
  open_gap_count=2),
L(1448, "dtfensevilla.com", "Dtfensevilla", primary="Insufficient Data", confidence="high",
  summary="Page served an obfuscated JS-based verification wall — no real content retrievable.",
  conv=50, cart=50, eng=50, followup=50, ci=50,
  ev_conv="bot-check/obfuscated verification page", ev_cart="has_cart=False (undetermined)",
  ev_eng="no signals extractable — verification wall", ev_followup="no signals extractable — verification wall",
  open_gap_count=0, disqualifier="anti-bot verification page — cannot assess real content"),
L(1449, "institutiebt.com", "Institutiebt", primary="Cart Recovery Opportunity", secondary="Follow-up Opportunity", confidence="medium",
  summary="Education institute (diplomas/certificates) with an attached e-shop, reviews already live, but no ESP.",
  conv=45, cart=55, eng=45, followup=50, ci=35,
  ev_conv="has_cart=True, no ESP", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="reviews present, cta_count_above_fold=2", ev_followup="has_email_form=True but no ESP automation for enrollment leads",
  open_gap_count=2),
L(1450, "slimit.ro", "Slimit", primary="Insufficient Data", confidence="low",
  summary="Domain resolved but page_text is empty and platform is unknown.",
  conv=50, cart=50, eng=50, followup=50, ci=50,
  ev_conv="page_text empty", ev_cart="has_cart=False (undetermined)",
  ev_eng="no signals extractable", ev_followup="no signals extractable",
  open_gap_count=0, disqualifier="empty/undetermined signals — cannot assess"),
L(1452, "strefagrilla.pl", "Strefagrilla", primary="Cart Recovery Opportunity", secondary="Follow-up Opportunity", confidence="low",
  summary="Polish grill/BBQ WooCommerce store whose fetched copy is mostly unrendered GTM tag boilerplate, no ESP.",
  conv=35, cart=50, eng=25, followup=40, ci=25,
  ev_conv="has_cart=True, no ESP; page content largely unrendered tag-manager boilerplate", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="no chat/reviews/popup", ev_followup="has_email_form=True but no ESP automation",
  open_gap_count=2),
L(1453, "imtraining.pl", "Imtraining", primary="Follow-up Opportunity", confidence="low",
  summary="Polish renewable-energy/offshore-wind training courses B2B business with reviews already live but no lead-capture form or ESP.",
  conv=35, cart=20, eng=35, followup=45, ci=25,
  ev_conv="has_cart=True likely false-positive for a B2B training-courses business", ev_cart="product_count_visible=0",
  ev_eng="reviews present", ev_followup="no email or contact form detected",
  open_gap_count=1),
L(1454, "rigrs.com", "Rigrs", primary="Insufficient Data", confidence="low",
  summary="Domain resolved but page_text is empty and platform is unknown.",
  conv=50, cart=50, eng=50, followup=50, ci=50,
  ev_conv="page_text empty", ev_cart="has_cart=False (undetermined)",
  ev_eng="no signals extractable", ev_followup="no signals extractable",
  open_gap_count=0, disqualifier="empty/undetermined signals — cannot assess"),
L(1455, "mustxsurgical.com", "Mustxsurgical", primary="Cart Recovery Opportunity", secondary="Follow-up Opportunity", confidence="medium",
  summary="Pakistani surgical-instruments manufacturer B2B WooCommerce store (7 products) with WhatsApp chat but no ESP.",
  conv=45, cart=55, eng=45, followup=50, ci=35,
  ev_conv="has_cart=True, no ESP", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="WhatsApp chat present but no reviews, cta_count_above_fold=2", ev_followup="has_email_form=True but no ESP automation",
  open_gap_count=2),
L(1457, "longtomstudios.co.uk", "Longtomstudios", primary="Insufficient Data", confidence="low",
  summary="Domain resolved but page_text is empty and platform is unknown.",
  conv=50, cart=50, eng=50, followup=50, ci=50,
  ev_conv="page_text empty", ev_cart="has_cart=False (undetermined)",
  ev_eng="no signals extractable", ev_followup="no signals extractable",
  open_gap_count=0, disqualifier="empty/undetermined signals — cannot assess"),
L(1458, "jinhuaceramic.com", "Jinhuaceramic", primary="Follow-up Opportunity", confidence="low",
  summary="Chinese ceramic-tableware B2B manufacturer (multi-language site, OEM/ODM) with both email and contact forms but no ESP.",
  conv=40, cart=20, eng=30, followup=50, ci=30,
  ev_conv="has_cart=True likely false-positive for a B2B manufacturer", ev_cart="product_count_visible=0",
  ev_eng="generic popup only, cta_count_above_fold=1", ev_followup="has_email_form=True and has_contact_form=True but no ESP automation",
  open_gap_count=1),
L(1459, "www.inframe-bg.com", "Inframe-Bg", primary="Cart Recovery Opportunity", secondary="Follow-up Opportunity", confidence="low",
  summary="Bulgarian art-prints WooCommerce store with reviews already live and an active discount offer in copy, but no ESP.",
  conv=40, cart=55, eng=35, followup=45, ci=30,
  ev_conv="has_cart=True, no ESP; discount messaging in copy", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="reviews present but no chat", ev_followup="has_email_form=True but no ESP automation",
  open_gap_count=2),
L(1460, "www.pergolashop.co.uk", "Pergolashop", primary="Not a Good Fit", confidence="medium",
  summary="UK pergola retailer (7 products) already running Mailchimp ESP with a high above-fold CTA count (8).",
  conv=25, cart=20, eng=30, followup=20, ci=30,
  ev_conv="Mailchimp ESP already live, cta_count_above_fold=8", ev_cart="has_esp_tag=mailchimp",
  ev_eng="strong above-fold CTA presence already in place", ev_followup="email capture and ESP already wired together",
  open_gap_count=1, disqualifier="already has ESP + strong CTA presence in place"),
L(1462, "banglawok.com", "Banglawok", primary="Cart Recovery Opportunity", secondary="Follow-up Opportunity", confidence="low",
  summary="Bangladeshi restaurant (Buffalo, NY) WooCommerce ordering site, product_count_visible=0 suggests thin page fetched.",
  conv=40, cart=55, eng=30, followup=45, ci=30,
  ev_conv="has_cart=True, no ESP", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="generic popup only, no chat/reviews, cta_count_above_fold=3", ev_followup="has_email_form=True but no ESP automation",
  open_gap_count=2),
L(1463, "kahvemalzemeleri.com", "Kahvemalzemeleri", primary="Cart Recovery Opportunity", secondary="Customer Engagement Opportunity", confidence="medium",
  summary="Turkish coffee-supplies wholesale/retail WooCommerce store (22 products) with no capture form or ESP.",
  conv=40, cart=60, eng=40, followup=30, ci=30,
  ev_conv="has_cart=True, no ESP, 22 products", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="generic popup only, no chat/reviews, cta_count_above_fold=5", ev_followup="no email capture form detected",
  open_gap_count=2),
L(1464, "nazaninmadadi.com", "Nazaninmadadi", primary="Follow-up Opportunity", confidence="low",
  summary="Iranian wellness/coaching business (workshops, meditations, podcast) with WhatsApp chat but no email-capture form or ESP.",
  conv=40, cart=25, eng=40, followup=50, ci=30,
  ev_conv="has_cart=True but this is a booking/consultation-driven coaching business", ev_cart="product_count_visible=0",
  ev_eng="WhatsApp chat already present", ev_followup="no email capture form detected despite active chat channel",
  open_gap_count=1),
L(1465, "waiypar.co.za", "Waiypar", primary="Cart Recovery Opportunity", secondary="Follow-up Opportunity", confidence="low",
  summary="South African retailer WooCommerce store (12 products) with no ESP.",
  conv=40, cart=55, eng=30, followup=45, ci=30,
  ev_conv="has_cart=True, no ESP", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="no chat/reviews/popup, cta_count_above_fold=3", ev_followup="has_email_form=True but no ESP automation",
  open_gap_count=2),
L(1466, "iskcontrivandrum.org", "Iskcontrivandrum", primary="Cart Recovery Opportunity", secondary="Follow-up Opportunity", confidence="low",
  summary="ISKCON temple (books, donations, pooja bookings) with tawk chat and booking already live, but no ESP.",
  conv=40, cart=45, eng=45, followup=45, ci=30,
  ev_conv="has_cart=True, no ESP", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="tawk chat and booking already present, cta_count_above_fold=7", ev_followup="no email capture form detected despite active chat and booking",
  open_gap_count=2),
L(1467, "hdrepairappliance.co.uk", "Hdrepairappliance", primary="Cart Recovery Opportunity", secondary="Follow-up Opportunity", confidence="low",
  summary="UK appliance-repair service with an attached shop (1 product), no ESP.",
  conv=35, cart=45, eng=30, followup=45, ci=25,
  ev_conv="has_cart=True but this is primarily a repair services business", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="generic popup only, cta_count_above_fold=2", ev_followup="has_email_form=True but no ESP automation",
  open_gap_count=2),
L(1468, "daneshandishan.com", "Daneshandishan", primary="Insufficient Data", confidence="high",
  summary="Gateway/upstream connection-timeout error — no content retrievable.",
  conv=50, cart=50, eng=50, followup=50, ci=50,
  ev_conv="upstream connection timeout", ev_cart="has_cart=False (undetermined)",
  ev_eng="no signals extractable — gateway error", ev_followup="no signals extractable — gateway error",
  open_gap_count=0, disqualifier="upstream gateway error — cannot assess"),
L(1469, "parsafood.com", "Parsafood", primary="Follow-up Opportunity", confidence="low",
  summary="Iranian food manufacturing/export B2B business with an email form but no ESP.",
  conv=40, cart=20, eng=30, followup=50, ci=30,
  ev_conv="has_cart=True likely false-positive for a B2B food manufacturer/exporter", ev_cart="product_count_visible=0",
  ev_eng="no chat/reviews/popup", ev_followup="has_email_form=True but no ESP automation",
  open_gap_count=1),
]

n = append_results(RESULTS)
print(f"appended {n} rows (chunk_015)")
