import sys
sys.path.insert(0, ".")
from layer3_write import append_results


def L(lead_id, domain, business_name, primary, confidence, summary,
      conv, cart, eng, followup, ci, ev_conv, ev_cart, ev_eng, ev_followup,
      open_gap_count, secondary=None, disqualifier=None):
    return (lead_id, domain, business_name, primary, secondary, confidence, summary,
            conv, cart, eng, followup, ci, ev_conv, ev_cart, ev_eng, ev_followup,
            open_gap_count, disqualifier)


RESULTS = [
L(970, "www.silentmillbrew.co", "Silentmillbrew", primary="Cart Recovery Opportunity", secondary="Follow-up Opportunity", confidence="medium",
  summary="UK microbrewery WooCommerce shop with both email and contact forms and reviews already live, but no ESP.",
  conv=50, cart=65, eng=50, followup=55, ci=40,
  ev_conv="has_cart=True, no ESP", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="reviews present but no chat/popup", ev_followup="has_email_form=True and has_contact_form=True but no ESP automation",
  open_gap_count=2),
L(971, "varese-corsi.it", "Varese-Corsi", primary="Follow-up Opportunity", secondary="Cart Recovery Opportunity", confidence="medium",
  summary="Italian course-booking marketplace with WhatsApp chat and booking already live, but no ESP behind its email form.",
  conv=45, cart=40, eng=55, followup=60, ci=40,
  ev_conv="has_cart=True but this is a course-booking marketplace, not physical goods", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="WhatsApp chat and booking already present", ev_followup="has_email_form=True but no ESP automation",
  open_gap_count=2),
L(972, "idclinic.lt", "Idclinic", primary="Follow-up Opportunity", secondary="Cart Recovery Opportunity", confidence="medium",
  summary="Lithuanian clinic with Tidio chat and reviews already live; has_esp_tag not confirmed despite a Mailchimp script reference appearing in raw page code.",
  conv=45, cart=35, eng=55, followup=55, ci=40,
  ev_conv="has_cart=True but this is a clinical service, not physical goods", ev_cart="has_esp_tag=none per extractor (a chimpstatic.com script reference appears in raw code but is not confirmed as an active ESP integration)",
  ev_eng="Tidio chat and reviews already present", ev_followup="has_email_form=True; ESP status uncertain, treated conservatively as not confirmed",
  open_gap_count=2),
L(973, "theinteriorplanet.com", "Theinteriorplanet", primary="Follow-up Opportunity", confidence="medium",
  summary="Indian interior-design B2B service ('GET A QUOTE' model) with no lead-capture form or ESP.",
  conv=45, cart=20, eng=40, followup=60, ci=35,
  ev_conv="has_cart=True likely false-positive for a quote-driven design services business", ev_cart="product_count_visible=0",
  ev_eng="cta_count_above_fold=4", ev_followup="no email or contact form detected for a quote-request business",
  open_gap_count=1),
L(974, "theintersectclub.com", "Theintersectclub", primary="Cart Recovery Opportunity", secondary="Follow-up Opportunity", confidence="medium",
  summary="Small WooCommerce shop (6 products) with reviews already live but no capture form or ESP.",
  conv=45, cart=65, eng=45, followup=45, ci=35,
  ev_conv="has_cart=True, no ESP", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="reviews present, cta_count_above_fold=4", ev_followup="no email capture form detected despite reviews present",
  open_gap_count=2),
L(975, "kart-jet-adventure.com", "Kart-Jet-Adventure", primary="Insufficient Data", confidence="low",
  summary="Domain resolved but page_text is empty and platform is unknown.",
  conv=50, cart=50, eng=50, followup=50, ci=50,
  ev_conv="page_text empty", ev_cart="has_cart=False (undetermined)",
  ev_eng="no signals extractable", ev_followup="no signals extractable",
  open_gap_count=0, disqualifier="empty/undetermined signals — cannot assess"),
L(976, "hiveteamsports.com", "Hiveteamsports", primary="Cart Recovery Opportunity", secondary="Follow-up Opportunity", confidence="low",
  summary="Custom soccer-uniform WooCommerce store, product_count_visible=0 suggests thin page fetched.",
  conv=40, cart=60, eng=40, followup=50, ci=30,
  ev_conv="has_cart=True, no ESP", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="no chat/reviews/popup, cta_count_above_fold=1", ev_followup="has_email_form=True but no ESP automation",
  open_gap_count=2),
L(977, "macmediapublishing.com", "Macmediapublishing", primary="Insufficient Data", confidence="low",
  summary="Domain resolved but page_text is empty and platform is unknown.",
  conv=50, cart=50, eng=50, followup=50, ci=50,
  ev_conv="page_text empty", ev_cart="has_cart=False (undetermined)",
  ev_eng="no signals extractable", ev_followup="no signals extractable",
  open_gap_count=0, disqualifier="empty/undetermined signals — cannot assess"),
L(978, "snikcart.com", "Snikcart", primary="Cart Recovery Opportunity", secondary="Follow-up Opportunity", confidence="medium",
  summary="General e-commerce store with a high above-fold CTA count (10) but no ESP.",
  conv=50, cart=65, eng=50, followup=55, ci=35,
  ev_conv="has_cart=True, no ESP, cta_count_above_fold=10", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="generic popup only, no chat/reviews despite high above-fold CTA count", ev_followup="has_email_form=True but no ESP automation",
  open_gap_count=2),
L(979, "akademiabehawioryzmu.pl", "Akademiabehawioryzmu", primary="Cart Recovery Opportunity", secondary="Follow-up Opportunity", confidence="low",
  summary="Polish dog-behavior academy (courses + shop) WooCommerce site, product_count_visible=0 suggests thin page fetched.",
  conv=40, cart=60, eng=40, followup=50, ci=30,
  ev_conv="has_cart=True, no ESP", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="no chat/reviews/popup capture", ev_followup="has_email_form=True but no ESP automation",
  open_gap_count=2),
L(980, "hranacurata.ro", "Hranacurata", primary="Cart Recovery Opportunity", secondary="Follow-up Opportunity", confidence="medium",
  summary="Romanian organic-food WooCommerce store (12 products) with reviews already live but no ESP.",
  conv=45, cart=65, eng=45, followup=55, ci=35,
  ev_conv="has_cart=True, no ESP", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="reviews present but no chat/popup", ev_followup="has_email_form=True but no ESP automation",
  open_gap_count=2),
L(981, "elgremiodemaria.com", "Elgremiodemaria", primary="Cart Recovery Opportunity", secondary="Customer Engagement Opportunity", confidence="low",
  summary="Spanish hair/beauty-salon products WooCommerce store, product_count_visible=0 suggests thin page fetched.",
  conv=40, cart=60, eng=40, followup=35, ci=30,
  ev_conv="has_cart=True, no ESP", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="generic popup only, no chat/reviews", ev_followup="no email capture form detected",
  open_gap_count=2),
L(982, "www.gemvoguejewelry.com", "Gemvoguejewelry", primary="Not a Good Fit", confidence="medium",
  summary="Turkish jewelry WooCommerce store already running Mailchimp ESP with reviews.",
  conv=25, cart=25, eng=30, followup=20, ci=30,
  ev_conv="Mailchimp ESP already live", ev_cart="has_esp_tag=mailchimp",
  ev_eng="reviews present", ev_followup="email capture and ESP already wired together",
  open_gap_count=1, disqualifier="already has ESP + reviews stack in place"),
L(983, "www.bioforcemed.com", "Bioforcemed", primary="Cart Recovery Opportunity", secondary="Follow-up Opportunity", confidence="low",
  summary="Turkish bioresonance-device WooCommerce store with WhatsApp chat, product_count_visible=0 suggests thin page fetched.",
  conv=40, cart=55, eng=45, followup=50, ci=35,
  ev_conv="has_cart=True, no ESP", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="WhatsApp chat present but no reviews", ev_followup="has_email_form=True but no ESP automation",
  open_gap_count=2),
L(984, "fixmini.com", "Fixmini", primary="Not a Good Fit", confidence="medium",
  summary="Turkish phone-repair franchise/dealer network already running Mailchimp ESP with both email and contact forms.",
  conv=25, cart=25, eng=30, followup=20, ci=30,
  ev_conv="Mailchimp ESP already live", ev_cart="has_esp_tag=mailchimp",
  ev_eng="dealer network already has forms in place", ev_followup="email capture and ESP already wired together",
  open_gap_count=1, disqualifier="already has ESP + capture forms in place"),
L(985, "www.nevby.hu", "Nevby", primary="Cart Recovery Opportunity", secondary="Follow-up Opportunity", confidence="medium",
  summary="Hungarian EV-charger WooCommerce store with an active summer discount promo but no ESP.",
  conv=45, cart=65, eng=40, followup=55, ci=35,
  ev_conv="has_cart=True, no ESP", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="no chat/reviews/popup", ev_followup="has_email_form=True but no ESP automation",
  open_gap_count=2),
L(986, "jamaicandiamond.com", "Jamaicandiamond", primary="Not a Good Fit", confidence="medium",
  summary="Jewelry retailer (47 products, 5826 reviews cited) already running Mailchimp ESP.",
  conv=20, cart=20, eng=25, followup=15, ci=25,
  ev_conv="Mailchimp ESP already live", ev_cart="has_esp_tag=mailchimp",
  ev_eng="large review volume cited in copy (5826), cta_count_above_fold=2", ev_followup="email capture and ESP already wired together",
  open_gap_count=1, disqualifier="already has ESP + strong review social proof in place"),
L(987, "lavandaflorarie.com", "Lavandaflorarie", primary="Cart Recovery Opportunity", secondary="Customer Engagement Opportunity", confidence="medium",
  summary="Romanian florist WooCommerce store (12 products) with reviews already live but no ESP or capture form.",
  conv=45, cart=65, eng=45, followup=35, ci=35,
  ev_conv="has_cart=True, no ESP", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="reviews present but no chat/popup", ev_followup="no email capture form detected",
  open_gap_count=2),
L(988, "herrajesybisagras.com", "Herrajesybisagras", primary="Cart Recovery Opportunity", secondary="Follow-up Opportunity", confidence="medium",
  summary="Mexican hardware/hinges B2B WooCommerce store (28 products) with WhatsApp chat but no ESP.",
  conv=45, cart=65, eng=50, followup=55, ci=35,
  ev_conv="has_cart=True, no ESP", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="WhatsApp chat present, cta_count_above_fold=4", ev_followup="no email capture form detected despite active chat",
  open_gap_count=2),
L(989, "bottarishop.ro", "Bottarishop", primary="Cart Recovery Opportunity", secondary="Follow-up Opportunity", confidence="low",
  summary="Romanian auto-accessories WooCommerce store, product_count_visible=0 suggests thin page fetched.",
  conv=40, cart=60, eng=40, followup=50, ci=30,
  ev_conv="has_cart=True, no ESP", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="generic popup only, no chat/reviews, cta_count_above_fold=1", ev_followup="has_email_form=True but no ESP automation",
  open_gap_count=2),
L(990, "www.amerinet-gpo.com", "Amerinet-Gpo", primary="Cart Recovery Opportunity", secondary="Follow-up Opportunity", confidence="medium",
  summary="Medical aesthetics wholesale B2B store (peptides, fillers) with cta_count_above_fold=6 but no ESP.",
  conv=45, cart=60, eng=45, followup=55, ci=35,
  ev_conv="has_cart=True, no ESP", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="generic popup only, no chat/reviews, cta_count_above_fold=6", ev_followup="has_email_form=True but no ESP automation",
  open_gap_count=2),
L(991, "web.likeshop.mx", "Web.Likeshop", primary="Insufficient Data", confidence="high",
  summary="Page served an anti-bot verification challenge — no real content retrievable.",
  conv=50, cart=50, eng=50, followup=50, ci=50,
  ev_conv="bot-check page, no real content", ev_cart="has_cart=False (undetermined)",
  ev_eng="no signals extractable — verification wall", ev_followup="no signals extractable — verification wall",
  open_gap_count=0, disqualifier="anti-bot verification page — cannot assess real content"),
L(992, "addmug.com", "Addmug", primary="Cart Recovery Opportunity", secondary="Follow-up Opportunity", confidence="medium",
  summary="Indian custom-mug-printing WooCommerce store with reviews already live but no ESP.",
  conv=45, cart=65, eng=45, followup=55, ci=35,
  ev_conv="has_cart=True, no ESP", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="reviews present, cta_count_above_fold=5", ev_followup="has_email_form=True but no ESP automation",
  open_gap_count=2),
L(993, "abeehawardrobe.com", "Abeehawardrobe", primary="Cart Recovery Opportunity", secondary="Follow-up Opportunity", confidence="medium",
  summary="Pakistani sustainable-apparel WooCommerce store with reviews and a high above-fold CTA count (10) but no ESP.",
  conv=50, cart=65, eng=50, followup=55, ci=35,
  ev_conv="has_cart=True, no ESP, cta_count_above_fold=10", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="reviews present", ev_followup="has_email_form=True but no ESP automation",
  open_gap_count=2),
L(994, "ferramentalab.com", "Ferramentalab", primary="Cart Recovery Opportunity", secondary="Follow-up Opportunity", confidence="medium",
  summary="Italian hardware-store WooCommerce site with tawk chat and reviews already live but no ESP.",
  conv=45, cart=65, eng=55, followup=55, ci=35,
  ev_conv="has_cart=True, no ESP", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="tawk chat and reviews already present", ev_followup="has_email_form=True but no ESP automation",
  open_gap_count=2),
L(995, "weddingplanet.in", "Weddingplanet", primary="Cart Recovery Opportunity", secondary="Customer Engagement Opportunity", confidence="medium",
  summary="Indian personalized-gifts WooCommerce store (9 products) with reviews already live but no capture form or ESP.",
  conv=45, cart=65, eng=45, followup=35, ci=35,
  ev_conv="has_cart=True, no ESP", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="reviews present but no chat/popup", ev_followup="no email capture form detected",
  open_gap_count=2),
L(996, "audiolivecenter.com", "Audiolivecenter", primary="Cart Recovery Opportunity", secondary="Customer Engagement Opportunity", confidence="low",
  summary="Spanish DJ equipment WooCommerce store, cta_count_above_fold=8 but no capture form or ESP.",
  conv=40, cart=60, eng=45, followup=35, ci=30,
  ev_conv="has_cart=True, no ESP", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="no chat/reviews/popup despite cta_count_above_fold=8", ev_followup="no email capture form detected",
  open_gap_count=2),
L(997, "kinetics.com.tr", "Kinetics", primary="Cart Recovery Opportunity", secondary="Follow-up Opportunity", confidence="low",
  summary="Turkish nail-care products WooCommerce store, product_count_visible=0 suggests thin page fetched.",
  conv=40, cart=60, eng=35, followup=50, ci=30,
  ev_conv="has_cart=True, no ESP", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="generic popup only, no chat/reviews", ev_followup="has_email_form=True but no ESP automation",
  open_gap_count=2),
L(998, "dalumvin.dk", "Dalumvin", primary="Cart Recovery Opportunity", secondary="Follow-up Opportunity", confidence="low",
  summary="Danish wine club with tasting-event ticket sales WooCommerce store, product_count_visible=0 suggests thin page fetched.",
  conv=40, cart=60, eng=40, followup=50, ci=30,
  ev_conv="has_cart=True, no ESP", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="generic popup only, no chat/reviews", ev_followup="has_email_form=True but no ESP automation",
  open_gap_count=2),
L(1000, "thebearmedia.co.uk", "Thebearmedia", primary="Follow-up Opportunity", confidence="medium",
  summary="UK digital-marketing agency (web dev, SEO, printing) with reviews already live but no ESP.",
  conv=45, cart=20, eng=50, followup=60, ci=40,
  ev_conv="has_cart=True likely false-positive for a B2B marketing agency", ev_cart="product_count_visible=0",
  ev_eng="reviews present (100+ 5-star), cta_count_above_fold=7", ev_followup="has_email_form=True but no ESP automation",
  open_gap_count=1),
L(1001, "www.homeheathub.co.nz", "Homeheathub", primary="Cart Recovery Opportunity", secondary="Follow-up Opportunity", confidence="medium",
  summary="NZ woodburner/fireplace installer and shop with cta_count_above_fold=7 but no ESP or capture form.",
  conv=45, cart=60, eng=45, followup=45, ci=35,
  ev_conv="has_cart=True, no ESP, 5 products", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="no chat/reviews/popup despite cta_count_above_fold=7", ev_followup="no email capture form detected for an install-quote business",
  open_gap_count=2),
L(1002, "importspacific.com", "Importspacific", primary="Cart Recovery Opportunity", secondary="Customer Engagement Opportunity", confidence="medium",
  summary="US stone-sinks/bathtubs WooCommerce store (18 products) with no capture form or ESP.",
  conv=45, cart=65, eng=40, followup=35, ci=35,
  ev_conv="has_cart=True, no ESP", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="no chat/reviews/popup", ev_followup="no email capture form detected",
  open_gap_count=2),
L(1003, "qualitycareconsultancy.co.uk", "Qualitycareconsultancy", primary="Not a Good Fit", confidence="medium",
  summary="UK care-industry consultancy already running Mailchimp ESP with a booking CTA.",
  conv=25, cart=20, eng=30, followup=20, ci=30,
  ev_conv="has_cart=True likely false-positive for a consultancy service", ev_cart="has_esp_tag=mailchimp",
  ev_eng="active booking CTA already present", ev_followup="email capture and ESP already wired together",
  open_gap_count=1, disqualifier="already has ESP in place"),
L(1004, "flient.net", "Flient", primary="Insufficient Data", confidence="low",
  summary="Domain resolved but page_text is empty and platform is unknown.",
  conv=50, cart=50, eng=50, followup=50, ci=50,
  ev_conv="page_text empty", ev_cart="has_cart=False (undetermined)",
  ev_eng="no signals extractable", ev_followup="no signals extractable",
  open_gap_count=0, disqualifier="empty/undetermined signals — cannot assess"),
L(1005, "tsuki.hu", "Tsuki", primary="Cart Recovery Opportunity", secondary="Follow-up Opportunity", confidence="low",
  summary="Hungarian menstrual-cup brand WooCommerce store, product_count_visible=0 suggests thin page fetched.",
  conv=40, cart=60, eng=35, followup=50, ci=30,
  ev_conv="has_cart=True, no ESP", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="no chat/reviews/popup", ev_followup="has_email_form=True but no ESP automation",
  open_gap_count=2),
L(1006, "gasendo.fi", "Gasendo", primary="Follow-up Opportunity", secondary="Cart Recovery Opportunity", confidence="medium",
  summary="Finnish at-home cancer-screening test-kit health service with no capture form or ESP despite repeated 'order test' CTAs.",
  conv=50, cart=45, eng=45, followup=60, ci=40,
  ev_conv="has_cart=True, no ESP", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="generic popup only, no chat/reviews", ev_followup="no email or contact form detected despite repeated 'Tilaa testi' (order test) CTAs",
  open_gap_count=2),
L(1007, "natoo-underwear.com", "Natoo-Underwear", primary="Cart Recovery Opportunity", secondary="Customer Engagement Opportunity", confidence="low",
  summary="West African underwear brand WooCommerce store, cta_count_above_fold=5 but no capture form or ESP.",
  conv=40, cart=60, eng=40, followup=35, ci=30,
  ev_conv="has_cart=True, no ESP", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="generic popup only, no chat/reviews despite cta_count_above_fold=5", ev_followup="no email capture form detected",
  open_gap_count=2),
L(1008, "radiohuttech.com", "Radiohuttech", primary="Cart Recovery Opportunity", secondary="Customer Engagement Opportunity", confidence="medium",
  summary="US tech-gadgets WooCommerce store (4 products) with no capture form or ESP.",
  conv=45, cart=65, eng=40, followup=35, ci=35,
  ev_conv="has_cart=True, no ESP", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="generic popup only, no chat/reviews, cta_count_above_fold=4", ev_followup="no email capture form detected",
  open_gap_count=2),
L(1009, "biosmx.com", "Biosmx", primary="Follow-up Opportunity", confidence="low",
  summary="Mexican bioresonance/wellness device retailer whose fetched copy mixes real product content with apparent lorem-ipsum placeholder text, suggesting an unfinished build.",
  conv=35, cart=25, eng=35, followup=45, ci=25,
  ev_conv="has_cart=True but no ESP; page content includes lorem-ipsum filler", ev_cart="product_count_visible=0",
  ev_eng="no chat/reviews/popup", ev_followup="no email capture form detected; site appears partially built",
  open_gap_count=2),
L(1010, "www.epicerie-lf.com", "Epicerie-Lf", primary="Not a Good Fit", confidence="medium",
  summary="French gourmet grocery/concept-store already running Brevo ESP with an email form.",
  conv=25, cart=25, eng=30, followup=20, ci=30,
  ev_conv="Brevo ESP already live", ev_cart="has_esp_tag=brevo",
  ev_eng="no chat/reviews but ESP already handling automation", ev_followup="email capture and Brevo ESP already wired together",
  open_gap_count=1, disqualifier="already has ESP in place"),
L(1011, "sanagreens.ro", "Sanagreens", primary="Cart Recovery Opportunity", secondary="Follow-up Opportunity", confidence="medium",
  summary="Romanian greens/supplements WooCommerce store with reviews already live but no ESP.",
  conv=45, cart=65, eng=45, followup=55, ci=35,
  ev_conv="has_cart=True, no ESP", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="reviews present but no chat/popup", ev_followup="has_email_form=True but no ESP automation",
  open_gap_count=2),
L(1013, "girlycolours.in", "Girlycolours", primary="Not a Good Fit", confidence="medium",
  summary="Indian fashion retailer (58 products) already running Mailchimp ESP with reviews and cta_count_above_fold=4.",
  conv=20, cart=20, eng=25, followup=15, ci=25,
  ev_conv="Mailchimp ESP already live", ev_cart="has_esp_tag=mailchimp",
  ev_eng="reviews present, cta_count_above_fold=4", ev_followup="email capture and ESP already wired together",
  open_gap_count=1, disqualifier="already has ESP + reviews + strong CTA presence in place"),
L(1014, "lusconi.com", "Lusconi", primary="Not a Good Fit", confidence="medium",
  summary="Vietnamese e-commerce store (21 products) already running Mailchimp ESP with cta_count_above_fold=7.",
  conv=20, cart=20, eng=25, followup=15, ci=25,
  ev_conv="Mailchimp ESP already live", ev_cart="has_esp_tag=mailchimp",
  ev_eng="cta_count_above_fold=7", ev_followup="email capture and ESP already wired together",
  open_gap_count=1, disqualifier="already has ESP + strong CTA presence in place"),
L(1015, "uralmedexpert.org", "Uralmedexpert", primary="Follow-up Opportunity", secondary="Cart Recovery Opportunity", confidence="medium",
  summary="Russian CPR/first-aid training-course provider with WhatsApp chat and booking already live, but no ESP.",
  conv=45, cart=40, eng=55, followup=60, ci=40,
  ev_conv="has_cart=True but this is a training-course business, not physical goods", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="WhatsApp chat and booking already present", ev_followup="has_email_form=True but no ESP automation",
  open_gap_count=2),
L(1016, "seduccionyestilo.com", "Seduccionyestilo", primary="Cart Recovery Opportunity", secondary="Follow-up Opportunity", confidence="medium",
  summary="Spanish home/fashion lifestyle WooCommerce store with reviews already live but no ESP.",
  conv=45, cart=65, eng=45, followup=55, ci=35,
  ev_conv="has_cart=True, no ESP", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="reviews present, active sale promotion messaging", ev_followup="has_email_form=True but no ESP automation",
  open_gap_count=2),
L(1017, "www.la-maison-du-jardinier.com", "La-Maison-Du-Jardinier", primary="Cart Recovery Opportunity", secondary="Follow-up Opportunity", confidence="medium",
  summary="French gardening-supplies WooCommerce store with reviews and an active discount code but no ESP.",
  conv=45, cart=65, eng=45, followup=55, ci=35,
  ev_conv="has_cart=True, no ESP", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="reviews present, active discount code (SCHOOL10)", ev_followup="has_email_form=True but no ESP automation",
  open_gap_count=2),
L(1018, "merantis.in", "Merantis", primary="Cart Recovery Opportunity", secondary="Follow-up Opportunity", confidence="medium",
  summary="Indian pharmaceutical company WooCommerce store (9 products) with reviews already live but no ESP.",
  conv=45, cart=60, eng=45, followup=55, ci=35,
  ev_conv="has_cart=True, no ESP", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="reviews present, cta_count_above_fold=3", ev_followup="has_email_form=True but no ESP automation",
  open_gap_count=2),
L(1019, "projectstwentytwo.co.uk", "Projectstwentytwo", primary="Insufficient Data", confidence="low",
  summary="Domain resolved but page_text is empty and platform is unknown.",
  conv=50, cart=50, eng=50, followup=50, ci=50,
  ev_conv="page_text empty", ev_cart="has_cart=False (undetermined)",
  ev_eng="no signals extractable", ev_followup="no signals extractable",
  open_gap_count=0, disqualifier="empty/undetermined signals — cannot assess"),
L(1020, "sun2solar.in", "Sun2Solar", primary="Insufficient Data", confidence="high",
  summary="Page served an anti-bot verification challenge — no real content retrievable.",
  conv=50, cart=50, eng=50, followup=50, ci=50,
  ev_conv="bot-check page, no real content", ev_cart="has_cart=False (undetermined)",
  ev_eng="no signals extractable — verification wall", ev_followup="no signals extractable — verification wall",
  open_gap_count=0, disqualifier="anti-bot verification page — cannot assess real content"),
L(1021, "memingo.nl", "Memingo", primary="Cart Recovery Opportunity", secondary="Follow-up Opportunity", confidence="medium",
  summary="Dutch wooden urns/memorial-products WooCommerce store (20 products) with a newsletter signup prompt but no ESP.",
  conv=45, cart=65, eng=40, followup=55, ci=35,
  ev_conv="has_cart=True, no ESP", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="generic popup only, no chat/reviews", ev_followup="has_email_form=True (newsletter prompt) but no ESP automation",
  open_gap_count=2),
L(1022, "fusionservicebots.com", "Fusionservicebots", primary="Multi-Opportunity", confidence="medium",
  summary="High-value service-robot retailer (reception/table robots, $899-$10,999) with reviews and an exceptionally high above-fold CTA count (22), but no capture form or ESP.",
  conv=55, cart=70, eng=55, followup=60, ci=45,
  ev_conv="has_cart=True, no ESP, very high-value cart items ($899-$10,999)", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="reviews present, cta_count_above_fold=22 (exceptionally high)", ev_followup="no email capture form detected despite very strong engagement surface",
  open_gap_count=3),
L(1023, "www.dayaglow.com", "Dayaglow", primary="Not a Good Fit", confidence="medium",
  summary="Turkish jewelry/home-decor WooCommerce store already running Mailchimp ESP.",
  conv=25, cart=25, eng=30, followup=20, ci=30,
  ev_conv="Mailchimp ESP already live", ev_cart="has_esp_tag=mailchimp",
  ev_eng="no chat/reviews but ESP already handling automation", ev_followup="email capture and ESP already wired together",
  open_gap_count=1, disqualifier="already has ESP in place"),
L(1024, "practicasfp.com", "Practicasfp", primary="Follow-up Opportunity", confidence="medium",
  summary="Spanish internship/job-placement platform with WhatsApp chat, reviews, and an active promo, but no ESP.",
  conv=45, cart=25, eng=55, followup=60, ci=40,
  ev_conv="has_cart=True likely false-positive for a job-placement platform", ev_cart="product_count_visible=0",
  ev_eng="WhatsApp chat, reviews, and promo already present", ev_followup="has_email_form=True but no ESP automation for internship-placement leads",
  open_gap_count=1),
L(1025, "sliceneazy.com", "Sliceneazy", primary="Not a Good Fit", confidence="medium",
  summary="Scottish pizza restaurant already running Mailchimp ESP with both email and contact forms and cta_count_above_fold=11.",
  conv=20, cart=20, eng=30, followup=15, ci=25,
  ev_conv="Mailchimp ESP already live", ev_cart="has_esp_tag=mailchimp",
  ev_eng="cta_count_above_fold=11", ev_followup="email capture and ESP already wired together",
  open_gap_count=1, disqualifier="already has ESP + strong CTA presence in place"),
L(1026, "makkahsouq.com", "Makkahsouq", primary="Not a Good Fit", confidence="medium",
  summary="Middle Eastern apparel WooCommerce store (17 products) already running Omnisend ESP.",
  conv=25, cart=25, eng=30, followup=20, ci=30,
  ev_conv="Omnisend ESP already live", ev_cart="has_esp_tag=omnisend",
  ev_eng="no chat/reviews but ESP already handling automation", ev_followup="email capture and ESP already wired together",
  open_gap_count=1, disqualifier="already has ESP in place"),
]

n = append_results(RESULTS)
print(f"appended {n} rows (chunk_008)")
