import sys
sys.path.insert(0, ".")
from layer3_write import append_results


def L(lead_id, domain, business_name, primary, confidence, summary,
      conv, cart, eng, followup, ci, ev_conv, ev_cart, ev_eng, ev_followup,
      open_gap_count, secondary=None, disqualifier=None):
    return (lead_id, domain, business_name, primary, secondary, confidence, summary,
            conv, cart, eng, followup, ci, ev_conv, ev_cart, ev_eng, ev_followup,
            open_gap_count, disqualifier)


RESULTS = [
L(1470, "junsamtubes.com", "Junsamtubes", primary="Cart Recovery Opportunity", secondary="Follow-up Opportunity", confidence="low",
  summary="Chinese aluminum-tubes B2B manufacturer WooCommerce store (1 product visible) with both email and contact forms but no ESP.",
  conv=40, cart=55, eng=30, followup=50, ci=30,
  ev_conv="has_cart=True, no ESP", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="generic popup only, no chat/reviews", ev_followup="has_email_form=True and has_contact_form=True but no ESP automation",
  open_gap_count=2),
L(1472, "paperart.com.tr", "Paperart", primary="Cart Recovery Opportunity", secondary="Follow-up Opportunity", confidence="low",
  summary="Turkish paper/stationery B2B WooCommerce store with WhatsApp chat but no ESP.",
  conv=40, cart=55, eng=40, followup=45, ci=30,
  ev_conv="has_cart=True, no ESP", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="WhatsApp chat already present", ev_followup="has_email_form=True but no ESP automation",
  open_gap_count=2),
L(1473, "fopacking.com", "Fopacking", primary="Insufficient Data", confidence="low",
  summary="Domain resolved but page_text is empty and platform is unknown.",
  conv=50, cart=50, eng=50, followup=50, ci=50,
  ev_conv="page_text empty", ev_cart="has_cart=False (undetermined)",
  ev_eng="no signals extractable", ev_followup="no signals extractable",
  open_gap_count=0, disqualifier="empty/undetermined signals — cannot assess"),
L(1474, "packboxes.co.uk", "Packboxes", primary="Cart Recovery Opportunity", secondary="Follow-up Opportunity", confidence="medium",
  summary="UK custom packaging B2B WooCommerce store with tawk chat and reviews already live but no ESP.",
  conv=45, cart=55, eng=45, followup=50, ci=35,
  ev_conv="has_cart=True, no ESP", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="tawk chat and reviews already present, cta_count_above_fold=1", ev_followup="has_email_form=True but no ESP automation",
  open_gap_count=2),
L(1475, "schon-company.com", "Schon-Company", primary="Cart Recovery Opportunity", secondary="Customer Engagement Opportunity", confidence="low",
  summary="WooCommerce store whose fetched copy is mostly unrendered slider/CSS boilerplate, no ESP.",
  conv=35, cart=50, eng=25, followup=25, ci=25,
  ev_conv="has_cart=True, no ESP; page content largely unrendered CSS boilerplate", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="cta_count_above_fold=1", ev_followup="no email capture form detected",
  open_gap_count=2),
L(1476, "protoncables.net", "Protoncables", primary="Insufficient Data", confidence="low",
  summary="Domain resolved but page_text is empty and platform is unknown.",
  conv=50, cart=50, eng=50, followup=50, ci=50,
  ev_conv="page_text empty", ev_cart="has_cart=False (undetermined)",
  ev_eng="no signals extractable", ev_followup="no signals extractable",
  open_gap_count=0, disqualifier="empty/undetermined signals — cannot assess"),
L(1477, "wallbedsbellingham.com", "Wallbedsbellingham", primary="Insufficient Data", confidence="low",
  summary="Domain resolved but page_text is empty and platform is unknown.",
  conv=50, cart=50, eng=50, followup=50, ci=50,
  ev_conv="page_text empty", ev_cart="has_cart=False (undetermined)",
  ev_eng="no signals extractable", ev_followup="no signals extractable",
  open_gap_count=0, disqualifier="empty/undetermined signals — cannot assess"),
L(1478, "elpremiopk.com", "Elpremiopk", primary="Insufficient Data", confidence="high",
  summary="Page served an anti-bot verification challenge — no real content retrievable.",
  conv=50, cart=50, eng=50, followup=50, ci=50,
  ev_conv="bot-check page, no real content", ev_cart="has_cart=False (undetermined)",
  ev_eng="no signals extractable — verification wall", ev_followup="no signals extractable — verification wall",
  open_gap_count=0, disqualifier="anti-bot verification page — cannot assess real content"),
L(1479, "xpmakina.com", "Xpmakina", primary="Insufficient Data", confidence="high",
  summary="Site explicitly states 'We'll be back soon! We are currently improving our website' — not fully live.",
  conv=50, cart=50, eng=50, followup=50, ci=50,
  ev_conv="site explicitly under maintenance/rebuild", ev_cart="has_cart=False, site inactive",
  ev_eng="no real content to evaluate engagement", ev_followup="no signals extractable — placeholder page",
  open_gap_count=0, disqualifier="site under maintenance — 'we'll be back soon' placeholder"),
L(1480, "bregtobjects.nl", "Bregtobjects", primary="Not a Good Fit", confidence="medium",
  summary="Dutch vintage-furniture retailer already running Mailchimp ESP with WhatsApp chat.",
  conv=25, cart=20, eng=30, followup=20, ci=30,
  ev_conv="Mailchimp ESP already live", ev_cart="has_esp_tag=mailchimp",
  ev_eng="WhatsApp chat already present", ev_followup="email capture and ESP already wired together",
  open_gap_count=1, disqualifier="already has ESP + chat stack in place"),
L(1481, "stepharmaceuticals.com", "Stepharmaceuticals", primary="Follow-up Opportunity", secondary="Cart Recovery Opportunity", confidence="low",
  summary="Spanish pharmaceutical/supplement manufacturer B2B with an email form but no ESP.",
  conv=40, cart=40, eng=25, followup=50, ci=30,
  ev_conv="has_cart=True but this is a B2B pharmaceutical manufacturer", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="no chat/reviews/popup", ev_followup="has_email_form=True but no ESP automation",
  open_gap_count=2),
L(1482, "latesa.nl", "Latesa", primary="Insufficient Data", confidence="high",
  summary="Site displays a WordPress critical error — no usable content retrievable.",
  conv=50, cart=50, eng=50, followup=50, ci=50,
  ev_conv="WordPress critical error page", ev_cart="has_cart=False (undetermined)",
  ev_eng="no signals extractable — site is broken", ev_followup="no signals extractable — site is broken",
  open_gap_count=0, disqualifier="site returns a WordPress critical error — cannot assess"),
L(1483, "costcutterpackaging.com", "Costcutterpackaging", primary="Multi-Opportunity", confidence="medium",
  summary="Global custom-packaging B2B business (US, Canada, Australia, UAE, Saudi Arabia) with tawk chat, reviews, and an active promo, but no ESP.",
  conv=50, cart=60, eng=55, followup=55, ci=40,
  ev_conv="has_cart=True, has_promo_bar=True, no ESP", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="tawk chat and reviews already present, multi-country operations", ev_followup="has_email_form=True and has_contact_form=True but no ESP automation",
  open_gap_count=2),
L(1484, "asansorsatis.com", "Asansorsatis", primary="Not a Good Fit", confidence="medium",
  summary="Turkish elevator-parts B2B retailer (26 products) already running Mailchimp ESP with WhatsApp chat.",
  conv=25, cart=20, eng=30, followup=20, ci=30,
  ev_conv="Mailchimp ESP already live", ev_cart="has_esp_tag=mailchimp",
  ev_eng="WhatsApp chat already present", ev_followup="email capture and ESP already wired together",
  open_gap_count=1, disqualifier="already has ESP + chat stack in place"),
L(1485, "amgroupmaquinaria.com", "Amgroupmaquinaria", primary="Cart Recovery Opportunity", secondary="Follow-up Opportunity", confidence="low",
  summary="Spanish industrial-machinery B2B WooCommerce store with WhatsApp chat and both email and contact forms, but no ESP.",
  conv=40, cart=55, eng=40, followup=50, ci=30,
  ev_conv="has_cart=True, no ESP", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="WhatsApp chat already present", ev_followup="has_email_form=True and has_contact_form=True but no ESP automation",
  open_gap_count=2),
L(1486, "telefonfixarna.se", "Telefonfixarna", primary="Follow-up Opportunity", secondary="Cart Recovery Opportunity", confidence="low",
  summary="Swedish phone-repair service with an attached parts shop (5 products) and reviews already live, but no ESP.",
  conv=40, cart=40, eng=40, followup=45, ci=30,
  ev_conv="has_cart=True but this is primarily a repair services business", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="reviews present", ev_followup="no email capture form detected despite reviews present",
  open_gap_count=2),
L(1487, "engemaky.com.br", "Engemaky", primary="Follow-up Opportunity", confidence="low",
  summary="Brazilian oil-and-gas/construction engineering B2B firm with WhatsApp chat, booking, and reviews already live, but page copy includes apparent theme-demo section names; no ESP.",
  conv=40, cart=25, eng=45, followup=50, ci=30,
  ev_conv="has_cart=True likely false-positive for a B2B engineering firm; page includes theme-demo section labels", ev_cart="product_count_visible=0",
  ev_eng="WhatsApp chat, booking, and reviews already present", ev_followup="has_email_form=True and has_contact_form=True but no ESP automation",
  open_gap_count=1),
L(1488, "whatmachines.com", "Whatmachines", primary="Cart Recovery Opportunity", secondary="Follow-up Opportunity", confidence="low",
  summary="German gym-equipment distributor (Gymleco) WooCommerce store, product_count_visible=0 suggests thin page fetched, no ESP.",
  conv=40, cart=55, eng=30, followup=45, ci=30,
  ev_conv="has_cart=True, no ESP", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="generic popup only, no chat/reviews", ev_followup="has_email_form=True but no ESP automation",
  open_gap_count=2),
L(1489, "gepesdaru.com", "Gepesdaru", primary="Follow-up Opportunity", confidence="low",
  summary="European crane/heavy-machinery B2B supplier whose page copy is dominated by generic account-registration boilerplate, no ESP.",
  conv=30, cart=15, eng=25, followup=35, ci=20,
  ev_conv="has_cart=False — B2B heavy-machinery supplier; page content is mostly generic registration boilerplate", ev_cart="has_cart=False",
  ev_eng="no chat/reviews/popup", ev_followup="no email or contact form clearly identified amid boilerplate content",
  open_gap_count=1),
L(1490, "gujcomart.in", "Gujcomart", primary="Not a Good Fit", confidence="medium",
  summary="Indian agri-processing multi-location retailer already running Mailchimp ESP with WhatsApp chat and reviews.",
  conv=25, cart=20, eng=30, followup=20, ci=30,
  ev_conv="Mailchimp ESP already live", ev_cart="has_esp_tag=mailchimp",
  ev_eng="WhatsApp chat and reviews already present, cta_count_above_fold=2", ev_followup="email capture and ESP already wired together",
  open_gap_count=1, disqualifier="already has ESP + chat + reviews stack in place"),
L(1491, "chinathermistor.com", "Chinathermistor", primary="Cart Recovery Opportunity", secondary="Follow-up Opportunity", confidence="low",
  summary="Chinese thermistor/temperature-sensor OEM/ODM manufacturer B2B WooCommerce store with reviews already live but no ESP.",
  conv=40, cart=55, eng=40, followup=45, ci=30,
  ev_conv="has_cart=True, no ESP", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="reviews present but no chat", ev_followup="has_email_form=True but no ESP automation",
  open_gap_count=2),
L(1492, "solidtec.no", "Solidtec", primary="Follow-up Opportunity", confidence="low",
  summary="Norwegian stone-countertops B2B supplier with no lead-capture form or ESP.",
  conv=35, cart=20, eng=25, followup=45, ci=25,
  ev_conv="has_cart=True likely false-positive for a B2B stone-fabrication supplier", ev_cart="product_count_visible=0",
  ev_eng="generic popup only, no chat/reviews", ev_followup="no email or contact form detected",
  open_gap_count=1),
L(1493, "ali-surgical.com", "Ali-Surgical", primary="Cart Recovery Opportunity", secondary="Follow-up Opportunity", confidence="low",
  summary="Pakistani dental/surgical instruments manufacturer B2B WooCommerce store with WhatsApp chat but no ESP.",
  conv=40, cart=55, eng=40, followup=45, ci=30,
  ev_conv="has_cart=True, no ESP", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="WhatsApp chat already present, cta_count_above_fold=1", ev_followup="no email capture form detected despite active chat",
  open_gap_count=2),
L(1494, "vitadoone.com", "Vitadoone", primary="Cart Recovery Opportunity", secondary="Follow-up Opportunity", confidence="medium",
  summary="Iranian bartending/coffee/baking-courses business with an attached shop (9 products) and reviews already live, but no ESP.",
  conv=45, cart=55, eng=45, followup=50, ci=35,
  ev_conv="has_cart=True, no ESP", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="reviews present but no chat", ev_followup="has_email_form=True but no ESP automation",
  open_gap_count=2),
L(1495, "stil-casa.ro", "Stil-Casa", primary="Cart Recovery Opportunity", secondary="Follow-up Opportunity", confidence="low",
  summary="Romanian chimney-systems B2B distributor WooCommerce store, product_count_visible=0 suggests thin page fetched.",
  conv=40, cart=55, eng=30, followup=45, ci=30,
  ev_conv="has_cart=True, no ESP", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="generic popup only, no chat/reviews", ev_followup="has_email_form=True but no ESP automation",
  open_gap_count=2),
L(1496, "fet-enchere.fr", "Fet-Enchere", primary="Follow-up Opportunity", confidence="low",
  summary="French auction house with an email form but no ESP.",
  conv=40, cart=20, eng=25, followup=50, ci=30,
  ev_conv="has_cart=True likely false-positive for an auction-house business", ev_cart="product_count_visible=0",
  ev_eng="no chat/reviews/popup", ev_followup="has_email_form=True but no ESP automation for buyer/seller leads",
  open_gap_count=1),
L(1497, "artbygurbani.com", "Artbygurbani", primary="Cart Recovery Opportunity", secondary="Follow-up Opportunity", confidence="medium",
  summary="Indian commissioned-art WooCommerce store (16 products) with WhatsApp chat and reviews already live but no ESP.",
  conv=45, cart=55, eng=50, followup=50, ci=35,
  ev_conv="has_cart=True, no ESP", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="WhatsApp chat and reviews already present", ev_followup="has_email_form=True but no ESP automation",
  open_gap_count=2),
L(1498, "www.sharpengineersna.com", "Sharpengineersna", primary="Follow-up Opportunity", confidence="low",
  summary="US gearless-machine bearing-housing casting components B2B manufacturer with a 'get a quote' CTA but no lead-capture form or ESP.",
  conv=35, cart=20, eng=25, followup=45, ci=25,
  ev_conv="has_cart=True likely false-positive for a B2B casting-components manufacturer", ev_cart="product_count_visible=1",
  ev_eng="cta_count_above_fold=2", ev_followup="no email or contact form detected behind the 'get a quote' CTA",
  open_gap_count=1),
L(1499, "fazcity.com", "Fazcity", primary="Insufficient Data", confidence="high",
  summary="Gateway/upstream connection-timeout error — no content retrievable.",
  conv=50, cart=50, eng=50, followup=50, ci=50,
  ev_conv="upstream connection timeout", ev_cart="has_cart=False (undetermined)",
  ev_eng="no signals extractable — gateway error", ev_followup="no signals extractable — gateway error",
  open_gap_count=0, disqualifier="upstream gateway error — cannot assess"),
L(1500, "nepaljuttafactory.com", "Nepaljuttafactory", primary="Cart Recovery Opportunity", secondary="Follow-up Opportunity", confidence="medium",
  summary="Nepalese shoe-factory WooCommerce store (27 products) with reviews already live but no ESP.",
  conv=45, cart=55, eng=40, followup=50, ci=35,
  ev_conv="has_cart=True, no ESP", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="reviews present but no chat", ev_followup="has_email_form=True but no ESP automation",
  open_gap_count=2),
L(1501, "lostejidos.com", "Lostejidos", primary="Insufficient Data", confidence="low",
  summary="Domain resolved but page_text is empty and platform is unknown.",
  conv=50, cart=50, eng=50, followup=50, ci=50,
  ev_conv="page_text empty", ev_cart="has_cart=False (undetermined)",
  ev_eng="no signals extractable", ev_followup="no signals extractable",
  open_gap_count=0, disqualifier="empty/undetermined signals — cannot assess"),
L(1502, "ishakoglupack.com", "Ishakoglupack", primary="Not a Good Fit", confidence="medium",
  summary="Turkish plastic-packaging B2B manufacturer already running Mailchimp ESP with WhatsApp chat.",
  conv=25, cart=20, eng=30, followup=20, ci=30,
  ev_conv="Mailchimp ESP already live", ev_cart="has_esp_tag=mailchimp",
  ev_eng="WhatsApp chat already present", ev_followup="email capture and ESP already wired together",
  open_gap_count=1, disqualifier="already has ESP + chat stack in place"),
L(1503, "www.hongqilaser.com", "Hongqilaser", primary="Cart Recovery Opportunity", secondary="Follow-up Opportunity", confidence="low",
  summary="Chinese laser medical-devices B2B manufacturer WooCommerce store (18 products) with WhatsApp chat and both email and contact forms, but no ESP.",
  conv=40, cart=55, eng=45, followup=50, ci=30,
  ev_conv="has_cart=True, no ESP", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="WhatsApp chat already present, cta_count_above_fold=4", ev_followup="has_email_form=True and has_contact_form=True but no ESP automation",
  open_gap_count=2),
L(1504, "funoonwear.com", "Funoonwear", primary="Cart Recovery Opportunity", secondary="Follow-up Opportunity", confidence="low",
  summary="Pakistani sportswear manufacturer/exporter B2B WooCommerce store with both email and contact forms but no ESP.",
  conv=40, cart=55, eng=30, followup=50, ci=30,
  ev_conv="has_cart=True, no ESP", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="generic popup only, no chat/reviews, cta_count_above_fold=2", ev_followup="has_email_form=True and has_contact_form=True but no ESP automation",
  open_gap_count=2),
L(1505, "instantlights.co.uk", "Instantlights", primary="Multi-Opportunity", confidence="medium",
  summary="UK LED-lighting retailer with an unusually large catalog (136 products) and an active promo but no ESP.",
  conv=50, cart=65, eng=45, followup=55, ci=40,
  ev_conv="has_cart=True, has_promo_bar=True, no ESP; 136 products", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="no chat/reviews despite large catalog", ev_followup="has_email_form=True but no ESP automation",
  open_gap_count=2),
L(1506, "dunesexpress.com", "Dunesexpress", primary="Cart Recovery Opportunity", secondary="Customer Engagement Opportunity", confidence="low",
  summary="Blinds/curtains retailer WooCommerce store, product_count_visible=1 suggests thin catalog, no ESP.",
  conv=35, cart=50, eng=25, followup=30, ci=25,
  ev_conv="has_cart=True, no ESP", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="generic popup only, no chat/reviews, cta_count_above_fold=2", ev_followup="no email capture form detected",
  open_gap_count=2),
L(1507, "vulcansportwear.com", "Vulcansportwear", primary="Cart Recovery Opportunity", secondary="Follow-up Opportunity", confidence="low",
  summary="Spanish custom-apparel manufacturer B2B WooCommerce store with WhatsApp chat and reviews already live but no ESP.",
  conv=40, cart=55, eng=45, followup=50, ci=30,
  ev_conv="has_cart=True, no ESP", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="WhatsApp chat and reviews already present", ev_followup="has_email_form=True but no ESP automation",
  open_gap_count=2),
L(1508, "samaamn.com", "Samaamn", primary="Insufficient Data", confidence="high",
  summary="Gateway/upstream connection-timeout error — no content retrievable.",
  conv=50, cart=50, eng=50, followup=50, ci=50,
  ev_conv="upstream connection timeout", ev_cart="has_cart=False (undetermined)",
  ev_eng="no signals extractable — gateway error", ev_followup="no signals extractable — gateway error",
  open_gap_count=0, disqualifier="upstream gateway error — cannot assess"),
L(1509, "rimaglobalperkasa.com", "Rimaglobalperkasa", primary="Cart Recovery Opportunity", secondary="Customer Engagement Opportunity", confidence="medium",
  summary="Indonesian heavy-equipment dealer B2B (forklifts, excavators) WooCommerce store (59 products) with no capture form or ESP.",
  conv=40, cart=60, eng=35, followup=30, ci=30,
  ev_conv="has_cart=True, no ESP, 59 products", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="no chat/reviews/popup, cta_count_above_fold=2", ev_followup="no email capture form detected",
  open_gap_count=2),
L(1510, "atlashomedesign.co", "Atlashomedesign", primary="Not a Good Fit", confidence="medium",
  summary="Egyptian blinds/window-treatments retailer already running Mailchimp ESP with reviews.",
  conv=25, cart=20, eng=30, followup=20, ci=30,
  ev_conv="Mailchimp ESP already live", ev_cart="has_esp_tag=mailchimp",
  ev_eng="reviews present, cta_count_above_fold=1", ev_followup="email capture and ESP already wired together",
  open_gap_count=1, disqualifier="already has ESP + reviews stack in place"),
L(1511, "medtest-ghana.com", "Medtest-Ghana", primary="Follow-up Opportunity", confidence="low",
  summary="Ghanaian medical-diagnostic-tests B2B firm with both email and contact forms and booking already offered, but no ESP.",
  conv=40, cart=20, eng=35, followup=50, ci=30,
  ev_conv="has_cart=True likely false-positive for a B2B diagnostics firm", ev_cart="product_count_visible=0",
  ev_eng="booking already offered, cta_count_above_fold=3", ev_followup="has_email_form=True and has_contact_form=True but no ESP automation",
  open_gap_count=1),
L(1513, "voltsine.in", "Voltsine", primary="Cart Recovery Opportunity", secondary="Follow-up Opportunity", confidence="low",
  summary="Indian electrical-equipment B2B WooCommerce store (22 products) with WhatsApp chat and reviews already live but no ESP.",
  conv=40, cart=55, eng=45, followup=50, ci=30,
  ev_conv="has_cart=True, no ESP", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="WhatsApp chat and reviews already present, cta_count_above_fold=2", ev_followup="has_email_form=True and has_contact_form=True but no ESP automation",
  open_gap_count=2),
L(1514, "www.thetrailerteam.com", "Thetrailerteam", primary="Insufficient Data", confidence="high",
  summary="Page served an obfuscated JS-based verification wall — no real content retrievable.",
  conv=50, cart=50, eng=50, followup=50, ci=50,
  ev_conv="bot-check/obfuscated verification page", ev_cart="has_cart=False (undetermined)",
  ev_eng="no signals extractable — verification wall", ev_followup="no signals extractable — verification wall",
  open_gap_count=0, disqualifier="anti-bot verification page — cannot assess real content"),
L(1515, "bulkandorganics.com", "Bulkandorganics", primary="Insufficient Data", confidence="high",
  summary="Cloudflare DNS resolution error (Error 1001) — domain not resolvable through Cloudflare.",
  conv=50, cart=50, eng=50, followup=50, ci=50,
  ev_conv="Cloudflare DNS resolution error", ev_cart="has_cart=False (undetermined)",
  ev_eng="no signals extractable — DNS error", ev_followup="no signals extractable — DNS error",
  open_gap_count=0, disqualifier="Cloudflare DNS resolution error — cannot assess"),
L(1516, "gycon.net", "Gycon", primary="Not a Good Fit", confidence="medium",
  summary="US construction/civil-engineering B2B firm already running Mailchimp ESP with Tidio chat.",
  conv=25, cart=15, eng=30, followup=20, ci=30,
  ev_conv="has_cart=True likely false-positive for a B2B construction firm", ev_cart="has_esp_tag=mailchimp",
  ev_eng="Tidio chat already present", ev_followup="email capture and ESP already wired together",
  open_gap_count=1, disqualifier="already has ESP + chat stack in place"),
L(1517, "www.cantinealdegheri.com", "Cantinealdegheri", primary="Insufficient Data", confidence="low",
  summary="Domain resolved but page_text is empty and platform is unknown.",
  conv=50, cart=50, eng=50, followup=50, ci=50,
  ev_conv="page_text empty", ev_cart="has_cart=False (undetermined)",
  ev_eng="no signals extractable", ev_followup="no signals extractable",
  open_gap_count=0, disqualifier="empty/undetermined signals — cannot assess"),
L(1518, "shreeimpex.co", "Shreeimpex", primary="Follow-up Opportunity", confidence="low",
  summary="Indian bags manufacturer/exporter B2B store with a Mailchimp ESP tag but no visible email-capture form to feed it.",
  conv=35, cart=30, eng=25, followup=40, ci=30,
  ev_conv="has_cart=True, has_esp_tag=mailchimp but has_email_form=False — ESP underused", ev_cart="has_esp_tag=mailchimp, has_email_form=False",
  ev_eng="no chat/reviews/popup", ev_followup="ESP present but no capture mechanism visibly wired to it",
  open_gap_count=1),
L(1519, "silkroad-es.com", "Silkroad-Es", primary="Follow-up Opportunity", confidence="low",
  summary="Spanish (Barcelona) immigration/visa/investment/tourism consulting business with multiple consultation-request forms mentioned in copy but has_email_form flagged false by the extractor, and no ESP.",
  conv=40, cart=25, eng=35, followup=50, ci=30,
  ev_conv="has_cart=True likely false-positive for a consulting business", ev_cart="reviews present",
  ev_eng="reviews present", ev_followup="page copy references multiple consultation forms but has_email_form=False and no ESP detected",
  open_gap_count=1),
L(1520, "aieskyline.co.uk", "Aieskyline", primary="Not a Good Fit", confidence="medium",
  summary="UK electric-taxi rental service already running Mailchimp ESP with cta_count_above_fold=6.",
  conv=25, cart=20, eng=30, followup=20, ci=30,
  ev_conv="has_cart=True likely false-positive for a vehicle-rental service", ev_cart="has_esp_tag=mailchimp",
  ev_eng="cta_count_above_fold=6", ev_followup="email capture and ESP already wired together",
  open_gap_count=1, disqualifier="already has ESP in place"),
L(1521, "www.nesasolusi.com", "Nesasolusi", primary="Follow-up Opportunity", confidence="low",
  summary="Indonesian industrial-equipment B2B distributor with a moderate above-fold CTA count (4) but no lead-capture form or ESP.",
  conv=35, cart=20, eng=30, followup=45, ci=25,
  ev_conv="has_cart=True likely false-positive for a B2B equipment distributor", ev_cart="product_count_visible=0",
  ev_eng="cta_count_above_fold=4", ev_followup="no email or contact form detected",
  open_gap_count=1),
L(1522, "horeca-hub.net", "Horeca-Hub", primary="Cart Recovery Opportunity", secondary="Customer Engagement Opportunity", confidence="low",
  summary="Egyptian food-ingredients B2B/HoReCa supplier WooCommerce store (11 products) with no capture form or ESP.",
  conv=35, cart=50, eng=25, followup=30, ci=25,
  ev_conv="has_cart=True, no ESP", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="no chat/reviews/popup, cta_count_above_fold=1", ev_followup="no email capture form detected",
  open_gap_count=2),
L(1523, "qortexdistributions.com", "Qortexdistributions", primary="Cart Recovery Opportunity", secondary="Follow-up Opportunity", confidence="low",
  summary="Electronics/automotive-accessories B2B distributor WooCommerce store with a moderate above-fold CTA count (4) but no ESP.",
  conv=40, cart=55, eng=30, followup=45, ci=30,
  ev_conv="has_cart=True, no ESP, cta_count_above_fold=4", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="generic popup only, no chat/reviews", ev_followup="has_email_form=True but no ESP automation",
  open_gap_count=2),
L(1524, "ronch.us", "Ronch", primary="Insufficient Data", confidence="low",
  summary="Domain resolved but page_text is empty and platform is unknown.",
  conv=50, cart=50, eng=50, followup=50, ci=50,
  ev_conv="page_text empty", ev_cart="has_cart=False (undetermined)",
  ev_eng="no signals extractable", ev_followup="no signals extractable",
  open_gap_count=0, disqualifier="empty/undetermined signals — cannot assess"),
L(1525, "khammash-otr.com", "Khammash-Otr", primary="Follow-up Opportunity", secondary="Cart Recovery Opportunity", confidence="low",
  summary="Bulgarian off-the-road tires B2B distributor with WhatsApp chat but no email-capture form or ESP.",
  conv=40, cart=40, eng=40, followup=45, ci=30,
  ev_conv="has_cart=True, no ESP", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="WhatsApp chat already present", ev_followup="no email capture form detected despite active chat channel",
  open_gap_count=2),
L(1526, "imenshim.com", "Imenshim", primary="Cart Recovery Opportunity", secondary="Customer Engagement Opportunity", confidence="low",
  summary="WooCommerce store (12 products) whose fetched copy is mostly unrendered jQuery script boilerplate, no ESP.",
  conv=35, cart=50, eng=25, followup=25, ci=25,
  ev_conv="has_cart=True, no ESP; page content largely unrendered jQuery boilerplate", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="no chat/reviews/popup", ev_followup="no email capture form detected",
  open_gap_count=2),
]

n = append_results(RESULTS)
print(f"appended {n} rows (chunk_016)")
