import sys
sys.path.insert(0, ".")
from layer3_write import append_results


def L(lead_id, domain, business_name, primary, confidence, summary,
      conv, cart, eng, followup, ci, ev_conv, ev_cart, ev_eng, ev_followup,
      open_gap_count, secondary=None, disqualifier=None):
    return (lead_id, domain, business_name, primary, secondary, confidence, summary,
            conv, cart, eng, followup, ci, ev_conv, ev_cart, ev_eng, ev_followup,
            open_gap_count, disqualifier)


RESULTS = [
L(1083, "myoradent.com", "Myoradent", primary="Not a Good Fit", confidence="medium",
  summary="US dental-care powder brand already running Mailchimp ESP with WhatsApp chat and reviews.",
  conv=25, cart=25, eng=35, followup=20, ci=30,
  ev_conv="Mailchimp ESP already live", ev_cart="has_esp_tag=mailchimp",
  ev_eng="WhatsApp chat and reviews already present, cta_count_above_fold=5", ev_followup="email capture and ESP already wired together",
  open_gap_count=1, disqualifier="already has ESP + chat + reviews stack in place"),
L(1084, "aiuth.org", "Aiuth", primary="Not a Good Fit", confidence="medium",
  summary="Iraq-Ukraine trade-relations B2B association already running Mailchimp ESP with an active promo.",
  conv=25, cart=20, eng=25, followup=20, ci=30,
  ev_conv="has_cart=True likely false-positive for a trade association", ev_cart="has_esp_tag=mailchimp",
  ev_eng="cta_count_above_fold=4", ev_followup="email capture and ESP already wired together",
  open_gap_count=1, disqualifier="already has ESP in place"),
L(1085, "hitfmcalabar.com", "Hitfmcalabar", primary="Follow-up Opportunity", confidence="medium",
  summary="Nigerian radio station with booking already offered but no email-capture form or ESP.",
  conv=40, cart=20, eng=45, followup=55, ci=35,
  ev_conv="has_cart=True likely false-positive for a radio station", ev_cart="product_count_visible=0",
  ev_eng="booking already offered, cta_count_above_fold=6", ev_followup="has_email_form=True but no ESP automation for advertiser/listener leads",
  open_gap_count=1),
L(1086, "crazecaffe.com", "Crazecaffe", primary="Cart Recovery Opportunity", secondary="Follow-up Opportunity", confidence="medium",
  summary="UK coffee-gear WooCommerce store (9 products) with a Poptin capture popup but no email form or ESP.",
  conv=45, cart=65, eng=45, followup=50, ci=35,
  ev_conv="has_cart=True, has_popup_script=True (poptin), no ESP", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="Poptin popup present, cta_count_above_fold=3", ev_followup="no confirmed email-capture form despite active popup",
  open_gap_count=2),
L(1087, "paperclipsplus.com", "Paperclipsplus", primary="Insufficient Data", confidence="low",
  summary="Domain resolved but page_text is empty and platform is unknown.",
  conv=50, cart=50, eng=50, followup=50, ci=50,
  ev_conv="page_text empty", ev_cart="has_cart=False (undetermined)",
  ev_eng="no signals extractable", ev_followup="no signals extractable",
  open_gap_count=0, disqualifier="empty/undetermined signals — cannot assess"),
L(1088, "cyrabeauty.ca", "Cyrabeauty", primary="Insufficient Data", confidence="low",
  summary="Domain resolved but page_text is empty and platform is unknown.",
  conv=50, cart=50, eng=50, followup=50, ci=50,
  ev_conv="page_text empty", ev_cart="has_cart=False (undetermined)",
  ev_eng="no signals extractable", ev_followup="no signals extractable",
  open_gap_count=0, disqualifier="empty/undetermined signals — cannot assess"),
L(1089, "chikitsaratna.in", "Chikitsaratna", primary="Insufficient Data", confidence="high",
  summary="Page shows the default aaPanel hosting-control-panel install page — no real site has been built yet.",
  conv=50, cart=50, eng=50, followup=50, ci=50,
  ev_conv="default aaPanel install page", ev_cart="no storefront exists",
  ev_eng="no real content — unbuilt site", ev_followup="no real content — unbuilt site",
  open_gap_count=0, disqualifier="site not built — default hosting-panel install page"),
L(1090, "silverpharma.tn", "Silverpharma", primary="Cart Recovery Opportunity", secondary="Follow-up Opportunity", confidence="medium",
  summary="Tunisian jewelry WooCommerce store with WhatsApp chat and reviews already live but no ESP.",
  conv=45, cart=65, eng=50, followup=50, ci=35,
  ev_conv="has_cart=True, no ESP", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="WhatsApp chat and reviews already present", ev_followup="no email capture form detected despite active chat",
  open_gap_count=2),
L(1091, "xhdindustries.com", "Xhdindustries", primary="Follow-up Opportunity", confidence="medium",
  summary="Australian heavy-equipment dealer (excavators, forklifts) B2B with an email form but no ESP.",
  conv=45, cart=20, eng=40, followup=60, ci=35,
  ev_conv="has_cart=True likely false-positive for a heavy-equipment dealer", ev_cart="product_count_visible=0",
  ev_eng="cta_count_above_fold=5", ev_followup="has_email_form=True but no ESP automation for high-value equipment leads",
  open_gap_count=1),
L(1092, "soorajachar.com", "Soorajachar", primary="Follow-up Opportunity", confidence="low",
  summary="Author/numerology-consultant personal brand with an Omnisend ESP tag but no visible email-capture form despite a 'free welcome gift' offer in copy.",
  conv=40, cart=25, eng=40, followup=45, ci=30,
  ev_conv="has_cart=True likely false-positive for a personal coaching/consulting brand", ev_cart="has_esp_tag=omnisend, has_email_form=False",
  ev_eng="booking already offered, cta_count_above_fold=3", ev_followup="ESP present but no capture mechanism visibly wired to it despite a 'free gift' offer",
  open_gap_count=1),
L(1093, "synaworlds.com", "Synaworlds", primary="Insufficient Data", confidence="low",
  summary="Domain resolved but page_text is empty and platform is unknown.",
  conv=50, cart=50, eng=50, followup=50, ci=50,
  ev_conv="page_text empty", ev_cart="has_cart=False (undetermined)",
  ev_eng="no signals extractable", ev_followup="no signals extractable",
  open_gap_count=0, disqualifier="empty/undetermined signals — cannot assess"),
L(1094, "argan-gold.com.ua", "Argan-Gold", primary="Cart Recovery Opportunity", secondary="Customer Engagement Opportunity", confidence="medium",
  summary="Ukrainian argan-oil cosmetics WooCommerce store (18 products) with no capture form or ESP.",
  conv=45, cart=65, eng=40, followup=35, ci=35,
  ev_conv="has_cart=True, no ESP", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="no chat/reviews/popup", ev_followup="no email capture form detected",
  open_gap_count=2),
L(1095, "humamedikal.com", "Humamedikal", primary="Cart Recovery Opportunity", secondary="Follow-up Opportunity", confidence="low",
  summary="Turkish medical supplements WooCommerce store with WhatsApp chat, product_count_visible=0 suggests thin page fetched.",
  conv=40, cart=55, eng=45, followup=45, ci=30,
  ev_conv="has_cart=True, no ESP", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="WhatsApp chat present but no reviews", ev_followup="no email capture form detected despite active chat",
  open_gap_count=2),
L(1096, "jbfloors-styling.nl", "Jbfloors-Styling", primary="Cart Recovery Opportunity", secondary="Follow-up Opportunity", confidence="medium",
  summary="Dutch flooring retailer (10 products) with WhatsApp chat and reviews already live but no ESP.",
  conv=45, cart=65, eng=50, followup=50, ci=35,
  ev_conv="has_cart=True, no ESP", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="WhatsApp chat and reviews already present", ev_followup="no email capture form detected despite active chat",
  open_gap_count=2),
L(1097, "sunmoon-kw.com", "Sunmoon-Kw", primary="Cart Recovery Opportunity", secondary="Follow-up Opportunity", confidence="medium",
  summary="Kuwaiti WooCommerce store (24 products) with no ESP.",
  conv=45, cart=65, eng=40, followup=55, ci=35,
  ev_conv="has_cart=True, no ESP", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="generic popup only, no chat/reviews, cta_count_above_fold=1", ev_followup="has_email_form=True but no ESP automation",
  open_gap_count=2),
L(1098, "kouleursdafrik.bj", "Kouleursdafrik", primary="Cart Recovery Opportunity", secondary="Follow-up Opportunity", confidence="medium",
  summary="Beninese fashion/decor WooCommerce store with reviews already live but no ESP.",
  conv=45, cart=65, eng=45, followup=55, ci=35,
  ev_conv="has_cart=True, no ESP", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="reviews present but no chat/popup", ev_followup="has_email_form=True but no ESP automation",
  open_gap_count=2),
L(1099, "modernskinderm.com", "Modernskinderm", primary="Follow-up Opportunity", confidence="medium",
  summary="US dermatology clinic (acne, Botox, laser therapy) with an email form and a high above-fold CTA count (6), but no ESP.",
  conv=45, cart=25, eng=45, followup=60, ci=35,
  ev_conv="has_cart=True likely false-positive for a clinical services provider", ev_cart="product_count_visible=0",
  ev_eng="cta_count_above_fold=6", ev_followup="has_email_form=True but no ESP automation for patient-consult leads",
  open_gap_count=1),
L(1100, "miamicarbondesigns.com", "Miamicarbondesigns", primary="Cart Recovery Opportunity", secondary="Follow-up Opportunity", confidence="medium",
  summary="Custom carbon-fiber steering-wheel maker (34 products) with both email and contact forms but no ESP.",
  conv=50, cart=65, eng=40, followup=55, ci=35,
  ev_conv="has_cart=True, no ESP", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="no chat/reviews/popup despite 34-product catalog", ev_followup="has_email_form=True and has_contact_form=True but no ESP automation",
  open_gap_count=2),
L(1109, "backaerttondeuse.com", "Backaerttondeuse", primary="Cart Recovery Opportunity", secondary="Follow-up Opportunity", confidence="low",
  summary="Belgian garden-equipment WooCommerce store with a Poptin capture popup, product_count_visible=0 suggests thin page fetched.",
  conv=40, cart=60, eng=45, followup=45, ci=30,
  ev_conv="has_cart=True, has_popup_script=True (poptin), no ESP", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="Poptin popup present, no chat/reviews", ev_followup="has_email_form=True but no ESP automation",
  open_gap_count=2),
L(1111, "enbattech.com", "Enbattech", primary="Insufficient Data", confidence="high",
  summary="Gateway/upstream connection error — no content retrievable.",
  conv=50, cart=50, eng=50, followup=50, ci=50,
  ev_conv="upstream connect error", ev_cart="has_cart=False (undetermined)",
  ev_eng="no signals extractable — gateway error", ev_followup="no signals extractable — gateway error",
  open_gap_count=0, disqualifier="upstream gateway error — cannot assess"),
L(1113, "saludtamarugal.com", "Saludtamarugal", primary="Follow-up Opportunity", confidence="medium",
  summary="Chilean mental-health/wellness clinic with WhatsApp chat but no email-capture form or ESP.",
  conv=45, cart=25, eng=50, followup=55, ci=35,
  ev_conv="has_cart=True likely false-positive for a clinical services provider", ev_cart="product_count_visible=0",
  ev_eng="WhatsApp chat already present", ev_followup="no email capture form detected despite active chat channel",
  open_gap_count=1),
L(1116, "screengo.in", "Screengo", primary="Follow-up Opportunity", confidence="medium",
  summary="Indian mobile-repair service (multi-city, multi-brand) with both email and contact forms but no ESP.",
  conv=45, cart=20, eng=40, followup=55, ci=35,
  ev_conv="has_cart=True likely false-positive for a repair services business", ev_cart="product_count_visible=0",
  ev_eng="generic popup only, cta_count_above_fold=2", ev_followup="has_email_form=True and has_contact_form=True but no ESP automation",
  open_gap_count=1),
L(1122, "visseriaed.ee", "Visseriaed", primary="Cart Recovery Opportunity", secondary="Follow-up Opportunity", confidence="low",
  summary="Estonian strawberry-plant nursery WooCommerce store, product_count_visible=0 suggests thin page fetched.",
  conv=40, cart=60, eng=35, followup=50, ci=30,
  ev_conv="has_cart=True, no ESP", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="no chat/reviews/popup", ev_followup="has_email_form=True but no ESP automation",
  open_gap_count=2),
L(1126, "cerasvelatur.com", "Cerasvelatur", primary="Cart Recovery Opportunity", secondary="Follow-up Opportunity", confidence="low",
  summary="Spanish candle-making WooCommerce store, product_count_visible=0 suggests thin page fetched.",
  conv=40, cart=60, eng=35, followup=50, ci=30,
  ev_conv="has_cart=True, no ESP", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="generic popup only, no chat/reviews", ev_followup="has_email_form=True but no ESP automation",
  open_gap_count=2),
L(1128, "gsbleshirondelles.com", "Gsbleshirondelles", primary="Follow-up Opportunity", confidence="medium",
  summary="Cameroonian bilingual school with reviews already live but no ESP behind its email form.",
  conv=45, cart=25, eng=50, followup=55, ci=35,
  ev_conv="has_cart=True likely false-positive for a K-12 school", ev_cart="product_count_visible=0",
  ev_eng="reviews present", ev_followup="has_email_form=True but no ESP automation for enrollment leads",
  open_gap_count=1),
L(1130, "angeleswellness.co", "Angeleswellness", primary="Cart Recovery Opportunity", secondary="Follow-up Opportunity", confidence="medium",
  summary="US cleanse/wellness-supplement WooCommerce store (7 products) with reviews already live but no ESP.",
  conv=45, cart=65, eng=45, followup=55, ci=35,
  ev_conv="has_cart=True, no ESP", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="reviews present, cta_count_above_fold=5", ev_followup="has_email_form=True but no ESP automation",
  open_gap_count=2),
L(1132, "silkenswan.com", "Silkenswan", primary="Multi-Opportunity", confidence="medium",
  summary="Sleepwear WooCommerce store (19 products) with reviews and a high above-fold CTA count (10), but no ESP.",
  conv=50, cart=65, eng=55, followup=55, ci=40,
  ev_conv="has_cart=True, no ESP, cta_count_above_fold=10", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="reviews present, strong above-fold CTA presence", ev_followup="has_email_form=True but no ESP automation",
  open_gap_count=2),
L(1133, "youwetravel.com", "Youwetravel", primary="Cart Recovery Opportunity", secondary="Follow-up Opportunity", confidence="medium",
  summary="India/Dubai/Singapore tour operator with booking and reviews already live but no ESP.",
  conv=50, cart=55, eng=55, followup=55, ci=40,
  ev_conv="has_cart=True, no ESP", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="booking and reviews already present, cta_count_above_fold=3", ev_followup="has_email_form=True but no ESP automation for high-value tour bookings",
  open_gap_count=2),
L(1140, "srsl.online", "Srsl", primary="Cart Recovery Opportunity", secondary="Customer Engagement Opportunity", confidence="medium",
  summary="UK DIY-products WooCommerce store (8 products) with an active promo but no capture form or ESP.",
  conv=45, cart=65, eng=45, followup=35, ci=35,
  ev_conv="has_cart=True, has_promo_bar=True, no ESP", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="generic popup only, no chat/reviews despite active promo", ev_followup="no email capture form detected",
  open_gap_count=2),
L(1143, "www.likeshop.mx", "Www.Likeshop", primary="Insufficient Data", confidence="high",
  summary="Page served an anti-bot verification challenge — no real content retrievable.",
  conv=50, cart=50, eng=50, followup=50, ci=50,
  ev_conv="bot-check page, no real content", ev_cart="has_cart=False (undetermined)",
  ev_eng="no signals extractable — verification wall", ev_followup="no signals extractable — verification wall",
  open_gap_count=0, disqualifier="anti-bot verification page — cannot assess real content"),
L(1145, "castanedalabmedic.com", "Castanedalabmedic", primary="Cart Recovery Opportunity", secondary="Follow-up Opportunity", confidence="medium",
  summary="Peruvian lab-equipment/reagents B2B WooCommerce store with tawk chat but no ESP.",
  conv=45, cart=55, eng=50, followup=45, ci=35,
  ev_conv="has_cart=True, no ESP", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="tawk chat already present", ev_followup="no email capture form detected despite active chat",
  open_gap_count=2),
L(1146, "ionianserenity.com", "Ionianserenity", primary="Cart Recovery Opportunity", secondary="Customer Engagement Opportunity", confidence="low",
  summary="Cyprus WooCommerce store with mostly unrendered theme boilerplate in fetched copy, no ESP.",
  conv=35, cart=55, eng=30, followup=30, ci=25,
  ev_conv="has_cart=True, no ESP; page content largely unrendered theme boilerplate", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="cta_count_above_fold=1", ev_followup="no email capture form detected",
  open_gap_count=2),
L(1147, "techaudits.co", "Techaudits", primary="Follow-up Opportunity", confidence="medium",
  summary="SEO/digital-marketing agency B2B (managed SEO, GBP audits) with an email form and a high above-fold CTA count (7), but no ESP.",
  conv=45, cart=25, eng=45, followup=60, ci=35,
  ev_conv="has_cart=True likely false-positive for a B2B marketing agency", ev_cart="product_count_visible=0",
  ev_eng="cta_count_above_fold=7", ev_followup="has_email_form=True but no ESP automation",
  open_gap_count=1),
L(1148, "mbmgroup.in", "Mbmgroup", primary="Follow-up Opportunity", confidence="medium",
  summary="Indian multi-business conglomerate (real estate, healthcare, pharma, tours) with WhatsApp chat and reviews already live, but no ESP.",
  conv=45, cart=25, eng=50, followup=60, ci=40,
  ev_conv="has_cart=True likely false-positive for a multi-vertical conglomerate", ev_cart="product_count_visible=0",
  ev_eng="WhatsApp chat and reviews already present, cta_count_above_fold=3", ev_followup="has_email_form=True and has_contact_form=True but no ESP automation",
  open_gap_count=1),
L(1149, "trusquwa.com", "Trusquwa", primary="Cart Recovery Opportunity", secondary="Follow-up Opportunity", confidence="low",
  summary="Elevator/escalator B2B store whose fetched copy includes WooCommerce theme-demo boilerplate ('Advanced Variable products with swatches'), suggesting an unconfigured or demo storefront.",
  conv=35, cart=50, eng=35, followup=45, ci=25,
  ev_conv="has_cart=True, no ESP; page content includes apparent theme-demo boilerplate text", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="cta_count_above_fold=2, content quality uncertain", ev_followup="has_email_form=True but no ESP automation; site may be an unconfigured demo",
  open_gap_count=2),
L(1150, "oncosuretesting.com", "Oncosuretesting", primary="Follow-up Opportunity", confidence="medium",
  summary="Oncology/cancer-testing service with an email form and a moderate above-fold CTA count (5), but no confirmed ESP.",
  conv=45, cart=25, eng=40, followup=60, ci=35,
  ev_conv="has_cart=True likely false-positive for a clinical testing service", ev_cart="product_count_visible=0",
  ev_eng="cta_count_above_fold=5; a HubSpot widget reference appears in raw code but chat is not confirmed by the extractor", ev_followup="has_email_form=True but no ESP automation for testing-inquiry leads",
  open_gap_count=1),
L(1151, "mtechcourse.com", "Mtechcourse", primary="Not a Good Fit", confidence="medium",
  summary="AI/data-science online course provider already running Mailchimp ESP with reviews.",
  conv=25, cart=20, eng=30, followup=20, ci=30,
  ev_conv="has_cart=True likely false-positive for a course provider", ev_cart="has_esp_tag=mailchimp",
  ev_eng="reviews present", ev_followup="email capture and ESP already wired together",
  open_gap_count=1, disqualifier="already has ESP + reviews stack in place"),
L(1152, "razzofficialsite.com", "Razzofficialsite", primary="Cart Recovery Opportunity", secondary="Customer Engagement Opportunity", confidence="medium",
  summary="Vape-products WooCommerce store (20 products) with reviews and an active discount promo but no ESP.",
  conv=45, cart=65, eng=50, followup=35, ci=35,
  ev_conv="has_cart=True, no ESP", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="reviews present, active promo (SAVE10 code)", ev_followup="no email capture form detected despite active promo",
  open_gap_count=2),
L(1153, "premiumgyerekruha.hu", "Premiumgyerekruha", primary="Insufficient Data", confidence="medium",
  summary="Hungarian kids-clothing site whose fetched copy is dominated by repeated XStore WordPress theme-demo boilerplate text and a 'shipping paused for vacation' notice, suggesting an unconfigured demo store rather than a live business.",
  conv=50, cart=50, eng=50, followup=50, ci=50,
  ev_conv="page content is XStore theme-demo boilerplate, not real store copy", ev_cart="shipping explicitly paused ('szünetel')",
  ev_eng="no reliable signals extractable from demo-theme content", ev_followup="no reliable signals extractable from demo-theme content",
  open_gap_count=0, disqualifier="page content is unconfigured theme-demo boilerplate with shipping paused — cannot assess real business"),
L(1154, "arenasports.co.za", "Arenasports", primary="Cart Recovery Opportunity", secondary="Follow-up Opportunity", confidence="low",
  summary="South African sporting-goods WooCommerce store with WhatsApp chat, product_count_visible=0 suggests thin page fetched.",
  conv=40, cart=60, eng=45, followup=45, ci=30,
  ev_conv="has_cart=True, no ESP", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="WhatsApp chat present but no reviews", ev_followup="has_email_form=True but no ESP automation",
  open_gap_count=2),
L(1155, "ravimx.com", "Ravimx", primary="Cart Recovery Opportunity", secondary="Follow-up Opportunity", confidence="medium",
  summary="Mexican food/spice brand WooCommerce store with reviews already live but no ESP.",
  conv=45, cart=60, eng=45, followup=55, ci=35,
  ev_conv="has_cart=True, no ESP", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="reviews present but no chat/popup capture", ev_followup="has_email_form=True but no ESP automation",
  open_gap_count=2),
L(1156, "finalmedic.ca", "Finalmedic", primary="Not a Good Fit", confidence="medium",
  summary="Canadian medical-supplies retailer (81 products) already running Mailchimp ESP with reviews and a very high above-fold CTA count (17).",
  conv=20, cart=20, eng=25, followup=15, ci=25,
  ev_conv="Mailchimp ESP already live, cta_count_above_fold=17", ev_cart="has_esp_tag=mailchimp",
  ev_eng="reviews and very strong above-fold CTA presence already in place", ev_followup="email capture and ESP already wired together",
  open_gap_count=1, disqualifier="already has ESP + reviews + strong CTA presence in place"),
L(1157, "maxkoya.com", "Maxkoya", primary="Not a Good Fit", confidence="medium",
  summary="Fashion apparel retailer (17 products) already running Mailchimp ESP.",
  conv=25, cart=20, eng=30, followup=20, ci=30,
  ev_conv="Mailchimp ESP already live", ev_cart="has_esp_tag=mailchimp",
  ev_eng="cta_count_above_fold=1", ev_followup="email capture and ESP already wired together",
  open_gap_count=1, disqualifier="already has ESP in place"),
L(1158, "goaldrivenrespite.com", "Goaldrivenrespite", primary="Cart Recovery Opportunity", secondary="Follow-up Opportunity", confidence="medium",
  summary="US respite-care service with an attached shop (8 products), booking, and reviews already live, but no ESP.",
  conv=50, cart=55, eng=55, followup=55, ci=40,
  ev_conv="has_cart=True, no ESP", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="booking and reviews already present, cta_count_above_fold=6", ev_followup="has_email_form=True but no ESP automation",
  open_gap_count=2),
L(1159, "sokgroup.co.uk", "Sokgroup", primary="Cart Recovery Opportunity", secondary="Customer Engagement Opportunity", confidence="low",
  summary="UK specialty-foods WooCommerce store with reviews already live but no capture form or ESP.",
  conv=40, cart=60, eng=45, followup=35, ci=30,
  ev_conv="has_cart=True, no ESP", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="reviews present, cta_count_above_fold=4", ev_followup="no email capture form detected",
  open_gap_count=2),
L(1160, "barn-bites.com", "Barn-Bites", primary="Insufficient Data", confidence="low",
  summary="Domain resolved but page_text is empty and platform is unknown.",
  conv=50, cart=50, eng=50, followup=50, ci=50,
  ev_conv="page_text empty", ev_cart="has_cart=False (undetermined)",
  ev_eng="no signals extractable", ev_followup="no signals extractable",
  open_gap_count=0, disqualifier="empty/undetermined signals — cannot assess"),
L(1161, "silceramica.ro", "Silceramica", primary="Cart Recovery Opportunity", secondary="Customer Engagement Opportunity", confidence="low",
  summary="Romanian WooCommerce store with mostly unrendered JS boilerplate in fetched copy, no ESP.",
  conv=35, cart=55, eng=30, followup=30, ci=25,
  ev_conv="has_cart=True, no ESP; page content largely unrendered JS boilerplate", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="no chat/reviews/popup", ev_followup="no email capture form detected",
  open_gap_count=2),
L(1162, "tasteindia.pl", "Tasteindia", primary="Cart Recovery Opportunity", secondary="Follow-up Opportunity", confidence="low",
  summary="Polish Indian-restaurant WooCommerce ordering site, product_count_visible=0 suggests thin page fetched.",
  conv=40, cart=60, eng=35, followup=50, ci=30,
  ev_conv="has_cart=True, no ESP", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="generic popup only, no chat/reviews", ev_followup="has_email_form=True but no ESP automation",
  open_gap_count=2),
L(1163, "katyacervio.it", "Katyacervio", primary="Cart Recovery Opportunity", secondary="Customer Engagement Opportunity", confidence="low",
  summary="Italian WooCommerce store with mostly unrendered theme boilerplate in fetched copy but a moderate above-fold CTA count (8), no ESP.",
  conv=40, cart=55, eng=40, followup=30, ci=25,
  ev_conv="has_cart=True, no ESP; page content largely unrendered theme boilerplate", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="cta_count_above_fold=8 despite thin readable content", ev_followup="no email capture form detected",
  open_gap_count=2),
L(1164, "sattvastha.com", "Sattvastha", primary="Insufficient Data", confidence="low",
  summary="Domain resolved but page_text is empty and platform is unknown.",
  conv=50, cart=50, eng=50, followup=50, ci=50,
  ev_conv="page_text empty", ev_cart="has_cart=False (undetermined)",
  ev_eng="no signals extractable", ev_followup="no signals extractable",
  open_gap_count=0, disqualifier="empty/undetermined signals — cannot assess"),
L(1165, "fitzfood.com", "Fitzfood", primary="Cart Recovery Opportunity", secondary="Follow-up Opportunity", confidence="low",
  summary="Turkish diet meal-package WooCommerce store, product_count_visible=0 suggests thin page fetched.",
  conv=40, cart=60, eng=35, followup=50, ci=30,
  ev_conv="has_cart=True, no ESP", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="generic popup only, no chat/reviews", ev_followup="has_email_form=True but no ESP automation",
  open_gap_count=2),
L(1166, "safesysinnovations.com", "Safesysinnovations", primary="Follow-up Opportunity", confidence="medium",
  summary="B2B tech/business-solutions consultancy with reviews already live and both email and contact forms, but no ESP.",
  conv=45, cart=25, eng=45, followup=60, ci=35,
  ev_conv="has_cart=True likely false-positive for a B2B consultancy", ev_cart="product_count_visible=0",
  ev_eng="reviews present, cta_count_above_fold=1", ev_followup="has_email_form=True and has_contact_form=True but no ESP automation",
  open_gap_count=1),
L(1168, "kvrl.in", "Kvrl", primary="Follow-up Opportunity", confidence="low",
  summary="Indian web/app development digital agency with an email form but no ESP.",
  conv=40, cart=20, eng=35, followup=55, ci=30,
  ev_conv="has_cart=True likely false-positive for a B2B digital agency", ev_cart="product_count_visible=0",
  ev_eng="generic popup only, cta_count_above_fold=1", ev_followup="has_email_form=True but no ESP automation",
  open_gap_count=1),
L(1169, "craftsasia.com", "Craftsasia", primary="Cart Recovery Opportunity", secondary="Follow-up Opportunity", confidence="medium",
  summary="US crafts/figurines retailer (4 products) with no ESP.",
  conv=45, cart=60, eng=40, followup=55, ci=35,
  ev_conv="has_cart=True, no ESP", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="generic popup only, no chat/reviews, cta_count_above_fold=4", ev_followup="has_email_form=True but no ESP automation",
  open_gap_count=2),
L(1170, "prasinotech.in", "Prasinotech", primary="Follow-up Opportunity", confidence="low",
  summary="Indian renewable-energy/RESCO B2B services provider with reviews already live but no ESP or capture form.",
  conv=40, cart=25, eng=40, followup=50, ci=30,
  ev_conv="has_cart=True likely false-positive for a B2B energy-services provider", ev_cart="product_count_visible=0",
  ev_eng="reviews present, cta_count_above_fold=2", ev_followup="no email or contact form detected",
  open_gap_count=1),
]

n = append_results(RESULTS)
print(f"appended {n} rows (chunk_010)")
