import sys
sys.path.insert(0, ".")
from layer3_write import append_results

# (lead_id, domain, business_name, primary, secondary, confidence, business_summary,
#  conv, cart, eng, followup, ci, ev_conv, ev_cart, ev_eng, ev_followup,
#  open_gap_count, disqualifier)
RESULTS = [
(796, "toppingaudio.ru", "Toppingaudio", "Cart Recovery Opportunity", "Customer Engagement Opportunity", "medium",
 "Russian WooCommerce audio-equipment retailer (Topping brand DACs/amps) with a small catalog.",
 45, 75, 45, 45, 35,
 "WooCommerce cart present, no ESP tag detected", "has_cart=True, has_esp_tag=none, has_popup_script=False",
 "no chat widget, cta_count_above_fold=0", "no email capture form on homepage/commerce page",
 2, None),
(797, "esquire.ee", "Esquire", "Cart Recovery Opportunity", "Customer Engagement Opportunity", "medium",
 "Estonian WooCommerce shop selling tattoo cartridges/inks and PPE supplies.",
 45, 75, 45, 40, 35,
 "WooCommerce cart, no ESP tag", "has_cart=True, has_esp_tag=none",
 "no chat widget, cta_count_above_fold=0, no reviews", "popup present but generic (not confirmed email capture), no email form",
 2, None),
(798, "himkan.com", "Himkan", "Follow-up Opportunity", "Cart Recovery Opportunity", "medium",
 "Beverage brand (energy drinks, soda, mineral water) WooCommerce site with tawk chat and reviews already live.",
 55, 55, 65, 65, 45,
 "has_cart=True but no ESP", "has_cart=True, has_esp_tag=none",
 "chat widget (tawk) and reviews already present, cta_count_above_fold=7", "has_email_form=True but has_esp_tag=none — captured emails have no automation",
 2, None),
(799, "electrobdshop.com", "Electrobdshop", "Cart Recovery Opportunity", "Customer Engagement Opportunity", "medium",
 "Bangladesh gadget/electronics WooCommerce shop, cash-on-delivery model.",
 40, 75, 45, 40, 30,
 "WooCommerce cart, no ESP", "has_cart=True, has_esp_tag=none",
 "no chat, no reviews, cta_count_above_fold=3", "no email capture form detected",
 2, None),
(800, "booksplaces.com", "Booksplaces", "Cart Recovery Opportunity", "Customer Engagement Opportunity", "low",
 "WooCommerce books marketplace; product_count_visible=0 suggests thin/degraded catalog page fetched.",
 40, 65, 40, 40, 30,
 "has_cart=True, no ESP", "has_cart=True, has_esp_tag=none",
 "no chat, no reviews, cta_count_above_fold=0", "generic popup only, no confirmed email capture form",
 2, None),
(801, "global-keys.co.uk", "Global Keys", "Not a Good Fit", None, "medium",
 "UK replacement car keys/remote fobs WooCommerce retailer already running Mailchimp ESP, Poptin popup capture, and customer reviews.",
 25, 25, 30, 20, 30,
 "Mailchimp ESP and Poptin capture already live", "has_esp_tag=mailchimp, has_popup_script=True (poptin)",
 "reviews present but cta_count_above_fold=1 is thin", "email capture and ESP already wired together",
 1, "already has ESP + popup capture + reviews stack in place"),
(802, "atmavedic.com", "Atmavedic", "Cart Recovery Opportunity", "Follow-up Opportunity", "medium",
 "Russian Vedic/astrology services and ceremonies WooCommerce store with WhatsApp chat.",
 45, 65, 55, 55, 35,
 "has_cart=True, no ESP", "has_cart=True, has_esp_tag=none",
 "WhatsApp chat present but no popup/reviews", "has_email_form=True but no ESP to automate follow-up",
 2, None),
(803, "koreanmakeup.mx", "Koreanmakeup", "Insufficient Data", None, "low",
 "Domain resolved but page_text is empty and platform is unknown — page did not render usable content.",
 50, 50, 50, 50, 50,
 "page_text empty, platform=unknown", "has_cart=False (undetermined, not confirmed absent)",
 "no signals extractable", "no signals extractable",
 0, "empty/undetermined signals — cannot assess"),
(804, "hollycreeksoap.com", "Hollycreeksoap", "Cart Recovery Opportunity", "Follow-up Opportunity", "medium",
 "New Jersey handmade soap/beard-care WooCommerce shop, direct-sale model.",
 45, 70, 45, 55, 35,
 "has_cart=True, no ESP", "has_cart=True, has_esp_tag=none",
 "no chat, no reviews, cta_count_above_fold=2", "has_email_form=True but no ESP behind it",
 2, None),
(807, "mfsracing.pl", "Mfsracing", "Cart Recovery Opportunity", "Customer Engagement Opportunity", "medium",
 "Large Polish motorcycle parts/accessories WooCommerce catalog (~28k products) with no ESP.",
 45, 75, 45, 40, 40,
 "has_cart=True, no ESP; very large catalog implies real cart abandonment volume", "has_cart=True, has_esp_tag=none",
 "generic popup only, no chat, no reviews", "no confirmed email capture form",
 2, None),
(808, "leliedoodles.nl", "Leliedoodles", "Cart Recovery Opportunity", "Customer Engagement Opportunity", "low",
 "Dutch small-scale Labradoodle breeder with a WooCommerce shop for dog supplies.",
 40, 65, 40, 35, 30,
 "has_cart=True, no ESP", "has_cart=True, has_esp_tag=none",
 "no chat, no reviews, no popup", "no email capture form detected",
 2, None),
(809, "wingschennai.org", "Wingschennai", "Insufficient Data", None, "low",
 "Domain resolved but page_text is empty and platform is unknown.",
 50, 50, 50, 50, 50,
 "page_text empty", "has_cart=False (undetermined)",
 "no signals extractable", "no signals extractable",
 0, "empty/undetermined signals — cannot assess"),
(810, "enzosbp.com", "Enzosbp", "Cart Recovery Opportunity", "Follow-up Opportunity", "medium",
 "Spanish focaccia/restaurant WooCommerce ordering site with reviews already showing.",
 45, 65, 50, 55, 35,
 "has_cart=True, no ESP", "has_cart=True, has_esp_tag=none",
 "reviews present but no chat/popup", "has_email_form=True but no ESP automation behind it",
 2, None),
(811, "bricobro.com", "Bricobro", "Cart Recovery Opportunity", "Customer Engagement Opportunity", "medium",
 "Italian DIY/hardware WooCommerce store running a discount-code promo banner in page copy.",
 45, 70, 45, 40, 35,
 "has_cart=True, no ESP despite active promo messaging", "has_cart=True, has_esp_tag=none",
 "reviews present but no chat, has_promo_bar not confirmed by extractor despite promo text", "no email capture form detected",
 2, None),
(812, "gwrifa.com", "Gwrifa", "Insufficient Data", None, "low",
 "Site explicitly under maintenance ('doing some work on the site') — no real business content live.",
 50, 50, 50, 50, 50,
 "site down for maintenance", "has_cart=False, platform=wordpress but no storefront live",
 "no signals extractable, site not live", "no signals extractable",
 0, "site under maintenance, no content to evaluate"),
(813, "www.redwallmural.com", "Redwallmural", "Follow-up Opportunity", "Cart Recovery Opportunity", "medium",
 "Wallpaper/mural WooCommerce retailer with tawk chat and reviews, but no ESP behind its email/contact forms.",
 50, 60, 55, 65, 45,
 "has_cart=True, has_email_form=True, has_contact_form=True, but has_esp_tag=none", "has_cart=True, has_esp_tag=none",
 "chat (tawk) and reviews already present", "two capture forms exist with no automation to follow up leads",
 2, None),
(815, "piecenapelletitalia.pl", "Piecenapelletitalia", "Insufficient Data", None, "low",
 "Domain resolved but page_text is empty and platform is unknown.",
 50, 50, 50, 50, 50,
 "page_text empty", "has_cart=False (undetermined)",
 "no signals extractable", "no signals extractable",
 0, "empty/undetermined signals — cannot assess"),
(816, "sodogrupe.lt", "Sodogrupe", "Cart Recovery Opportunity", "Customer Engagement Opportunity", "low",
 "Lithuanian fruit-tree nursery/wholesale WooCommerce shop.",
 40, 65, 40, 35, 30,
 "has_cart=True, no ESP", "has_cart=True, has_esp_tag=none",
 "no chat, no reviews", "no email capture form detected",
 2, None),
(817, "shamayimcouncil.com", "Shamayimcouncil", "Cart Recovery Opportunity", "Follow-up Opportunity", "medium",
 "Ghanaian church/ministry site selling learning materials and offering appointment booking, cta_count_above_fold=7.",
 45, 65, 55, 45, 35,
 "has_cart=True, no ESP", "has_cart=True, has_esp_tag=none",
 "booking already offered, high above-fold CTA count", "no email capture form despite active engagement",
 2, None),
(818, "jaadzana.com", "Jaadzana", "Not a Good Fit", None, "medium",
 "Moroccan handwoven rug e-commerce store already running Mailchimp ESP, Tidio chat, and reviews across a 20-product catalog.",
 25, 25, 30, 20, 30,
 "Mailchimp ESP + Tidio chat + reviews already live", "has_esp_tag=mailchimp",
 "chat widget and reviews already in place", "email capture and ESP already wired together",
 1, "already has ESP + chat + reviews stack in place"),
(819, "fagoyapi.com", "Fagoyapi", "Follow-up Opportunity", None, "medium",
 "Turkish real-estate developer (villa/residential projects) site with no lead-capture form detected.",
 50, 30, 40, 60, 40,
 "real-estate project marketing, not true e-commerce despite platform tag", "has_cart likely false-positive, product_count_visible=0",
 "no chat, no reviews, cta_count_above_fold=0", "no email or contact form detected for high-value property inquiries",
 2, None),
(820, "hagrokov.sk", "Hagrokov", "Cart Recovery Opportunity", "Follow-up Opportunity", "medium",
 "Slovak custom metalwork (livestock handling equipment, shelters) WooCommerce site.",
 45, 65, 45, 55, 35,
 "has_cart=True, no ESP", "has_cart=True, has_esp_tag=none",
 "no chat, no reviews", "has_email_form=True but no ESP automation",
 2, None),
(821, "woodworkantalya.com.tr", "Woodworkantalya", "Cart Recovery Opportunity", "Customer Engagement Opportunity", "low",
 "Turkish custom wood furniture WooCommerce store.",
 40, 65, 40, 35, 30,
 "has_cart=True, no ESP", "has_cart=True, has_esp_tag=none",
 "no chat, no reviews", "no email capture form detected",
 2, None),
(822, "tupperstars.sk", "Tupperstars", "Cart Recovery Opportunity", "Customer Engagement Opportunity", "low",
 "Slovak Tupperware reseller WooCommerce site.",
 40, 65, 40, 35, 30,
 "has_cart=True, no ESP", "has_cart=True, has_esp_tag=none",
 "no chat, no reviews, no popup", "no email capture form detected",
 2, None),
(823, "motoposlovalnica.si", "Motoposlovalnica", "Follow-up Opportunity", None, "medium",
 "Slovenian motorcycle service/repair shop (service business, not a cart-based store) with contact and email forms but no ESP.",
 45, 20, 40, 65, 40,
 "has_cart=False — service business, cart recovery not applicable", "has_cart=False",
 "no chat, no reviews", "has_email_form=True and has_contact_form=True but no ESP to automate follow-up",
 1, None),
(824, "3mogarden.ca", "3Mogarden", "Insufficient Data", None, "low",
 "Domain resolved but page_text is empty and platform is unknown.",
 50, 50, 50, 50, 50,
 "page_text empty", "has_cart=False (undetermined)",
 "no signals extractable", "no signals extractable",
 0, "empty/undetermined signals — cannot assess"),
(825, "enaidabeauty.com", "Enaidabeauty", "Multi-Opportunity", None, "medium",
 "Sizable K-beauty retailer (35 products, 14 brands) with a promo bar and popup, but no ESP behind email capture.",
 55, 65, 55, 65, 45,
 "has_cart=True, has_promo_bar=True, no ESP", "has_cart=True, has_esp_tag=none",
 "popup present, sizable catalog (35 products/14 brands) but no chat/reviews", "has_email_form=True but no ESP automation",
 3, None),
(826, "mandycamerondesigns.com", "Mandycamerondesigns", "Insufficient Data", None, "low",
 "Domain resolved but page_text is empty and platform is unknown.",
 50, 50, 50, 50, 50,
 "page_text empty", "has_cart=False (undetermined)",
 "no signals extractable", "no signals extractable",
 0, "empty/undetermined signals — cannot assess"),
(827, "propolymersource.com", "Propolymersource", "Cart Recovery Opportunity", "Follow-up Opportunity", "medium",
 "US concrete-coatings/epoxy supplies WooCommerce store with a broad product line.",
 45, 65, 45, 55, 35,
 "has_cart=True, no ESP", "has_cart=True, has_esp_tag=none",
 "no chat, no reviews", "has_email_form=True but no ESP automation",
 2, None),
(828, "labelmirjai.com", "Labelmirjai", "Cart Recovery Opportunity", "Follow-up Opportunity", "medium",
 "WooCommerce fashion/apparel store (22 products) running a checkout discount-code promo, no ESP.",
 45, 65, 50, 55, 35,
 "has_cart=True, has_promo_bar=True, no ESP", "has_cart=True, has_esp_tag=none",
 "promo bar active but no chat/reviews", "has_email_form=True but no ESP automation",
 2, None),
(829, "mvmavia.ru", "Mvmavia", "Cart Recovery Opportunity", "Follow-up Opportunity", "medium",
 "Russian aviation parts/services WooCommerce site with a large catalog (43 products visible).",
 50, 65, 45, 55, 40,
 "has_cart=True, no ESP, large catalog (43 products)", "has_cart=True, has_esp_tag=none",
 "no chat, no reviews", "has_email_form=True and has_contact_form=True but no ESP automation",
 2, None),
(831, "atoztaxndbooks.com", "Atoztaxndbooks", "Follow-up Opportunity", None, "medium",
 "US bookkeeping/tax services business (service leads, not e-commerce despite cart flag) with reviews and email form but no ESP.",
 50, 25, 55, 65, 45,
 "has_cart likely false-positive for a services business", "product_count_visible=0",
 "reviews present, cta_count_above_fold=4", "has_email_form=True but no ESP automation for service inquiries",
 2, None),
(832, "service-balauseri.ro", "Service Balauseri", "Not a Good Fit", None, "medium",
 "Romanian appliance/auto service business already running Mailchimp ESP, popup capture, reviews, and both email and contact forms.",
 30, 20, 40, 25, 35,
 "Mailchimp ESP already live with popup capture", "has_esp_tag=mailchimp, has_popup_script=True",
 "reviews present, cta_count_above_fold=4, booking language in copy", "email capture and ESP already wired together",
 1, "already has ESP + popup capture + reviews + booking flow in place"),
(833, "fanshopgloriabistrita.ro", "Fanshopgloriabistrita", "Insufficient Data", None, "low",
 "Site shows 'Revenim in curand' (coming soon) — not a live storefront despite WordPress/Mailchimp tags detected.",
 50, 50, 50, 50, 50,
 "site not live (coming soon placeholder)", "has_cart=False, site inactive",
 "no real content to evaluate engagement", "ESP tag may be template artifact, not confirmed live capture",
 0, "site not live — coming soon placeholder"),
(834, "hallokraamcadeau.nl", "Hallokraamcadeau", "Multi-Opportunity", None, "medium",
 "Dutch baby-gift WooCommerce store (16 products) with no ESP, no chat, no popup capture at all.",
 45, 70, 45, 40, 35,
 "has_cart=True, no ESP, 16 products visible", "has_cart=True, has_esp_tag=none",
 "no chat, no reviews, no popup — zero engagement infrastructure", "no email capture form detected",
 3, None),
(835, "ludog.fr", "Ludog", "Follow-up Opportunity", None, "medium",
 "French solo dog-training service business (booking-based, not cart-based) with contact/email forms but no ESP.",
 45, 20, 40, 65, 40,
 "has_cart likely false-positive for a solo service business", "product_count_visible=0",
 "no chat, no reviews", "has_email_form=True and has_contact_form=True but no ESP automation",
 1, None),
(836, "tigrbusiness.ru", "Tigrbusiness", "Cart Recovery Opportunity", "Follow-up Opportunity", "medium",
 "Russian tools/equipment WooCommerce store with Poptin popup capture but no ESP.",
 50, 65, 45, 55, 35,
 "has_cart=True, has_popup_script=True (poptin), no ESP", "has_cart=True, has_esp_tag=none",
 "no chat, no reviews", "has_email_form=True and has_contact_form=True but captured leads have no ESP automation",
 2, None),
(837, "hapico.co.in", "Hapico", "Not a Good Fit", None, "medium",
 "Indian Kashmiri wellness/cosmetics brand (28 products) already running Mailchimp ESP, WhatsApp chat, popup capture, and reviews.",
 25, 25, 30, 20, 30,
 "Mailchimp ESP + WhatsApp chat + reviews already live", "has_esp_tag=mailchimp",
 "chat, reviews, and popup capture already in place, cta_count_above_fold=3", "email capture and ESP already wired together",
 1, "already has ESP + chat + reviews + popup capture stack in place"),
(838, "hesnz.nz", "Hesnz", "Cart Recovery Opportunity", "Customer Engagement Opportunity", "low",
 "New Zealand industrial lifting/rigging equipment importer WooCommerce store.",
 40, 65, 40, 35, 30,
 "has_cart=True, no ESP", "has_cart=True, has_esp_tag=none",
 "no chat, no reviews, cta_count_above_fold=2", "no email capture form detected",
 2, None),
(839, "dcni.co.uk", "Dcni", "Follow-up Opportunity", "Cart Recovery Opportunity", "medium",
 "Northern Ireland scuba diving/boat tour operator (booking-driven, cart flag likely false-positive) with WhatsApp chat but no email capture.",
 45, 40, 55, 60, 40,
 "has_cart flag likely false-positive for a tour-booking business", "product_count_visible=18 (course/tour listings, not physical cart)",
 "WhatsApp chat already present", "no email capture form for high-value dive-course/tour inquiries despite active chat",
 2, None),
(840, "sunandfinecrop.com", "Sunandfinecrop", "Not a Good Fit", None, "high",
 "Parked Hostinger domain with no live business site — placeholder 'build your website' content only.",
 10, 10, 10, 10, 10,
 "parked domain, no business content", "no storefront exists",
 "no engagement infrastructure — not a real site", "no capture forms — not a real site",
 0, "parked/unbuilt domain, no live business to evaluate"),
(841, "manaslu.co.uk", "Manaslu", "Cart Recovery Opportunity", "Customer Engagement Opportunity", "medium",
 "UK wholesale Nepal wool clothing retailer/wholesaler WooCommerce site.",
 45, 65, 40, 40, 35,
 "has_cart=True, no ESP", "has_cart=True, has_esp_tag=none",
 "generic popup only, no chat, no reviews", "no confirmed email capture form",
 2, None),
(842, "imbertmnif.com", "Imbertmnif", "Follow-up Opportunity", None, "medium",
 "Tunisian footwear manufacturer (B2B, production-focused site) with contact/email forms but no ESP.",
 45, 20, 40, 65, 40,
 "has_cart likely false-positive for a B2B manufacturer site", "product_count_visible=0",
 "no chat, no reviews", "has_email_form=True and has_contact_form=True but no ESP automation for B2B leads",
 1, None),
(843, "luminariasled5v.com", "Luminariasled5V", "Follow-up Opportunity", None, "low",
 "Industrial/public-space LED lighting solutions provider (B2B inquiry-driven, not consumer cart).",
 40, 20, 35, 55, 35,
 "has_cart likely false-positive for a B2B lighting solutions provider", "product_count_visible=0",
 "no chat, no reviews", "no email or contact form detected for B2B lighting inquiries",
 1, None),
(844, "evidencesystem.ca", "Evidencesystem", "Follow-up Opportunity", None, "medium",
 "Canadian dental/medical consent-form SaaS platform (B2B software, not e-commerce) with no lead-capture form detected.",
 40, 15, 35, 60, 40,
 "has_cart likely false-positive for a B2B SaaS platform", "product_count_visible=0",
 "generic popup only, no chat", "no email capture form detected for a subscription software product",
 1, None),
(845, "maskirajse.rs", "Maskirajse", "Cart Recovery Opportunity", "Follow-up Opportunity", "low",
 "Serbian costumes/masks WooCommerce shop with Mailchimp ESP tag detected but no email capture form found.",
 45, 55, 45, 45, 40,
 "has_cart=True, has_esp_tag=mailchimp but no email_form detected — ESP may be underused", "has_esp_tag=mailchimp, has_email_form=False",
 "cta_count_above_fold=1, no chat/reviews", "ESP present but no visible capture mechanism feeding it",
 2, None),
(846, "mostraining.co.uk", "Mostraining", "Follow-up Opportunity", None, "medium",
 "UK electrical/construction NVQ training provider (education leads, not cart-based) with contact/email forms but no ESP.",
 45, 20, 40, 65, 40,
 "has_cart likely false-positive for a training/education business", "product_count_visible=0",
 "generic popup only, no chat/reviews, cta_count_above_fold=1", "has_email_form=True and has_contact_form=True but no ESP automation",
 1, None),
(847, "ansen.ro", "Ansen", "Cart Recovery Opportunity", "Customer Engagement Opportunity", "low",
 "Romanian general household/pet goods WooCommerce store with WhatsApp chat.",
 40, 65, 45, 35, 30,
 "has_cart=True, no ESP", "has_cart=True, has_esp_tag=none",
 "WhatsApp chat present but no reviews/popup", "no email capture form detected despite active chat",
 2, None),
(848, "articoo.art", "Articoo", "Cart Recovery Opportunity", "Follow-up Opportunity", "medium",
 "Stock-photo/print marketplace (creator marketplace, WooCommerce) with reviews but no ESP.",
 45, 60, 50, 55, 35,
 "has_cart=True, no ESP", "has_cart=True, has_esp_tag=none",
 "reviews present, cta_count_above_fold=1", "has_email_form=True but no ESP automation",
 2, None),
(849, "deportes27.com", "Deportes27", "Cart Recovery Opportunity", "Follow-up Opportunity", "medium",
 "Spanish sporting goods (running, football, skiing) WooCommerce store, no ESP.",
 45, 65, 45, 55, 35,
 "has_cart=True, no ESP", "has_cart=True, has_esp_tag=none",
 "generic popup only, no chat/reviews", "has_email_form=True but no ESP automation",
 2, None),
(850, "croccacoccole.com", "Croccacoccole", "Not a Good Fit", None, "medium",
 "Italian cold-pressed pet food brand already running Klaviyo ESP, WhatsApp chat, and popup capture.",
 25, 25, 30, 20, 30,
 "Klaviyo ESP + WhatsApp chat + popup capture already live", "has_esp_tag=klaviyo",
 "WhatsApp chat already present", "email capture and Klaviyo ESP already wired together",
 1, "already has ESP + chat + popup capture stack in place"),
(851, "ofisciniz.com.tr", "Ofisciniz", "Cart Recovery Opportunity", "Customer Engagement Opportunity", "low",
 "Turkish office-furniture WooCommerce store with reviews but no ESP/chat/popup.",
 40, 65, 45, 35, 30,
 "has_cart=True, no ESP", "has_cart=True, has_esp_tag=none",
 "reviews present but no chat/popup", "no email capture form detected",
 2, None),
(852, "goafricaexpeditions.com", "Goafricaexpeditions", "Follow-up Opportunity", None, "medium",
 "African safari/tour operator (high-value inquiry-driven business, cart flag likely false-positive) with no lead-capture form detected.",
 45, 20, 40, 65, 40,
 "has_cart likely false-positive for a tour-package inquiry business", "product_count_visible=4 (tour packages, not physical cart)",
 "no chat, no reviews", "no email or contact form detected for high-value safari-package inquiries",
 1, None),
(853, "subtvonline.com", "Subtvonline", "Cart Recovery Opportunity", "Follow-up Opportunity", "medium",
 "French IPTV subscription service WooCommerce site with WhatsApp chat but no ESP.",
 45, 65, 50, 55, 35,
 "has_cart=True, no ESP", "has_cart=True, has_esp_tag=none",
 "WhatsApp chat present, cta_count_above_fold=1", "has_email_form=True but no ESP automation",
 2, None),
(854, "thelandsstore.com", "Thelandsstore", "Cart Recovery Opportunity", None, "medium",
 "Shilajit supplement WooCommerce store with Mailchimp ESP already tagged, cta_count_above_fold=6.",
 40, 45, 45, 30, 35,
 "has_cart=True, has_esp_tag=mailchimp but no email_form detected on homepage/commerce page", "has_esp_tag=mailchimp, has_email_form=False",
 "cta_count_above_fold=6 but no chat/reviews", "ESP present but capture mechanism not visibly wired to it",
 1, None),
]

n = append_results(RESULTS)
print(f"appended {n} rows (chunk_005)")
