import sys
sys.path.insert(0, ".")
from layer3_write import append_results


def L(lead_id, domain, business_name, primary, confidence, summary,
      conv, cart, eng, followup, ci, ev_conv, ev_cart, ev_eng, ev_followup,
      open_gap_count, secondary=None, disqualifier=None):
    return (lead_id, domain, business_name, primary, secondary, confidence, summary,
            conv, cart, eng, followup, ci, ev_conv, ev_cart, ev_eng, ev_followup,
            open_gap_count, disqualifier)


RESULTS = [
L(1641, "hydrophilic.biz", "Hydrophilic", primary="Cart Recovery Opportunity", secondary="Follow-up Opportunity", confidence="low",
  summary="Workplace-hydration/water-cooler subscription service (9 products) with no ESP.",
  conv=40, cart=55, eng=30, followup=40, ci=25,
  ev_conv="has_cart=True, no ESP, cta_count_above_fold=3", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="no chat/reviews/popup", ev_followup="has_email_form=True but no ESP automation",
  open_gap_count=2),
L(1642, "americansolar.com.pk", "Americansolar", primary="Cart Recovery Opportunity", secondary="Customer Engagement Opportunity", confidence="low",
  summary="Pakistani solar-panels B2B/B2C retailer with reviews already live but no capture form or ESP.",
  conv=35, cart=50, eng=30, followup=25, ci=25,
  ev_conv="has_cart=True, no ESP", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="reviews present, cta_count_above_fold=5", ev_followup="no email capture form detected",
  open_gap_count=2),
L(1643, "statachain.com", "Statachain", primary="Follow-up Opportunity", confidence="low",
  summary="Freight/shipping-capacity marketplace (shippers/buyers signup) with an email form but no ESP.",
  conv=35, cart=20, eng=25, followup=40, ci=25,
  ev_conv="has_cart=True likely false-positive for a logistics marketplace", ev_cart="product_count_visible=0",
  ev_eng="cta_count_above_fold=1", ev_followup="has_email_form=True but no ESP automation for marketplace signups",
  open_gap_count=1),
L(1644, "sthavistah.com", "Sthavistah", primary="Cart Recovery Opportunity", secondary="Customer Engagement Opportunity", confidence="low",
  summary="Indian WooCommerce retailer (4 products), thin content, no ESP.",
  conv=30, cart=45, eng=25, followup=25, ci=20,
  ev_conv="has_cart=True, no ESP", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="generic popup only, no chat/reviews, cta_count_above_fold=1", ev_followup="no email capture form detected",
  open_gap_count=2),
L(1645, "beermatprint.co.uk", "Beermatprint", primary="Cart Recovery Opportunity", secondary="Follow-up Opportunity", confidence="low",
  summary="UK custom beermat/coaster printing B2B business (2 products) with both email and contact forms but no ESP.",
  conv=35, cart=50, eng=25, followup=40, ci=25,
  ev_conv="has_cart=True, no ESP, cta_count_above_fold=2", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="generic popup only, no chat/reviews", ev_followup="has_email_form=True and has_contact_form=True but no ESP automation",
  open_gap_count=2),
L(1646, "salab.it", "Salab", primary="Not a Good Fit", confidence="medium",
  summary="Italian carbon-fiber fabrication B2B business already running Mailchimp ESP with WhatsApp chat.",
  conv=25, cart=15, eng=30, followup=20, ci=30,
  ev_conv="has_cart=True likely false-positive for a B2B fabrication business", ev_cart="has_esp_tag=mailchimp",
  ev_eng="WhatsApp chat already present", ev_followup="email capture and ESP already wired together",
  open_gap_count=1, disqualifier="already has ESP + chat stack in place"),
L(1647, "thestolenlamb.com", "Thestolenlamb", primary="Cart Recovery Opportunity", secondary="Follow-up Opportunity", confidence="low",
  summary="Food/restaurant brand whose fetched copy is mostly unrendered Elementor CSS boilerplate, no ESP.",
  conv=35, cart=45, eng=25, followup=35, ci=25,
  ev_conv="has_cart=True, no ESP; page content largely unrendered CSS boilerplate", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="cta_count_above_fold=3", ev_followup="has_email_form=True but no ESP automation",
  open_gap_count=2),
L(1648, "vbrandindia.com", "Vbrandindia", primary="Cart Recovery Opportunity", secondary="Follow-up Opportunity", confidence="low",
  summary="Indian mobility/wheelchair solutions retailer (18 products) with both email and contact forms and booking already live, but no ESP.",
  conv=40, cart=55, eng=35, followup=45, ci=30,
  ev_conv="has_cart=True, no ESP", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="booking already offered, cta_count_above_fold=3", ev_followup="has_email_form=True and has_contact_form=True but no ESP automation",
  open_gap_count=2),
L(1649, "poolcare.com.mx", "Poolcare", primary="Cart Recovery Opportunity", secondary="Follow-up Opportunity", confidence="low",
  summary="Mexican solar pool-heating B2B/B2C business with both email and contact forms but no ESP.",
  conv=35, cart=50, eng=25, followup=40, ci=25,
  ev_conv="has_cart=True, no ESP", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="no chat/reviews/popup", ev_followup="has_email_form=True and has_contact_form=True but no ESP automation",
  open_gap_count=2),
L(1650, "apaladomiciliu.ro", "Apaladomiciliu", primary="Follow-up Opportunity", secondary="Cart Recovery Opportunity", confidence="low",
  summary="Romanian water-delivery subscription business with no lead-capture form or ESP.",
  conv=35, cart=40, eng=25, followup=45, ci=25,
  ev_conv="has_cart=True but this is primarily a delivery-subscription/quote business", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="generic popup only, no chat/reviews", ev_followup="no email capture form detected for a quote-request business",
  open_gap_count=2),
L(1651, "olonola.com", "Olonola", primary="Cart Recovery Opportunity", secondary="Customer Engagement Opportunity", confidence="low",
  summary="Premium olive-oil brand, product_count_visible=0 suggests thin page fetched, no ESP.",
  conv=30, cart=45, eng=25, followup=25, ci=20,
  ev_conv="has_cart=True, no ESP", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="no chat/reviews/popup", ev_followup="no email capture form detected",
  open_gap_count=2),
L(1652, "pharmagratis.com", "Pharmagratis", primary="Cart Recovery Opportunity", secondary="Customer Engagement Opportunity", confidence="low",
  summary="Bulgarian pharma-products B2B distributor with reviews already live but no capture form or ESP.",
  conv=35, cart=45, eng=30, followup=25, ci=25,
  ev_conv="has_cart=True, no ESP", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="reviews present but no chat", ev_followup="no email capture form detected",
  open_gap_count=2),
L(1653, "morocco-toptours.com", "Morocco-Toptours", primary="Not a Good Fit", confidence="medium",
  summary="Moroccan tour operator already running Mailchimp ESP with booking and reviews.",
  conv=20, cart=15, eng=30, followup=15, ci=25,
  ev_conv="has_cart=True likely false-positive for a tour operator", ev_cart="has_esp_tag=mailchimp",
  ev_eng="booking and reviews already present", ev_followup="email capture and ESP already wired together",
  open_gap_count=1, disqualifier="already has ESP + booking + reviews stack in place"),
L(1654, "svrprint.com", "Svrprint", primary="Cart Recovery Opportunity", secondary="Customer Engagement Opportunity", confidence="low",
  summary="Bulgarian DTF/print-services B2B business, product_count_visible=0 suggests thin page fetched, no ESP.",
  conv=30, cart=45, eng=25, followup=25, ci=20,
  ev_conv="has_cart=True, no ESP", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="generic popup only, no chat/reviews", ev_followup="no email capture form detected",
  open_gap_count=2),
L(1655, "nyx-healthsolution.com", "Nyx-Healthsolution", primary="Cart Recovery Opportunity", secondary="Customer Engagement Opportunity", confidence="low",
  summary="Austrian veterinary health-products retailer (2 products) with no capture form or ESP.",
  conv=30, cart=45, eng=25, followup=25, ci=20,
  ev_conv="has_cart=True, no ESP, cta_count_above_fold=1", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="no chat/reviews/popup", ev_followup="no email capture form detected",
  open_gap_count=2),
L(1656, "resonateav.co.za", "Resonateav", primary="Cart Recovery Opportunity", secondary="Follow-up Opportunity", confidence="low",
  summary="South African AV/events equipment rental B2B business with an email form but no ESP.",
  conv=35, cart=45, eng=25, followup=40, ci=25,
  ev_conv="has_cart=True, no ESP", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="no chat/reviews/popup", ev_followup="has_email_form=True but no ESP automation",
  open_gap_count=2),
L(1657, "swedtraining.com", "Swedtraining", primary="Follow-up Opportunity", confidence="low",
  summary="Sweden-based corporate training institute (est. 2013, Arabic-market focus) with an email form but no ESP.",
  conv=35, cart=20, eng=25, followup=45, ci=25,
  ev_conv="has_cart=False — B2B training institute", ev_cart="has_cart=False",
  ev_eng="no chat/reviews/popup", ev_followup="has_email_form=True but no ESP automation",
  open_gap_count=1),
L(1658, "joosteneventsupport.nl", "Joosteneventsupport", primary="Follow-up Opportunity", confidence="low",
  summary="Dutch event-equipment rental B2B business (quote-request model) with no lead-capture form or ESP.",
  conv=35, cart=20, eng=25, followup=40, ci=25,
  ev_conv="has_cart=True likely false-positive for a quote-driven rental business", ev_cart="product_count_visible=0",
  ev_eng="no chat/reviews/popup", ev_followup="no email or contact form detected",
  open_gap_count=1),
L(1659, "tapsplastics.com", "Tapsplastics", primary="Insufficient Data", confidence="low",
  summary="Domain resolved but page_text is empty and platform is unknown.",
  conv=50, cart=50, eng=50, followup=50, ci=50,
  ev_conv="page_text empty", ev_cart="has_cart=False (undetermined)",
  ev_eng="no signals extractable", ev_followup="no signals extractable",
  open_gap_count=0, disqualifier="empty/undetermined signals — cannot assess"),
L(1660, "bigwoodsbeef.com", "Bigwoodsbeef", primary="Cart Recovery Opportunity", secondary="Customer Engagement Opportunity", confidence="low",
  summary="US family-farm beef direct-to-consumer WooCommerce store (18 products) with no capture form or ESP.",
  conv=35, cart=50, eng=25, followup=25, ci=25,
  ev_conv="has_cart=True, no ESP, cta_count_above_fold=1", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="no chat/reviews/popup", ev_followup="no email capture form detected",
  open_gap_count=2),
L(1661, "spectraintlfz.com", "Spectraintlfz", primary="Cart Recovery Opportunity", secondary="Follow-up Opportunity", confidence="low",
  summary="UAE oilfield/marine equipment trading B2B business with WhatsApp chat and a high above-fold CTA count (9), but no ESP.",
  conv=40, cart=50, eng=40, followup=45, ci=30,
  ev_conv="has_cart=True, no ESP, cta_count_above_fold=9", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="WhatsApp chat already present", ev_followup="has_email_form=True and has_contact_form=True but no ESP automation",
  open_gap_count=2),
L(1662, "limedlabs.in", "Limedlabs", primary="Cart Recovery Opportunity", secondary="Customer Engagement Opportunity", confidence="low",
  summary="Indian pharmaceutical B2B company WooCommerce store (23 products) with no capture form or ESP.",
  conv=35, cart=50, eng=25, followup=25, ci=25,
  ev_conv="has_cart=True, no ESP, cta_count_above_fold=1", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="no chat/reviews/popup", ev_followup="no email capture form detected",
  open_gap_count=2),
L(1663, "excultur.com.mx", "Excultur", primary="Follow-up Opportunity", secondary="Cart Recovery Opportunity", confidence="low",
  summary="Mexican tour operator (Pueblo Mágico tours) with WhatsApp chat, booking, and reviews already live, but no ESP.",
  conv=40, cart=35, eng=45, followup=45, ci=30,
  ev_conv="has_cart=True but this is a tour-booking business", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="WhatsApp chat, booking, and reviews already present", ev_followup="no email capture form detected despite active chat and booking",
  open_gap_count=2),
L(1664, "slnweathersystems.com", "Slnweathersystems", primary="Cart Recovery Opportunity", secondary="Follow-up Opportunity", confidence="low",
  summary="Indian HVAC specialist B2B business (16 products) with a free site-survey offer and a high above-fold CTA count (7), but no ESP.",
  conv=40, cart=50, eng=35, followup=45, ci=30,
  ev_conv="has_cart=True, no ESP, cta_count_above_fold=7", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="generic popup only, no chat/reviews", ev_followup="has_email_form=True but no ESP automation",
  open_gap_count=2),
L(1665, "bandungcheesecuit.com", "Bandungcheesecuit", primary="Cart Recovery Opportunity", secondary="Follow-up Opportunity", confidence="low",
  summary="Indonesian bakery (since 2017) with tawk chat and reviews already live but no ESP.",
  conv=40, cart=50, eng=40, followup=40, ci=30,
  ev_conv="has_cart=True, no ESP", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="tawk chat and reviews already present, cta_count_above_fold=2", ev_followup="has_email_form=True but no ESP automation",
  open_gap_count=2),
L(1666, "trattoriatandoor.se", "Trattoriatandoor", primary="Cart Recovery Opportunity", secondary="Customer Engagement Opportunity", confidence="low",
  summary="Swedish restaurant ordering site with reviews already live but no capture form or ESP.",
  conv=35, cart=50, eng=30, followup=25, ci=25,
  ev_conv="has_cart=True, no ESP", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="reviews present, cta_count_above_fold=2", ev_followup="no email capture form detected",
  open_gap_count=2),
L(1667, "ledvertising.ma", "Ledvertising", primary="Cart Recovery Opportunity", secondary="Customer Engagement Opportunity", confidence="low",
  summary="Moroccan LED-signage B2B manufacturer (15 products) with reviews already live but no capture form or ESP.",
  conv=35, cart=50, eng=30, followup=25, ci=25,
  ev_conv="has_cart=True, no ESP", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="reviews present", ev_followup="no email capture form detected",
  open_gap_count=2),
L(1668, "kmglaw.co.ke", "Kmglaw", primary="Follow-up Opportunity", confidence="low",
  summary="Kenyan law firm with reviews already live and a high above-fold CTA count (5), but no lead-capture form or ESP.",
  conv=40, cart=20, eng=40, followup=50, ci=30,
  ev_conv="has_cart=True likely false-positive for a law firm", ev_cart="product_count_visible=0",
  ev_eng="reviews present, cta_count_above_fold=5", ev_followup="no email or contact form detected for high-value legal-consult leads",
  open_gap_count=1),
L(1669, "hebeibaofengsteel.com", "Hebeibaofengsteel", primary="Cart Recovery Opportunity", secondary="Follow-up Opportunity", confidence="low",
  summary="Chinese steel-structure B2B manufacturer (16 products) with a high above-fold CTA count (6) but no ESP.",
  conv=40, cart=50, eng=35, followup=45, ci=30,
  ev_conv="has_cart=True, no ESP, cta_count_above_fold=6", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="generic popup only, no chat/reviews", ev_followup="has_email_form=True but no ESP automation",
  open_gap_count=2),
L(1670, "speak-easy.ca", "Speak-Easy", primary="Follow-up Opportunity", secondary="Cart Recovery Opportunity", confidence="low",
  summary="Canadian public-speaking coaching/courses business with free webinars and booking already offered, but no ESP.",
  conv=40, cart=35, eng=40, followup=50, ci=30,
  ev_conv="has_cart=True but this is a coaching/courses business", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="booking already offered ('free webinars'), cta_count_above_fold=4", ev_followup="has_email_form=True but no ESP automation",
  open_gap_count=2),
L(1671, "toymaxx.co.uk", "Toymaxx", primary="Cart Recovery Opportunity", secondary="Customer Engagement Opportunity", confidence="low",
  summary="UK toy retailer WooCommerce store with an active promo but no capture form or ESP.",
  conv=35, cart=50, eng=30, followup=25, ci=25,
  ev_conv="has_cart=True, has_promo_bar=True, no ESP", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="generic popup only, no chat/reviews, cta_count_above_fold=3", ev_followup="no email capture form detected",
  open_gap_count=2),
L(1673, "syscamp.ma", "Syscamp", primary="Cart Recovery Opportunity", secondary="Follow-up Opportunity", confidence="low",
  summary="Moroccan software/web-development B2B agency with a digital-products shop but no ESP.",
  conv=35, cart=45, eng=25, followup=40, ci=25,
  ev_conv="has_cart=True, no ESP", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="generic popup only, no chat/reviews", ev_followup="has_email_form=True but no ESP automation",
  open_gap_count=2),
L(1674, "shreejifoodproducts.com", "Shreejifoodproducts", primary="Follow-up Opportunity", confidence="low",
  summary="Indian food B2B manufacturer (6 brands, 20 products) with WhatsApp chat but no email-capture form or ESP.",
  conv=35, cart=20, eng=35, followup=40, ci=25,
  ev_conv="has_cart=False — B2B food manufacturer", ev_cart="has_cart=False",
  ev_eng="WhatsApp chat already present, cta_count_above_fold=2", ev_followup="no email capture form detected despite active chat channel",
  open_gap_count=1),
L(1675, "cbs-ci.com", "Cbs-Ci", primary="Follow-up Opportunity", confidence="low",
  summary="Ivory Coast consulting-firm B2B business whose page copy includes visible generic placeholder text, with an email form but no ESP.",
  conv=30, cart=20, eng=20, followup=35, ci=20,
  ev_conv="has_cart=True likely false-positive for a B2B consulting firm; page includes generic placeholder text", ev_cart="product_count_visible=0",
  ev_eng="no chat/reviews/popup", ev_followup="has_email_form=True but no ESP automation; content quality uncertain",
  open_gap_count=1),
L(1677, "saffronzionsville.com", "Saffronzionsville", primary="Cart Recovery Opportunity", secondary="Follow-up Opportunity", confidence="low",
  summary="US Indian restaurant WooCommerce ordering site with no ESP.",
  conv=35, cart=45, eng=25, followup=40, ci=25,
  ev_conv="has_cart=True, no ESP", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="generic popup only, no chat/reviews, cta_count_above_fold=2", ev_followup="has_email_form=True but no ESP automation",
  open_gap_count=2),
L(1678, "piracs.co.uk", "Piracs", primary="Follow-up Opportunity", confidence="low",
  summary="UK removals/moving-services B2B/B2C business with a moderate above-fold CTA count (3) but no lead-capture form or ESP.",
  conv=35, cart=20, eng=25, followup=40, ci=25,
  ev_conv="has_cart=True likely false-positive for a removals services business", ev_cart="product_count_visible=0",
  ev_eng="generic popup only, cta_count_above_fold=3", ev_followup="no email or contact form detected",
  open_gap_count=1),
L(1679, "elevaempresas.com", "Elevaempresas", primary="Follow-up Opportunity", confidence="low",
  summary="Colombian SAP B1/tech-consulting B2B business with WhatsApp chat but no email-capture form or ESP.",
  conv=35, cart=20, eng=30, followup=40, ci=25,
  ev_conv="has_cart=False — B2B tech consulting", ev_cart="has_cart=False",
  ev_eng="WhatsApp chat already present", ev_followup="no email capture form detected despite active chat channel",
  open_gap_count=1),
L(1680, "dsmzservices.my", "Dsmzservices", primary="Follow-up Opportunity", secondary="Cart Recovery Opportunity", confidence="low",
  summary="Malaysian business-speaker/training-programs provider with an attached small shop but no ESP.",
  conv=35, cart=40, eng=25, followup=40, ci=25,
  ev_conv="has_cart=True but this is primarily a speaker/training-programs business", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="cta_count_above_fold=3", ev_followup="no email capture form detected",
  open_gap_count=2),
L(1681, "bharattanning.com", "Bharattanning", primary="Cart Recovery Opportunity", secondary="Follow-up Opportunity", confidence="low",
  summary="Indian leather B2B manufacturer (4 products) with both email and contact forms but no ESP.",
  conv=35, cart=50, eng=25, followup=40, ci=25,
  ev_conv="has_cart=True, no ESP, cta_count_above_fold=1", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="no chat/reviews/popup", ev_followup="has_email_form=True and has_contact_form=True but no ESP automation",
  open_gap_count=2),
L(1682, "flames2firedevo.org", "Flames2Firedevo", primary="Insufficient Data", confidence="high",
  summary="Site explicitly states 'Under maintenance' — not live.",
  conv=50, cart=50, eng=50, followup=50, ci=50,
  ev_conv="site under maintenance", ev_cart="has_cart=False, site inactive",
  ev_eng="no real content to evaluate — placeholder page", ev_followup="no real content to evaluate — placeholder page",
  open_gap_count=0, disqualifier="site under maintenance"),
L(1683, "mini-rc-combat.com", "Mini-Rc-Combat", primary="Insufficient Data", confidence="high",
  summary="Gateway/upstream connection-timeout error — no content retrievable.",
  conv=50, cart=50, eng=50, followup=50, ci=50,
  ev_conv="upstream connection timeout", ev_cart="has_cart=False (undetermined)",
  ev_eng="no signals extractable — gateway error", ev_followup="no signals extractable — gateway error",
  open_gap_count=0, disqualifier="upstream gateway error — cannot assess"),
L(1684, "quatangthanhphat.com", "Quatangthanhphat", primary="Cart Recovery Opportunity", secondary="Customer Engagement Opportunity", confidence="low",
  summary="Vietnamese WooCommerce store whose fetched copy is mostly unrendered GTM tag boilerplate, no ESP.",
  conv=30, cart=45, eng=20, followup=25, ci=20,
  ev_conv="has_cart=True, no ESP; page content largely unrendered tag-manager boilerplate", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="no chat/reviews/popup", ev_followup="no email capture form detected",
  open_gap_count=2),
L(1685, "kaamnoosh.com", "Kaamnoosh", primary="Not a Good Fit", confidence="medium",
  summary="Apparel retailer (6 products) already running Mailchimp ESP with an active promo.",
  conv=25, cart=20, eng=25, followup=20, ci=30,
  ev_conv="Mailchimp ESP already live, active promo (up to 50% off)", ev_cart="has_esp_tag=mailchimp",
  ev_eng="cta_count_above_fold=2", ev_followup="email capture and ESP already wired together",
  open_gap_count=1, disqualifier="already has ESP + active promo in place"),
L(1686, "niebowmiescierzeszow.pl", "Niebowmiescierzeszow", primary="Follow-up Opportunity", secondary="Cart Recovery Opportunity", confidence="low",
  summary="Polish cafe/bakery with online ordering already offered but no email-capture form or ESP.",
  conv=35, cart=35, eng=30, followup=40, ci=25,
  ev_conv="has_cart=True but this is primarily a cafe/order-online business", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="booking already offered", ev_followup="no email capture form detected despite active ordering flow",
  open_gap_count=2),
L(1687, "dsracademy.uk", "Dsracademy", primary="Insufficient Data", confidence="high",
  summary="Site explicitly states 'Coming Soon — New WordPress website is being built' — not yet live.",
  conv=50, cart=50, eng=50, followup=50, ci=50,
  ev_conv="site explicitly not yet launched", ev_cart="has_cart=False, site inactive",
  ev_eng="no real content to evaluate — placeholder page", ev_followup="no real content to evaluate — placeholder page",
  open_gap_count=0, disqualifier="site not live — 'coming soon' placeholder"),
L(1688, "newagesolutions.africa", "Newagesolutions", primary="Insufficient Data", confidence="high",
  summary="Fetched page is a 404 Not Found error page — no real business content retrievable, despite an ESP script tag detected sitewide.",
  conv=50, cart=50, eng=50, followup=50, ci=50,
  ev_conv="fetched page is a 404 error page", ev_cart="has_cart=True flagged but page is a 404 error",
  ev_eng="no real content — 404 error page", ev_followup="no real content — 404 error page",
  open_gap_count=0, disqualifier="fetched page returns 404 Not Found — cannot assess real content"),
L(1689, "burropools.com", "Burropools", primary="Follow-up Opportunity", confidence="low",
  summary="US pool-cleaning/repair-services business with a high above-fold CTA count (6) but no lead-capture form or ESP.",
  conv=40, cart=20, eng=35, followup=50, ci=30,
  ev_conv="has_cart=False — pool services business", ev_cart="has_cart=False",
  ev_eng="cta_count_above_fold=6", ev_followup="no email or contact form detected",
  open_gap_count=1),
L(1690, "iwa.co.ke", "Iwa", primary="Cart Recovery Opportunity", secondary="Follow-up Opportunity", confidence="low",
  summary="Kenyan freight/logistics B2B business with both email and contact forms but no ESP.",
  conv=35, cart=45, eng=25, followup=40, ci=25,
  ev_conv="has_cart=True, no ESP, cta_count_above_fold=2", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="generic popup only, no chat/reviews", ev_followup="has_email_form=True and has_contact_form=True but no ESP automation",
  open_gap_count=2),
L(1691, "pivateknik.com.tr", "Pivateknik", primary="Cart Recovery Opportunity", secondary="Follow-up Opportunity", confidence="low",
  summary="Turkish WooCommerce store with WhatsApp chat, but fetched copy is mostly unrendered Elementor CSS boilerplate, no ESP.",
  conv=30, cart=45, eng=30, followup=35, ci=20,
  ev_conv="has_cart=True, no ESP; page content largely unrendered CSS boilerplate", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="WhatsApp chat present despite thin readable content", ev_followup="has_email_form=True but no ESP automation",
  open_gap_count=2),
L(1692, "lythubtechnologies.com", "Lythubtechnologies", primary="Insufficient Data", confidence="high",
  summary="Site displays a WordPress error page — no usable content retrievable.",
  conv=50, cart=50, eng=50, followup=50, ci=50,
  ev_conv="WordPress error page", ev_cart="has_cart=False (undetermined)",
  ev_eng="no signals extractable — site is broken", ev_followup="no signals extractable — site is broken",
  open_gap_count=0, disqualifier="site returns a WordPress error — cannot assess"),
L(1693, "spasofcolorado.com", "Spasofcolorado", primary="Follow-up Opportunity", confidence="low",
  summary="US hot-tub/spa retailer with both email and contact forms but no ESP.",
  conv=35, cart=25, eng=25, followup=40, ci=25,
  ev_conv="has_cart=False — informational catalog site, not confirmed e-commerce", ev_cart="has_cart=False",
  ev_eng="generic popup only, cta_count_above_fold=1", ev_followup="has_email_form=True and has_contact_form=True but no ESP automation",
  open_gap_count=1),
L(1694, "condominiomardeoro.com", "Condominiomardeoro", primary="Follow-up Opportunity", confidence="medium",
  summary="Costa Rican real-estate business (houses for sale) with WhatsApp chat and a very high above-fold CTA count (12), but no ESP.",
  conv=45, cart=20, eng=45, followup=55, ci=35,
  ev_conv="has_cart=False — real-estate sales business", ev_cart="has_cart=False",
  ev_eng="WhatsApp chat already present, cta_count_above_fold=12 (very high)", ev_followup="has_email_form=True but no ESP automation for high-value property leads",
  open_gap_count=1),
L(1695, "girlssetgo.org", "Girlssetgo", primary="Not a Good Fit", confidence="medium",
  summary="US non-profit STEM bootcamp for girls already running Mailchimp ESP.",
  conv=20, cart=15, eng=25, followup=15, ci=25,
  ev_conv="has_cart=False — donation/enrollment-driven non-profit", ev_cart="has_esp_tag=mailchimp",
  ev_eng="cta_count_above_fold=5", ev_followup="email capture and ESP already wired together",
  open_gap_count=1, disqualifier="already has ESP in place"),
L(1696, "pianetabbq.it", "Pianetabbq", primary="Insufficient Data", confidence="low",
  summary="Domain resolved but page_text is empty and platform is unknown.",
  conv=50, cart=50, eng=50, followup=50, ci=50,
  ev_conv="page_text empty", ev_cart="has_cart=False (undetermined)",
  ev_eng="no signals extractable", ev_followup="no signals extractable",
  open_gap_count=0, disqualifier="empty/undetermined signals — cannot assess"),
L(1697, "lotus-dentistry.com", "Lotus-Dentistry", primary="Follow-up Opportunity", confidence="low",
  summary="US dental clinic with online booking and reviews already live but no ESP.",
  conv=40, cart=20, eng=40, followup=50, ci=30,
  ev_conv="has_cart=False — appointment-booking clinical practice", ev_cart="has_cart=False",
  ev_eng="booking and reviews already present, cta_count_above_fold=3", ev_followup="no email capture form detected for a patient-consult clinic",
  open_gap_count=1),
]

n = append_results(RESULTS)
print(f"appended {n} rows (chunk_019)")
