import sys
sys.path.insert(0, ".")
from layer3_write import append_results


def L(lead_id, domain, business_name, primary, confidence, summary,
      conv, cart, eng, followup, ci, ev_conv, ev_cart, ev_eng, ev_followup,
      open_gap_count, secondary=None, disqualifier=None):
    return (lead_id, domain, business_name, primary, secondary, confidence, summary,
            conv, cart, eng, followup, ci, ev_conv, ev_cart, ev_eng, ev_followup,
            open_gap_count, disqualifier)


RESULTS = [
L(1027, "a2zhomedesignsolutions.com", "A2Zhomedesignsolutions", primary="Cart Recovery Opportunity", secondary="Follow-up Opportunity", confidence="medium",
  summary="Interior-design consultancy with an attached shop (5 products) and high above-fold CTA count (6), but no ESP.",
  conv=50, cart=60, eng=50, followup=55, ci=40,
  ev_conv="has_cart=True, no ESP, cta_count_above_fold=6", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="generic popup only, no chat/reviews", ev_followup="has_email_form=True but no ESP automation",
  open_gap_count=2),
L(1028, "verdeoptimo.com", "Verdeoptimo", primary="Follow-up Opportunity", confidence="low",
  summary="Spanish irrigation-system design/installation service with no lead-capture form or ESP.",
  conv=40, cart=20, eng=35, followup=55, ci=30,
  ev_conv="has_cart=True likely false-positive for a quote-driven installation service", ev_cart="product_count_visible=0",
  ev_eng="no chat, no reviews", ev_followup="no email or contact form detected for a service-quote business",
  open_gap_count=1),
L(1029, "laundrybox.cl", "Laundrybox", primary="Follow-up Opportunity", secondary="Cart Recovery Opportunity", confidence="low",
  summary="Chilean on-demand laundry delivery service with WhatsApp chat but no email-capture form or ESP.",
  conv=40, cart=35, eng=45, followup=50, ci=30,
  ev_conv="has_cart=True but this is a subscription delivery service", ev_cart="product_count_visible=0",
  ev_eng="WhatsApp chat present", ev_followup="no email capture form detected despite active chat channel",
  open_gap_count=2),
L(1030, "sittihouston.com", "Sittihouston", primary="Not a Good Fit", confidence="medium",
  summary="Mediterranean catering business (48 menu items) already running Mailchimp ESP with reviews.",
  conv=25, cart=25, eng=30, followup=20, ci=30,
  ev_conv="Mailchimp ESP already live", ev_cart="has_esp_tag=mailchimp",
  ev_eng="reviews present, cta_count_above_fold=5", ev_followup="email capture and ESP already wired together",
  open_gap_count=1, disqualifier="already has ESP + reviews stack in place"),
L(1031, "purexdrop.com", "Purexdrop", primary="Multi-Opportunity", confidence="medium",
  summary="Shopify store (13 products) with WhatsApp chat and an exceptionally high above-fold CTA count (16), but no ESP.",
  conv=55, cart=65, eng=55, followup=55, ci=40,
  ev_conv="has_cart=True, no ESP, cta_count_above_fold=16 (very high)", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="WhatsApp chat present, very strong above-fold CTA presence", ev_followup="has_email_form=True but no ESP automation",
  open_gap_count=2),
L(1032, "angushalalmeat.co.uk", "Angushalalmeat", primary="Insufficient Data", confidence="low",
  summary="Domain resolved but page_text is empty and platform is unknown.",
  conv=50, cart=50, eng=50, followup=50, ci=50,
  ev_conv="page_text empty", ev_cart="has_cart=False (undetermined)",
  ev_eng="no signals extractable", ev_followup="no signals extractable",
  open_gap_count=0, disqualifier="empty/undetermined signals — cannot assess"),
L(1033, "zoeste.com", "Zoeste", primary="Cart Recovery Opportunity", secondary="Customer Engagement Opportunity", confidence="low",
  summary="Spanish women's fashion WooCommerce store, product_count_visible=0 suggests thin page fetched.",
  conv=40, cart=60, eng=40, followup=35, ci=30,
  ev_conv="has_cart=True, no ESP", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="generic popup only, no chat/reviews", ev_followup="no email capture form detected",
  open_gap_count=2),
L(1034, "verheulopleidingen.nl", "Verheulopleidingen", primary="Follow-up Opportunity", confidence="medium",
  summary="Dutch safety/logistics training-course provider with booking already offered but no email capture or ESP.",
  conv=45, cart=20, eng=45, followup=60, ci=35,
  ev_conv="has_cart=True likely false-positive for a training-course provider", ev_cart="product_count_visible=0",
  ev_eng="booking already offered", ev_followup="no email capture form detected despite active booking flow",
  open_gap_count=1),
L(1035, "filtrwody.com", "Filtrwody", primary="Insufficient Data", confidence="high",
  summary="DNS resolution failed (transient resolver error) — no content retrievable.",
  conv=50, cart=50, eng=50, followup=50, ci=50,
  ev_conv="DNS resolution failed", ev_cart="has_cart=False (undetermined)",
  ev_eng="no signals extractable — DNS failure", ev_followup="no signals extractable — DNS failure",
  open_gap_count=0, disqualifier="DNS resolution failed — cannot assess"),
L(1036, "hytte-land.no", "Hytte-Land", primary="Cart Recovery Opportunity", secondary="Follow-up Opportunity", confidence="medium",
  summary="Norwegian outdoor-cabin/shed builder WooCommerce store with no ESP.",
  conv=45, cart=65, eng=40, followup=55, ci=35,
  ev_conv="has_cart=True, no ESP", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="generic popup only, no chat/reviews", ev_followup="has_email_form=True but no ESP automation",
  open_gap_count=2),
L(1037, "verdora.com.my", "Verdora", primary="Cart Recovery Opportunity", secondary="Customer Engagement Opportunity", confidence="low",
  summary="Malaysian skincare WooCommerce store, product_count_visible=0 suggests thin page fetched.",
  conv=40, cart=60, eng=40, followup=35, ci=30,
  ev_conv="has_cart=True, no ESP", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="no chat/reviews/popup", ev_followup="no email capture form detected",
  open_gap_count=2),
L(1038, "premiumcustomboxes.ca", "Premiumcustomboxes", primary="Cart Recovery Opportunity", secondary="Follow-up Opportunity", confidence="medium",
  summary="Canadian custom-packaging B2B WooCommerce store with tawk chat and both email and contact forms, no ESP.",
  conv=45, cart=60, eng=50, followup=55, ci=35,
  ev_conv="has_cart=True, no ESP", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="tawk chat present, cta_count_above_fold=1", ev_followup="has_email_form=True and has_contact_form=True but no ESP automation",
  open_gap_count=2),
L(1039, "highoctanelemonade.com", "Highoctanelemonade", primary="Cart Recovery Opportunity", secondary="Follow-up Opportunity", confidence="medium",
  summary="Craft-lemonade WooCommerce store (6 products) with an active promo but no ESP.",
  conv=45, cart=65, eng=45, followup=55, ci=35,
  ev_conv="has_cart=True, has_promo_bar=True, no ESP", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="generic popup only, no chat/reviews, cta_count_above_fold=5", ev_followup="has_email_form=True but no ESP automation",
  open_gap_count=2),
L(1040, "outillageaouami.com", "Outillageaouami", primary="Cart Recovery Opportunity", secondary="Follow-up Opportunity", confidence="medium",
  summary="Moroccan B2B tools distributor (12 products, quote-request model) with a high above-fold CTA count (7) but no ESP.",
  conv=45, cart=60, eng=45, followup=55, ci=35,
  ev_conv="has_cart=True, no ESP, cta_count_above_fold=7", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="generic popup only, no chat/reviews despite high above-fold CTA count", ev_followup="no email capture form detected",
  open_gap_count=2),
L(1041, "mgamotors.ge", "Mgamotors", primary="Insufficient Data", confidence="low",
  summary="Domain resolved but page_text is empty and platform is unknown.",
  conv=50, cart=50, eng=50, followup=50, ci=50,
  ev_conv="page_text empty", ev_cart="has_cart=False (undetermined)",
  ev_eng="no signals extractable", ev_followup="no signals extractable",
  open_gap_count=0, disqualifier="empty/undetermined signals — cannot assess"),
L(1042, "emkenstationersltd.co.ke", "Emkenstationersltd", primary="Cart Recovery Opportunity", secondary="Customer Engagement Opportunity", confidence="medium",
  summary="Kenyan stationery WooCommerce store (33 products) with a high above-fold CTA count (9) but no capture form or ESP.",
  conv=45, cart=65, eng=45, followup=35, ci=35,
  ev_conv="has_cart=True, no ESP, 33 products", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="no chat/reviews/popup despite cta_count_above_fold=9", ev_followup="no email capture form detected",
  open_gap_count=2),
L(1043, "skysurge.co", "Skysurge", primary="Insufficient Data", confidence="high",
  summary="Cloudflare 522 connection-timeout error — origin server unreachable, no content retrievable.",
  conv=50, cart=50, eng=50, followup=50, ci=50,
  ev_conv="Cloudflare 522 error", ev_cart="has_cart=False (undetermined)",
  ev_eng="no signals extractable — origin unreachable", ev_followup="no signals extractable — origin unreachable",
  open_gap_count=0, disqualifier="origin server unreachable (Cloudflare 522) — cannot assess"),
L(1044, "jjtrucktrailerparts.com", "Jjtrucktrailerparts", primary="Insufficient Data", confidence="low",
  summary="Domain resolved but page_text is empty and platform is unknown.",
  conv=50, cart=50, eng=50, followup=50, ci=50,
  ev_conv="page_text empty", ev_cart="has_cart=False (undetermined)",
  ev_eng="no signals extractable", ev_followup="no signals extractable",
  open_gap_count=0, disqualifier="empty/undetermined signals — cannot assess"),
L(1045, "cafemontetoro.com", "Cafemontetoro", primary="Cart Recovery Opportunity", secondary="Follow-up Opportunity", confidence="medium",
  summary="Spanish coffee roaster WooCommerce store with WhatsApp chat and reviews already live but no ESP.",
  conv=45, cart=65, eng=50, followup=50, ci=35,
  ev_conv="has_cart=True, no ESP", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="WhatsApp chat and reviews already present", ev_followup="no email capture form detected despite active chat",
  open_gap_count=2),
L(1046, "zmetic.com", "Zmetic", primary="Cart Recovery Opportunity", secondary="Follow-up Opportunity", confidence="medium",
  summary="Indian jewelry WooCommerce store (33 products) with WhatsApp chat but no ESP.",
  conv=45, cart=65, eng=45, followup=50, ci=35,
  ev_conv="has_cart=True, no ESP", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="WhatsApp chat present but no reviews", ev_followup="no email capture form detected despite active chat",
  open_gap_count=2),
L(1047, "grupozenti.com", "Grupozenti", primary="Cart Recovery Opportunity", secondary="Customer Engagement Opportunity", confidence="low",
  summary="Ice-cream flavors/kits wholesale WooCommerce store, product_count_visible=0 suggests thin page fetched.",
  conv=40, cart=60, eng=35, followup=35, ci=30,
  ev_conv="has_cart=True, no ESP", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="no chat/reviews/popup", ev_followup="no email capture form detected",
  open_gap_count=2),
L(1048, "thuylammoc.com", "Thuylammoc", primary="Insufficient Data", confidence="low",
  summary="Domain resolved but page_text is empty and platform is unknown.",
  conv=50, cart=50, eng=50, followup=50, ci=50,
  ev_conv="page_text empty", ev_cart="has_cart=False (undetermined)",
  ev_eng="no signals extractable", ev_followup="no signals extractable",
  open_gap_count=0, disqualifier="empty/undetermined signals — cannot assess"),
L(1049, "inlandsecurity.co.ke", "Inlandsecurity", primary="Cart Recovery Opportunity", secondary="Follow-up Opportunity", confidence="medium",
  summary="Kenyan security-systems installer with WhatsApp chat, booking, and reviews already live, but no ESP.",
  conv=50, cart=60, eng=55, followup=55, ci=40,
  ev_conv="has_cart=True, no ESP", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="WhatsApp chat, booking, and reviews already present", ev_followup="has_email_form=True but no ESP automation",
  open_gap_count=2),
L(1050, "ohprint.be", "Ohprint", primary="Follow-up Opportunity", secondary="Cart Recovery Opportunity", confidence="low",
  summary="Belgian print-on-demand/gift-photo store, apparently mid-rebuild ('working on something great'), with an email form but no ESP.",
  conv=35, cart=35, eng=35, followup=45, ci=25,
  ev_conv="has_cart=True, no ESP; site copy suggests an active rebuild in progress", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="no chat/reviews/popup", ev_followup="has_email_form=True (newsletter signup) but no ESP automation",
  open_gap_count=2),
L(1051, "niyamaktech.com", "Niyamaktech", primary="Not a Good Fit", confidence="medium",
  summary="Staffing/recruitment services B2B business already running Mailchimp ESP.",
  conv=25, cart=20, eng=30, followup=20, ci=30,
  ev_conv="has_cart=True likely false-positive for a staffing services business", ev_cart="has_esp_tag=mailchimp",
  ev_eng="cta_count_above_fold=3", ev_followup="email capture and ESP already wired together",
  open_gap_count=1, disqualifier="already has ESP in place"),
L(1052, "inlosangeleslocal.com", "Inlosangeleslocal", primary="Not a Good Fit", confidence="medium",
  summary="Los Angeles local-business directory/listings platform already running Mailchimp ESP with reviews.",
  conv=25, cart=20, eng=30, followup=20, ci=30,
  ev_conv="has_cart=True likely false-positive for a listings directory", ev_cart="has_esp_tag=mailchimp",
  ev_eng="reviews present, cta_count_above_fold=1", ev_followup="email capture and ESP already wired together",
  open_gap_count=1, disqualifier="already has ESP + reviews stack in place"),
L(1053, "kemytgallery.com", "Kemytgallery", primary="Not a Good Fit", confidence="medium",
  summary="Egyptian-themed art print WooCommerce store (22 products) already running Omnisend ESP with an active promo.",
  conv=20, cart=20, eng=25, followup=15, ci=25,
  ev_conv="Omnisend ESP already live, active promo (Kemyt25 code)", ev_cart="has_esp_tag=omnisend",
  ev_eng="active promo already present", ev_followup="email capture and ESP already wired together",
  open_gap_count=1, disqualifier="already has ESP + active promo in place"),
L(1054, "primeconnecthub.com", "Primeconnecthub", primary="Multi-Opportunity", confidence="medium",
  summary="General-merchandise marketplace (20 products) with reviews and an exceptionally high above-fold CTA count (19), but no ESP.",
  conv=55, cart=65, eng=55, followup=55, ci=40,
  ev_conv="has_cart=True, no ESP, cta_count_above_fold=19 (very high)", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="reviews present, very strong above-fold CTA presence", ev_followup="has_email_form=True but no ESP automation",
  open_gap_count=2),
L(1055, "nguyetsport.com", "Nguyetsport", primary="Cart Recovery Opportunity", secondary="Follow-up Opportunity", confidence="medium",
  summary="Gothic-themed apparel WooCommerce store (22 products) with reviews already live but no ESP.",
  conv=45, cart=65, eng=45, followup=55, ci=35,
  ev_conv="has_cart=True, no ESP", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="reviews present but no chat/popup", ev_followup="has_email_form=True but no ESP automation",
  open_gap_count=2),
L(1056, "smarthometoledo.com", "Smarthometoledo", primary="Insufficient Data", confidence="high",
  summary="Server returns 503 Service Unavailable — no content retrievable.",
  conv=50, cart=50, eng=50, followup=50, ci=50,
  ev_conv="503 service unavailable", ev_cart="has_cart=False (undetermined)",
  ev_eng="no signals extractable — server error", ev_followup="no signals extractable — server error",
  open_gap_count=0, disqualifier="server returns 503 — cannot assess"),
L(1057, "bubble-cards.com", "Bubble-Cards", primary="Cart Recovery Opportunity", secondary="Follow-up Opportunity", confidence="medium",
  summary="German Shopify greeting-cards store with reviews already live but no ESP.",
  conv=45, cart=65, eng=45, followup=55, ci=35,
  ev_conv="has_cart=True, no ESP", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="reviews present, active WhatsApp contact number in header", ev_followup="has_email_form=True but no ESP automation",
  open_gap_count=2),
L(1058, "rcp-tools.ro", "Rcp-Tools", primary="Insufficient Data", confidence="high",
  summary="Page served an obfuscated JS-based verification wall ('Please wait while your request is being verified') — no real content retrievable.",
  conv=50, cart=50, eng=50, followup=50, ci=50,
  ev_conv="bot-check/obfuscated verification page", ev_cart="has_cart=False (undetermined)",
  ev_eng="no signals extractable — verification wall", ev_followup="no signals extractable — verification wall",
  open_gap_count=0, disqualifier="anti-bot verification page — cannot assess real content"),
L(1059, "garnyze.cz", "Garnyze", primary="Cart Recovery Opportunity", secondary="Customer Engagement Opportunity", confidence="low",
  summary="Czech curtains/blinds WooCommerce store, product_count_visible=0 suggests thin page fetched.",
  conv=40, cart=60, eng=35, followup=35, ci=30,
  ev_conv="has_cart=True, no ESP", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="generic popup only, no chat/reviews", ev_followup="no email capture form detected",
  open_gap_count=2),
L(1060, "terepkiraly.hu", "Terepkiraly", primary="Cart Recovery Opportunity", secondary="Follow-up Opportunity", confidence="medium",
  summary="Hungarian outdoor/off-road gear WooCommerce store (7 products) with reviews already live but no ESP.",
  conv=45, cart=65, eng=45, followup=55, ci=35,
  ev_conv="has_cart=True, no ESP", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="reviews present but no chat/popup", ev_followup="has_email_form=True but no ESP automation",
  open_gap_count=2),
L(1061, "cutestpuppiesforsale.com", "Cutestpuppiesforsale", primary="Cart Recovery Opportunity", secondary="Follow-up Opportunity", confidence="medium",
  summary="US puppy-sales retailer (7 breeds) with tawk chat and reviews already live but no ESP.",
  conv=45, cart=65, eng=55, followup=55, ci=35,
  ev_conv="has_cart=True, no ESP", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="tawk chat and reviews already present, cta_count_above_fold=6", ev_followup="no email capture form detected despite active chat",
  open_gap_count=2),
L(1062, "parcel2u.co.uk", "Parcel2U", primary="Cart Recovery Opportunity", secondary="Follow-up Opportunity", confidence="medium",
  summary="UK smart parcel-locker product WooCommerce store with both email and contact forms but no ESP.",
  conv=45, cart=60, eng=40, followup=55, ci=35,
  ev_conv="has_cart=True, no ESP", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="no chat/reviews, cta_count_above_fold=1", ev_followup="has_email_form=True and has_contact_form=True but no ESP automation",
  open_gap_count=2),
L(1063, "heatsense.dk", "Heatsense", primary="Cart Recovery Opportunity", secondary="Customer Engagement Opportunity", confidence="low",
  summary="Danish light/laser-therapy devices WooCommerce store (humans and animals), product_count_visible=0 suggests thin page fetched.",
  conv=40, cart=60, eng=40, followup=35, ci=30,
  ev_conv="has_cart=True, no ESP", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="reviews present but no chat/popup", ev_followup="no email capture form detected",
  open_gap_count=2),
L(1064, "autodominar.com", "Autodominar", primary="Not a Good Fit", confidence="low",
  summary="Directory/listings-style site already running Mailchimp ESP with reviews.",
  conv=25, cart=20, eng=30, followup=20, ci=30,
  ev_conv="Mailchimp ESP already live; page appears to be a generic listings-directory theme", ev_cart="has_esp_tag=mailchimp",
  ev_eng="reviews present", ev_followup="email capture and ESP already wired together",
  open_gap_count=1, disqualifier="already has ESP in place; page content is a generic directory theme"),
L(1065, "stitchcraftec.co.za", "Stitchcraftec", primary="Multi-Opportunity", confidence="medium",
  summary="South African sewing-machine retailer (16 products) with reviews and a high above-fold CTA count (14), but no ESP.",
  conv=50, cart=65, eng=55, followup=55, ci=40,
  ev_conv="has_cart=True, no ESP, cta_count_above_fold=14", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="reviews present, strong above-fold CTA presence", ev_followup="has_email_form=True but no ESP automation",
  open_gap_count=2),
L(1066, "drurviharia.com", "Drurviharia", primary="Follow-up Opportunity", confidence="medium",
  summary="Indian homeopathy/acupuncture clinic with both email and contact forms and reviews already live, but no ESP.",
  conv=45, cart=25, eng=50, followup=55, ci=40,
  ev_conv="has_cart=True likely false-positive for a clinical services business", ev_cart="product_count_visible=0",
  ev_eng="reviews present, cta_count_above_fold=2", ev_followup="has_email_form=True and has_contact_form=True but no ESP automation for appointment leads",
  open_gap_count=1),
L(1067, "myhomecourt.ca", "Myhomecourt", primary="Cart Recovery Opportunity", secondary="Follow-up Opportunity", confidence="low",
  summary="Canadian home sports-court builder WooCommerce site, product_count_visible=0 suggests thin page fetched.",
  conv=40, cart=55, eng=35, followup=50, ci=30,
  ev_conv="has_cart=True, no ESP", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="generic popup only, no chat/reviews, cta_count_above_fold=1", ev_followup="has_email_form=True but no ESP automation",
  open_gap_count=2),
L(1068, "sensorynow.com", "Sensorynow", primary="Cart Recovery Opportunity", secondary="Follow-up Opportunity", confidence="medium",
  summary="Sensory-processing equipment retailer with reviews already live but no ESP.",
  conv=45, cart=60, eng=45, followup=55, ci=35,
  ev_conv="has_cart=True, no ESP", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="reviews present, cta_count_above_fold=5", ev_followup="has_email_form=True but no ESP automation",
  open_gap_count=2),
L(1069, "rbsprolab.com", "Rbsprolab", primary="Cart Recovery Opportunity", secondary="Follow-up Opportunity", confidence="medium",
  summary="Hair extensions WooCommerce store (10 products) with no ESP.",
  conv=45, cart=60, eng=35, followup=55, ci=35,
  ev_conv="has_cart=True, no ESP", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="no chat/reviews/popup, cta_count_above_fold=1", ev_followup="has_email_form=True but no ESP automation",
  open_gap_count=2),
L(1070, "hckoutdoorfridges.co.uk", "Hckoutdoorfridges", primary="Insufficient Data", confidence="low",
  summary="Domain resolved but page_text is empty and platform is unknown.",
  conv=50, cart=50, eng=50, followup=50, ci=50,
  ev_conv="page_text empty", ev_cart="has_cart=False (undetermined)",
  ev_eng="no signals extractable", ev_followup="no signals extractable",
  open_gap_count=0, disqualifier="empty/undetermined signals — cannot assess"),
L(1071, "lavandalux.com", "Lavandalux", primary="Cart Recovery Opportunity", secondary="Follow-up Opportunity", confidence="low",
  summary="Serbian lavender-products WooCommerce store, product_count_visible=0 suggests thin page fetched.",
  conv=40, cart=60, eng=35, followup=50, ci=30,
  ev_conv="has_cart=True, no ESP", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="generic popup only, no chat/reviews", ev_followup="has_email_form=True but no ESP automation",
  open_gap_count=2),
L(1073, "will2winacademy.com", "Will2Winacademy", primary="Follow-up Opportunity", secondary="Cart Recovery Opportunity", confidence="medium",
  summary="Orlando basketball training academy with booking already offered and a small shop (7 products), but no ESP.",
  conv=45, cart=40, eng=45, followup=55, ci=35,
  ev_conv="has_cart=True but this is a training-academy service, not physical goods primarily", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="booking already offered", ev_followup="has_email_form=True but no ESP automation",
  open_gap_count=2),
L(1074, "antuongtravel.com", "Antuongtravel", primary="Follow-up Opportunity", confidence="low",
  summary="Vietnamese tour operator (domestic tours, hotels, flights) with no lead-capture form or ESP.",
  conv=40, cart=20, eng=35, followup=55, ci=30,
  ev_conv="has_cart=True likely false-positive for a tour-package business", ev_cart="product_count_visible=0",
  ev_eng="no chat, no reviews", ev_followup="no email or contact form detected for high-value tour inquiries",
  open_gap_count=1),
L(1075, "playdent.cl", "Playdent", primary="Not a Good Fit", confidence="medium",
  summary="Chilean dental clinic already running Mailchimp ESP with WhatsApp chat and reviews.",
  conv=25, cart=20, eng=35, followup=20, ci=30,
  ev_conv="has_cart=True likely false-positive for a dental clinic", ev_cart="has_esp_tag=mailchimp",
  ev_eng="WhatsApp chat and reviews already present", ev_followup="email capture and ESP already wired together",
  open_gap_count=1, disqualifier="already has ESP + chat + reviews stack in place"),
L(1076, "almelaw.com", "Almelaw", primary="Follow-up Opportunity", confidence="medium",
  summary="Macedonian law firm (immigration, renewable energy, IT/startup consulting) with an email form but no ESP.",
  conv=45, cart=20, eng=35, followup=60, ci=35,
  ev_conv="has_cart=True likely false-positive for a law firm", ev_cart="product_count_visible=0",
  ev_eng="no chat, no reviews", ev_followup="has_email_form=True but no ESP automation for high-value legal-consult leads",
  open_gap_count=1),
L(1077, "gradezilla.org", "Gradezilla", primary="Not a Good Fit", confidence="medium",
  summary="Digital-marketing training course provider already running Mailchimp ESP with WhatsApp chat.",
  conv=25, cart=20, eng=35, followup=20, ci=30,
  ev_conv="has_cart=True likely false-positive for a course provider", ev_cart="has_esp_tag=mailchimp",
  ev_eng="WhatsApp chat already present, cta_count_above_fold=2", ev_followup="email capture and ESP already wired together",
  open_gap_count=1, disqualifier="already has ESP + chat stack in place"),
L(1078, "klimazseni.hu", "Klimazseni", primary="Follow-up Opportunity", secondary="Cart Recovery Opportunity", confidence="low",
  summary="Hungarian AC/heat-pump installer with a quote-request model but no lead-capture form or ESP.",
  conv=40, cart=40, eng=35, followup=55, ci=30,
  ev_conv="has_cart=True, no ESP", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="no chat/reviews/popup", ev_followup="no email or contact form detected for a quote-request installer",
  open_gap_count=2),
L(1079, "maisonsiesie.be", "Maisonsiesie", primary="Cart Recovery Opportunity", secondary="Customer Engagement Opportunity", confidence="low",
  summary="Belgian WooCommerce store with mostly unrendered JS boilerplate in fetched copy, no ESP.",
  conv=35, cart=55, eng=30, followup=30, ci=25,
  ev_conv="has_cart=True, no ESP; page content largely unrendered JS boilerplate", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="no chat/reviews/popup", ev_followup="no email capture form detected",
  open_gap_count=2),
L(1080, "acheter-ici.net", "Acheter-Ici", primary="Cart Recovery Opportunity", secondary="Follow-up Opportunity", confidence="low",
  summary="Electronics/computers marketplace WooCommerce store, product_count_visible=0 suggests thin page fetched.",
  conv=40, cart=60, eng=35, followup=50, ci=30,
  ev_conv="has_cart=True, no ESP", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="no chat/reviews/popup", ev_followup="has_email_form=True but no ESP automation",
  open_gap_count=2),
L(1081, "elixircarcare.com", "Elixircarcare", primary="Cart Recovery Opportunity", secondary="Follow-up Opportunity", confidence="medium",
  summary="Shopify car-care products store (9 products) with reviews already live but no ESP.",
  conv=45, cart=65, eng=45, followup=55, ci=35,
  ev_conv="has_cart=True, no ESP", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="reviews present, cta_count_above_fold=1", ev_followup="has_email_form=True but no ESP automation",
  open_gap_count=2),
L(1082, "njwholesaleprovision.com", "Njwholesaleprovision", primary="Cart Recovery Opportunity", secondary="Customer Engagement Opportunity", confidence="medium",
  summary="US wholesale juice/deli distributor B2B (42 products) with reviews already live but no capture form or ESP.",
  conv=45, cart=65, eng=45, followup=35, ci=35,
  ev_conv="has_cart=True, no ESP", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="reviews present but no chat/popup", ev_followup="no email capture form detected",
  open_gap_count=2),
]

n = append_results(RESULTS)
print(f"appended {n} rows (chunk_009)")
