import sys
sys.path.insert(0, ".")
from layer3_write import append_results


def L(lead_id, domain, business_name, primary, confidence, summary,
      conv, cart, eng, followup, ci, ev_conv, ev_cart, ev_eng, ev_followup,
      open_gap_count, secondary=None, disqualifier=None):
    return (lead_id, domain, business_name, primary, secondary, confidence, summary,
            conv, cart, eng, followup, ci, ev_conv, ev_cart, ev_eng, ev_followup,
            open_gap_count, disqualifier)


RESULTS = [
L(1230, "spittiasolutions.com", "Spittiasolutions", primary="Insufficient Data", confidence="low",
  summary="Domain resolved but page_text is empty and platform is unknown.",
  conv=50, cart=50, eng=50, followup=50, ci=50,
  ev_conv="page_text empty", ev_cart="has_cart=False (undetermined)",
  ev_eng="no signals extractable", ev_followup="no signals extractable",
  open_gap_count=0, disqualifier="empty/undetermined signals — cannot assess"),
L(1231, "bioroses.com", "Bioroses", primary="Cart Recovery Opportunity", secondary="Follow-up Opportunity", confidence="medium",
  summary="Skincare WooCommerce store with an active discount promo but no ESP.",
  conv=45, cart=65, eng=45, followup=55, ci=35,
  ev_conv="has_cart=True, has_promo_bar=True, no ESP", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="generic popup only, no chat/reviews, cta_count_above_fold=6", ev_followup="has_email_form=True but no ESP automation",
  open_gap_count=2),
L(1232, "lolitaoman.com", "Lolitaoman", primary="Cart Recovery Opportunity", secondary="Customer Engagement Opportunity", confidence="medium",
  summary="Omani flowers/beauty WooCommerce store (43 products) with no capture form or ESP.",
  conv=45, cart=65, eng=40, followup=35, ci=35,
  ev_conv="has_cart=True, no ESP, 43 products", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="no chat/reviews/popup", ev_followup="no email capture form detected",
  open_gap_count=2),
L(1233, "d-ert.com", "D-Ert", primary="Follow-up Opportunity", confidence="medium",
  summary="Indian composting/gardening-equipment rental business with booking and reviews already live but no ESP.",
  conv=45, cart=20, eng=50, followup=55, ci=35,
  ev_conv="has_cart=False — service/rental business, cart recovery not applicable", ev_cart="has_cart=False",
  ev_eng="booking and reviews already present", ev_followup="has_email_form=True and has_contact_form=True but no ESP automation",
  open_gap_count=1),
L(1235, "boatandtrade.com", "Boatandtrade", primary="Follow-up Opportunity", confidence="medium",
  summary="Boat-sales listings marketplace with an email form but no ESP.",
  conv=40, cart=20, eng=35, followup=55, ci=30,
  ev_conv="has_cart=False — listings marketplace, not a physical cart", ev_cart="has_cart=False",
  ev_eng="generic popup only", ev_followup="has_email_form=True but no ESP automation for buyer/seller leads",
  open_gap_count=1),
L(1236, "z4cad.nl", "Z4Cad", primary="Cart Recovery Opportunity", secondary="Follow-up Opportunity", confidence="medium",
  summary="Dutch CAD/BIM software reseller B2B WooCommerce store with no ESP.",
  conv=45, cart=60, eng=35, followup=55, ci=35,
  ev_conv="has_cart=True, no ESP", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="generic popup only, no chat/reviews", ev_followup="has_email_form=True but no ESP automation",
  open_gap_count=2),
L(1237, "psmmeditech.com", "Psmmeditech", primary="Cart Recovery Opportunity", secondary="Customer Engagement Opportunity", confidence="medium",
  summary="Medical-equipment wholesale B2B WooCommerce store (10 products) with a high above-fold CTA count (14) but no ESP.",
  conv=50, cart=65, eng=50, followup=35, ci=35,
  ev_conv="has_cart=True, no ESP, cta_count_above_fold=14", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="no chat/reviews/popup despite very high above-fold CTA count", ev_followup="no email capture form detected",
  open_gap_count=2),
L(1240, "sasanoilandgas.com", "Sasanoilandgas", primary="Follow-up Opportunity", confidence="low",
  summary="Nigerian oilfield-services B2B firm with a high above-fold CTA count (8) but no lead-capture form or ESP.",
  conv=40, cart=20, eng=40, followup=50, ci=30,
  ev_conv="has_cart=False — B2B energy-services firm", ev_cart="has_cart=False",
  ev_eng="cta_count_above_fold=8", ev_followup="no email or contact form detected",
  open_gap_count=1),
L(1243, "queensboroughwest.org", "Queensboroughwest", primary="Cart Recovery Opportunity", secondary="Follow-up Opportunity", confidence="low",
  summary="Rotary Club community organization with an attached shop, booking, and reviews already live, but no ESP.",
  conv=40, cart=55, eng=50, followup=45, ci=30,
  ev_conv="has_cart=True, no ESP", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="booking and reviews already present", ev_followup="has_email_form=True and has_contact_form=True but no ESP automation",
  open_gap_count=2),
L(1244, "adest.co.in", "Adest", primary="Follow-up Opportunity", confidence="low",
  summary="Indian business (likely IT/digital services) with WhatsApp chat and reviews already live, but no ESP.",
  conv=40, cart=25, eng=45, followup=50, ci=30,
  ev_conv="platform=unknown, has_cart=False", ev_cart="has_cart=False",
  ev_eng="WhatsApp chat and reviews already present, cta_count_above_fold=1", ev_followup="has_email_form=True but no ESP automation",
  open_gap_count=1),
L(1246, "precisiontelemed.com", "Precisiontelemed", primary="Follow-up Opportunity", confidence="medium",
  summary="US telehealth (compounded medications) service with reviews already live but no lead-capture form or ESP.",
  conv=45, cart=20, eng=45, followup=55, ci=35,
  ev_conv="has_cart=False — telehealth service, not physical-goods cart", ev_cart="has_cart=False",
  ev_eng="reviews present, cta_count_above_fold=5", ev_followup="no email or contact form detected for a telehealth-consult business",
  open_gap_count=1),
L(1247, "greenbayshopping.com", "Greenbayshopping", primary="Cart Recovery Opportunity", secondary="Follow-up Opportunity", confidence="medium",
  summary="Indian nuts/spices/dried-fruits WooCommerce store (25 products) with both email and contact forms and reviews already live, but no ESP.",
  conv=50, cart=60, eng=50, followup=55, ci=35,
  ev_conv="has_cart=True, no ESP", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="reviews present, cta_count_above_fold=4", ev_followup="has_email_form=True and has_contact_form=True but no ESP automation",
  open_gap_count=2),
L(1249, "alanw.uk", "Alanw", primary="Insufficient Data", confidence="low",
  summary="Domain resolved but page_text is empty and platform is unknown.",
  conv=50, cart=50, eng=50, followup=50, ci=50,
  ev_conv="page_text empty", ev_cart="has_cart=False (undetermined)",
  ev_eng="no signals extractable", ev_followup="no signals extractable",
  open_gap_count=0, disqualifier="empty/undetermined signals — cannot assess"),
L(1250, "www.alien-oxygen.com", "Alien-Oxygen", primary="Insufficient Data", confidence="low",
  summary="Domain resolved but page_text is empty and platform is unknown.",
  conv=50, cart=50, eng=50, followup=50, ci=50,
  ev_conv="page_text empty", ev_cart="has_cart=False (undetermined)",
  ev_eng="no signals extractable", ev_followup="no signals extractable",
  open_gap_count=0, disqualifier="empty/undetermined signals — cannot assess"),
L(1251, "kayan-medical-supplies.com", "Kayan-Medical-Supplies", primary="Cart Recovery Opportunity", secondary="Follow-up Opportunity", confidence="low",
  summary="Egyptian medical-supplies WooCommerce store with reviews already live but no capture form or ESP.",
  conv=40, cart=60, eng=40, followup=40, ci=30,
  ev_conv="has_cart=True, no ESP", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="reviews present but no chat/popup", ev_followup="no email capture form detected",
  open_gap_count=2),
L(1252, "yuliaschonfeldt.com", "Yuliaschonfeldt", primary="Insufficient Data", confidence="high",
  summary="Page states 'no Web site at this address' — domain is not hosting a live business.",
  conv=50, cart=50, eng=50, followup=50, ci=50,
  ev_conv="no website at this address", ev_cart="no storefront exists",
  ev_eng="no real content — no site", ev_followup="no real content — no site",
  open_gap_count=0, disqualifier="no website configured at this domain"),
L(1253, "www.genlabsanabolics.com", "Genlabsanabolics", primary="Insufficient Data", confidence="high",
  summary="Fetched page content is entirely unrelated Seventh Generation home-care product copy — appears to be a domain misconfiguration or wrong-content serve, not this business's real site.",
  conv=50, cart=50, eng=50, followup=50, ci=50,
  ev_conv="fetched content unrelated to the domain's apparent business", ev_cart="has_cart=False, content mismatch",
  ev_eng="no reliable signals — content does not match expected business", ev_followup="no reliable signals — content does not match expected business",
  open_gap_count=0, disqualifier="fetched page content does not match the domain's expected business — likely misconfigured or wrong content served"),
L(1254, "casept.pl", "Casept", primary="Follow-up Opportunity", confidence="low",
  summary="Polish pest-control/disinfection B2B services business with no lead-capture form or ESP.",
  conv=40, cart=25, eng=35, followup=50, ci=30,
  ev_conv="has_cart=True likely false-positive for a B2B services business", ev_cart="product_count_visible=0",
  ev_eng="generic popup only, no chat/reviews", ev_followup="no email or contact form detected",
  open_gap_count=1),
L(1255, "www.visti.co.ke", "Visti", primary="Cart Recovery Opportunity", secondary="Follow-up Opportunity", confidence="medium",
  summary="Kenyan sign-language training institute with a bookshop (12 products) and a high above-fold CTA count (6) but no ESP.",
  conv=45, cart=55, eng=45, followup=50, ci=35,
  ev_conv="has_cart=True, no ESP, cta_count_above_fold=6", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="no chat/reviews/popup", ev_followup="has_email_form=True but no ESP automation for enrollment/bookshop leads",
  open_gap_count=2),
L(1256, "orising.ca", "Orising", primary="Cart Recovery Opportunity", secondary="Follow-up Opportunity", confidence="medium",
  summary="Canadian hair-loss-treatment retailer (23 products) with WhatsApp chat but no ESP.",
  conv=45, cart=65, eng=50, followup=50, ci=35,
  ev_conv="has_cart=True, no ESP", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="WhatsApp chat present but no reviews", ev_followup="has_email_form=True but no ESP automation",
  open_gap_count=2),
L(1258, "mitapatia.com", "Mitapatia", primary="Insufficient Data", confidence="low",
  summary="Domain resolved but page_text is empty and platform is unknown.",
  conv=50, cart=50, eng=50, followup=50, ci=50,
  ev_conv="page_text empty", ev_cart="has_cart=False (undetermined)",
  ev_eng="no signals extractable", ev_followup="no signals extractable",
  open_gap_count=0, disqualifier="empty/undetermined signals — cannot assess"),
L(1259, "comarestours.com", "Comarestours", primary="Follow-up Opportunity", confidence="low",
  summary="Spanish tour operator (Arabic-language site) with no lead-capture form or ESP.",
  conv=40, cart=20, eng=35, followup=50, ci=30,
  ev_conv="has_cart=True likely false-positive for a tour-package business", ev_cart="product_count_visible=0",
  ev_eng="generic popup only, no chat/reviews", ev_followup="no email or contact form detected",
  open_gap_count=1),
L(1260, "sadiqit.com", "Sadiqit", primary="Follow-up Opportunity", confidence="medium",
  summary="Bangladeshi IT company with WhatsApp chat, reviews, and a very high above-fold CTA count (12), but no ESP.",
  conv=50, cart=25, eng=55, followup=60, ci=40,
  ev_conv="has_cart=True likely false-positive for a B2B IT company", ev_cart="product_count_visible=0",
  ev_eng="WhatsApp chat and reviews already present, cta_count_above_fold=12", ev_followup="no email capture form detected despite active chat",
  open_gap_count=1),
L(1261, "floridamoldtesters.com", "Floridamoldtesters", primary="Cart Recovery Opportunity", secondary="Follow-up Opportunity", confidence="medium",
  summary="US mold-testing service with an attached shop (2 products), both email and contact forms, and reviews already live, but no ESP.",
  conv=45, cart=45, eng=50, followup=55, ci=35,
  ev_conv="has_cart=True, no ESP", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="reviews present, cta_count_above_fold=6", ev_followup="has_email_form=True and has_contact_form=True but no ESP automation",
  open_gap_count=2),
L(1262, "tcmcindia.com", "Tcmcindia", primary="Follow-up Opportunity", confidence="low",
  summary="Indian coaching/consulting business with no ESP.",
  conv=40, cart=20, eng=35, followup=50, ci=30,
  ev_conv="has_cart=True likely false-positive for a coaching/consulting business", ev_cart="product_count_visible=0",
  ev_eng="generic popup only, cta_count_above_fold=2", ev_followup="has_email_form=True but no ESP automation",
  open_gap_count=1),
L(1263, "masterfulsips.co.uk", "Masterfulsips", primary="Cart Recovery Opportunity", secondary="Follow-up Opportunity", confidence="low",
  summary="UK wine-tasting/consulting business with booking already offered, but page copy includes apparent multi-niche theme-demo content ('Home Business Coach', 'Home Femininity Coach'), no ESP.",
  conv=35, cart=45, eng=40, followup=45, ci=25,
  ev_conv="has_cart=True, no ESP; page content includes apparent theme-demo boilerplate for unrelated niches", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="booking already offered, cta_count_above_fold=5", ev_followup="has_email_form=True and has_contact_form=True but no ESP automation",
  open_gap_count=2),
L(1264, "mozheledu.com", "Mozheledu", primary="Follow-up Opportunity", confidence="low",
  summary="Omani online education/exam-prep platform with no lead-capture form or ESP.",
  conv=40, cart=20, eng=35, followup=50, ci=30,
  ev_conv="has_cart=True likely false-positive for an education platform", ev_cart="product_count_visible=0",
  ev_eng="generic popup only, no chat/reviews", ev_followup="no email or contact form detected for a course-enrollment business",
  open_gap_count=1),
L(1265, "cathyrockwood.com", "Cathyrockwood", primary="Cart Recovery Opportunity", secondary="Follow-up Opportunity", confidence="low",
  summary="Canadian fitness personal brand with an attached shop and donations page, product_count_visible=0 suggests thin page fetched, no ESP.",
  conv=40, cart=55, eng=35, followup=45, ci=30,
  ev_conv="has_cart=True, no ESP", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="generic popup only, no chat/reviews", ev_followup="has_email_form=True but no ESP automation",
  open_gap_count=2),
L(1266, "avapilates.com", "Avapilates", primary="Insufficient Data", confidence="high",
  summary="Page returns 'Access Denied!' — no content retrievable.",
  conv=50, cart=50, eng=50, followup=50, ci=50,
  ev_conv="access denied error", ev_cart="has_cart=False (undetermined)",
  ev_eng="no signals extractable — access denied", ev_followup="no signals extractable — access denied",
  open_gap_count=0, disqualifier="page returns 'Access Denied' — cannot assess"),
L(1267, "dorismartinez.cz", "Dorismartinez", primary="Not a Good Fit", confidence="medium",
  summary="Czech Latin-dance instructor/choreographer already running Mailchimp ESP.",
  conv=25, cart=20, eng=30, followup=20, ci=30,
  ev_conv="has_cart=True likely false-positive for a solo dance-instruction business", ev_cart="has_esp_tag=mailchimp",
  ev_eng="no chat/reviews", ev_followup="email capture and ESP already wired together",
  open_gap_count=1, disqualifier="already has ESP in place"),
L(1268, "tourinrabat.com", "Tourinrabat", primary="Not a Good Fit", confidence="medium",
  summary="Moroccan tour operator already running Mailchimp ESP with booking and reviews.",
  conv=20, cart=20, eng=30, followup=15, ci=25,
  ev_conv="Mailchimp ESP already live", ev_cart="has_esp_tag=mailchimp",
  ev_eng="booking and reviews already present, cta_count_above_fold=7", ev_followup="email capture and ESP already wired together",
  open_gap_count=1, disqualifier="already has ESP + booking + reviews stack in place"),
L(1269, "tesimpots.com", "Tesimpots", primary="Follow-up Opportunity", confidence="medium",
  summary="Quebec tax-preparation service with reviews already live but no lead-capture form or ESP.",
  conv=45, cart=20, eng=40, followup=55, ci=35,
  ev_conv="has_cart=True likely false-positive for a tax-services business", ev_cart="product_count_visible=0",
  ev_eng="reviews present", ev_followup="no email or contact form detected for a tax-filing services business",
  open_gap_count=1),
L(1270, "lettucesell.com", "Lettucesell", primary="Cart Recovery Opportunity", secondary="Follow-up Opportunity", confidence="medium",
  summary="Consignment/resale marketplace with WhatsApp chat, both email and contact forms, and reviews already live, but no ESP.",
  conv=45, cart=55, eng=50, followup=55, ci=35,
  ev_conv="has_cart=True, no ESP", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="WhatsApp chat and reviews already present, cta_count_above_fold=4", ev_followup="has_email_form=True and has_contact_form=True but no ESP automation",
  open_gap_count=2),
L(1271, "360configurator.ro", "360Configurator", primary="Follow-up Opportunity", confidence="low",
  summary="Romanian B2B architecture/structures configurator platform with no lead-capture form or ESP detected.",
  conv=35, cart=20, eng=30, followup=45, ci=25,
  ev_conv="has_cart=False — B2B configurator/design platform", ev_cart="has_cart=False",
  ev_eng="no chat/reviews/popup, content is thin", ev_followup="no email or contact form detected",
  open_gap_count=1),
L(1272, "vistarentacar.me", "Vistarentacar", primary="Not a Good Fit", confidence="medium",
  summary="Montenegrin car-rental business already running Mailchimp ESP with reviews.",
  conv=25, cart=20, eng=30, followup=20, ci=30,
  ev_conv="has_cart=True likely false-positive for a car-rental business", ev_cart="has_esp_tag=mailchimp",
  ev_eng="reviews present, cta_count_above_fold=4", ev_followup="email capture and ESP already wired together",
  open_gap_count=1, disqualifier="already has ESP + reviews stack in place"),
L(1273, "pmrepairs.co.uk", "Pmrepairs", primary="Follow-up Opportunity", confidence="low",
  summary="UK computer/IT repair service with an email form but no ESP.",
  conv=40, cart=20, eng=30, followup=50, ci=30,
  ev_conv="has_cart=True likely false-positive for a repair services business", ev_cart="product_count_visible=0",
  ev_eng="no chat/reviews/popup", ev_followup="has_email_form=True but no ESP automation",
  open_gap_count=1),
L(1274, "puddlemagazine.co.uk", "Puddlemagazine", primary="Follow-up Opportunity", confidence="low",
  summary="UK local-business directory/listings magazine with no lead-capture form or ESP detected.",
  conv=35, cart=20, eng=30, followup=40, ci=25,
  ev_conv="has_cart=False — listings/directory platform, not e-commerce", ev_cart="has_cart=False",
  ev_eng="no chat/reviews/popup", ev_followup="no email or contact form detected",
  open_gap_count=1),
L(1275, "rollinghillspse.com", "Rollinghillspse", primary="Follow-up Opportunity", confidence="medium",
  summary="US fleet/vehicle-equipment upfitting B2B business (multiple brand partnerships) with an email form but no ESP.",
  conv=45, cart=20, eng=35, followup=55, ci=35,
  ev_conv="has_cart=True likely false-positive for a B2B upfitting business", ev_cart="product_count_visible=0",
  ev_eng="generic popup only, no chat/reviews", ev_followup="has_email_form=True but no ESP automation",
  open_gap_count=1),
L(1277, "gongbad.dk", "Gongbad", primary="Follow-up Opportunity", secondary="Cart Recovery Opportunity", confidence="low",
  summary="Danish sound-bath wellness studio with both email and contact forms and a booking-driven business model, but no ESP.",
  conv=40, cart=40, eng=35, followup=50, ci=30,
  ev_conv="has_cart=True but this is a booking-driven wellness service", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="no chat/reviews/popup", ev_followup="has_email_form=True and has_contact_form=True but no ESP automation for session bookings",
  open_gap_count=2),
L(1278, "www.carclassrent.com", "Carclassrent", primary="Cart Recovery Opportunity", secondary="Follow-up Opportunity", confidence="low",
  summary="Italian car-rental business with WhatsApp chat and both email and contact forms, but no ESP.",
  conv=40, cart=55, eng=45, followup=45, ci=30,
  ev_conv="has_cart=True, no ESP", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="WhatsApp chat present but no reviews", ev_followup="has_email_form=True and has_contact_form=True but no ESP automation",
  open_gap_count=2),
L(1280, "cheresteabuftea.ro", "Cheresteabuftea", primary="Cart Recovery Opportunity", secondary="Customer Engagement Opportunity", confidence="low",
  summary="Romanian custom-wood-products B2B WooCommerce store (9 products) with no ESP.",
  conv=40, cart=55, eng=30, followup=40, ci=30,
  ev_conv="has_cart=True, no ESP", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="generic popup only, no chat/reviews", ev_followup="no email capture form detected",
  open_gap_count=2),
L(1281, "newagestudio.hu", "Newagestudio", primary="Follow-up Opportunity", confidence="low",
  summary="Hungarian hair-extension/microblading training academy with an email form but no ESP.",
  conv=40, cart=20, eng=35, followup=50, ci=30,
  ev_conv="has_cart=True likely false-positive for a training academy", ev_cart="product_count_visible=0",
  ev_eng="no chat/reviews/popup", ev_followup="has_email_form=True but no ESP automation",
  open_gap_count=1),
L(1282, "aircoserviceslotman.nl", "Aircoserviceslotman", primary="Follow-up Opportunity", confidence="low",
  summary="Dutch AC/heat-pump installer/repair service with WhatsApp chat but no lead-capture form or ESP.",
  conv=40, cart=20, eng=40, followup=50, ci=30,
  ev_conv="has_cart=True likely false-positive for an installer/repair service", ev_cart="product_count_visible=0",
  ev_eng="WhatsApp chat already present", ev_followup="no email capture form detected despite active chat channel",
  open_gap_count=1),
L(1287, "oomvetkoek.co.za", "Oomvetkoek", primary="Cart Recovery Opportunity", secondary="Customer Engagement Opportunity", confidence="low",
  summary="South African restaurant (vetkoek) WooCommerce ordering site, product_count_visible=0 suggests thin page fetched.",
  conv=40, cart=55, eng=30, followup=30, ci=25,
  ev_conv="has_cart=True, no ESP", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="generic popup only, no chat/reviews", ev_followup="no email capture form detected",
  open_gap_count=2),
L(1288, "dermaprivee.com", "Dermaprivee", primary="Follow-up Opportunity", confidence="medium",
  summary="German aesthetic/dermatology clinic (appointment-booking model) with reviews already live but no lead-capture form or ESP.",
  conv=45, cart=20, eng=45, followup=55, ci=35,
  ev_conv="has_cart=True likely false-positive for a clinical aesthetics practice", ev_cart="product_count_visible=0",
  ev_eng="reviews present", ev_followup="no email or contact form detected for a booking-driven clinic",
  open_gap_count=1),
L(1289, "graciousevents.co.nz", "Graciousevents", primary="Cart Recovery Opportunity", secondary="Follow-up Opportunity", confidence="low",
  summary="New Zealand event-planning business with booking already offered but no email-capture form or ESP.",
  conv=40, cart=45, eng=40, followup=45, ci=30,
  ev_conv="has_cart=True, no ESP", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="booking already offered, cta_count_above_fold=4", ev_followup="no email capture form detected despite active booking flow",
  open_gap_count=2),
L(1290, "ncmsllabs.com", "Ncmsllabs", primary="Not a Good Fit", confidence="medium",
  summary="Indian testing-labs B2B business already running Mailchimp ESP.",
  conv=25, cart=20, eng=30, followup=20, ci=30,
  ev_conv="has_cart=True likely false-positive for a B2B testing-labs business", ev_cart="has_esp_tag=mailchimp",
  ev_eng="cta_count_above_fold=4", ev_followup="email capture and ESP already wired together",
  open_gap_count=1, disqualifier="already has ESP in place"),
L(1291, "partygopacks.ca", "Partygopacks", primary="Cart Recovery Opportunity", secondary="Customer Engagement Opportunity", confidence="low",
  summary="Canadian party-activities rental business (laser tag, photo booths) WooCommerce store (6 products) with no ESP.",
  conv=40, cart=55, eng=40, followup=35, ci=30,
  ev_conv="has_cart=True, no ESP", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="generic popup only, no chat/reviews, cta_count_above_fold=2", ev_followup="no email capture form detected",
  open_gap_count=2),
L(1292, "creative-side.ro", "Creative-Side", primary="Follow-up Opportunity", confidence="medium",
  summary="Romanian web-design/development B2B agency with WhatsApp chat and reviews already live, but no ESP.",
  conv=45, cart=25, eng=50, followup=60, ci=35,
  ev_conv="has_cart=True likely false-positive for a B2B design agency", ev_cart="product_count_visible=0",
  ev_eng="WhatsApp chat and reviews already present", ev_followup="has_email_form=True and has_contact_form=True but no ESP automation",
  open_gap_count=1),
L(1293, "ringobeauty.co.jp", "Ringobeauty", primary="Cart Recovery Opportunity", secondary="Follow-up Opportunity", confidence="low",
  summary="Japanese beauty-equipment manufacturer B2B WooCommerce store, product_count_visible=0 suggests thin page fetched.",
  conv=40, cart=55, eng=30, followup=45, ci=30,
  ev_conv="has_cart=True, no ESP", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="generic popup only, no chat/reviews", ev_followup="has_email_form=True but no ESP automation",
  open_gap_count=2),
L(1294, "bonfieldeventpark.ca", "Bonfieldeventpark", primary="Cart Recovery Opportunity", secondary="Customer Engagement Opportunity", confidence="low",
  summary="Canadian event-park venue WooCommerce site (12 products) with no capture form or ESP.",
  conv=40, cart=55, eng=30, followup=30, ci=25,
  ev_conv="has_cart=True, no ESP", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="no chat/reviews/popup, cta_count_above_fold=2", ev_followup="no email capture form detected",
  open_gap_count=2),
L(1295, "makadija.com", "Makadija", primary="Not a Good Fit", confidence="medium",
  summary="Tunisian gourmet-biscuits WooCommerce store already running Mailchimp ESP.",
  conv=25, cart=20, eng=30, followup=20, ci=30,
  ev_conv="Mailchimp ESP already live", ev_cart="has_esp_tag=mailchimp",
  ev_eng="no chat/reviews", ev_followup="email capture and ESP already wired together",
  open_gap_count=1, disqualifier="already has ESP in place"),
L(1296, "laneveritallena.com", "Laneveritallena", primary="Follow-up Opportunity", confidence="low",
  summary="Spanish (Tenerife) weekly meal-delivery service, currently in a pre-launch waitlist phase ('subscribe to be notified'), with reviews already live but no ESP.",
  conv=40, cart=40, eng=40, followup=45, ci=30,
  ev_conv="has_cart=True, no ESP; service appears to be in a pre-launch waitlist phase", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="reviews present, cta_count_above_fold=3", ev_followup="has_email_form=True (waitlist signup) but no ESP automation",
  open_gap_count=2),
L(1297, "wodomat.pl", "Wodomat", primary="Cart Recovery Opportunity", secondary="Customer Engagement Opportunity", confidence="low",
  summary="Polish water-vending-machine business (B2B partner model) with no capture form or ESP.",
  conv=35, cart=50, eng=30, followup=30, ci=25,
  ev_conv="has_cart=True, no ESP", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="no chat/reviews/popup", ev_followup="no email capture form detected",
  open_gap_count=2),
L(1298, "saidivyadesigns.com", "Saidivyadesigns", primary="Cart Recovery Opportunity", secondary="Customer Engagement Opportunity", confidence="low",
  summary="Indian blouse-design WooCommerce store (21 products, very large sub-catalog) with no capture form or ESP.",
  conv=40, cart=60, eng=35, followup=30, ci=30,
  ev_conv="has_cart=True, no ESP, large sub-catalog of designs", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="no chat/reviews/popup", ev_followup="no email capture form detected",
  open_gap_count=2),
]

n = append_results(RESULTS)
print(f"appended {n} rows (chunk_012)")
