import sys
sys.path.insert(0, ".")
from layer3_write import append_results


def L(lead_id, domain, business_name, primary, confidence, summary,
      conv, cart, eng, followup, ci, ev_conv, ev_cart, ev_eng, ev_followup,
      open_gap_count, secondary=None, disqualifier=None):
    return (lead_id, domain, business_name, primary, secondary, confidence, summary,
            conv, cart, eng, followup, ci, ev_conv, ev_cart, ev_eng, ev_followup,
            open_gap_count, disqualifier)


RESULTS = [
L(1527, "www.slszonwering.nl", "Slszonwering", primary="Cart Recovery Opportunity", secondary="Follow-up Opportunity", confidence="low",
  summary="Dutch window-shading/awnings retailer with reviews already live but no capture form or ESP.",
  conv=40, cart=55, eng=35, followup=40, ci=30,
  ev_conv="has_cart=True, no ESP", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="reviews present but no chat/popup", ev_followup="no email capture form detected",
  open_gap_count=2),
L(1528, "www.negpower.sg", "Negpower", primary="Not a Good Fit", confidence="medium",
  summary="Singaporean EV-charger B2B manufacturer already running Mailchimp ESP with WhatsApp chat and reviews.",
  conv=25, cart=20, eng=30, followup=20, ci=30,
  ev_conv="Mailchimp ESP already live", ev_cart="has_esp_tag=mailchimp",
  ev_eng="WhatsApp chat and reviews already present, cta_count_above_fold=2", ev_followup="email capture and ESP already wired together",
  open_gap_count=1, disqualifier="already has ESP + chat + reviews stack in place"),
L(1529, "chamundafabchem.com", "Chamundafabchem", primary="Follow-up Opportunity", confidence="low",
  summary="Indian pharma/chemical process-machinery B2B manufacturer with WhatsApp chat but no email-capture form or ESP.",
  conv=35, cart=20, eng=35, followup=45, ci=25,
  ev_conv="has_cart=False — B2B industrial equipment manufacturer", ev_cart="has_cart=False",
  ev_eng="WhatsApp chat already present", ev_followup="no email capture form detected despite active chat channel",
  open_gap_count=1),
L(1530, "haingkw.com", "Haingkw", primary="Not a Good Fit", confidence="low",
  summary="Multi-country accessories retailer already running Mailchimp ESP, though the fetched page includes unconfigured theme placeholder text.",
  conv=25, cart=20, eng=25, followup=20, ci=25,
  ev_conv="has_cart=True likely false-positive; page includes 'ADD ANYTHING HERE' unconfigured theme placeholder", ev_cart="has_esp_tag=mailchimp",
  ev_eng="cta_count_above_fold=1", ev_followup="email capture and ESP already wired together",
  open_gap_count=1, disqualifier="already has ESP in place; page content appears partly unconfigured"),
L(1531, "jlcuisine.com", "Jlcuisine", primary="Follow-up Opportunity", confidence="low",
  summary="US catering business with both email and contact forms but no ESP.",
  conv=40, cart=20, eng=25, followup=50, ci=30,
  ev_conv="has_cart=True likely false-positive for a catering services business", ev_cart="product_count_visible=0",
  ev_eng="no chat/reviews/popup", ev_followup="has_email_form=True and has_contact_form=True but no ESP automation",
  open_gap_count=1),
L(1532, "dashvisors.com", "Dashvisors", primary="Follow-up Opportunity", confidence="low",
  summary="B2B business-intelligence/dashboards SaaS with no lead-capture form or ESP.",
  conv=35, cart=20, eng=25, followup=45, ci=25,
  ev_conv="has_cart=True likely false-positive for a B2B SaaS product", ev_cart="product_count_visible=1",
  ev_eng="cta_count_above_fold=3", ev_followup="no email or contact form detected",
  open_gap_count=1),
L(1533, "renhealthqare.com", "Renhealthqare", primary="Cart Recovery Opportunity", secondary="Follow-up Opportunity", confidence="low",
  summary="Dialysis/medical-supplies B2B WooCommerce store (8 products) with reviews already live but no ESP.",
  conv=40, cart=55, eng=35, followup=40, ci=30,
  ev_conv="has_cart=True, no ESP", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="reviews present but no chat", ev_followup="no email capture form detected",
  open_gap_count=2),
L(1534, "www.pgipro.com", "Pgipro", primary="Cart Recovery Opportunity", secondary="Follow-up Opportunity", confidence="low",
  summary="US promotional-products B2B manufacturer (est. 1979, 42 products, 15 brands) with Tidio chat but no ESP.",
  conv=40, cart=55, eng=40, followup=45, ci=30,
  ev_conv="has_cart=True, no ESP", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="Tidio chat already present", ev_followup="no email capture form detected despite active chat",
  open_gap_count=2),
L(1535, "portalprint.co.uk", "Portalprint", primary="Cart Recovery Opportunity", secondary="Follow-up Opportunity", confidence="medium",
  summary="UK print shop WooCommerce store (6 products) with both email and contact forms, booking, and reviews already live, but no ESP.",
  conv=45, cart=55, eng=45, followup=50, ci=35,
  ev_conv="has_cart=True, no ESP", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="booking and reviews already present", ev_followup="has_email_form=True and has_contact_form=True but no ESP automation",
  open_gap_count=2),
L(1536, "bookyacht.in", "Bookyacht", primary="Not a Good Fit", confidence="medium",
  summary="Indian yacht-booking business already running Mailchimp ESP with reviews and a very high above-fold CTA count (11).",
  conv=20, cart=15, eng=30, followup=15, ci=25,
  ev_conv="has_cart=True likely false-positive for a booking business", ev_cart="has_esp_tag=mailchimp",
  ev_eng="reviews present, cta_count_above_fold=11 (very high)", ev_followup="email capture and ESP already wired together",
  open_gap_count=1, disqualifier="already has ESP + reviews + strong CTA presence in place"),
L(1537, "namooverseas.in", "Namooverseas", primary="Cart Recovery Opportunity", secondary="Follow-up Opportunity", confidence="low",
  summary="Indian WooCommerce store (5 products) whose fetched copy is mostly unrendered WordPress module-import JSON boilerplate, no ESP.",
  conv=35, cart=50, eng=25, followup=40, ci=25,
  ev_conv="has_cart=True, no ESP; page content largely unrendered technical boilerplate", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="cta_count_above_fold=2", ev_followup="has_email_form=True and has_contact_form=True but no ESP automation",
  open_gap_count=2),
L(1538, "www.machiaccesorioshg.com.co", "Machiaccesorioshg", primary="Not a Good Fit", confidence="medium",
  summary="Colombian meat-processing/scale-equipment B2B retailer already running Mailchimp ESP with WhatsApp chat and reviews.",
  conv=25, cart=20, eng=30, followup=20, ci=30,
  ev_conv="Mailchimp ESP already live", ev_cart="has_esp_tag=mailchimp",
  ev_eng="WhatsApp chat and reviews already present", ev_followup="email capture and ESP already wired together",
  open_gap_count=1, disqualifier="already has ESP + chat + reviews stack in place"),
L(1540, "www.greentechusa.us", "Greentechusa", primary="Insufficient Data", confidence="high",
  summary="Site displays a PHP/MySQL extension misconfiguration error — WordPress cannot run, no usable content retrievable.",
  conv=50, cart=50, eng=50, followup=50, ci=50,
  ev_conv="PHP/MySQL extension misconfiguration error", ev_cart="has_cart=False (undetermined)",
  ev_eng="no signals extractable — site is broken", ev_followup="no signals extractable — site is broken",
  open_gap_count=0, disqualifier="site returns a PHP/MySQL configuration error — cannot assess"),
L(1541, "geol.by", "Geol", primary="Cart Recovery Opportunity", secondary="Follow-up Opportunity", confidence="low",
  summary="Belarusian medical-refrigeration-equipment B2B manufacturer WooCommerce store (12 products) with WhatsApp chat but no ESP.",
  conv=40, cart=55, eng=40, followup=45, ci=30,
  ev_conv="has_cart=True, no ESP", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="WhatsApp chat already present", ev_followup="no email capture form detected despite active chat",
  open_gap_count=2),
L(1542, "www.carlexit.com", "Carlexit", primary="Cart Recovery Opportunity", secondary="Customer Engagement Opportunity", confidence="low",
  summary="Server-hardware/components B2B marketplace with a quote-list feature and a high above-fold CTA count (9), but no capture form or ESP.",
  conv=40, cart=55, eng=40, followup=30, ci=30,
  ev_conv="has_cart=True, no ESP, cta_count_above_fold=9", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="generic popup only, no chat/reviews despite high above-fold CTA count", ev_followup="no email capture form detected",
  open_gap_count=2),
L(1543, "agnsceylon.com", "Agnsceylon", primary="Cart Recovery Opportunity", secondary="Follow-up Opportunity", confidence="low",
  summary="Sri Lankan retailer WooCommerce store (5 products) with WhatsApp chat but no ESP.",
  conv=40, cart=55, eng=40, followup=40, ci=30,
  ev_conv="has_cart=True, no ESP", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="WhatsApp chat already present, cta_count_above_fold=3", ev_followup="no email capture form detected despite active chat",
  open_gap_count=2),
L(1544, "cargate-eg.com", "Cargate-Eg", primary="Cart Recovery Opportunity", secondary="Follow-up Opportunity", confidence="low",
  summary="Egyptian luxury/used car dealer marketplace with reviews already live but no ESP.",
  conv=40, cart=55, eng=35, followup=45, ci=30,
  ev_conv="has_cart=True, no ESP", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="reviews present, cta_count_above_fold=2", ev_followup="has_email_form=True but no ESP automation",
  open_gap_count=2),
L(1545, "tastextiles.com", "Tastextiles", primary="Cart Recovery Opportunity", secondary="Follow-up Opportunity", confidence="low",
  summary="Bangladeshi apparel manufacturer/exporter B2B WooCommerce store (26 products) with WhatsApp chat but no ESP.",
  conv=40, cart=55, eng=40, followup=45, ci=30,
  ev_conv="has_cart=True, no ESP", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="WhatsApp chat already present, cta_count_above_fold=1", ev_followup="has_email_form=True but no ESP automation",
  open_gap_count=2),
L(1546, "alaminvet.com", "Alaminvet", primary="Cart Recovery Opportunity", secondary="Follow-up Opportunity", confidence="low",
  summary="Syrian veterinary pharmaceutical B2B WooCommerce store (26 products) with WhatsApp chat but no ESP.",
  conv=35, cart=55, eng=40, followup=40, ci=30,
  ev_conv="has_cart=True, no ESP", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="WhatsApp chat already present, cta_count_above_fold=1", ev_followup="no email capture form detected despite active chat",
  open_gap_count=2),
L(1547, "www.apsconceptlighting.com", "Apsconceptlighting", primary="Cart Recovery Opportunity", secondary="Follow-up Opportunity", confidence="low",
  summary="LED lighting solutions B2B manufacturer, product_count_visible=0 suggests thin page fetched, no ESP.",
  conv=35, cart=50, eng=25, followup=40, ci=25,
  ev_conv="has_cart=True, no ESP", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="no chat/reviews/popup, cta_count_above_fold=3", ev_followup="has_email_form=True but no ESP automation",
  open_gap_count=2),
L(1548, "nicaksu.com", "Nicaksu", primary="Cart Recovery Opportunity", secondary="Follow-up Opportunity", confidence="low",
  summary="Turkish B2B manufacturer WooCommerce store (11 products) with WhatsApp chat and reviews already live but no ESP.",
  conv=40, cart=55, eng=45, followup=45, ci=30,
  ev_conv="has_cart=True, no ESP", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="WhatsApp chat and reviews already present, cta_count_above_fold=4", ev_followup="has_email_form=True and has_contact_form=True but no ESP automation",
  open_gap_count=2),
L(1549, "www.hadaitleatherwayind.com", "Hadaitleatherwayind", primary="Cart Recovery Opportunity", secondary="Customer Engagement Opportunity", confidence="low",
  summary="Pakistani leather-sportswear manufacturer/exporter B2B WooCommerce store (20 products) with no capture form or ESP.",
  conv=35, cart=55, eng=25, followup=30, ci=25,
  ev_conv="has_cart=True, no ESP", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="no chat/reviews/popup, cta_count_above_fold=1", ev_followup="no email capture form detected",
  open_gap_count=2),
L(1550, "sd-spring.com", "Sd-Spring", primary="Insufficient Data", confidence="low",
  summary="Domain resolved but page_text is empty and platform is unknown.",
  conv=50, cart=50, eng=50, followup=50, ci=50,
  ev_conv="page_text empty", ev_cart="has_cart=False (undetermined)",
  ev_eng="no signals extractable", ev_followup="no signals extractable",
  open_gap_count=0, disqualifier="empty/undetermined signals — cannot assess"),
L(1551, "flavoursofchennai.com", "Flavoursofchennai", primary="Not a Good Fit", confidence="medium",
  summary="Wholesale grocery retailer (28 products) already running Mailchimp ESP with reviews and an active promo.",
  conv=25, cart=20, eng=30, followup=20, ci=30,
  ev_conv="Mailchimp ESP already live, active promo", ev_cart="has_esp_tag=mailchimp",
  ev_eng="reviews present, cta_count_above_fold=3", ev_followup="email capture and ESP already wired together",
  open_gap_count=1, disqualifier="already has ESP + reviews + promo in place"),
L(1552, "conason.com", "Conason", primary="Multi-Opportunity", confidence="medium",
  summary="Chinese hair-dryer OEM/ODM B2B manufacturer with both email and contact forms and a very high above-fold CTA count (9), but no ESP.",
  conv=50, cart=55, eng=45, followup=55, ci=35,
  ev_conv="has_cart=True, no ESP, cta_count_above_fold=9 (very high)", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="strong above-fold CTA presence, no chat/reviews", ev_followup="has_email_form=True and has_contact_form=True but no ESP automation",
  open_gap_count=2),
L(1553, "ipssac.com", "Ipssac", primary="Insufficient Data", confidence="low",
  summary="Domain resolved but page_text is empty and platform is unknown.",
  conv=50, cart=50, eng=50, followup=50, ci=50,
  ev_conv="page_text empty", ev_cart="has_cart=False (undetermined)",
  ev_eng="no signals extractable", ev_followup="no signals extractable",
  open_gap_count=0, disqualifier="empty/undetermined signals — cannot assess"),
L(1554, "fardantrading.com", "Fardantrading", primary="Follow-up Opportunity", secondary="Cart Recovery Opportunity", confidence="low",
  summary="Dubai trading company B2B (12 products) with booking already offered but no email-capture form or ESP.",
  conv=40, cart=45, eng=35, followup=45, ci=30,
  ev_conv="has_cart=True, no ESP", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="booking already offered, cta_count_above_fold=4", ev_followup="no email capture form detected despite active booking flow",
  open_gap_count=2),
L(1555, "nowcustomboxes.com", "Nowcustomboxes", primary="Insufficient Data", confidence="high",
  summary="Page served an obfuscated JS-based verification wall — no real content retrievable.",
  conv=50, cart=50, eng=50, followup=50, ci=50,
  ev_conv="bot-check/obfuscated verification page", ev_cart="has_cart=False (undetermined)",
  ev_eng="no signals extractable — verification wall", ev_followup="no signals extractable — verification wall",
  open_gap_count=0, disqualifier="anti-bot verification page — cannot assess real content"),
L(1556, "spw-c.com", "Spw-C", primary="Cart Recovery Opportunity", secondary="Customer Engagement Opportunity", confidence="low",
  summary="Industrial-seals B2B manufacturer WooCommerce store (10 products) with no capture form or ESP.",
  conv=35, cart=50, eng=25, followup=30, ci=25,
  ev_conv="has_cart=True, no ESP", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="no chat/reviews/popup", ev_followup="no email capture form detected",
  open_gap_count=2),
L(1557, "toribaintl.com", "Toribaintl", primary="Cart Recovery Opportunity", secondary="Customer Engagement Opportunity", confidence="low",
  summary="Pakistani sportswear manufacturer/exporter B2B WooCommerce store (8 products) with no capture form or ESP.",
  conv=35, cart=50, eng=25, followup=30, ci=25,
  ev_conv="has_cart=True, no ESP", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="generic popup only, no chat/reviews, cta_count_above_fold=1", ev_followup="no email capture form detected",
  open_gap_count=2),
L(1558, "tuz-info.org", "Tuz-Info", primary="Follow-up Opportunity", confidence="low",
  summary="Albanian wastewater-treatment B2B business with no lead-capture form or ESP.",
  conv=35, cart=20, eng=25, followup=45, ci=25,
  ev_conv="has_cart=True likely false-positive for a B2B environmental-services business", ev_cart="product_count_visible=0",
  ev_eng="no chat/reviews/popup", ev_followup="no email or contact form detected",
  open_gap_count=1),
L(1559, "simonshardware.com", "Simonshardware", primary="Cart Recovery Opportunity", secondary="Customer Engagement Opportunity", confidence="low",
  summary="US access-control/security-hardware B2B business, product_count_visible=0 suggests thin page fetched, no ESP.",
  conv=35, cart=50, eng=25, followup=30, ci=25,
  ev_conv="has_cart=True, no ESP", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="generic popup only, no chat/reviews, cta_count_above_fold=3", ev_followup="no email capture form detected",
  open_gap_count=2),
L(1560, "delcomsac.com", "Delcomsac", primary="Cart Recovery Opportunity", secondary="Follow-up Opportunity", confidence="low",
  summary="Peruvian electronics/computer-accessories B2B distributor with both email and contact forms but no ESP.",
  conv=35, cart=50, eng=25, followup=40, ci=25,
  ev_conv="has_cart=True, no ESP", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="no chat/reviews/popup", ev_followup="has_email_form=True and has_contact_form=True but no ESP automation",
  open_gap_count=2),
L(1561, "shangshanpetro.com", "Shangshanpetro", primary="Insufficient Data", confidence="low",
  summary="Domain resolved but page_text is empty and platform is unknown.",
  conv=50, cart=50, eng=50, followup=50, ci=50,
  ev_conv="page_text empty", ev_cart="has_cart=False (undetermined)",
  ev_eng="no signals extractable", ev_followup="no signals extractable",
  open_gap_count=0, disqualifier="empty/undetermined signals — cannot assess"),
L(1563, "www.cndwmn.com", "Cndwmn", primary="Cart Recovery Opportunity", secondary="Customer Engagement Opportunity", confidence="low",
  summary="Chinese WooCommerce store (49 products) with reviews already live, but page copy includes anti-copy/right-click-blocking JS, no ESP.",
  conv=35, cart=55, eng=35, followup=30, ci=25,
  ev_conv="has_cart=True, no ESP; page uses anti-copy scripting, content quality uncertain", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="reviews present", ev_followup="no email capture form detected",
  open_gap_count=2),
L(1564, "signatureledlighting.com", "Signatureledlighting", primary="Insufficient Data", confidence="low",
  summary="Domain resolved but page_text is empty and platform is unknown.",
  conv=50, cart=50, eng=50, followup=50, ci=50,
  ev_conv="page_text empty", ev_cart="has_cart=False (undetermined)",
  ev_eng="no signals extractable", ev_followup="no signals extractable",
  open_gap_count=0, disqualifier="empty/undetermined signals — cannot assess"),
L(1565, "www.acetexgroup.com", "Acetexgroup", primary="Not a Good Fit", confidence="medium",
  summary="B2B business (2 products visible) already running Klaviyo ESP.",
  conv=25, cart=20, eng=25, followup=20, ci=30,
  ev_conv="Klaviyo ESP already live", ev_cart="has_esp_tag=klaviyo",
  ev_eng="no chat/reviews", ev_followup="email capture and Klaviyo ESP already wired together",
  open_gap_count=1, disqualifier="already has ESP in place"),
L(1566, "vyoguatemala.com", "Vyoguatemala", primary="Cart Recovery Opportunity", secondary="Follow-up Opportunity", confidence="low",
  summary="Guatemalan agricultural-equipment B2B distributor with WhatsApp chat but no ESP.",
  conv=35, cart=50, eng=35, followup=40, ci=25,
  ev_conv="has_cart=True, no ESP", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="WhatsApp chat already present", ev_followup="no email capture form detected despite active chat",
  open_gap_count=2),
L(1567, "acord-line.ro", "Acord-Line", primary="Cart Recovery Opportunity", secondary="Customer Engagement Opportunity", confidence="low",
  summary="Romanian WooCommerce store whose fetched copy is mostly obfuscated JS, no ESP.",
  conv=30, cart=50, eng=25, followup=25, ci=20,
  ev_conv="has_cart=True, no ESP; page content is mostly obfuscated JS", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="no chat/reviews/popup", ev_followup="no email capture form detected",
  open_gap_count=2),
L(1568, "debiengineering.com", "Debiengineering", primary="Cart Recovery Opportunity", secondary="Customer Engagement Opportunity", confidence="low",
  summary="Ethiopian automotive spare-parts B2B WooCommerce store (11 products) with no capture form or ESP.",
  conv=35, cart=50, eng=25, followup=30, ci=25,
  ev_conv="has_cart=True, no ESP", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="generic popup only, no chat/reviews, cta_count_above_fold=2", ev_followup="no email capture form detected",
  open_gap_count=2),
L(1569, "gpolarol.com", "Gpolarol", primary="Cart Recovery Opportunity", secondary="Follow-up Opportunity", confidence="low",
  summary="Brazilian DPPO/DPPC safety-equipment B2B WooCommerce store with WhatsApp chat but no ESP.",
  conv=35, cart=50, eng=35, followup=40, ci=25,
  ev_conv="has_cart=True, no ESP", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="WhatsApp chat already present", ev_followup="has_email_form=True but no ESP automation",
  open_gap_count=2),
L(1570, "refix-dz.com", "Refix-Dz", primary="Follow-up Opportunity", confidence="low",
  summary="Algerian electrical-fittings B2B manufacturer with no lead-capture form or ESP.",
  conv=35, cart=20, eng=25, followup=45, ci=25,
  ev_conv="has_cart=True likely false-positive for a B2B manufacturer", ev_cart="product_count_visible=0",
  ev_eng="no chat/reviews/popup", ev_followup="no email or contact form detected",
  open_gap_count=1),
L(1571, "pbg.cr", "Pbg", primary="Cart Recovery Opportunity", secondary="Follow-up Opportunity", confidence="low",
  summary="Costa Rican distribution/trading B2B group with both email and contact forms but no ESP.",
  conv=35, cart=50, eng=25, followup=40, ci=25,
  ev_conv="has_cart=True, no ESP", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="no chat/reviews/popup", ev_followup="has_email_form=True and has_contact_form=True but no ESP automation",
  open_gap_count=2),
L(1572, "bondplandcorp.com", "Bondplandcorp", primary="Cart Recovery Opportunity", secondary="Customer Engagement Opportunity", confidence="low",
  summary="WooCommerce store whose fetched copy is mostly unrendered page-loader CSS boilerplate, no ESP.",
  conv=30, cart=50, eng=25, followup=25, ci=20,
  ev_conv="has_cart=True, no ESP; page content largely unrendered CSS boilerplate", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="no chat/reviews/popup", ev_followup="no email capture form detected",
  open_gap_count=2),
L(1573, "decoflow.co.za", "Decoflow", primary="Not a Good Fit", confidence="medium",
  summary="South African decor-rental business already running Mailchimp ESP with a very high above-fold CTA count (14).",
  conv=20, cart=15, eng=30, followup=15, ci=25,
  ev_conv="has_cart=True likely false-positive for a decor-rental business", ev_cart="has_esp_tag=mailchimp",
  ev_eng="cta_count_above_fold=14 (very high)", ev_followup="email capture and ESP already wired together",
  open_gap_count=1, disqualifier="already has ESP + strong CTA presence in place"),
L(1574, "sdhandling.com", "Sdhandling", primary="Follow-up Opportunity", secondary="Cart Recovery Opportunity", confidence="low",
  summary="UK industrial/oil-and-gas equipment B2B business with both email and contact forms, booking, and reviews already live, but no ESP.",
  conv=40, cart=40, eng=45, followup=50, ci=30,
  ev_conv="has_cart=True but this is a B2B industrial equipment business", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="booking and reviews already present", ev_followup="has_email_form=True and has_contact_form=True but no ESP automation",
  open_gap_count=2),
L(1575, "sunlightleisure.com", "Sunlightleisure", primary="Insufficient Data", confidence="low",
  summary="Domain resolved but page_text is empty and platform is unknown.",
  conv=50, cart=50, eng=50, followup=50, ci=50,
  ev_conv="page_text empty", ev_cart="has_cart=False (undetermined)",
  ev_eng="no signals extractable", ev_followup="no signals extractable",
  open_gap_count=0, disqualifier="empty/undetermined signals — cannot assess"),
L(1576, "srnorganizasyon.com", "Srnorganizasyon", primary="Follow-up Opportunity", confidence="low",
  summary="Turkish event/catering-equipment rental B2B business with booking and reviews already live, but no email-capture form or ESP.",
  conv=35, cart=25, eng=35, followup=45, ci=25,
  ev_conv="has_cart=True likely false-positive for an equipment-rental business", ev_cart="product_count_visible=0",
  ev_eng="booking and reviews already present", ev_followup="no email capture form detected despite active booking flow",
  open_gap_count=1),
L(1577, "ikzarsa.com", "Ikzarsa", primary="Cart Recovery Opportunity", secondary="Customer Engagement Opportunity", confidence="low",
  summary="Barber/razor-tools B2B manufacturer WooCommerce store (16 products) with no capture form or ESP.",
  conv=35, cart=50, eng=25, followup=30, ci=25,
  ev_conv="has_cart=True, no ESP", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="generic popup only, no chat/reviews", ev_followup="no email capture form detected",
  open_gap_count=2),
L(1578, "haatekala.com", "Haatekala", primary="Cart Recovery Opportunity", secondary="Follow-up Opportunity", confidence="low",
  summary="Nepalese handcrafted-goods manufacturer/exporter B2B WooCommerce store (20 products) with WhatsApp chat but no ESP.",
  conv=35, cart=55, eng=40, followup=40, ci=30,
  ev_conv="has_cart=True, no ESP", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="WhatsApp chat already present, cta_count_above_fold=4", ev_followup="no email capture form detected despite active chat",
  open_gap_count=2),
L(1579, "amazonicagroup.com", "Amazonicagroup", primary="Cart Recovery Opportunity", secondary="Follow-up Opportunity", confidence="low",
  summary="UK flooring B2B distributor (trade-account model) with both email and contact forms but no ESP.",
  conv=35, cart=50, eng=25, followup=40, ci=25,
  ev_conv="has_cart=True, no ESP", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="no chat/reviews/popup, cta_count_above_fold=3", ev_followup="has_email_form=True and has_contact_form=True but no ESP automation",
  open_gap_count=2),
L(1580, "vitavision.com.ar", "Vitavision", primary="Insufficient Data", confidence="high",
  summary="Site explicitly states 'COMING SOON' — not yet live.",
  conv=50, cart=50, eng=50, followup=50, ci=50,
  ev_conv="site explicitly not yet launched", ev_cart="has_cart=True flagged but site is not live",
  ev_eng="no real content to evaluate — placeholder page", ev_followup="no real content to evaluate — placeholder page",
  open_gap_count=0, disqualifier="site not live — 'coming soon' placeholder"),
L(1581, "evpro.com.my", "Evpro", primary="Follow-up Opportunity", secondary="Cart Recovery Opportunity", confidence="low",
  summary="Malaysian EV-charger installer/distributor B2B with both email and contact forms and booking already live, but no ESP.",
  conv=40, cart=40, eng=35, followup=50, ci=30,
  ev_conv="has_cart=True but this is a B2B installer/distributor business", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="booking already offered", ev_followup="has_email_form=True and has_contact_form=True but no ESP automation",
  open_gap_count=2),
L(1582, "almamachine.com", "Almamachine", primary="Insufficient Data", confidence="high",
  summary="Site displays a PHP fatal error (WP Rocket / Cloudflare plugin conflict) — no usable content retrievable.",
  conv=50, cart=50, eng=50, followup=50, ci=50,
  ev_conv="PHP fatal error page", ev_cart="has_cart=False (undetermined)",
  ev_eng="no signals extractable — site is broken", ev_followup="no signals extractable — site is broken",
  open_gap_count=0, disqualifier="site returns a PHP fatal error — cannot assess"),
L(1583, "dineshbolts.com", "Dineshbolts", primary="Not a Good Fit", confidence="medium",
  summary="Indian fasteners B2B manufacturer already running Mailchimp ESP with both email and contact forms.",
  conv=25, cart=20, eng=25, followup=20, ci=30,
  ev_conv="Mailchimp ESP already live", ev_cart="has_esp_tag=mailchimp",
  ev_eng="cta_count_above_fold=1", ev_followup="email capture and ESP already wired together",
  open_gap_count=1, disqualifier="already has ESP in place"),
]

n = append_results(RESULTS)
print(f"appended {n} rows (chunk_017)")
