import sys
sys.path.insert(0, ".")
from layer3_write import append_results

RESULTS = [
("639","skalasa.co.za","Skalasa","Follow-up Opportunity",None,"Low",
 "South African 100% vegan hair-care e-commerce brand.",
 10,30,40,50,50,
 "11 CTAs above the fold give a very clear path.","A Mailchimp ESP tag and popup are present.",
 "has_chat_widget is none across several hair-type categories.",
 "has_email_form is false -- no capture form was confirmed in the static markup, though a Mailchimp tag is loaded, suggesting one may exist dynamically.",0,None),
("640","indouvr.com","Indouvr","Follow-up Opportunity",None,"Medium",
 "Indian premium denim jeans brand.",
 40,40,25,60,50,
 "cta_count_above_fold is 0.","A popup script is present but has_esp_tag is none.",
 "has_chat_widget is none on a narrow denim-focused catalog.",
 "has_email_form is false, has_contact_form is false, has_esp_tag is none -- no capture mechanism.",1,None),
("644","autotani.com","Autotani","Follow-up Opportunity",None,"Low",
 "Albanian car-rental and towing service (Korce).",
 40,15,30,50,50,
 "cta_count_above_fold is 0; 'Rezervo Online' is a real CTA not counted.",
 "Not a real retail cart (rental business).","Rental fleet listing isn't a catalog; low relevance.",
 "has_email_form is false -- no capture form was confirmed in the static markup, though a Mailchimp tag is loaded, suggesting one may exist dynamically.",0,None),
("646","kokooutlet.lt","Kokooutlet","Customer Engagement Opportunity",None,"High",
 "Lithuanian furniture outlet e-commerce brand.",
 35,30,65,15,50,
 "cta_count_above_fold is 0; Lithuanian detector miss likely.","An Omnisend ESP tag and popup are present.",
 "has_chat_widget is none across a wide furniture catalog (sofas, beds, tables, chairs, wardrobes, mirrors, wall panels).",
 "has_email_form is true with an Omnisend ESP tag -- a capture mechanism exists.",0,None),
("647","roadkidzmotorparts.com","Roadkidzmotorparts","Customer Engagement Opportunity","Follow-up Opportunity","Medium",
 "Motorcycle parts and accessories e-commerce store.",
 40,40,65,60,50,
 "2 CTAs above the fold.","A popup script is present but has_esp_tag is none.",
 "has_chat_widget is none across a genuinely wide, technical catalog (disc/brake systems, engine oil, clutch parts) -- buyers likely need guidance matching the right part.",
 "has_email_form is false, has_contact_form is false, has_esp_tag is none -- no capture mechanism.",2,None),
("652","matkahobi.ee","Matkahobi","Cart Recovery Opportunity",None,"Low",
 "Estonian sauna-tent and mini-caravan rental/sales business.",
 40,40,30,20,50,
 "cta_count_above_fold is 0.","A popup script is present but has_esp_tag is none.",
 "has_chat_widget is none on a narrow niche catalog.","has_email_form is true (evidence: 'Email') -- a capture mechanism exists.",0,None),
("654","www.arabesqgifts.com","Arabesqgifts","Cart Recovery Opportunity",None,"Low",
 "Egyptian alabaster candle-holder and lighting e-commerce brand (Shopify).",
 40,30,40,15,50,
 "2 CTAs above the fold.","A Klaviyo ESP tag and popup are present.",
 "has_chat_widget is none across ceiling lights and candle-holder categories.",
 "has_email_form is true with a Klaviyo ESP tag -- a capture mechanism exists.",0,None),
("660","furkanaydinworks.com","Furkanaydinworks","Follow-up Opportunity",None,"Low",
 "Turkish auto-detailing/refurbishment service by car brand and model.",
 35,15,20,55,50,
 "cta_count_above_fold is 0.","Not a real retail cart (auto service business).","WhatsApp chat widget is present.",
 "has_email_form is false, has_contact_form is false, has_esp_tag is none -- no capture mechanism.",1,None),
("661","cellulotech.co.za","Cellulotech","Follow-up Opportunity",None,"Medium",
 "South African sustainable bamboo cutlery e-commerce brand.",
 40,55,25,60,50,
 "2 CTAs above the fold.","has_popup_script is false and has_esp_tag is none -- no recovery mechanism.",
 "has_chat_widget is none on a narrow single-product-line catalog.",
 "has_email_form is false, has_contact_form is false, has_esp_tag is none -- no capture mechanism.",1,None),
("663","gametimebasket.com","Gametimebasket","Follow-up Opportunity",None,"Low",
 "Quebec basketball gym booking/reservation service.",
 40,10,20,55,50,
 "cta_count_above_fold is 0; 'Reservez des maintenant' is a real CTA not counted.",
 "has_cart is false -- not a retail cart business (gym booking).","Not a catalog business; low relevance.",
 "has_email_form is false, has_contact_form is false, has_esp_tag is none -- no capture mechanism.",1,None),
("665","momadjewelry.com","Momadjewelry","Cart Recovery Opportunity",None,"Low",
 "Greek stainless-steel jewelry e-commerce brand.",
 40,35,40,20,50,
 "cta_count_above_fold is 0.","A popup script is present but has_esp_tag is none, on a small 4-product catalog.",
 "has_chat_widget is none across several jewelry categories.","has_email_form is true -- a capture mechanism exists.",0,None),
("666","tanvicreation.in","Tanvicreation","Customer Engagement Opportunity",None,"Low",
 "Indian ethnic-wear (suits) e-commerce brand.",
 15,40,50,20,50,
 "6 CTAs above the fold give a clear path.","A popup script is present but has_esp_tag is none.",
 "has_chat_widget is none on a real 24-product catalog.","has_email_form is true (evidence: 'Email *') -- a capture mechanism exists.",0,None),
("667","umenzosports.com","Umenzosports","Customer Engagement Opportunity",None,"High",
 "Sports apparel and uniform e-commerce brand covering many sports.",
 40,30,80,15,50,
 "cta_count_above_fold is 0 despite a real 78-product catalog.","A Mailchimp ESP tag and popup are present.",
 "has_chat_widget is none across a massive multi-sport catalog (goalkeeper gloves, sportswear, uniforms for football, basketball, rugby, swimming, martial arts).",
 "has_email_form is true (evidence: honeypot field) with a Mailchimp ESP tag -- a capture mechanism exists.",0,None),
("668","localleverage.ai","Localleverage","Follow-up Opportunity",None,"Low",
 "AI-powered marketing/booking system for local businesses (SaaS/agency).",
 40,10,35,55,50,
 "cta_count_above_fold is 0; 'Book Free Strategy Call' is a real CTA not counted.",
 "has_cart is false -- not a retail cart business (B2B SaaS).",
 "has_chat_widget is none across SEO/marketing/automation/AI service lines.",
 "has_email_form is false, has_contact_form is false, has_esp_tag is none -- no capture mechanism.",1,None),
("669","camp-growth.nl","Camp Growth","Customer Engagement Opportunity",None,"Low",
 "Dutch coaching and group-travel company.",
 40,25,55,20,50,
 "cta_count_above_fold is 0.","Not a real retail cart (coaching/travel business).",
 "has_chat_widget is none across a wide mix of coaching types and group travel destinations (Belgium, Madeira, Austria).",
 "has_email_form is true (evidence: 'Telefoonnummer') -- a capture mechanism exists.",0,None),
("670","mariosjewellers.co.za","Mariosjewellers","Customer Engagement Opportunity",None,"High",
 "South African luxury watch and jewelry retailer (Longines, Rado, Montblanc, Tissot).",
 45,40,80,20,50,
 "Only 1 CTA above the fold despite an active promo bar.","A popup script is present but has_esp_tag is none, on a real 46-product catalog.",
 "has_chat_widget is none across an unusually wide luxury watch-brand catalog (16 brands: Longines, Rado, Montblanc, Frederique Constant, Hamilton, Tissot, and more).",
 "has_email_form is true (a honeypot 'Anti-spam' field confirms a real form) -- a capture mechanism exists.",0,None),
("671","iconicstays.in","Iconicstays","Follow-up Opportunity",None,"Low",
 "Indian short-stay serviced-apartment rental company.",
 15,15,20,55,50,
 "6 CTAs above the fold give a clear path.","Not a real retail cart (apartment-rental booking).",
 "Not a catalog business; low relevance.",
 "has_email_form is false, has_contact_form is false, has_esp_tag is none -- no capture mechanism.",1,None),
("672","odayshoptanzania.com","Odayshoptanzania","Customer Engagement Opportunity",None,"Low",
 "Tanzanian home-appliance e-commerce store.",
 10,40,55,20,50,
 "12 CTAs above the fold give a clear path.","A popup script is present but has_esp_tag is none.",
 "has_chat_widget is none across a wide 44-product appliance catalog (audio, personal care, blenders, microwaves).",
 "has_email_form is true -- a capture mechanism exists.",0,None),
("674","electrozonepk.com","Electrozonepk","Conversion Opportunity",None,"Low",
 "Pakistani electronics/appliance e-commerce store.",
 45,40,20,15,50,
 "cta_count_above_fold is 0 despite an enormous 107-category catalog.","A popup script is present but has_esp_tag is none.",
 "WhatsApp chat widget is present despite the very wide catalog, closing this gap per the signal.",
 "has_email_form is true and has_contact_form is true (evidence: 'Your Name (required)') -- a capture mechanism exists.",0,None),
("675","lit-soft.com","Lit Soft","Customer Engagement Opportunity",None,"Low",
 "SAP S/4HANA training and placement consultancy.",
 40,15,55,55,50,
 "Only 1 CTA above the fold.","Not a real retail cart (training/consultancy business).",
 "has_chat_widget is none across several technical SAP modules (FICO, SD, MM, PP, QM, EWM, TM).",
 "has_email_form is false, has_contact_form is false, has_esp_tag is none -- no capture mechanism.",0,None),
("676","exportwearbd.com","Exportwearbd","Follow-up Opportunity",None,"Medium",
 "Bangladeshi kids' and women's fashion export e-commerce brand.",
 40,40,20,60,50,
 "Only 1 CTA above the fold despite an active promo.","A popup script is present but has_esp_tag is none.",
 "WhatsApp chat widget is present.",
 "has_email_form is false, has_contact_form is false, has_esp_tag is none -- no capture mechanism.",1,None),
("681","voiceofprambanan.org","Voiceofprambanan","Conversion Opportunity",None,"Low",
 "Indonesian Hindu religious/cultural organization (event permits, documentation).",
 40,20,30,20,50,
 "cta_count_above_fold is 0.","Not a real retail cart (nonprofit/cultural organization).",
 "has_chat_widget is none across a few event categories.","has_email_form is true -- a capture mechanism exists.",0,None),
("682","www.decoriohome.com","Decoriohome","Not a Good Fit",None,"High",
 "Turkish wall art/wallpaper e-commerce brand -- the site currently displays a 'site being renewed' placeholder message.",
 50,50,50,50,50,
 "not determinable from available signals","not determinable from available signals","not determinable from available signals","not determinable from available signals",
 0,"Site displays a 'renewing/coming soon' placeholder message ('Sitemiz Yenileniyor') -- not currently a live storefront."),
("684","thegmh.com","Thegmh","Cart Recovery Opportunity",None,"Low",
 "New Zealand Manuka honey e-commerce brand.",
 15,35,20,20,50,
 "6 CTAs above the fold give a clear path.","A popup script is present but has_esp_tag is none, on a narrow catalog.",
 "has_chat_widget is none on a single-product-focus catalog.","has_email_form is true (evidence: 'Email*') -- a capture mechanism exists.",0,None),
("685","nimeshthaker.com","Nimeshthaker","Customer Engagement Opportunity",None,"Low",
 "Indian SEBI-registered stock/mutual-fund research and advisory service.",
 20,10,40,15,50,
 "3 CTAs above the fold.","has_cart is false -- not a retail cart business (advisory service).",
 "has_chat_widget is none across several advisory service lines (mutual funds, equity, trade signals).",
 "has_email_form is true and has_contact_form is true (evidence: 'Your name') -- a capture mechanism exists.",0,None),
("690","mudahbelajardigital.com","Mudahbelajardigital","Conversion Opportunity",None,"Low",
 "Indonesian digital-marketing training courses (Medan).",
 40,20,20,15,50,
 "cta_count_above_fold is 0; 'Daftar Sekarang' (register now) is a real CTA not counted.",
 "Not a real retail cart (course business).","WhatsApp chat widget is present.",
 "has_email_form is true with a Mailchimp ESP tag -- a capture mechanism exists.",0,None),
("692","skincellshop.lt","Skincellshop","Customer Engagement Opportunity",None,"High",
 "Lithuanian professional skincare e-commerce brand carrying multiple clinical brands.",
 35,35,75,20,50,
 "cta_count_above_fold is 0; Lithuanian detector miss likely.","A popup script is present but has_esp_tag is none.",
 "has_chat_widget is none across 14 distinct professional skincare brands (Alphascience, Bioderma, Endocare, Heliocare, Medik8, ZO Skin Health, and more) -- a genuinely wide, overlapping-brand scenario.",
 "has_email_form is true -- a capture mechanism exists.",0,None),
("693","princegallerybd.com","Princegallerybd","Follow-up Opportunity",None,"Medium",
 "Bangladeshi Korean-beauty-product e-commerce store.",
 10,40,20,65,50,
 "11 CTAs above the fold give a clear path.","A popup script is present but has_esp_tag is none, on a real 205-product catalog.",
 "WhatsApp chat widget is present despite the very wide catalog, closing this gap per the signal.",
 "has_email_form is false, has_contact_form is false, has_esp_tag is none -- no capture mechanism.",1,None),
("694","imaprestige.com","Imaprestige","Customer Engagement Opportunity",None,"Medium",
 "Canadian large-format printing and signage company (murals, banners, vinyl decals).",
 40,25,65,20,50,
 "cta_count_above_fold is 0.","Not a real retail cart (B2B print/signage business).",
 "has_chat_widget is none across a wide print-product catalog (wall murals, banners, vinyl lettering, decals, architectural plans).",
 "has_email_form is true -- a capture mechanism exists.",0,None),
("695","sillagearabia.com","Sillagearabia","Follow-up Opportunity",None,"Medium",
 "UAE perfume and oud e-commerce brand.",
 10,30,20,55,50,
 "12 CTAs above the fold give a very clear path.","A Poptin exit-intent popup is present but has_esp_tag is none.",
 "WhatsApp chat widget is present.",
 "has_email_form is false, has_contact_form is false, has_esp_tag is none -- no capture form confirmed despite the active Poptin popup.",1,None),
("696","stylehom.com","Stylehom","Follow-up Opportunity",None,"Medium",
 "Gulf-region furniture e-commerce brand.",
 35,40,20,60,50,
 "cta_count_above_fold is 0; Arabic detector miss likely.","A popup script is present but has_esp_tag is none.",
 "WhatsApp chat widget is present.",
 "has_email_form is false, has_contact_form is false, has_esp_tag is none -- no capture mechanism.",1,None),
("702","laevachi.com","Laevachi","Follow-up Opportunity",None,"Medium",
 "Indian bridal and ethnic-wear e-commerce brand.",
 35,55,20,60,50,
 "cta_count_above_fold is 0 despite an active promo bar.","has_popup_script is false and has_esp_tag is none on a real 27-product catalog -- no recovery mechanism.",
 "WhatsApp chat widget is present despite a wide 21-category catalog, closing this gap per the signal.",
 "has_email_form is false, has_contact_form is false, has_esp_tag is none -- no capture mechanism.",1,None),
("707","ultradach.pl","Ultradach","Follow-up Opportunity",None,"Medium",
 "Polish roofing company (roofs, tiles, sheet metal, gutters, membranes).",
 40,15,45,60,50,
 "cta_count_above_fold is 0.","Not a real retail cart (roofing service business).",
 "has_chat_widget is none across a moderately wide roofing product/service range.",
 "has_email_form is false, has_contact_form is false, has_esp_tag is none -- no capture mechanism.",1,None),
("709","23fab.com","23Fab","Customer Engagement Opportunity",None,"Low",
 "Spanish performance-car exhaust-systems e-commerce brand.",
 40,30,45,15,50,
 "cta_count_above_fold is 0 despite an active financing offer.","A Mailchimp ESP tag is present but no popup.",
 "has_chat_widget is none across a technical exhaust product line (admission, downpipe, collectors, kits).",
 "has_email_form is true with a Mailchimp ESP tag -- a capture mechanism exists.",0,None),
("710","dsoinstallaties.nl","Dsoinstallaties","Conversion Opportunity",None,"Low",
 "Dutch installation company -- the site is mid-redesign, showing a placeholder page with a working contact form.",
 35,10,20,15,50,
 "cta_count_above_fold is 0; the page is a redesign placeholder.","has_cart is false -- not a retail cart business.",
 "Services unclear while the site is mid-redesign; low relevance.",
 "has_email_form is true and has_contact_form is true (evidence: 'Voornaam') -- a capture mechanism exists despite the placeholder page.",0,None),
("711","skinfactorycr.com","Skinfactorycr","Customer Engagement Opportunity",None,"Medium",
 "Costa Rican dermatology clinic and skincare shop carrying multiple clinical brands.",
 40,30,65,15,50,
 "cta_count_above_fold is 0 despite an active 2x1 promo.","Not a real retail cart (clinic/shop hybrid).",
 "has_chat_widget is none across many distinct skincare brands (ACM, Avene, Bioderma, Bioeffect, BioNike, Cantabria Labs, and more) -- a wide, overlapping-brand scenario.",
 "has_email_form is true and has_contact_form is true (evidence: 'Nombre') -- a capture mechanism exists.",0,None),
("712","positiveelektrik.com.tr","Positiveelektrik","Customer Engagement Opportunity",None,"Low",
 "Turkish electrical outlet/socket manufacturer (B2B).",
 40,25,40,15,50,
 "cta_count_above_fold is 0.","A Mailchimp ESP tag and popup are present.",
 "has_chat_widget is none across a moderately technical product line (USB fast-charging outlets).",
 "has_email_form is true with a Mailchimp ESP tag -- a capture mechanism exists.",0,None),
("713","katkoreanstore.com","Katkoreanstore","Conversion Opportunity",None,"Low",
 "Costa Rican Korean-beauty-brand e-commerce store.",
 35,40,20,25,50,
 "cta_count_above_fold is 0; Spanish detector miss likely.","A popup script is present but has_esp_tag is none, on a real catalog spanning 5 Korean beauty brands.",
 "WhatsApp chat widget is present.",
 "has_email_form is true, though form_evidence ('Remember me') suggests a login field rather than a marketing signup.",0,None),
("714","themerchstudio.cl","Themerchstudio","Conversion Opportunity",None,"Low",
 "Chilean corporate merchandise/gifts B2B business.",
 40,25,20,20,50,
 "cta_count_above_fold is 0; 'COTIZAR AHORA' (quote now) is a real CTA not counted.",
 "Not a real retail cart (B2B custom-merchandise business).","WhatsApp chat widget is present.",
 "has_email_form is true -- a capture mechanism exists.",0,None),
("715","madame-dakar.com","Madame Dakar","Follow-up Opportunity",None,"Medium",
 "Senegalese fashion e-commerce brand.",
 35,40,20,60,50,
 "cta_count_above_fold is 0; French detector miss likely.","A popup script is present but has_esp_tag is none.",
 "WhatsApp chat widget is present.",
 "has_email_form is false, has_contact_form is false, has_esp_tag is none -- no capture mechanism.",1,None),
("716","allwedoismarketing.com","Allwedoismarketing","Follow-up Opportunity",None,"Low",
 "Digital marketing agency (All Marketing Agency).",
 40,15,30,55,50,
 "cta_count_above_fold is 0; 'Contact an Expert' is a real CTA not counted.",
 "Not a real retail cart (agency services).",
 "has_chat_widget is none across marketing service offerings.",
 "has_email_form is false, has_contact_form is false, has_esp_tag is none -- no capture mechanism.",1,None),
("717","sugandhausa.com","Sugandhausa","Follow-up Opportunity",None,"Medium",
 "US-based Indian pooja flowers and religious-items e-commerce brand.",
 40,40,55,60,50,
 "Only 1 CTA above the fold on a real 12-product catalog.","A popup script is present but has_esp_tag is none.",
 "has_chat_widget is none across a wide range of religious product categories (garlands, pooja items, mandirs, home decor).",
 "has_email_form is false, has_contact_form is false, has_esp_tag is none -- no capture mechanism.",1,None),
("719","jdonline.in","Jdonline","Customer Engagement Opportunity",None,"Low",
 "Indian fashion-technology institute (JD Institute, est. 1988).",
 15,15,35,10,50,
 "8 CTAs above the fold give a clear path.","Not a real retail cart (education institute).",
 "has_chat_widget is none across certification, diploma, and free course lines.",
 "has_email_form is true and has_contact_form is true with a Mailchimp ESP tag -- a capture mechanism exists.",0,None),
("722","trappenmaat.be","Trappenmaat","Follow-up Opportunity",None,"Medium",
 "Dutch/Belgian custom staircase e-commerce brand (148 reviews, 9.6/10 rating).",
 40,30,20,50,50,
 "cta_count_above_fold is 0.","A Klaviyo ESP tag is present but no popup.",
 "WhatsApp chat widget is present.",
 "has_email_form is false -- no capture form was confirmed in the static markup, though a Klaviyo tag is loaded, suggesting one may exist dynamically.",0,None),
("723","panchaamritvastu.com","Panchaamritvastu","Customer Engagement Opportunity",None,"Low",
 "Indian Vastu Shastra consultancy with property listings and an online shop.",
 15,35,40,15,50,
 "5 CTAs above the fold give a clear path.","A popup script is present but has_esp_tag is none, on a 15-product catalog.",
 "has_chat_widget is none across consultancy, property, and shop offerings.",
 "has_email_form is true and has_contact_form is true (evidence: 'Name') -- a capture mechanism exists.",0,None),
("724","westernauctions.ca","Westernauctions","Follow-up Opportunity",None,"Medium",
 "Canadian gold and silver precious-metals buying/selling business (Aurora & GTA).",
 10,15,30,60,50,
 "8 CTAs above the fold give a clear path.","Not a real retail cart (precious-metals trading business).",
 "has_chat_widget is none; buying/selling metals isn't a browsable catalog.",
 "has_email_form is false, has_contact_form is false, has_esp_tag is none -- no capture mechanism for high-value trading leads.",1,None),
("727","zenspirit74.net","Zenspirit74","Not a Good Fit",None,"High",
 "Not determinable -- the site returns a database connection error and is technically broken.",
 50,50,50,50,50,
 "not determinable from available signals","not determinable from available signals","not determinable from available signals","not determinable from available signals",
 0,"Site returns 'Error establishing a database connection' -- technically broken and inaccessible, not a live business page."),
("728","beymaral-honey.com","Beymaral Honey","Follow-up Opportunity",None,"Low",
 "Kyrgyzstan premium organic white honey e-commerce brand.",
 15,35,20,55,50,
 "6 CTAs above the fold give a clear path.","A popup script is present but has_esp_tag is none.",
 "WhatsApp chat widget is present.",
 "has_email_form is false, has_contact_form is false, has_esp_tag is none -- no capture mechanism.",1,None),
("730","luxurystylecarservice.com","Luxurystylecarservice","Conversion Opportunity",None,"Low",
 "Los Angeles luxury chauffeur/car service (airport transfers, weddings, corporate).",
 45,15,40,20,50,
 "cta_count_above_fold is 0; 'REQUEST QUOTE' is a real CTA not counted.",
 "Not a real retail cart (chauffeur service).",
 "has_chat_widget is none across several service types (airport, weddings, corporate, casinos).",
 "has_email_form is true -- a capture mechanism exists.",0,None),
("731","sakeking.hk","Sakeking","Follow-up Opportunity",None,"Low",
 "Hong Kong sake retailer and education brand.",
 35,15,20,55,50,
 "cta_count_above_fold is 0; Chinese detector miss likely.","has_cart is false -- not a retail cart business per the signal.",
 "WhatsApp chat widget is present.",
 "has_email_form is false, has_contact_form is false, has_esp_tag is none -- no capture mechanism.",1,None),
("733","vestelpakistan.com","Vestelpakistan","Customer Engagement Opportunity",None,"Low",
 "Pakistani Vestel appliance dealer.",
 40,25,45,15,50,
 "cta_count_above_fold is 0; a WhatsApp order button is styled in the page CSS but wasn't detected as a chat widget or CTA.",
 "A Mailchimp ESP tag and popup are present.",
 "has_chat_widget is none across a moderate 19-product appliance catalog.",
 "has_email_form is true with a Mailchimp ESP tag -- a capture mechanism exists.",0,None),
("734","ariadneparis.com","Ariadneparis","Customer Engagement Opportunity",None,"Low",
 "French fashion e-commerce brand.",
 40,30,50,15,50,
 "cta_count_above_fold is 0; the fetched page text leads with builder CSS, obscuring any real CTA.",
 "An Omnisend ESP tag and popup are present.",
 "has_chat_widget is none across 11 product categories.",
 "has_email_form is true with an Omnisend ESP tag -- a capture mechanism exists.",0,None),
("735","egecarsisi.nl","Egecarsisi","Customer Engagement Opportunity","Follow-up Opportunity","High",
 "Dutch Turkish specialty-grocery e-commerce brand.",
 40,40,75,60,50,
 "cta_count_above_fold is 0; Turkish detector miss likely.","A popup script is present but has_esp_tag is none.",
 "has_chat_widget is none across an extensive grocery catalog (dried fruits, tahini-molasses, pickles, vinegars, spices, honey, jams, cheese, sauces, olives, nuts).",
 "has_email_form is false, has_contact_form is false, has_esp_tag is none -- no capture mechanism.",2,None),
("736","giarcidia.com","Giarcidia","Cart Recovery Opportunity",None,"Low",
 "US pet-deworming medicine e-commerce brand (Shopify) with an unrelated tequila product line.",
 15,35,40,20,50,
 "5 CTAs above the fold give a clear path.","A popup script is present but has_esp_tag is none.",
 "has_chat_widget is none across an unusually mixed catalog (pet medicine and tequila).",
 "has_email_form is true (evidence: signup for free shipping) -- a capture mechanism exists.",0,None),
("738","divafur.com","Divafur","Follow-up Opportunity",None,"Medium",
 "Slovenian fur and leather fashion e-commerce brand.",
 35,40,50,60,50,
 "cta_count_above_fold is 0; Slovenian detector miss likely.","A popup script is present but has_esp_tag is none.",
 "has_chat_widget is none across several apparel categories (dresses, footwear, fur headwear, leather jackets).",
 "has_email_form is false, has_contact_form is false, has_esp_tag is none -- no capture mechanism.",1,None),
]

n = append_results(RESULTS)
print(f"appended {n} rows (chunk_003)")
