import sys
sys.path.insert(0, ".")
from layer3_write import append_results

RESULTS = [
("292","daralands.com","Daralands","Follow-up Opportunity",None,"Medium",
 "Jordanian real-estate listing portal selling land plots direct from owners.",
 40,15,30,60,50,
 "cta_count_above_fold is 0; Arabic detector miss likely.","Not a real retail cart (real-estate listings).",
 "Listings aren't a product catalog; low relevance.",
 "has_email_form is false, has_contact_form is false, has_esp_tag is none -- no capture mechanism for interested buyers.",1,None),
("293","eqkidbooks.com","Eqkidbooks","Cart Recovery Opportunity",None,"Low",
 "Shopify brand selling emotional-intelligence themed children's books.",
 40,40,30,20,50,
 "2 CTAs above the fold.","A popup script is present but has_esp_tag is none, on a narrow 9-product catalog.",
 "has_chat_widget is none on a narrow 3-category catalog; low relevance.",
 "has_email_form is true (evidence: 'Email') -- a capture mechanism exists.",0,None),
("295","jamdanioamadergolpo.com","Jamdanioamadergolpo","Cart Recovery Opportunity",None,"Medium",
 "Bangladeshi handloom saree e-commerce brand (Jamdani, Halfsilk, cotton).",
 15,65,45,20,50,
 "9 CTAs above the fold give a clear purchase path.",
 "has_popup_script is false and has_esp_tag is none -- no recovery mechanism at all on a real saree catalog.",
 "has_chat_widget is none across several distinct weave/fabric types.",
 "has_email_form is true (evidence: 'Subscription Form') -- a capture mechanism exists.",1,None),
("296","fiihii.com","Fiihii","Conversion Opportunity",None,"Low",
 "UK flavored-drinks and frozen treat brand ('The Frinks').",
 45,40,30,20,50,
 "cta_count_above_fold is 0; a cookie-consent banner may dominate the first content instead of a buy button.",
 "A popup script is present but has_esp_tag is none.","has_chat_widget is none on a small 4-product catalog.",
 "has_email_form is true (evidence: 'Email') -- a capture mechanism exists.",0,None),
("302","swingfreemobility.com","Swingfreemobility","Conversion Opportunity",None,"Low",
 "Golf mobility and stretching-system e-commerce brand.",
 45,40,30,20,50,
 "Only 1 CTA above the fold.","A popup script is present but has_esp_tag is none, on a 13-product catalog.",
 "has_chat_widget is none on a narrow single-niche catalog.",
 "has_email_form is true (evidence: 'Email') -- a capture mechanism exists.",0,None),
("303","merakicheese.com","Merakicheese","Follow-up Opportunity",None,"High",
 "Kolkata artisan cheese delivery brand (fresh, aged, gourmet cheese and hampers).",
 15,40,50,70,50,
 "4 CTAs above the fold give a clear path.","A popup script is present but has_esp_tag is none.",
 "has_chat_widget is none across a moderately wide cheese catalog (21 products, several lines).",
 "has_email_form is false, has_contact_form is false, has_esp_tag is none -- no capture mechanism on real priced products.",1,None),
("308","occhilux.com","Occhilux","Follow-up Opportunity",None,"Medium",
 "Italian optician selling designer eyewear (Dolce&Gabbana and other brands).",
 35,40,20,65,50,
 "cta_count_above_fold is 0; Italian detector miss likely.","A popup script is present but has_esp_tag is none.",
 "WhatsApp chat widget is present.",
 "has_email_form is false, has_contact_form is false, has_esp_tag is none -- no capture mechanism on real-value designer eyewear (163-263 EUR items).",1,None),
("309","dovanatau.lt","Dovanatau","Follow-up Opportunity",None,"Medium",
 "Lithuanian gift shop selling sweets and toys.",
 30,40,40,60,50,
 "cta_count_above_fold is 0; Lithuanian 'Pirkti dabar' (buy now) appears in text but not matched.",
 "A popup script is present but has_esp_tag is none.",
 "has_chat_widget is none across sweets/toys/gift categories.",
 "has_email_form is false, has_contact_form is false, has_esp_tag is none -- no capture mechanism.",1,None),
("310","appbanao.com","Appbanao","Cart Recovery Opportunity",None,"Low",
 "No-code app-development training courses.",
 15,25,20,15,50,
 "6 CTAs above the fold give a clear path.","Not a real retail cart (course business).",
 "Single-course focus; low relevance.","has_email_form is true with a Mailchimp ESP tag -- a capture mechanism exists.",0,None),
("311","dilanciftci.com","Dilanciftci","Follow-up Opportunity",None,"Low",
 "Turkish individual therapy/counseling practice.",
 35,15,20,55,50,
 "cta_count_above_fold is 0, though an online-booking phone number is prominent.",
 "Not a real retail cart (therapy practice).","Single-practitioner service; low relevance.",
 "has_email_form is false, has_contact_form is false, has_esp_tag is none -- no digital capture mechanism beyond a phone number.",1,None),
("312","zoalasilver.com","Zoalasilver","Follow-up Opportunity",None,"Medium",
 "Egyptian silver jewelry e-commerce brand (bracelets, necklaces).",
 10,35,20,55,50,
 "12 CTAs above the fold give a very clear purchase path.","A Mailchimp ESP tag is present but no popup.",
 "WhatsApp chat widget is present.",
 "has_email_form is false -- no capture form was confirmed in the static markup, though a Mailchimp tag is loaded, suggesting one may exist dynamically.",1,None),
("313","worldlinklabs.com","Worldlinklabs","Follow-up Opportunity","Customer Engagement Opportunity","Medium",
 "South African SAP cloud/AI consulting firm (S/4HANA, BPT, ABAP Cloud, GRC).",
 20,15,65,65,50,
 "3 CTAs above the fold.","Not a real retail cart (B2B consulting).",
 "has_chat_widget is none across a genuinely technical, wide SAP service catalog (S/4HANA, BPT, AI, ABAP Cloud, Work Zone, GRC, Fiori) -- a high-consideration enterprise decision.",
 "has_email_form is false, has_contact_form is false, has_esp_tag is none -- no capture mechanism for high-value B2B leads.",2,None),
("314","eightballjacket.com","Eightballjacket","Conversion Opportunity",None,"Low",
 "Branded '8 Ball Jacket' apparel e-commerce brand.",
 40,30,15,25,50,
 "Only 1 CTA above the fold despite an active discount promo.",
 "A Mailchimp ESP tag is present but no popup.","A Tawk chat widget is present.",
 "has_email_form is true, though form_evidence ('Order ID') suggests this may be an order-tracking field rather than a marketing signup -- treated as a capture mechanism per the signal as detected.",0,None),
("315","tek-talks.com","Tek Talks","Customer Engagement Opportunity",None,"Low",
 "European tech/design conference (Tek Talks).",
 15,15,35,20,50,
 "5 CTAs above the fold give a clear path.","Not a real retail cart (conference/event business).",
 "has_chat_widget is none across several distinct conference tracks (C-Suite, Dist@Tech, Dev, Inno@Startup).",
 "has_email_form is true (subscribe) -- a capture mechanism exists.",0,None),
("316","jalaramdelight.com","Jalaramdelight","Conversion Opportunity",None,"Low",
 "Indian snacks and spice-blend manufacturer/e-commerce brand.",
 40,30,20,15,50,
 "2 CTAs above the fold, a modest showing.","A Mailchimp ESP tag and popup script are both present.",
 "WhatsApp chat widget is present.","has_email_form is true with a Mailchimp ESP tag -- a capture mechanism exists.",0,None),
("319","teeisajewels.com","Teeisajewels","Insufficient Data",None,"Low",
 "Not determinable -- the fetched page returned no visible text content at all.",
 50,50,50,50,50,
 "not determinable from available signals","not determinable from available signals","not determinable from available signals","not determinable from available signals",0,None),
("323","esnmconnect.com","Esnmconnect","Customer Engagement Opportunity",None,"High",
 "French-language naturopathy e-learning platform.",
 40,20,70,15,50,
 "cta_count_above_fold is 0 and no clear enroll button is visible in the excerpt.",
 "Not a real retail cart (course platform).",
 "has_chat_widget is none across an extensive course catalog (aromatherapy x2, acupuncture, cupping, phytotherapy, nutrition, reflexology, cosmetics manufacturing, naturopathy fundamentals, anatomy, physiology) -- a genuinely wide, technical curriculum.",
 "has_email_form is true with a Mailchimp ESP tag -- a capture mechanism exists.",0,None),
("325","helpingseniorsthrive.org","Helpingseniorsthrive","Follow-up Opportunity",None,"Low",
 "Houston nonprofit providing senior services and Medicare education.",
 15,15,30,55,50,
 "5 CTAs above the fold ('Donate Now!' repeated).","Not a real retail cart (nonprofit).",
 "Service categories aren't a real catalog; low relevance.",
 "has_email_form is false, has_contact_form is false, has_esp_tag is none -- no capture mechanism.",1,None),
("337","www.africanbutsouth.co.za","Africanbutsouth","Follow-up Opportunity",None,"Medium",
 "South African streetwear/headwear brand (limited-edition drops).",
 40,40,30,65,50,
 "2 CTAs above the fold.","A popup script is present but has_esp_tag is none.",
 "has_chat_widget is none on a narrow 12-product catalog.",
 "has_email_form is false, has_contact_form is false, has_esp_tag is none -- no capture mechanism.",1,None),
("340","azamsonline.com","Azamsonline","Follow-up Opportunity",None,"Medium",
 "Pakistani formal/bridal velvet fashion brand (pre-launch teaser page with live purchasable products).",
 40,40,40,65,50,
 "2 CTAs above the fold.","A popup script is present but has_esp_tag is none.",
 "has_chat_widget is none on a 21-product bridal/formal catalog.",
 "has_email_form is false, has_contact_form is false, has_esp_tag is none -- no capture mechanism, though the page is labeled 'Coming soon' which adds some uncertainty.",1,None),
("343","customejewelry.com","Customejewelry","Follow-up Opportunity",None,"Medium",
 "Custom photo-engraved jewelry e-commerce brand.",
 40,40,45,65,50,
 "Only 1 CTA above the fold despite an active promo bar.","A popup script is present but has_esp_tag is none.",
 "has_chat_widget is none across several personalized-jewelry product types where guidance could help.",
 "has_email_form is false, has_contact_form is false, has_esp_tag is none -- no capture mechanism.",1,None),
("344","misha-store.com","Misha Store","Follow-up Opportunity","Cart Recovery Opportunity","Medium",
 "Indian ethnic-wear e-commerce brand (sarees, kurthis, dresses).",
 40,60,20,60,50,
 "Only 1 CTA above the fold despite an active promo bar.",
 "has_popup_script is false and has_esp_tag is none -- no recovery mechanism at all.",
 "WhatsApp chat widget is present.",
 "has_email_form is false, has_contact_form is false, has_esp_tag is none -- no capture mechanism.",2,None),
("348","tromboo.in","Tromboo","Customer Engagement Opportunity",None,"High",
 "Indian luxury embroidered fashion brand (menswear and womenswear).",
 15,30,75,10,50,
 "9 CTAs above the fold give a clear purchase path.","A Mailchimp ESP tag and popup script are both present.",
 "has_chat_widget is none across a very wide 91-product, 3-brand, 9-category catalog (Heritage Crafts, Kashida, Menswear, Nawaabi, Sustainable Fashion, Upcycling) -- a genuinely broad, high-consideration catalog.",
 "has_email_form is true and has_contact_form is true with a Mailchimp ESP tag -- a capture mechanism exists.",0,None),
("356","sennailspa.com","Sennailspa","Cart Recovery Opportunity",None,"Low",
 "Nail salon offering spa services and appointment booking.",
 15,20,20,15,50,
 "4 CTAs above the fold give a clear path.","Not a real retail cart (appointment-based salon); a Mailchimp ESP tag and popup are present, so already reasonably well covered.",
 "Single salon service; low relevance.","has_email_form is true (SMS opt-in) with a Mailchimp ESP tag -- a capture mechanism exists.",0,None),
("357","threeelixir.com","Threeelixir","Follow-up Opportunity",None,"Medium",
 "Bangladeshi men's fashion e-commerce brand (panjabi, polo, pants).",
 15,40,40,65,50,
 "5 CTAs above the fold give a clear path.","A popup script is present but has_esp_tag is none.",
 "has_chat_widget is none on a moderate 21-product catalog.",
 "has_email_form is false, has_contact_form is false, has_esp_tag is none -- no capture mechanism.",1,None),
("358","tullowhandcarwash.ie","Tullowhandcarwash","Follow-up Opportunity",None,"Low",
 "Irish hand car wash and detailing service.",
 10,15,15,55,50,
 "8 CTAs above the fold ('Book Now' repeated, though has_booking wasn't structurally matched).",
 "Not a real retail cart (local service business).","Single local service; low relevance.",
 "has_email_form is false, has_contact_form is false, has_esp_tag is none -- no digital capture mechanism.",1,None),
("359","adrianinsures.com","Adrianinsures","Customer Engagement Opportunity",None,"High",
 "Canadian insurance broker (Mississauga) selling life, disability, and business insurance.",
 15,15,65,15,50,
 "4 CTAs above the fold give a clear path.","Not a real retail cart (insurance brokerage).",
 "has_chat_widget is none across a wide, high-consideration insurance product line (term/whole life, disability, critical illness, final expense, business, newcomers).",
 "has_email_form is true with a Mailchimp ESP tag -- a capture mechanism exists.",0,None),
("362","alphaprintandsigns.com","Alphaprintandsigns","Conversion Opportunity",None,"Low",
 "UK signage and vehicle-graphics printing company.",
 45,20,20,20,50,
 "Only 1 CTA above the fold on a very wide signage catalog.","Not a real retail cart (B2B custom signage).",
 "WhatsApp chat widget is present, though the catalog itself is unusually wide.",
 "has_email_form is true -- a capture mechanism exists.",0,None),
("364","artecomics.it","Artecomics","Customer Engagement Opportunity",None,"High",
 "Italian collectibles store selling card games, manga, Funko figures, and board games.",
 35,40,70,20,50,
 "cta_count_above_fold is 0; Italian detector miss likely.","A popup script is present but has_esp_tag is none.",
 "has_chat_widget is none across a very wide collectibles catalog (card games, figures, manga, Funko, board games, books, posters).",
 "has_email_form is true -- a capture mechanism exists.",0,None),
("371","witstechnology.us","Witstechnology","Follow-up Opportunity",None,"Low",
 "Digital marketing/SEO agency.",
 40,20,30,55,50,
 "cta_count_above_fold is 0; 'Start'/'Contact Us' text is present but not counted as buttons.",
 "Not a real retail cart (agency services).","Service line is narrow-to-moderate; low relevance.",
 "has_email_form is false, has_contact_form is false, has_esp_tag is none -- no capture mechanism.",1,None),
("372","rakkeshruddiyar.com","Rakkeshruddiyar","Conversion Opportunity",None,"Low",
 "Indian fitness-certification training academy (bodybuilding courses).",
 40,20,30,15,50,
 "Only 1 CTA above the fold.","Not a real retail cart (course business).",
 "has_chat_widget is none across a moderate range of certification courses.",
 "has_email_form is true and has_contact_form is true (evidence: 'Name') -- a capture mechanism exists.",0,None),
("375","islamicwallarts.co.uk","Islamicwallarts","Cart Recovery Opportunity",None,"Medium",
 "UK Islamic calligraphy wall-art e-commerce brand (digital and physical prints).",
 45,65,35,20,50,
 "cta_count_above_fold is 0 despite detailed product/delivery policy text; no clear buy button in the excerpt.",
 "has_popup_script is false and has_esp_tag is none -- no recovery mechanism at all.",
 "has_chat_widget is none across a moderate 'Shop by Meaning' catalog.",
 "has_email_form is true (evidence: 'Email address') -- a capture mechanism exists.",1,None),
("380","ethia.cz","Ethia","Cart Recovery Opportunity",None,"Medium",
 "Czech natural/handmade cosmetics brand.",
 40,60,30,20,50,
 "cta_count_above_fold is 0; 'Objevit produkty' (discover products) is a real CTA in the text but not counted.",
 "has_popup_script is false and has_esp_tag is none on a real handmade-cosmetics catalog -- no recovery mechanism.",
 "has_chat_widget is none on a narrow skin/hair catalog.",
 "has_email_form is true -- a capture mechanism exists.",0,None),
("390","realchefmo.online","Realchefmo","Follow-up Opportunity",None,"Low",
 "Private chef and catering business (bento box experiences, classes).",
 40,15,20,55,50,
 "2 CTAs above the fold.","Not a real retail cart (catering/service business).",
 "Single-chef service; low relevance.",
 "has_email_form is false, has_contact_form is false, has_esp_tag is none -- no capture mechanism for catering inquiries.",1,None),
("400","lagaffes.com","Lagaffes","Follow-up Opportunity","Cart Recovery Opportunity","Medium",
 "Indian loungewear and sleepwear e-commerce brand.",
 35,65,20,65,50,
 "cta_count_above_fold is 0 despite active promo codes; no clear buy button in the excerpt.",
 "has_popup_script is false and has_esp_tag is none on a real 30-product catalog -- no recovery mechanism.",
 "WhatsApp chat widget is present.",
 "has_email_form is false, has_contact_form is false, has_esp_tag is none -- no capture mechanism.",2,None),
("401","smart-courses.org","Smart Courses","Conversion Opportunity",None,"Low",
 "Egyptian training center offering computer, programming, robotics, and design courses.",
 45,20,20,15,50,
 "cta_count_above_fold is 0 despite a very wide course catalog; no clear enroll button visible in the excerpt.",
 "Not a real retail cart (course business).",
 "WhatsApp chat widget is present despite the wide catalog, closing this gap per the signal.",
 "has_email_form is true and has_contact_form is true (evidence: name field) -- a capture mechanism exists.",0,None),
("406","conceiling.com","Conceiling","Customer Engagement Opportunity",None,"High",
 "Lithuanian frameless-ceiling-systems manufacturer serving 9 European markets (HVAC/ventilation).",
 15,30,70,15,50,
 "6 CTAs above the fold give a clear path.","An Omnisend ESP tag and popup script are both present.",
 "has_chat_widget is none across a wide, technical B2B catalog (ventilation, frameless air diffusers, recessed spotlights, safety platforms) -- a genuinely high-consideration purchase.",
 "has_email_form is true with an Omnisend ESP tag -- a capture mechanism exists.",0,None),
("410","urskaverbuc.si","Urskaverbuc","Customer Engagement Opportunity",None,"Low",
 "Slovenian spiritual/energy-healing coach offering multiple therapy programs.",
 45,25,55,20,50,
 "cta_count_above_fold is 0 and no clear booking button is visible in the excerpt.",
 "Not a real retail cart (coaching/services business).",
 "has_chat_widget is none across several distinct therapy/program offerings.",
 "has_email_form is true (evidence: 'Email') -- a capture mechanism exists.",0,None),
("411","thebeerbeauty.com","Thebeerbeauty","Not a Good Fit",None,"High",
 "Not determinable -- the site is an unconfigured WordPress demo template ('W3V Demo TBB') with default placeholder content.",
 50,50,50,50,50,
 "not determinable from available signals","not determinable from available signals","not determinable from available signals","not determinable from available signals",
 0,"Unconfigured WordPress demo template ('W3V Demo TBB', default 'Hello world' post) -- no real business content."),
("412","decant.lt","Decant","Multi-Opportunity",None,"High",
 "Lithuanian luxury-perfume decant/sample e-commerce brand.",
 45,62,80,65,50,
 "cta_count_above_fold is 0 and no clear buy button is visible in the excerpt.",
 "has_popup_script is false and has_esp_tag is none -- no recovery mechanism at all.",
 "has_chat_widget is none across an unusually wide luxury-brand catalog (Armani, Chanel, Creed, Tom Ford, Le Labo, YSL, and many more) -- a genuinely wide, overlapping-brand scenario.",
 "has_email_form is false, has_contact_form is false, has_esp_tag is none -- no capture mechanism.",3,None),
("415","crescendo.org.in","Crescendo","Follow-up Opportunity",None,"Low",
 "Indian inter-collegiate youth festival (student cultural/sports event).",
 40,15,20,55,50,
 "cta_count_above_fold is 0; 'Register Now' text is present but not counted as a button.",
 "Not a real retail cart (student event).","Not a catalog business; low relevance.",
 "has_email_form is false, has_contact_form is false, has_esp_tag is none -- no capture mechanism for event sign-ups.",1,None),
("423","zavsol.com","Zavsol","Customer Engagement Opportunity",None,"Low",
 "Digital marketing agency (Zavsol) providing web and marketing services.",
 15,20,30,10,50,
 "4 CTAs above the fold give a clear path.","A Mailchimp ESP tag and popup are present.",
 "has_chat_widget is none across 6 service categories; moderate relevance for a services agency.",
 "has_email_form is true and has_contact_form is true with a Mailchimp ESP tag -- a capture mechanism exists.",0,None),
("426","magisclothing.com","Magisclothing","Customer Engagement Opportunity",None,"Medium",
 "Indian handloom clothing e-commerce brand.",
 40,35,65,15,50,
 "Only 1 CTA above the fold.","A Mailchimp ESP tag is present but no popup.",
 "has_chat_widget is none despite the page text showing a large real catalog (65 'Magis Everyday' items, 53 handloom items) well beyond the structurally counted 4 products.",
 "has_email_form is true with a Mailchimp ESP tag -- a capture mechanism exists.",0,None),
("430","procertico.com","Procertico","Conversion Opportunity",None,"Low",
 "ISO 9001 quality-management consulting service.",
 40,20,20,10,50,
 "cta_count_above_fold is 0; 'Send Brief'/'Go to Shop' are real CTAs in the text but not counted.",
 "Not a real retail cart (consulting service).","Single consulting service; low relevance.",
 "has_email_form is true and has_contact_form is true with a Mailchimp ESP tag -- a capture mechanism exists.",0,None),
("431","vidasmilecare.com","Vidasmilecare","Follow-up Opportunity","Cart Recovery Opportunity","Medium",
 "US direct-to-consumer dental products brand (dentures, veneers, mouthguards).",
 20,60,20,65,50,
 "3 CTAs above the fold.","has_popup_script is false and has_esp_tag is none on a real 14-product medical-adjacent catalog -- no recovery mechanism.",
 "A Tawk chat widget is present.","has_email_form is false, has_contact_form is false, has_esp_tag is none -- no capture mechanism.",2,None),
("432","www.ppapparelhub.com","Ppapparelhub","Customer Engagement Opportunity",None,"High",
 "US wholesale/custom apparel supplier (t-shirts, uniforms, safety workwear).",
 45,40,70,15,50,
 "cta_count_above_fold is 0 despite a real 17-product catalog.","A popup script is present but has_esp_tag is none.",
 "has_chat_widget is none across a very wide B2B apparel catalog spanning men's, women's, kids, safety, and custom-made lines.",
 "has_email_form is true and has_contact_form is true (evidence: 'Your Name') -- a capture mechanism exists.",0,None),
("433","mmti.in","Mmti","Follow-up Opportunity","Customer Engagement Opportunity","High",
 "Indian plastic-injection-molding machinery supplier (new and refurbished machines).",
 40,35,65,65,50,
 "Only 1 CTA above the fold on a high-ticket B2B machinery site.","A popup script is present but has_esp_tag is none.",
 "has_chat_widget is none on a technical, high-consideration industrial machinery catalog (India/Bangladesh series, refurbished Japanese/German/American lines).",
 "has_email_form is false, has_contact_form is false, has_esp_tag is none -- no capture mechanism for high-value B2B leads.",2,None),
("435","mmatata.com","Mmatata","Conversion Opportunity",None,"Low",
 "AI-powered wholesale event-furniture supplier (tables/chairs) for party rental businesses.",
 40,35,25,15,50,
 "cta_count_above_fold is 0 on a B2B wholesale site.","A popup script is present but has_esp_tag is none.",
 "has_chat_widget is none on a narrow single-category catalog.",
 "has_email_form is true and has_contact_form is true -- a capture mechanism exists.",0,None),
("437","afrikkalabashmarket.com","Afrikkalabashmarket","Conversion Opportunity",None,"Low",
 "US-based African grocery e-commerce store.",
 45,40,20,25,50,
 "cta_count_above_fold is 0 despite a wide grocery catalog spanning many categories.",
 "A popup script is present but has_esp_tag is none.","WhatsApp chat widget is present.",
 "has_email_form is true, though form_evidence ('Remember me') suggests a login field rather than a marketing signup -- treated as a capture mechanism per the signal as detected.",0,None),
("440","alremalalzahefa.com","Alremalalzahefa","Follow-up Opportunity",None,"Low",
 "Saudi B2B tent/marquee rental company (events, Hajj, military, exhibitions).",
 40,15,20,55,50,
 "cta_count_above_fold is 0 despite a wide tent-category range.","Not a real retail cart (rental service).",
 "WhatsApp chat widget is present.",
 "has_email_form is false, has_contact_form is false, has_esp_tag is none -- no capture mechanism.",1,None),
("441","archersbattlefield.com","Archersbattlefield","Customer Engagement Opportunity",None,"Low",
 "Toronto combat-archery and entertainment venue (birthday parties, team building).",
 10,15,40,10,50,
 "13 CTAs above the fold give a very clear path.","Not a real retail cart (entertainment venue).",
 "has_chat_widget is none across 7 activity categories; moderate relevance.",
 "has_email_form is true and has_contact_form is true with a Mailchimp ESP tag -- a capture mechanism exists.",0,None),
("442","hafizriazdentalcare.com","Hafizriazdentalcare","Conversion Opportunity",None,"Low",
 "Pakistani dental clinic (site appears to still carry template placeholder text, e.g. 'Have a Project? info@website.com').",
 40,25,20,20,50,
 "2 CTAs above the fold.","Not a real retail cart (dental clinic).","Single practice; low relevance.",
 "has_email_form is true -- a capture mechanism exists.",0,None),
("444","gruasatlantis.com","Gruasatlantis","Conversion Opportunity",None,"Low",
 "Colombian 24-hour towing/crane service (Bogota).",
 40,20,20,15,50,
 "cta_count_above_fold is 0; 'SOLICITAR GRUA' (request a tow) is a clear repeated CTA in the text but not counted.",
 "Not a real retail cart (towing service).","WhatsApp chat widget is present.",
 "has_email_form is true and has_contact_form is true (evidence: 'Una Cotizacion') -- a capture mechanism exists.",0,None),
("446","lispinkcakes.com","Lispinkcakes","Follow-up Opportunity",None,"Low",
 "Denver custom-cake business and baking classes.",
 40,15,20,55,50,
 "Only 1 CTA above the fold.","Not a real retail cart (custom order/classes business).",
 "A Tidio chat widget is present.",
 "has_email_form is false, has_contact_form is false, has_esp_tag is none -- no capture mechanism.",1,None),
("449","dopestorepk.com","Dopestorepk","Cart Recovery Opportunity",None,"Medium",
 "Pakistani sneaker and streetwear e-commerce brand.",
 10,40,20,20,50,
 "12 CTAs above the fold give a very clear purchase path.","A popup script is present but has_esp_tag is none, on a real 14-product catalog.",
 "WhatsApp chat widget is present.","has_email_form is true (evidence: 'Your Email') -- a capture mechanism exists.",0,None),
]

n = append_results(RESULTS)
print(f"appended {n} rows (chunk_001)")
