import sys
sys.path.insert(0, ".")
from layer3_write import append_results

# (lead_id, domain, business_name, primary, secondary, confidence, business_summary,
#  conv, cart, eng, followup, ci, ev_conv, ev_cart, ev_eng, ev_followup,
#  open_gap_count, disqualifier)
RESULTS = [
(855, "feldefel.com", "Feldefel", "Cart Recovery Opportunity", "Customer Engagement Opportunity", "medium",
 "Romanian household/cleaning-supplies WooCommerce store.",
 45, 70, 45, 40, 35,
 "has_cart=True, no ESP", "has_cart=True, has_esp_tag=none",
 "generic popup only, no chat/reviews", "no email capture form detected",
 2, None),
(856, "acisafety.co.uk", "Aci Safety", "Not a Good Fit", None, "medium",
 "UK health & safety document templates store already running Mailchimp ESP with reviews and cta_count_above_fold=12.",
 25, 25, 30, 20, 30,
 "Mailchimp ESP already live", "has_esp_tag=mailchimp",
 "reviews present, very high above-fold CTA count (12)", "email capture and ESP already wired together",
 1, "already has ESP + reviews + strong CTA presence in place"),
(857, "mousastore.com", "Mousastore", "Cart Recovery Opportunity", "Customer Engagement Opportunity", "medium",
 "Egyptian football gear/shoes WooCommerce store.",
 45, 70, 45, 35, 30,
 "has_cart=True, no ESP", "has_cart=True, has_esp_tag=none",
 "no chat, no reviews, cta_count_above_fold=1", "no email capture form detected",
 2, None),
(858, "www.n5.com.ua", "N5", "Cart Recovery Opportunity", "Follow-up Opportunity", "medium",
 "Ukrainian WooCommerce store running a discount-for-email popup with no ESP behind it.",
 50, 65, 45, 55, 40,
 "has_cart=True, no ESP despite active discount popup copy", "has_cart=True, has_esp_tag=none",
 "no chat, no reviews", "has_email_form=True, popup discount offer present, but no ESP automation",
 2, None),
(859, "zayleather.com", "Zayleather", "Not a Good Fit", None, "medium",
 "Leather jacket retailer (66 products, 8 brands) already running Mailchimp ESP and tawk chat.",
 25, 25, 30, 20, 30,
 "Mailchimp ESP + tawk chat already live", "has_esp_tag=mailchimp",
 "chat widget already present", "email capture and ESP already wired together",
 1, "already has ESP + chat stack in place"),
(860, "instylebestrating.nl", "Instylebestrating", "Follow-up Opportunity", "Cart Recovery Opportunity", "medium",
 "Dutch garden/landscaping WooCommerce store with reviews but no email capture or ESP.",
 45, 60, 45, 55, 35,
 "has_cart=True, no ESP", "has_cart=True, has_esp_tag=none",
 "reviews present but no chat/popup", "no email capture form detected despite reviews present",
 2, None),
(861, "rccgfaitharena.com", "Rccgfaitharena", "Not a Good Fit", None, "medium",
 "Church/ministry site already running Mailchimp ESP, OptinMonster popup capture, and appointment booking.",
 20, 20, 30, 15, 25,
 "Mailchimp ESP + OptinMonster popup already live", "has_esp_tag=mailchimp, has_popup_script=True (optinmonster)",
 "booking already offered, cta_count_above_fold=3", "email capture and ESP already wired together",
 1, "already has ESP + popup capture + booking stack in place"),
(862, "epoxyresinandcraftsupplies.co.ke", "Epoxyresinandcraftsupplies", "Not a Good Fit", None, "medium",
 "Kenyan epoxy/craft-supplies WooCommerce store already running Mailchimp ESP with reviews.",
 25, 25, 35, 20, 30,
 "Mailchimp ESP already live", "has_esp_tag=mailchimp",
 "reviews present", "email capture and ESP already wired together",
 1, "already has ESP + reviews stack in place"),
(863, "wellvibe.co", "Wellvibe", "Cart Recovery Opportunity", "Customer Engagement Opportunity", "medium",
 "Indian beauty/personal-care WooCommerce store (K-beauty focus).",
 45, 70, 40, 35, 30,
 "has_cart=True, no ESP", "has_cart=True, has_esp_tag=none",
 "generic popup only, no chat/reviews", "no email capture form detected",
 2, None),
(864, "rutex.space", "Rutex", "Cart Recovery Opportunity", "Follow-up Opportunity", "medium",
 "Russian artisanal textile brand (decorative pillows, silk paintings) WooCommerce store with reviews but no ESP.",
 45, 65, 45, 55, 35,
 "has_cart=True, no ESP", "has_cart=True, has_esp_tag=none",
 "reviews present but no chat/popup", "has_email_form=True but no ESP automation",
 2, None),
(865, "onagitv.com", "Onagitv", "Cart Recovery Opportunity", "Follow-up Opportunity", "medium",
 "IPTV subscription service WooCommerce site with WhatsApp chat but no ESP.",
 45, 65, 50, 55, 35,
 "has_cart=True, no ESP", "has_cart=True, has_esp_tag=none",
 "WhatsApp chat present, cta_count_above_fold=4", "has_email_form=True but no ESP automation",
 2, None),
(866, "socatres.com", "Socatres", "Insufficient Data", None, "high",
 "Hosting account suspended — no live site content to evaluate.",
 50, 50, 50, 50, 50,
 "account suspended", "no storefront exists",
 "no engagement infrastructure — not a live site", "no capture forms — not a live site",
 0, "hosting account suspended, site not live"),
(868, "d1toy.com", "D1Toy", "Not a Good Fit", None, "medium",
 "China-based toy wholesaler already running Mailchimp ESP with reviews.",
 25, 25, 30, 20, 30,
 "Mailchimp ESP already live", "has_esp_tag=mailchimp",
 "reviews present", "email capture and ESP already wired together",
 1, "already has ESP + reviews stack in place"),
(869, "supermarketgio.ro", "Supermarketgio", "Cart Recovery Opportunity", "Follow-up Opportunity", "low",
 "Romanian online supermarket delivery WooCommerce site with WhatsApp chat, product_count_visible=0 suggests thin page.",
 40, 60, 45, 55, 35,
 "has_cart=True, no ESP", "has_cart=True, has_esp_tag=none",
 "WhatsApp chat present but no reviews/popup", "has_email_form=True but no ESP automation",
 2, None),
(870, "www.unbrokn.fr", "Unbrokn", "Not a Good Fit", None, "medium",
 "French apparel brand already running Mailchimp ESP with reviews.",
 25, 25, 30, 20, 30,
 "Mailchimp ESP already live", "has_esp_tag=mailchimp",
 "reviews present", "email capture and ESP already wired together",
 1, "already has ESP + reviews stack in place"),
(871, "www.aivisionoptical.com", "Aivisionoptical", "Follow-up Opportunity", None, "medium",
 "Mobile optical/eyecare service with tawk chat, appointment booking, and reviews already live, but no lead-capture form found.",
 45, 30, 55, 60, 40,
 "has_cart=True but likely false-positive for a mobile clinical service", "product_count_visible=0",
 "chat (tawk), booking, and reviews already present", "no email or contact form detected to capture leads despite active chat/booking",
 1, None),
(872, "gamatilbod.com", "Gamatilbod", "Cart Recovery Opportunity", "Follow-up Opportunity", "low",
 "Icelandic container-sales WooCommerce store.",
 40, 60, 40, 55, 30,
 "has_cart=True, no ESP", "has_cart=True, has_esp_tag=none",
 "generic popup only, no chat/reviews", "has_email_form=True but no ESP automation",
 2, None),
(873, "www.rosita-chocolat.fr", "Rosita-Chocolat", "Cart Recovery Opportunity", "Follow-up Opportunity", "low",
 "French artisanal chocolate WooCommerce store, product_count_visible=0 suggests thin page fetched.",
 40, 60, 40, 55, 30,
 "has_cart=True, no ESP", "has_cart=True, has_esp_tag=none",
 "no chat/reviews/popup", "has_email_form=True but no ESP automation",
 2, None),
(874, "dktechnology.in", "Dktechnology", "Cart Recovery Opportunity", "Follow-up Opportunity", "medium",
 "Indian used/refurbished computer parts WooCommerce store with both email and contact forms but no ESP.",
 45, 65, 45, 55, 35,
 "has_cart=True, no ESP", "has_cart=True, has_esp_tag=none",
 "generic popup only, no chat/reviews", "has_email_form=True and has_contact_form=True but no ESP automation",
 2, None),
(875, "www.zetaeffeshop.it", "Zetaeffeshop", "Insufficient Data", None, "high",
 "Hosting account suspended — no live site content to evaluate.",
 50, 50, 50, 50, 50,
 "account suspended", "no storefront exists",
 "no engagement infrastructure — not a live site", "no capture forms — not a live site",
 0, "hosting account suspended, site not live"),
(876, "bahcehortum.com", "Bahcehortum", "Cart Recovery Opportunity", "Follow-up Opportunity", "low",
 "Turkish garden-hose WooCommerce store, product_count_visible=0 suggests thin page fetched.",
 40, 60, 40, 55, 30,
 "has_cart=True, no ESP", "has_cart=True, has_esp_tag=none",
 "generic popup only, no chat/reviews", "has_email_form=True but no ESP automation",
 2, None),
(877, "modamindfuels.com", "Modamindfuels", "Cart Recovery Opportunity", "Customer Engagement Opportunity", "medium",
 "International nootropics/supplement WooCommerce shop with cta_count_above_fold=10 but no capture form or ESP.",
 45, 70, 50, 40, 35,
 "has_cart=True, no ESP", "has_cart=True, has_esp_tag=none",
 "generic popup only, no chat/reviews despite high above-fold CTA count (10)", "no email capture form detected despite high engagement surface",
 2, None),
(878, "uprinters.in", "Uprinters", "Cart Recovery Opportunity", "Follow-up Opportunity", "low",
 "Indian custom-printing service site (also runs a job-listing section) with no capture form or ESP.",
 40, 55, 40, 50, 30,
 "has_cart=True, no ESP, thin catalog", "has_cart=True, product_count_visible=0",
 "generic popup only, no chat/reviews", "no email capture form detected for a quote/order-driven service",
 2, None),
(879, "stomec.com", "Stomec", "Follow-up Opportunity", "Cart Recovery Opportunity", "medium",
 "Tunisian precision-tooling B2B supplier ('devis gratuit' free quote model) with reviews but no lead-capture form or ESP.",
 45, 45, 45, 55, 35,
 "has_cart=True but B2B quote-request model, no ESP", "has_cart=True, has_esp_tag=none",
 "reviews present", "no email/contact form detected for a quote-request driven B2B business",
 2, None),
(880, "wetapcards.com", "Wetapcards", "Cart Recovery Opportunity", "Follow-up Opportunity", "medium",
 "Indian NFC digital business-card manufacturer with reviews, promo bar, and high above-fold CTA count (12), but no ESP.",
 55, 65, 55, 60, 40,
 "has_cart=True, has_promo_bar=True, no ESP", "has_cart=True, has_esp_tag=none",
 "reviews present, cta_count_above_fold=12", "has_email_form=True but no ESP automation",
 2, None),
(881, "www.reducerex3.ro", "Reducerex3", "Cart Recovery Opportunity", "Follow-up Opportunity", "low",
 "Romanian discount marketplace WooCommerce site with WhatsApp chat, product_count_visible=0 suggests thin page fetched.",
 40, 60, 45, 55, 30,
 "has_cart=True, no ESP", "has_cart=True, has_esp_tag=none",
 "WhatsApp chat present but no reviews/popup", "no email capture form detected despite active chat",
 2, None),
(882, "www.saturnnlgd.com", "Saturnnlgd", "Cart Recovery Opportunity", "Follow-up Opportunity", "medium",
 "Jewelry WooCommerce store (gold/silver collections) with no ESP.",
 45, 65, 40, 55, 35,
 "has_cart=True, no ESP", "has_cart=True, has_esp_tag=none",
 "no chat, no reviews, no popup", "has_email_form=True but no ESP automation",
 2, None),
(883, "vparadise.mn", "Vparadise", "Cart Recovery Opportunity", "Customer Engagement Opportunity", "medium",
 "Mongolian vape shop WooCommerce store with a sizable catalog (30 products) but only an age-gate popup, no capture form.",
 45, 70, 40, 35, 30,
 "has_cart=True, no ESP, 30 products visible", "has_cart=True, has_esp_tag=none",
 "no chat, no reviews; popup is an age gate, not capture", "no email capture form detected",
 2, None),
(884, "ngbtelecoms.com", "Ngbtelecoms", "Cart Recovery Opportunity", "Follow-up Opportunity", "low",
 "Senegalese telecom equipment WooCommerce store, product_count_visible=0 suggests thin page fetched.",
 40, 60, 40, 55, 30,
 "has_cart=True, no ESP", "has_cart=True, has_esp_tag=none",
 "no chat/reviews/popup", "has_email_form=True but no ESP automation",
 2, None),
(885, "dr-fashion.net", "Dr-Fashion", "Cart Recovery Opportunity", "Follow-up Opportunity", "medium",
 "Egyptian medical scrubs apparel WooCommerce store (20 products) with no ESP.",
 45, 65, 40, 55, 35,
 "has_cart=True, no ESP", "has_cart=True, has_esp_tag=none",
 "no chat, no reviews, no popup", "has_email_form=True but no ESP automation",
 2, None),
(886, "pnrnatural.com", "Pnrnatural", "Cart Recovery Opportunity", "Follow-up Opportunity", "low",
 "Turkish aromatherapy/natural personal-care WooCommerce store, product_count_visible=0 suggests thin page fetched.",
 40, 60, 40, 55, 30,
 "has_cart=True, no ESP", "has_cart=True, has_esp_tag=none",
 "generic popup only, no chat/reviews", "has_email_form=True and has_contact_form=True but no ESP automation",
 2, None),
(887, "nudetoneboutique.com", "Nudetoneboutique", "Not a Good Fit", None, "medium",
 "Luxury handbag/designer consignment retailer (52 products) already running Mailchimp ESP with cta_count_above_fold=15.",
 25, 25, 30, 20, 30,
 "Mailchimp ESP already live, very high above-fold CTA count (15)", "has_esp_tag=mailchimp",
 "strong above-fold CTA presence already in place", "email capture and ESP already wired together",
 1, "already has ESP + strong CTA presence in place"),
(888, "cosmopackegypt.com", "Cosmopackegypt", "Not a Good Fit", None, "medium",
 "Egyptian baby-products retailer (38 products) already running Mailchimp ESP with cta_count_above_fold=11 and an active coupon promo.",
 25, 25, 30, 20, 30,
 "Mailchimp ESP already live, active coupon promo", "has_esp_tag=mailchimp",
 "strong above-fold CTA presence already in place", "email capture and ESP already wired together",
 1, "already has ESP + strong CTA presence in place"),
(889, "videxled.ro", "Videxled", "Cart Recovery Opportunity", "Follow-up Opportunity", "low",
 "Romanian LED lighting WooCommerce store with WhatsApp chat, product_count_visible=0 suggests thin page fetched.",
 40, 60, 45, 50, 30,
 "has_cart=True, no ESP", "has_cart=True, has_esp_tag=none",
 "WhatsApp chat present but no reviews/popup capture", "no email capture form detected despite active chat",
 2, None),
(890, "boxking.co.za", "Boxking", "Cart Recovery Opportunity", "Customer Engagement Opportunity", "medium",
 "South African moving-box supplier WooCommerce store with reviews but no ESP or capture form.",
 45, 70, 45, 40, 35,
 "has_cart=True, no ESP", "has_cart=True, has_esp_tag=none",
 "reviews present but no chat/popup", "no email capture form detected",
 2, None),
(891, "goatmarine.co.uk", "Goatmarine", "Insufficient Data", None, "high",
 "Hosting account suspended — no live site content to evaluate.",
 50, 50, 50, 50, 50,
 "account suspended", "no storefront exists",
 "no engagement infrastructure — not a live site", "no capture forms — not a live site",
 0, "hosting account suspended, site not live"),
(892, "www.mystiqueerotica.com", "Mystiqueerotica", "Not a Good Fit", None, "medium",
 "Nigerian adult-products retailer already running Mailchimp ESP with an active promo bar and cta_count_above_fold=4.",
 25, 25, 30, 20, 30,
 "Mailchimp ESP already live, active promo bar", "has_esp_tag=mailchimp, has_promo_bar=True",
 "promo bar active", "email capture and ESP already wired together",
 1, "already has ESP + promo bar in place"),
(893, "tuttygarden.com.br", "Tuttygarden", "Cart Recovery Opportunity", "Customer Engagement Opportunity", "low",
 "Brazilian garden pots/planters WooCommerce store, product_count_visible=0 suggests thin page fetched.",
 40, 60, 40, 35, 30,
 "has_cart=True, no ESP", "has_cart=True, has_esp_tag=none",
 "no chat/reviews/popup", "no email capture form detected",
 2, None),
(894, "www.bellematizz.com", "Bellematizz", "Cart Recovery Opportunity", "Follow-up Opportunity", "low",
 "Portuguese fashion WooCommerce store with a very thin catalog (1 product visible).",
 35, 55, 35, 45, 25,
 "has_cart=True, no ESP, only 1 product visible", "has_cart=True, has_esp_tag=none",
 "generic popup only, no chat/reviews", "has_email_form=True but no ESP automation",
 2, None),
(895, "www.cobaltoamalfi.it", "Cobaltoamalfi", "Cart Recovery Opportunity", "Customer Engagement Opportunity", "low",
 "Italian retail WooCommerce store, product_count_visible=0 suggests thin page fetched.",
 40, 60, 40, 35, 30,
 "has_cart=True, no ESP", "has_cart=True, has_esp_tag=none",
 "generic popup only, no chat/reviews", "no email capture form detected",
 2, None),
(896, "drkailasa.com", "Drkailasa", "Cart Recovery Opportunity", "Follow-up Opportunity", "medium",
 "Indian Ayurvedic diabetes-remedy WooCommerce store with reviews but no ESP.",
 45, 65, 45, 55, 35,
 "has_cart=True, no ESP", "has_cart=True, has_esp_tag=none",
 "reviews present, cta_count_above_fold=4", "has_email_form=True but no ESP automation",
 2, None),
(897, "djurvardsbutiken.se", "Djurvardsbutiken", "Not a Good Fit", None, "medium",
 "Swedish pet-supplement retailer already running Mailchimp ESP with reviews and Klarna financing.",
 25, 25, 30, 20, 30,
 "Mailchimp ESP already live", "has_esp_tag=mailchimp",
 "reviews present", "email capture and ESP already wired together",
 1, "already has ESP + reviews stack in place"),
(898, "agencyworldinternet.com", "Agencyworldinternet", "Insufficient Data", None, "high",
 "Server returns 404 Not Found — no live site content to evaluate.",
 50, 50, 50, 50, 50,
 "404 not found", "no storefront exists",
 "no engagement infrastructure — not a live site", "no capture forms — not a live site",
 0, "page returns 404, site not live",),
(899, "globalfinelistings.com", "Globalfinelistings", "Not a Good Fit", None, "low",
 "Listings/classifieds site already running Mailchimp ESP, though page content appears thin/under construction.",
 30, 25, 30, 25, 30,
 "Mailchimp ESP tag present", "has_esp_tag=mailchimp",
 "cta_count_above_fold=2, page content thin (mostly template CSS)", "email capture and ESP already wired together",
 1, "already has ESP tag present; page content otherwise too thin to assess further"),
(900, "metbuildings.com", "Metbuildings", "Follow-up Opportunity", None, "medium",
 "US commercial steel-building manufacturer (B2B, custom quote model) with contact/email forms but no ESP.",
 45, 20, 40, 65, 40,
 "has_cart=False — B2B quote-driven business, cart recovery not applicable", "has_cart=False",
 "no chat, no reviews", "has_email_form=True and has_contact_form=True but no ESP automation for quote leads",
 1, None),
(901, "spiceofeastafrica.com", "Spiceofeastafrica", "Insufficient Data", None, "low",
 "Domain resolved but page_text is empty and platform is unknown.",
 50, 50, 50, 50, 50,
 "page_text empty", "has_cart=False (undetermined)",
 "no signals extractable", "no signals extractable",
 0, "empty/undetermined signals — cannot assess"),
(902, "agrilinkmarketplace.com", "Agrilinkmarketplace", "Follow-up Opportunity", None, "low",
 "US agricultural/construction equipment classifieds marketplace ('Post Your Ad') with no capture form or ESP.",
 40, 30, 40, 55, 35,
 "has_cart=True likely false-positive for a classifieds marketplace", "product_count_visible=0",
 "generic popup only, cta_count_above_fold=1", "no email capture form detected for a listings marketplace",
 2, None),
(903, "keytostay.com", "Keytostay", "Follow-up Opportunity", None, "medium",
 "US short-term-rental property management service with an email form but no ESP.",
 45, 20, 45, 60, 40,
 "platform=other, has_cart=False — service business, cart recovery not applicable", "has_cart=False",
 "cta_count_above_fold=3", "has_email_form=True but no ESP automation for owner-inquiry leads",
 1, None),
(904, "theimecompany.com", "Theimecompany", "Follow-up Opportunity", None, "medium",
 "US legal/medical independent-exam services business with booking already offered but no email capture form.",
 45, 30, 50, 60, 40,
 "has_cart=True likely false-positive for a legal services business", "product_count_visible=0",
 "booking already offered, cta_count_above_fold=4", "no email or contact form detected despite active booking flow",
 1, None),
(905, "thelifecareexperts.com", "Thelifecareexperts", "Follow-up Opportunity", None, "medium",
 "US life-care consulting service with high above-fold CTA count (7) but no lead-capture form or ESP.",
 45, 20, 45, 60, 35,
 "has_cart=True likely false-positive for a consulting service", "product_count_visible=4 (likely book/resource listings, not physical cart)",
 "cta_count_above_fold=7", "no email or contact form detected for a consulting-lead business",
 1, None),
(906, "fantomtakelag.tech", "Fantomtakelag", "Follow-up Opportunity", None, "low",
 "Ukrainian industrial rigging/relocation B2B service with WhatsApp chat but no email capture form.",
 40, 20, 45, 55, 35,
 "has_cart=False — B2B service business, cart recovery not applicable", "has_cart=False",
 "WhatsApp chat present", "no email capture form detected despite active chat channel",
 1, None),
(907, "wockleanmakatussin.com", "Wockleanmakatussin", "Cart Recovery Opportunity", "Follow-up Opportunity", "medium",
 "Online pharmacy/cough-syrup retailer with WhatsApp chat, reviews, and promo bar, but no ESP.",
 45, 65, 55, 60, 40,
 "has_cart=True, no ESP", "has_cart=True, has_esp_tag=none",
 "WhatsApp chat, reviews, and promo bar all present", "has_email_form=True but no ESP automation",
 2, None),
(908, "betterbuysintl.com", "Betterbuysintl", "Follow-up Opportunity", None, "medium",
 "US commodities-trading B2B service (sourcing/processing/transport) with WhatsApp chat and email form but no ESP.",
 45, 25, 45, 60, 40,
 "has_cart=True likely false-positive for a B2B trading service", "product_count_visible=0",
 "WhatsApp chat present, cta_count_above_fold=3", "has_email_form=True but no ESP automation",
 1, None),
(909, "ilm-advertiser.com", "Ilm Advertiser", "Follow-up Opportunity", None, "low",
 "US classified/advertising listing service ('Post Your Listing') with reviews but no capture form or ESP.",
 40, 25, 40, 55, 35,
 "has_cart=True likely false-positive for a listings service", "product_count_visible=0",
 "reviews present, cta_count_above_fold=2", "no email capture form detected for a listings-driven service",
 1, None),
(910, "mondaystuff.com", "Mondaystuff", "Cart Recovery Opportunity", "Follow-up Opportunity", "medium",
 "US gothic/skull-themed apparel WooCommerce store with reviews but no ESP.",
 45, 65, 45, 55, 35,
 "has_cart=True, no ESP", "has_cart=True, has_esp_tag=none",
 "reviews present but no chat/popup", "has_email_form=True but no ESP automation",
 2, None),
]

n = append_results(RESULTS)
print(f"appended {n} rows (chunk_006)")
