import sys
sys.path.insert(0, ".")
from layer3_write import append_results

RESULTS = [
("144","l-cher.com","L Cher","Cart Recovery Opportunity",None,"Low",
 "Life-coaching business selling 1:1 coaching and course products online.",
 15,35,30,15,50,
 "4 CTAs above the fold give a clear path.","Popup script and Mailchimp ESP present but not confirmed as recovery-specific.",
 "Tawk-free chat is absent but catalog is small (4 products); low relevance.","has_email_form is true with a Mailchimp ESP tag.",0,None),
("145","rymproducts.com","Rymproducts","Follow-up Opportunity","Customer Engagement Opportunity","High",
 "San Diego artisan soap and skincare bar brand.",
 55,45,70,75,50,
 "cta_count_above_fold is 0; only nav/category links visible, no clear buy button.",
 "A popup script is present but has_esp_tag is none.",
 "has_chat_widget is none across a catalog spanning 50 detected categories -- wide for a soap brand.",
 "has_email_form is false, has_contact_form is false, has_esp_tag is none -- no capture mechanism at all.",2,None),
("146","centgroup.org","Centgroup","Conversion Opportunity",None,"Low",
 "Business consulting agency offering marketing and growth consultations.",
 40,40,15,15,50,
 "Only 1 CTA above the fold on a consulting/services site.","Not a real retail cart (services business); popup present, no ESP.",
 "WhatsApp chat widget is present.","has_email_form is true (Newsletter) -- a capture mechanism exists.",0,None),
("147","snackinn.co.in","Snackinn","Follow-up Opportunity",None,"High",
 "Indian peanut butter e-commerce brand (classic and chocolate variants).",
 15,45,30,75,50,
 "4 CTAs above the fold plus a Buy-1-Get-1 promo give a clear purchase path.",
 "A popup script is present but has_esp_tag is none.",
 "has_chat_widget is none on a narrow 10-product catalog; low relevance.",
 "has_email_form is false, has_contact_form is false, has_esp_tag is none -- no capture mechanism.",1,None),
("151","spedireconunclic.com","Spedireconunclic","Follow-up Opportunity",None,"Medium",
 "Italian parcel and package shipping service (domestic and international).",
 30,20,15,65,50,
 "cta_count_above_fold is 0; 'Spedisci ora' (ship now) appears as a nav item but no clear above-fold button.",
 "Not a real product cart (shipping-quote service).","WhatsApp chat widget is present.",
 "has_email_form is false, has_contact_form is false, has_esp_tag is none -- no capture mechanism for a visitor who isn't ready to ship today.",1,None),
("156","sportsandhealth.se","Sportsandhealth","Cart Recovery Opportunity",None,"High",
 "Swedish sportswear and supplements e-commerce store.",
 35,70,55,20,50,
 "cta_count_above_fold is 0; likely a Swedish-language detector miss ('Kop').",
 "has_popup_script is false and has_esp_tag is none on a real 23-product catalog -- no recovery mechanism at all.",
 "has_chat_widget is none across men's/women's apparel, equipment, and supplements -- moderate breadth.",
 "has_email_form is true (evidence: 'Skriv in din E-post') -- a capture mechanism exists.",1,None),
("157","shop.rollerize.co.uk","Shop","Follow-up Opportunity",None,"Medium",
 "UK roller disco brand selling branded clothing alongside session bookings.",
 15,40,25,65,50,
 "4 CTAs above the fold give a clear path.","A popup script is present but has_esp_tag is none.",
 "has_chat_widget is none on a small 5-product catalog; low relevance.",
 "has_email_form is false and has_contact_form is false -- no capture form, though a WhatsApp community link is mentioned in the page text (not a chat widget).",0,None),
("164","fredzlavf.com","Fredzlavf","Customer Engagement Opportunity",None,"Medium",
 "Fashion e-commerce brand selling jewellery and sweatshirts/outerwear.",
 40,40,65,15,50,
 "2 CTAs above the fold, a modest showing.","A popup script is present but has_esp_tag is none.",
 "has_chat_widget is none across 9 categories spanning jewellery and apparel lines -- a wide catalog for a single brand.",
 "has_email_form is true and has_contact_form is true (evidence: 'Imie') -- a capture mechanism exists.",1,None),
("186","cali-nights.com","Cali Nights","Conversion Opportunity",None,"Low",
 "Los Angeles nightlife/events promoter selling event tickets.",
 40,25,25,15,50,
 "Only 2 CTAs detected ('BUY TICKETS') above the fold.","Not a real retail cart (ticketed events business).",
 "Event listings aren't a product catalog; low relevance.","has_email_form is true with an Omnisend ESP tag -- a capture mechanism exists.",0,None),
("194","desidudeinnovation.com","Desidudeinnovation","Not a Good Fit",None,"High",
 "Not determinable -- the site shows only a 'coming soon' under-construction placeholder.",
 50,50,50,50,50,
 "not determinable from available signals","not determinable from available signals","not determinable from available signals","not determinable from available signals",
 0,"Site is a 'coming soon' placeholder with no live business content."),
("195","alfurqanwelfare.org.pk","Alfurqanwelfare","Cart Recovery Opportunity",None,"Low",
 "Pakistani Islamic charity funding education for underprivileged children via Zakat donations.",
 35,30,20,20,50,
 "2 'Donate Now' CTAs are present above the fold.","has_cart is true (WooCommerce donation flow) with no popup and no ESP tag, though this framing fits a donation flow loosely.",
 "A Tawk chat widget is present.","has_email_form is true -- a capture mechanism exists.",0,None),
("196","maisonadena.fr","Maisonadena","Conversion Opportunity",None,"Low",
 "La Rochelle/Ile de Re short-term rental concierge service for property owners.",
 50,20,20,20,50,
 "cta_count_above_fold is 0 and no clear inquiry button is visible in the excerpted text.",
 "Not a real product cart (concierge service).","Not a catalog business; low relevance.",
 "has_email_form is true -- a capture mechanism exists.",0,None),
("197","floristeriaroma.cl","Floristeriaroma","Customer Engagement Opportunity",None,"Low",
 "Chilean flower shop selling bouquets for occasions (birthdays, anniversaries, condolences).",
 25,40,45,20,50,
 "cta_count_above_fold is 0; Spanish 'Agregar al carrito' likely present but not matched.",
 "A popup script is present but has_esp_tag is none, on real priced bouquets.",
 "has_chat_widget is none across a fairly wide occasion-based catalog.",
 "has_email_form is true -- a capture mechanism exists.",0,None),
("198","erosvip.net","Erosvip","Not a Good Fit",None,"High",
 "Adult escort-services listing marketplace/directory, not a conventional commerce or lead-gen business.",
 50,50,50,50,50,
 "not determinable from available signals","not determinable from available signals","not determinable from available signals","not determinable from available signals",
 0,"Adult escort-services marketplace/directory -- outside the agency's target commerce/lead-gen business model."),
("201","ecopurus.com","Ecopurus","Not a Good Fit",None,"High",
 "Not determinable -- the site shows only an 'under development' placeholder.",
 50,50,50,50,50,
 "not determinable from available signals","not determinable from available signals","not determinable from available signals","not determinable from available signals",
 0,"Site shows an 'under development' placeholder with no live business content."),
("204","handpickedbyher.com","Handpickedbyher","Customer Engagement Opportunity",None,"Medium",
 "Indian ethnic-wear e-commerce brand specializing in Chikankari kurtis and suits.",
 15,35,55,15,50,
 "8 CTAs above the fold give a clear purchase path.","An Omnisend ESP tag is present but no popup.",
 "has_chat_widget is none across 32 products spanning multiple embroidery/print styles.",
 "has_email_form is true with an Omnisend ESP tag -- a capture mechanism exists.",0,None),
("206","rabiakofficial.com","Rabiakofficial","Cart Recovery Opportunity",None,"Low",
 "Pakistani/Islamic modest-fashion e-commerce brand (abayas, hijabs, prayer wear).",
 40,40,20,20,50,
 "2 CTAs above the fold, a modest showing.","A popup script is present but has_esp_tag is none, on an 18-product catalog.",
 "WhatsApp chat widget is present.","has_email_form is true (evidence: 'Subscription Form') -- a capture mechanism exists.",0,None),
("213","aravresort.com","Aravresort","Conversion Opportunity",None,"Low",
 "Indian resort offering rooms, dining, and wedding-venue hosting.",
 45,20,20,20,50,
 "Only 1 CTA above the fold ('BOOK YOUR STAY').","Not a real retail cart (resort booking business).",
 "Not a catalog business; low relevance.","has_email_form is true -- a capture mechanism exists.",0,None),
("215","earsolutions.us","Earsolutions","Cart Recovery Opportunity",None,"Medium",
 "US hearing-aid clinic and e-commerce retailer (Phonak, Oticon, Starkey, and more brands).",
 40,40,20,20,50,
 "2 CTAs above the fold ('Call Now', 'Check Price').","has_popup_script is true but has_esp_tag is none, on a real 15-product/20-category medical device catalog.",
 "A Tawk chat widget is present.","has_email_form is true (evidence: 'Enter your email') -- a capture mechanism exists.",0,None),
("216","naturalgemsstones.com","Naturalgemsstones","Follow-up Opportunity","Cart Recovery Opportunity","High",
 "Gemstone e-commerce brand selling natural precious and semi-precious stones.",
 10,65,30,70,50,
 "16 CTAs above the fold give a very clear purchase path.",
 "has_popup_script is false and has_esp_tag is none on a real 12-product catalog -- no recovery mechanism.",
 "has_chat_widget is none but the catalog is narrow (1 category); moderate relevance.",
 "has_email_form is false, has_contact_form is false, has_esp_tag is none -- no capture mechanism on a priced gemstone catalog.",2,None),
("220","hoodprof.org","Hoodprof","Cart Recovery Opportunity",None,"Low",
 "Community library/literacy nonprofit (HoodProf) offering library cards and e-library access.",
 20,30,20,20,50,
 "3 CTAs above the fold.","has_cart is true via WooCommerce with no ESP tag, though this framing fits a library/nonprofit flow loosely.",
 "Not a retail catalog; low relevance.","has_email_form is true (evidence: 'Email Address *') -- a capture mechanism exists.",0,None),
("221","caresrgv.com","Caresrgv","Conversion Opportunity",None,"Low",
 "Patel-Desai Foundation, a charity/arts/research/engineering/science nonprofit.",
 40,30,20,20,50,
 "cta_count_above_fold is 0; 'Donate' links are present but not counted as CTAs.",
 "Not a real retail cart (nonprofit donation flow).","Not a catalog business; low relevance.",
 "has_email_form is true -- a capture mechanism exists.",0,None),
("223","shuddhiyogshala.com","Shuddhiyogshala","Customer Engagement Opportunity",None,"Low",
 "Indian yoga teacher-training school offering YTTC courses and retreats.",
 15,25,45,20,50,
 "4 CTAs above the fold give a clear path.","Not a real retail cart (course/retreat business).",
 "has_chat_widget is none across several distinct course/retreat offerings -- a moderately high-consideration training decision.",
 "has_email_form is true -- a capture mechanism exists.",0,None),
("224","imassagenyc.com","Imassagenyc","Follow-up Opportunity",None,"Medium",
 "NYC Thai medical massage spa.",
 15,20,20,60,50,
 "5 CTAs above the fold, including repeated 'Book Now' text (has_booking was not structurally matched, but the intent is visible).",
 "Not a real retail cart (spa service).","Single-service business; low relevance.",
 "has_email_form is false and has_contact_form is false -- no digital capture path for a visitor who isn't ready to book.",1,None),
("225","www.holisticcareagency.com","Holisticcareagency","Conversion Opportunity",None,"Low",
 "New Jersey home healthcare agency providing patient-centered in-home care.",
 40,15,20,15,50,
 "2 CTAs above the fold, a modest showing for a services inquiry site.",
 "Not a real retail cart (healthcare service business).","Not a catalog business; low relevance.",
 "has_email_form is true and has_contact_form is true (evidence: 'Your Name') -- a capture mechanism exists.",0,None),
("227","salvage.com.co","Salvage","Follow-up Opportunity","Cart Recovery Opportunity","Medium",
 "Colombian fashion brand selling nature-inspired women's clothing (kimonos, blouses, skirts).",
 45,65,20,70,50,
 "cta_count_above_fold is 0; Spanish 'Anadir al carrito' likely present but not matched.",
 "has_popup_script is false and has_esp_tag is none on a real clothing catalog -- no recovery mechanism.",
 "WhatsApp chat widget is present.",
 "has_email_form is false, has_contact_form is false, has_esp_tag is none -- no capture mechanism at all.",2,None),
("232","amela.lt","Amela","Customer Engagement Opportunity",None,"Low",
 "Lithuanian clothing e-commerce brand with a large social following (32k+).",
 30,40,55,20,50,
 "cta_count_above_fold is 0; likely a Lithuanian-language detector miss.",
 "A popup script is present but has_esp_tag is none.",
 "has_chat_widget is none across wide women's/men's/kids clothing categories.",
 "has_email_form is true -- a capture mechanism exists.",0,None),
("233","superpc.co.za","Superpc","Multi-Opportunity",None,"High",
 "South African PC and appliance retailer selling computer components and home appliances.",
 40,70,75,75,50,
 "2 CTAs above the fold, a weak showing for a large catalog.",
 "has_popup_script is false and has_esp_tag is none on a real 88-product catalog -- no recovery mechanism.",
 "has_chat_widget is none across a very wide catalog spanning PC components, appliances, and accessories -- a genuinely wide/complex range.",
 "has_email_form is false, has_contact_form is false, has_esp_tag is none -- no capture mechanism at all.",3,None),
("234","miogar-pem.com","Miogar Pem","Customer Engagement Opportunity",None,"Low",
 "Peruvian home-goods and footwear e-commerce store (kitchen, bedroom, shoes for the whole family).",
 30,40,55,20,50,
 "cta_count_above_fold is 0; Spanish detector miss likely.","A popup script is present but has_esp_tag is none.",
 "has_chat_widget is none across wide home/footwear categories spanning multiple age groups.",
 "has_email_form is true (evidence: 'Email *') -- a capture mechanism exists.",0,None),
("235","crystal-design.ro","Crystal Design","Customer Engagement Opportunity",None,"Low",
 "Romanian jewelry brand selling necklaces, earrings, bracelets, and rings.",
 25,30,45,15,50,
 "cta_count_above_fold is 0; Romanian detector miss likely.","A Mailchimp ESP tag and popup script are both present.",
 "has_chat_widget is none across several jewelry categories.","has_email_form is true with a Mailchimp ESP tag -- a capture mechanism exists.",0,None),
("236","twojpiernik.pl","Twojpiernik","Cart Recovery Opportunity",None,"Medium",
 "Polish gingerbread-cookie decorating courses, workshops, and kits.",
 30,65,45,20,50,
 "cta_count_above_fold is 0; Polish detector miss likely.",
 "has_popup_script is false and has_esp_tag is none on a real 13-product catalog -- no recovery mechanism.",
 "has_chat_widget is none across various course/workshop skill levels.","has_email_form is true -- a capture mechanism exists.",0,None),
("237","londonoud.com","Londonoud","Customer Engagement Opportunity",None,"High",
 "UK oud and perfume (Eau de Parfum) e-commerce brand.",
 15,40,75,20,50,
 "5 CTAs above the fold give a clear path.","A popup script is present but has_esp_tag is none.",
 "has_chat_widget is none despite the page text showing roughly 496 products across Men/Women/Unisex/Oil Range lines -- a genuinely massive fragrance catalog.",
 "has_email_form is true -- a capture mechanism exists.",1,None),
("238","santehe.com.mx","Santehe","Follow-up Opportunity",None,"Medium",
 "Mexican wellness-supplement e-commerce brand (magnesium, omega-3, MCT oil, collagen).",
 40,30,50,65,50,
 "cta_count_above_fold is 0; Spanish 'Ver mas' appears but isn't a clear add-to-cart CTA.",
 "A popup script and Mailchimp ESP tag are both present.",
 "has_chat_widget is none across two supplement brand lines (Equilibre, Forte) with moderate breadth.",
 "has_email_form is false -- no capture form was confirmed in the static markup, though a Mailchimp tag is loaded, suggesting one may exist dynamically.",1,None),
("239","zafferanoterramore.it","Zafferanoterramore","Cart Recovery Opportunity",None,"Low",
 "Italian saffron farm (Calabria) selling pure saffron pistils direct to consumer.",
 25,35,20,15,50,
 "cta_count_above_fold is 0; Italian 'Aggiungi al carrello' likely present but not matched.",
 "A Poptin exit-intent popup is present but has_esp_tag is none.",
 "WhatsApp chat widget is present.","has_email_form is true and has_contact_form is true (evidence: 'Nome') -- a capture mechanism exists.",0,None),
("240","theartikoshop.com","Theartikoshop","Customer Engagement Opportunity",None,"Low",
 "Greek handbag and accessories e-commerce brand.",
 15,40,55,20,50,
 "8 CTAs above the fold give a clear path.","A popup script is present but has_esp_tag is none.",
 "has_chat_widget is none across 19 products spanning multiple bag styles.","has_email_form is true -- a capture mechanism exists.",0,None),
("241","kunstgrasonderhoud.com","Kunstgrasonderhoud","Follow-up Opportunity",None,"Medium",
 "Dutch/Belgian artificial-grass maintenance products and machinery webshop.",
 30,40,20,65,50,
 "cta_count_above_fold is 0; Dutch 'In winkelwagen' likely present but not matched.",
 "A popup script is present but has_esp_tag is none.","WhatsApp chat widget is present.",
 "has_email_form is false, has_contact_form is false, has_esp_tag is none -- no capture mechanism.",1,None),
("244","drivelosophy.com","Drivelosophy","Customer Engagement Opportunity",None,"Low",
 "Car-enthusiast e-commerce brand selling 3D-printed model frames and automotive prints.",
 45,35,55,15,50,
 "cta_count_above_fold is 0 despite an active promo countdown; no clear buy button in the excerpt.",
 "A popup script is present but has_esp_tag is none.",
 "has_chat_widget is none across 26 products spanning multiple car brands (Ferrari, Porsche, Lamborghini).",
 "has_email_form is true and has_contact_form is true (evidence: 'Your name') -- a capture mechanism exists.",0,None),
("245","speed99rpm.in","Speed99Rpm","Follow-up Opportunity",None,"High",
 "Indian car-accessories e-commerce brand (exterior/interior upgrades).",
 10,40,20,65,50,
 "9 CTAs above the fold give a very clear purchase path.","A popup script is present but has_esp_tag is none.",
 "WhatsApp chat widget is present.","has_email_form is false, has_contact_form is false, has_esp_tag is none -- no capture mechanism.",1,None),
("246","mostradoresatumedida.com","Mostradoresatumedida","Follow-up Opportunity",None,"Medium",
 "Spanish custom furniture manufacturer specializing in reception desks and counters.",
 45,20,45,60,50,
 "cta_count_above_fold is 0 and no clear quote-request button is visible in the excerpt.",
 "Not a real retail cart (custom-manufacturing business).",
 "has_chat_widget is none across several custom furniture types (vintage industrial style).",
 "has_email_form is false, has_contact_form is false, has_esp_tag is none -- no capture mechanism for custom-order inquiries.",1,None),
("247","turnright.lt","Turnright","Follow-up Opportunity",None,"Low",
 "Lithuanian car/bike orienteering event organizer.",
 45,20,30,60,50,
 "cta_count_above_fold is 0 and no clear registration button is visible in the excerpt.",
 "Not a real retail cart (event-registration business).",
 "has_chat_widget is none across a narrow set of event types.",
 "has_email_form is false, has_contact_form is false, has_esp_tag is none -- no capture mechanism for event sign-ups.",1,None),
("248","delonial.ro","Delonial","Conversion Opportunity",None,"Low",
 "Romanian bespoke furniture workshop (made-to-order, not stock inventory).",
 45,10,25,15,50,
 "cta_count_above_fold is 0 and no clear quote-request button is visible in the excerpt.",
 "has_cart is false -- not a retail cart business (bespoke workshop).",
 "Not a catalog business; low relevance.",
 "has_email_form is true and has_contact_form is true (evidence: 'Nume') -- a capture mechanism exists.",0,None),
("249","bluefactory.ro","Bluefactory","Follow-up Opportunity","Cart Recovery Opportunity","Medium",
 "Romanian AdBlue (diesel exhaust fluid) supplier selling bulk and packaged product.",
 20,60,30,65,50,
 "cta_count_above_fold is 0, but Romanian 'Adauga in cos' (add to cart) appears repeatedly -- a detector miss, not a real absence.",
 "has_popup_script is false and has_esp_tag is none on a real priced B2B product line -- no recovery mechanism.",
 "has_chat_widget is none but the catalog is a narrow single product line; moderate relevance.",
 "has_email_form is false, has_contact_form is false, has_esp_tag is none -- no capture mechanism.",2,None),
("250","dhdpantglobalschools.com","Dhdpantglobalschools","Cart Recovery Opportunity",None,"Low",
 "Indian kindergarten/school (DHD Pant Global Schools).",
 15,25,20,20,50,
 "5 CTAs above the fold ('Enroll Now!') give a clear path.","has_cart is true via WooCommerce with no ESP tag, though this framing fits a school-enrollment flow loosely.",
 "WhatsApp chat widget is present.","has_email_form is true -- a capture mechanism exists.",0,None),
("253","danzio.in","Danzio","Cart Recovery Opportunity",None,"Low",
 "Indian genuine-leather footwear e-commerce brand.",
 40,40,20,25,50,
 "cta_count_above_fold is 0 despite an active promo bar; no clear buy button in the excerpt.",
 "A popup script is present but has_esp_tag is none, on a real 25-product catalog.",
 "WhatsApp chat widget is present.",
 "has_email_form is true (evidence: 'Username or email' -- likely a login field, but the boolean signal reads true) -- treated as a capture mechanism per the signals as detected.",0,None),
("255","marybradleywellbeing.com","Marybradleywellbeing","Conversion Opportunity",None,"Low",
 "Stress-management coach offering courses and corporate wellbeing programs.",
 40,20,15,10,50,
 "cta_count_above_fold is 0; 'Work With Me'/'Get in touch' are real CTAs in the text but not counted as buttons.",
 "Not a real retail cart (coaching/course business).","WhatsApp chat widget is present.",
 "has_email_form is true and has_contact_form is true with a Mailchimp ESP tag -- a capture mechanism exists.",0,None),
("263","myindysoul.com","Myindysoul","Conversion Opportunity",None,"Low",
 "Indian custom t-shirt and apparel e-commerce brand.",
 45,40,30,20,50,
 "Only 1 CTA above the fold despite a free-delivery promo.","A popup script is present but has_esp_tag is none.",
 "has_chat_widget is none on a moderate 10-product catalog.","has_email_form is true (newsletter signup) -- a capture mechanism exists.",0,None),
("264","jbstrainings.co.uk","Jbstrainings","Follow-up Opportunity",None,"Medium",
 "UK forklift/plant operator training provider (RTITB and AITT accredited).",
 15,15,55,60,50,
 "6 CTAs above the fold give a clear path.","Not a real retail cart (training-course business).",
 "has_chat_widget is none across several distinct forklift/plant training course types -- a moderately technical decision.",
 "has_email_form is false, has_contact_form is false, has_esp_tag is none -- no capture mechanism for course inquiries.",1,None),
("267","leader-extincteur.com","Leader Extincteur","Cart Recovery Opportunity",None,"Low",
 "French fire-safety equipment supplier (fire extinguishers).",
 25,35,20,15,50,
 "cta_count_above_fold is 0; French 'Ajouter au panier' likely present but not matched.",
 "A popup script is present but has_esp_tag is none, on a real 19-product/6-category catalog.",
 "WhatsApp chat widget is present.",
 "has_email_form is true and has_contact_form is true (a honeypot field is present, implying a real form) -- a capture mechanism exists.",0,None),
("269","insuk.lt","Insuk","Customer Engagement Opportunity","Follow-up Opportunity","Medium",
 "Lithuanian B2B construction-fastener supplier (screws, nails, wood-joint hardware).",
 40,55,70,65,50,
 "cta_count_above_fold is 0; Lithuanian detector miss likely.",
 "has_popup_script is false and has_esp_tag is none -- moderate concern given uncertain catalog depth.",
 "has_chat_widget is none across a wide range of fastener/hardware types and named brands (Wkret-Met, Schmid Schrauben) -- a B2B buyer would benefit from guidance.",
 "has_email_form is false, has_contact_form is false, has_esp_tag is none -- no capture mechanism.",2,None),
("270","mehndiwalaa.com","Mehndiwalaa","Not a Good Fit",None,"High",
 "Not determinable -- the site is an unconfigured default WordPress installation showing only the 'Hello world!' starter post.",
 50,50,50,50,50,
 "not determinable from available signals","not determinable from available signals","not determinable from available signals","not determinable from available signals",
 0,"Unconfigured default WordPress installation ('Hello world!' starter post) -- no real business content."),
("271","totitraumaunit.co.za","Totitraumaunit","Conversion Opportunity",None,"Low",
 "South African anti-violence/trauma-support nonprofit (Amanzimtoti Trauma Unit).",
 45,30,20,15,50,
 "Only 1 CTA above the fold.","Not a real retail cart (nonprofit).","Not a catalog business; low relevance.",
 "has_email_form is true with a Mailchimp ESP tag -- a capture mechanism exists.",0,None),
("279","nordlights.lt","Nordlights","Customer Engagement Opportunity",None,"High",
 "Lithuanian B2B/retail LED lighting-systems supplier.",
 35,30,70,10,50,
 "cta_count_above_fold is 0; Lithuanian detector miss likely, though a leasing/payment-plan offer is visible.",
 "An Omnisend ESP tag and popup script are both present.",
 "has_chat_widget is none across many distinct lighting system families (rail, linear, magnetic, profiles, strips, power supplies, controllers) -- a genuinely wide technical catalog.",
 "has_email_form is true and has_contact_form is true with an Omnisend ESP tag -- a capture mechanism exists.",0,None),
("280","prunanaturalmallorca.com","Prunanaturalmallorca","Follow-up Opportunity",None,"Medium",
 "Mallorca artisanal candle and home-fragrance brand.",
 35,35,20,60,50,
 "cta_count_above_fold is 0; Spanish detector miss likely.","A popup script is present but has_esp_tag is none.",
 "WhatsApp chat widget is present.",
 "has_email_form is false, has_contact_form is false, has_esp_tag is none -- no capture mechanism.",1,None),
("285","luxedesign.ma","Luxedesign","Follow-up Opportunity",None,"Medium",
 "Moroccan furniture e-commerce brand (tables, chairs, sofas, living-room furniture).",
 35,30,20,60,50,
 "cta_count_above_fold is 0; French detector miss likely, though an active spring-sale promo is visible.",
 "A popup script is present but has_esp_tag is none.","WhatsApp chat widget is present.",
 "has_email_form is false -- no capture form was confirmed in the static markup, though a Mailchimp tag is loaded, suggesting one may exist dynamically.",1,None),
("286","thambapannidesigns.com","Thambapannidesigns","Conversion Opportunity",None,"Low",
 "Digital marketing and branding design agency.",
 40,15,20,20,50,
 "2 CTAs above the fold, a modest showing for a services agency.",
 "Not a real retail cart (services agency).","Not a catalog business; low relevance.",
 "has_email_form is true (evidence: 'Email *') -- a capture mechanism exists.",0,None),
]

n = append_results(RESULTS)
print(f"appended {n} rows (chunk_000)")
