import sys
sys.path.insert(0, ".")
from layer3_write import append_results

RESULTS = [
("450","gabbyricci.com","Gabbyricci","Follow-up Opportunity",None,"Low",
 "US medical spa offering facials and anti-aging skin treatments.",
 40,15,20,55,50,
 "3 CTAs above the fold plus a grand-opening promo.","Not a real retail cart (spa service).",
 "Not a catalog business; low relevance.",
 "has_email_form is false, has_contact_form is false, has_esp_tag is none -- no capture mechanism.",1,None),
("451","glowingdwells.com","Glowingdwells","Follow-up Opportunity",None,"Low",
 "Indian home-services/estimate company (Glowing Dwells).",
 45,35,20,50,50,
 "6 CTAs above the fold give a clear path.","A popup script and Mailchimp ESP tag are both present.",
 "WhatsApp chat widget is present.",
 "has_email_form is false -- no capture form was confirmed in the static markup, though a Mailchimp tag is loaded, suggesting one may exist dynamically.",0,None),
("453","vesu.neonpanda.in","Vesu","Customer Engagement Opportunity",None,"Low",
 "Indian family entertainment center (trampoline, bowling, laser tag, VR games).",
 15,35,55,20,50,
 "9 CTAs above the fold give a clear path.","A popup script is present but has_esp_tag is none.",
 "has_chat_widget is none across a very wide range of activity types (trampoline, bowling, laser tag, VR, karting, carnival games).",
 "has_email_form is true -- a capture mechanism exists.",0,None),
("454","touchandgreet.com","Touchandgreet","Cart Recovery Opportunity",None,"Low",
 "Bangladeshi NFC digital business card e-commerce brand.",
 10,35,20,15,50,
 "11 CTAs above the fold give a very clear path.","A popup script is present but has_esp_tag is none, on a 9-product catalog.",
 "WhatsApp chat widget is present.","has_email_form is true and has_contact_form is true (evidence: 'First Name') -- a capture mechanism exists.",0,None),
("461","idglob.com","Idglob","Follow-up Opportunity","Cart Recovery Opportunity","Medium",
 "Organic and bamboo cotton T-shirt manufacturer/e-commerce brand (iDesign).",
 40,60,20,65,50,
 "2 CTAs above the fold.","has_popup_script is false and has_esp_tag is none on a real 16-product catalog -- no recovery mechanism.",
 "WhatsApp chat widget is present.",
 "has_email_form is false, has_contact_form is false, has_esp_tag is none -- no capture mechanism.",2,None),
("462","androidaudio.lt","Androidaudio","Customer Engagement Opportunity",None,"High",
 "Lithuanian car audio and multimedia electronics e-commerce brand.",
 35,40,65,20,50,
 "cta_count_above_fold is 0; Lithuanian detector miss likely.","A popup script is present but has_esp_tag is none.",
 "has_chat_widget is none across a very wide catalog (multimedia units, cameras, adapters, wiring, OBD diagnostics, dashcams, amplifiers, speakers by brand).",
 "has_email_form is true (evidence: 'El.Pastas *') -- a capture mechanism exists.",0,None),
("465","ievadeco.com","Ievadeco","Cart Recovery Opportunity",None,"Low",
 "Latvian home decor, lighting, and furniture e-commerce brand.",
 35,40,20,20,50,
 "cta_count_above_fold is 0.","A popup script is present but has_esp_tag is none.",
 "WhatsApp chat widget is present.","has_email_form is true -- a capture mechanism exists.",0,None),
("466","flamez.ca","Flamez","Follow-up Opportunity",None,"Low",
 "Canadian halal fried chicken and sandwich restaurant.",
 15,15,30,55,50,
 "5 CTAs above the fold ('Order Now') give a clear path.","Not a real retail cart (restaurant ordering).",
 "Menu categories aren't a real catalog; low relevance.",
 "has_email_form is false, has_contact_form is false, has_esp_tag is none -- no capture mechanism.",1,None),
("467","floweratelierco.com","Floweratelierco","Follow-up Opportunity",None,"Medium",
 "El Paso florist offering same-day flower delivery for occasions.",
 40,40,20,65,50,
 "Only 1 CTA above the fold.","A popup script is present but has_esp_tag is none, on a real 11-product catalog.",
 "A Tawk chat widget is present.",
 "has_email_form is false, has_contact_form is false, has_esp_tag is none -- no capture mechanism on time-sensitive flower purchases.",1,None),
("469","bigdogg.be","Bigdogg","Follow-up Opportunity",None,"Medium",
 "Belgian streetwear e-commerce brand.",
 40,55,20,60,50,
 "Only 1 CTA above the fold.","has_popup_script is false and has_esp_tag is none on a small 3-product catalog -- no recovery mechanism.",
 "has_chat_widget is none on a narrow catalog; low relevance.",
 "has_email_form is false, has_contact_form is false, has_esp_tag is none -- no capture mechanism.",1,None),
("470","linoyamitpahot.com","Linoyamitpahot","Cart Recovery Opportunity",None,"Low",
 "Israeli headscarf/tichel e-commerce brand.",
 35,30,20,15,50,
 "cta_count_above_fold is 0; Hebrew detector miss likely.","A Klaviyo ESP tag is present but no popup.",
 "A Tawk chat widget is present.","has_email_form is true with a Klaviyo ESP tag -- a capture mechanism exists.",0,None),
("472","chandigarhheights.com","Chandigarhheights","Conversion Opportunity",None,"Low",
 "Indian hotel (Chandigarh Heights) offering overnight and day-use bookings.",
 40,20,25,15,50,
 "2 CTAs above the fold.","Not a real retail cart (hotel booking business).",
 "Room amenities aren't a real catalog; low relevance.",
 "has_email_form is true with a Mailchimp ESP tag -- a capture mechanism exists.",0,None),
("473","plateriawuero.mx","Plateriawuero","Cart Recovery Opportunity",None,"Medium",
 "Mexican silver jewelry e-commerce brand (rings, earrings, chains, bracelets).",
 35,55,20,20,50,
 "cta_count_above_fold is 0; Spanish detector miss likely.","has_popup_script is false and has_esp_tag is none on a real 20-product catalog -- no recovery mechanism.",
 "WhatsApp chat widget is present.","has_email_form is true -- a capture mechanism exists.",0,None),
("474","krushnatrading.com","Krushnatrading","Follow-up Opportunity",None,"Medium",
 "Indian manufacturer of disposable-industry machinery (paper plate machines, agarbatti equipment).",
 45,40,20,65,50,
 "Only 1 CTA above the fold on a B2B machinery site.","A popup script is present but has_esp_tag is none.",
 "WhatsApp chat widget is present.",
 "has_email_form is false, has_contact_form is false, has_esp_tag is none -- no capture mechanism for B2B leads.",1,None),
("475","jnatural.com.tr","Jnatural","Follow-up Opportunity",None,"Medium",
 "Turkish natural cosmetics/skincare brand.",
 40,55,30,60,50,
 "cta_count_above_fold is 0; Turkish detector miss likely.","has_popup_script is false and has_esp_tag is none -- no recovery mechanism.",
 "has_chat_widget is none on a narrow single-line catalog.",
 "has_email_form is false, has_contact_form is false, has_esp_tag is none -- no capture mechanism.",1,None),
("479","odenpakistan.com","Odenpakistan","Customer Engagement Opportunity",None,"Low",
 "Pakistani home-appliance retailer (LED TVs, ACs, refrigerators, fans).",
 15,40,55,20,50,
 "4 CTAs above the fold give a clear path.","A popup script is present but has_esp_tag is none.",
 "has_chat_widget is none across several distinct appliance categories.",
 "has_email_form is true -- a capture mechanism exists.",0,None),
("487","sjaana.com","Sjaana","Cart Recovery Opportunity",None,"Low",
 "Pakistani perfume e-commerce brand (men's, women's, and bundle collections).",
 40,40,40,20,50,
 "2 CTAs above the fold.","A popup script is present but has_esp_tag is none.",
 "has_chat_widget is none across several bundle/collection types.",
 "has_email_form is true -- a capture mechanism exists.",0,None),
("488","wicef.com","Wicef","Follow-up Opportunity",None,"Low",
 "Kenyan venture-capital and business-consulting firm.",
 20,15,35,55,50,
 "4 CTAs above the fold.","Not a real retail cart (VC/consulting business).",
 "has_chat_widget is none across several service lines (training, consultation, investor, innovator).",
 "has_email_form is false, has_contact_form is false, has_esp_tag is none -- no capture mechanism.",1,None),
("499","chillichutney.ca","Chillichutney","Follow-up Opportunity",None,"Low",
 "Indian restaurant in Victoria, BC.",
 15,15,20,55,50,
 "5 CTAs above the fold give a clear path.","Not a real retail cart (restaurant).",
 "Not a catalog business; low relevance.",
 "has_email_form is false, has_contact_form is false, has_esp_tag is none -- no capture mechanism.",1,None),
("500","cuadrosdefutbol.com","Cuadrosdefutbol","Follow-up Opportunity",None,"Medium",
 "Spanish retro-football wall-art e-commerce brand.",
 35,40,20,60,50,
 "cta_count_above_fold is 0; Spanish detector miss likely.","A popup script is present but has_esp_tag is none.",
 "WhatsApp chat widget is present.",
 "has_email_form is false, has_contact_form is false, has_esp_tag is none -- no capture mechanism.",1,None),
("501","classroomoftraders.com","Classroomoftraders","Conversion Opportunity",None,"Low",
 "Indian stock/forex trading education academy.",
 40,25,40,20,50,
 "2 CTAs above the fold despite an active webinar promo.","Not a real retail cart (course business).",
 "has_chat_widget is none across trading and forex-signal course types.",
 "has_email_form is true -- a capture mechanism exists.",0,None),
("506","danceros.com","Danceros","Conversion Opportunity",None,"Low",
 "Online dance-course platform.",
 45,20,20,25,50,
 "Only 1 CTA above the fold.","Not a real retail cart (course business).",
 "has_chat_widget is none on a single-course focus; low relevance.",
 "has_email_form is true and has_contact_form is true, though form_evidence ('Billing Details') suggests a checkout field rather than a marketing signup.",0,None),
("510","www.allaboutmaths.co.za","Allaboutmaths","Follow-up Opportunity",None,"Low",
 "South African bilingual (Afrikaans/English) CAPS math worksheet e-commerce brand.",
 10,30,40,50,50,
 "12 CTAs above the fold give a very clear purchase path.","A Mailchimp ESP tag and popup are present.",
 "has_chat_widget is none across math test/worksheet categories.",
 "has_email_form is false -- no capture form was confirmed in the static markup, though a Mailchimp tag is loaded, suggesting one may exist dynamically.",0,None),
("511","silksense.in","Silksense","Cart Recovery Opportunity",None,"Low",
 "Indian feminine hygiene and baby-care e-commerce brand.",
 15,40,20,20,50,
 "4 CTAs above the fold give a clear path.","A popup script is present but has_esp_tag is none, on a 5-product catalog.",
 "A Tawk chat widget is present.","has_email_form is true -- a capture mechanism exists.",0,None),
("520","finfun.lt","Finfun","Cart Recovery Opportunity",None,"Low",
 "Lithuanian snacks, candy, and drinks e-commerce brand.",
 30,40,40,20,50,
 "cta_count_above_fold is 0; Lithuanian detector miss likely.","A popup script is present but has_esp_tag is none.",
 "has_chat_widget is none across several snack/drink/candy categories.",
 "has_email_form is true -- a capture mechanism exists.",0,None),
("523","mangalamghrit.com","Mangalamghrit","Cart Recovery Opportunity",None,"Low",
 "Indian traditional ghee (clarified butter) e-commerce brand.",
 15,35,20,20,50,
 "7 CTAs above the fold give a clear path.","A popup script is present but has_esp_tag is none, on a 4-product catalog.",
 "WhatsApp chat widget is present.","has_email_form is true (evidence: 'phone' field) -- a capture mechanism exists.",0,None),
("526","hycoproducts.in","Hycoproducts","Customer Engagement Opportunity",None,"Medium",
 "Indian power-equipment retailer (pressure washers, compressors, plus electronics).",
 45,40,60,25,50,
 "cta_count_above_fold is 0 despite an EMI-financing offer; no clear buy button visible in the excerpt.",
 "A popup script is present but has_esp_tag is none, on a real 46-product catalog.",
 "has_chat_widget is none across a wide, somewhat unusual mix of power tools and consumer electronics.",
 "has_email_form is true, though form_evidence ('Remember Me') suggests a login field rather than a marketing signup.",0,None),
("528","ieerg.org","Ieerg","Conversion Opportunity",None,"Low",
 "Pakistani environmental/governance research nonprofit (site still shows placeholder lorem-ipsum content).",
 45,20,30,15,50,
 "cta_count_above_fold is 0 and the visible body copy is lorem-ipsum placeholder text, suggesting an incomplete site build.",
 "Not a real retail cart (nonprofit).",
 "Event/registration categories aren't a real catalog; low relevance.",
 "has_email_form is true and has_contact_form is true (evidence: 'Fill Your Registration') -- a capture mechanism exists.",0,None),
("531","ksi-gravure.com","Ksi Gravure","Follow-up Opportunity",None,"Low",
 "French laser-engraving studio selling personalized fantasy/mythology-themed gifts.",
 40,15,40,55,50,
 "cta_count_above_fold is 0; 'Devis' (quote) is a real CTA in the text but not counted.",
 "Not a real retail cart (custom-order business).",
 "has_chat_widget is none across several themed collections (Medieval, Dragons, Fantasy, Vikings, Manga).",
 "has_email_form is false, has_contact_form is false, has_esp_tag is none -- no capture mechanism for custom-order inquiries.",1,None),
("533","dsechess.com","Dsechess","Follow-up Opportunity",None,"Low",
 "Turkish chess club/academy (sports club with chess training).",
 35,15,20,55,50,
 "cta_count_above_fold is 0.","Not a real retail cart (chess club).","WhatsApp chat widget is present.",
 "has_email_form is false, has_contact_form is false, has_esp_tag is none -- no capture mechanism.",1,None),
("546","conquer.pk","Conquer","Follow-up Opportunity","Customer Engagement Opportunity","Medium",
 "Pakistani streetwear e-commerce brand.",
 40,40,60,65,50,
 "2 CTAs above the fold, a modest showing for a 39-product catalog.","A popup script is present but has_esp_tag is none.",
 "has_chat_widget is none across a wide range of apparel categories (hoodies, essentials, oversized tees, activewear, casual wear).",
 "has_email_form is false, has_contact_form is false, has_esp_tag is none -- no capture mechanism.",2,None),
("548","knocksportspk.com","Knocksportspk","Customer Engagement Opportunity",None,"Low",
 "Pakistani cricket-equipment e-commerce brand (bats, kit bags, pads).",
 15,30,45,15,50,
 "8 CTAs above the fold give a clear path.","A Mailchimp ESP tag and popup are present.",
 "has_chat_widget is none across several cricket-gear categories.",
 "has_email_form is true with a Mailchimp ESP tag -- a capture mechanism exists.",0,None),
("550","wreckdekalb.com","Wreckdekalb","Follow-up Opportunity",None,"Low",
 "US rage-room, splatter-room, and VR escape-room entertainment venue.",
 40,15,35,55,50,
 "cta_count_above_fold is 0; 'Book your Escape Today!' is a real CTA in the text but not counted.",
 "Not a real retail cart (entertainment-venue booking).",
 "has_chat_widget is none across a few distinct activity types.",
 "has_email_form is false, has_contact_form is false, has_esp_tag is none -- no capture mechanism.",1,None),
("571","lesfleursdandochris.fr","Lesfleursdandochris","Conversion Opportunity",None,"Low",
 "French florist (Fleurs d'Andochris) with a loyalty-points program.",
 40,30,20,15,50,
 "cta_count_above_fold is 0.","A Brevo ESP tag is present but no popup.",
 "Not a wide catalog; low relevance.","has_email_form is true (evidence: 'Newsletter') with a Brevo ESP tag -- a capture mechanism exists.",0,None),
("573","zaytunaacademy.in","Zaytunaacademy","Customer Engagement Opportunity",None,"Low",
 "Indian Islamic homeschooling academy offering courses, workshops, and counselling.",
 40,20,55,15,50,
 "Only 1 CTA above the fold.","Not a real retail cart (education/counselling business).",
 "has_chat_widget is none across a wide mix of course, workshop, and counselling offerings.",
 "has_email_form is true with a Mailchimp ESP tag -- a capture mechanism exists.",0,None),
("575","durumcuisausta.com","Durumcuisausta","Follow-up Opportunity",None,"Low",
 "Turkish durum-wrap restaurant (Dalaman).",
 30,15,20,55,50,
 "cta_count_above_fold is 0; 'Siparis ver' (order now) is a real repeated CTA not counted.",
 "Not a real retail cart (restaurant).","WhatsApp chat widget is present.",
 "has_email_form is false, has_contact_form is false, has_esp_tag is none -- no capture mechanism.",1,None),
("576","sunlineracademy.com","Sunlineracademy","Conversion Opportunity",None,"Low",
 "UK vocational/interview-skills training academy.",
 40,20,35,15,50,
 "cta_count_above_fold is 0; 'Find courses' is a real CTA not counted.","Not a real retail cart (course business).",
 "has_chat_widget is none across courses, toolkit, and shop offerings.",
 "has_email_form is true with a Mailchimp ESP tag -- a capture mechanism exists.",0,None),
("581","playwell.ee","Playwell","Customer Engagement Opportunity","Cart Recovery Opportunity","High",
 "Estonian LEGO retailer.",
 35,60,80,20,50,
 "cta_count_above_fold is 0; Estonian detector miss likely.",
 "has_popup_script is false and has_esp_tag is none -- no recovery mechanism on a real LEGO catalog.",
 "has_chat_widget is none across an unusually wide LEGO theme catalog (City, Classic, Creator, Disney, Friends, Harry Potter, Jurassic World, Animal Crossing, and many more).",
 "has_email_form is true (evidence: 'Liitu uudiskirjaga') -- a capture mechanism exists.",2,None),
("584","dglive.in","Dglive","Follow-up Opportunity",None,"Low",
 "Indian digital marketing agency.",
 45,15,30,55,50,
 "Only 1 CTA above the fold.","Not a real retail cart (agency services).",
 "has_chat_widget is none across moderate service offerings.",
 "has_email_form is false, has_contact_form is false, has_esp_tag is none -- no capture mechanism.",1,None),
("594","myhappycoffeeclub.co.uk","Myhappycoffeeclub","Customer Engagement Opportunity",None,"Low",
 "UK coffee-subscription e-commerce brand.",
 40,40,55,20,50,
 "2 CTAs above the fold.","A popup script is present but has_esp_tag is none.",
 "has_chat_widget is none across a wide 32-product coffee catalog (subscription, single origin, blended, decaf).",
 "has_email_form is true -- a capture mechanism exists.",0,None),
("598","targetraderpk.com","Targetraderpk","Follow-up Opportunity",None,"Medium",
 "Pakistani household plastic-products manufacturer.",
 40,40,50,65,50,
 "2 CTAs above the fold despite a real 26-product catalog.","A popup script is present but has_esp_tag is none.",
 "has_chat_widget is none across a moderately wide household-goods catalog.",
 "has_email_form is false, has_contact_form is false, has_esp_tag is none -- no capture mechanism.",1,None),
("604","finenpick.com","Finenpick","Customer Engagement Opportunity",None,"High",
 "Bangladeshi multi-category e-commerce store (auto, electronics, sports, gifts, food, fashion, beauty, home).",
 40,40,80,20,50,
 "cta_count_above_fold is 0; Bengali detector miss likely.","A popup script is present but has_esp_tag is none.",
 "has_chat_widget is none across a massive 106-product catalog spanning nearly a dozen unrelated categories.",
 "has_email_form is true (evidence: 'Email address *Required') -- a capture mechanism exists.",0,None),
("605","moroosi.com","Moroosi","Customer Engagement Opportunity",None,"Medium",
 "Pakistani traditional/aesthetic accessories e-commerce brand ('Azadi Collectives').",
 40,30,60,55,50,
 "2 CTAs above the fold.","A Mailchimp ESP tag and popup are present.",
 "has_chat_widget is none across a wide 33-product accessory catalog.",
 "has_email_form is false -- no capture form was confirmed in the static markup, though a Mailchimp tag is loaded, suggesting one may exist dynamically.",0,None),
("610","t4obutter.com","T4Obutter","Cart Recovery Opportunity",None,"Low",
 "US natural skincare/body-butter e-commerce brand.",
 15,25,20,15,50,
 "4 CTAs above the fold give a clear path.","A Mailchimp ESP tag and popup are present.",
 "A Tidio chat widget is present.","has_email_form is true with a Mailchimp ESP tag -- a capture mechanism exists.",0,None),
("614","key-safety.com","Key Safety","Customer Engagement Opportunity",None,"Low",
 "US EHS/OSHA/DOT/ISO compliance consulting firm.",
 40,15,40,15,50,
 "2 CTAs above the fold.","Not a real retail cart (consulting service).",
 "has_chat_widget is none across several regulatory compliance service lines -- moderately technical.",
 "has_email_form is true with a Mailchimp ESP tag -- a capture mechanism exists.",0,None),
("619","pixelshield.in","Pixelshield","Cart Recovery Opportunity",None,"Medium",
 "Indian TV screen-protector e-commerce brand.",
 20,55,30,20,50,
 "3 CTAs above the fold.","has_popup_script is false and has_esp_tag is none on a real 17-product catalog -- no recovery mechanism.",
 "has_chat_widget is none on a narrow single-niche catalog.","has_email_form is true -- a capture mechanism exists.",0,None),
("620","cbiojaoude.com","Cbiojaoude","Customer Engagement Opportunity",None,"Low",
 "Candle/home-fragrance e-commerce brand.",
 10,25,30,15,50,
 "10 CTAs above the fold give a very clear path.","A Mailchimp ESP tag and popup are present.",
 "has_chat_widget is none; catalog width unclear from a gallery-style layout.",
 "has_email_form is true with a Mailchimp ESP tag -- a capture mechanism exists.",0,None),
("623","flaviorenato.com","Flaviorenato","Customer Engagement Opportunity",None,"Low",
 "Brazilian sales-training and consulting business (insurance/finance sector, award-winning).",
 40,20,40,20,50,
 "cta_count_above_fold is 0; 'LEIA MAIS' (read more) is a real CTA not counted.",
 "Not a real retail cart (consulting/training business).",
 "has_chat_widget is none across several service lines (sales performance, management, ebooks, courses).",
 "has_email_form is true -- a capture mechanism exists.",0,None),
("624","marucareindia.com","Marucareindia","Customer Engagement Opportunity",None,"Low",
 "Indian AI-powered blood-testing and health-checkup service.",
 15,25,45,20,50,
 "5 CTAs above the fold give a clear path.","Not a real retail cart (health-checkup booking).",
 "has_chat_widget is none across several medically technical checkup panels.",
 "has_email_form is true -- a capture mechanism exists.",0,None),
("625","luxxeredlight.com","Luxxeredlight","Cart Recovery Opportunity",None,"Medium",
 "US full-body red-light therapy device e-commerce brand.",
 40,55,30,20,50,
 "Only 1 CTA above the fold.","has_popup_script is false and has_esp_tag is none on a real medical-device catalog -- no recovery mechanism.",
 "has_chat_widget is none on a narrow 4-product catalog.","has_email_form is true -- a capture mechanism exists.",0,None),
("628","budsautoparts.com","Budsautoparts","Customer Engagement Opportunity",None,"High",
 "US auto-parts e-commerce store.",
 40,25,70,10,50,
 "cta_count_above_fold is 0 despite a real 24-product catalog.","A Mailchimp ESP tag and popup are present.",
 "has_chat_widget is none across a very wide auto-parts catalog (bed covers, doors, engine, exhaust, seats, interior, lighting, suspension, wheels).",
 "has_email_form is true and has_contact_form is true (evidence: 'Your name') with a Mailchimp ESP tag -- a capture mechanism exists.",0,None),
("629","myschoolformazione.it","Myschoolformazione","Conversion Opportunity",None,"Low",
 "Italian English-language school using the Callan Method.",
 40,20,20,20,50,
 "cta_count_above_fold is 0.","Not a real retail cart (language-school business).",
 "WhatsApp chat widget is present.","has_email_form is true -- a capture mechanism exists.",0,None),
("631","thesunpowerco.com","Thesunpowerco","Follow-up Opportunity",None,"Medium",
 "Indian solar-panel manufacturer (photovoltaic technology since 2018).",
 15,20,20,60,50,
 "8 CTAs above the fold give a clear path.","Not a real retail cart (B2B solar/farms business).",
 "A Tawk chat widget is present.",
 "has_email_form is false, has_contact_form is false, has_esp_tag is none -- no capture mechanism for B2B solar leads.",1,None),
("632","startkaif.ro","Startkaif","Customer Engagement Opportunity",None,"Medium",
 "Romanian shisha/hookah accessories e-commerce brand.",
 35,30,60,15,50,
 "cta_count_above_fold is 0; Romanian detector miss likely.","A Mailchimp ESP tag and popup are present.",
 "has_chat_widget is none across a wide 28-product catalog (aromas, hookahs, coals, glassware, lighters, consumables).",
 "has_email_form is true with a Mailchimp ESP tag -- a capture mechanism exists.",0,None),
("633","panoramikstocks.com","Panoramikstocks","Follow-up Opportunity",None,"Low",
 "Spanish general-merchandise e-commerce store (the page text includes a literal 'test product' listing, suggesting an incomplete or in-progress store).",
 10,40,35,60,50,
 "12 CTAs above the fold give a clear path.","A popup script is present but has_esp_tag is none.",
 "has_chat_widget is none; catalog appears unfinished/mixed (a literal 'test product' listing was observed).",
 "has_email_form is false, has_contact_form is false, has_esp_tag is none -- no capture mechanism, though the store itself may still be under construction.",1,None),
]

n = append_results(RESULTS)
print(f"appended {n} rows (chunk_002)")
