import sys
sys.path.insert(0, ".")
from layer3_write import append_results


def L(lead_id, domain, business_name, primary, confidence, summary,
      conv, cart, eng, followup, ci, ev_conv, ev_cart, ev_eng, ev_followup,
      open_gap_count, secondary=None, disqualifier=None):
    return (lead_id, domain, business_name, primary, secondary, confidence, summary,
            conv, cart, eng, followup, ci, ev_conv, ev_cart, ev_eng, ev_followup,
            open_gap_count, disqualifier)


RESULTS = [
L(1299, "starlightcustoms.co.uk", "Starlightcustoms", primary="Follow-up Opportunity", confidence="medium",
  summary="UK car-customization service with both email and contact forms but no ESP.",
  conv=45, cart=20, eng=35, followup=55, ci=30,
  ev_conv="has_cart=True likely false-positive for a custom auto-modification service", ev_cart="product_count_visible=0",
  ev_eng="cta_count_above_fold=2", ev_followup="has_email_form=True and has_contact_form=True but no ESP automation",
  open_gap_count=1),
L(1300, "peters-ict.com", "Peters-Ict", primary="Follow-up Opportunity", secondary="Cart Recovery Opportunity", confidence="medium",
  summary="Dutch IT-services business with an attached shop, WhatsApp chat, and reviews already live, but no ESP.",
  conv=45, cart=40, eng=50, followup=55, ci=35,
  ev_conv="has_cart=True but this is a B2B IT services business", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="WhatsApp chat and reviews already present", ev_followup="has_email_form=True and has_contact_form=True but no ESP automation",
  open_gap_count=2),
L(1301, "aanyatours.com", "Aanyatours", primary="Cart Recovery Opportunity", secondary="Follow-up Opportunity", confidence="medium",
  summary="Indian tour operator (18 products/packages) with WhatsApp chat and reviews already live but no ESP.",
  conv=45, cart=60, eng=50, followup=55, ci=35,
  ev_conv="has_cart=True, no ESP", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="WhatsApp chat and reviews already present, cta_count_above_fold=2", ev_followup="has_email_form=True but no ESP automation",
  open_gap_count=2),
L(1302, "rmtclinic.net", "Rmtclinic", primary="Follow-up Opportunity", confidence="low",
  summary="Massage/chiropractic/physiotherapy practitioner directory with booking and reviews already live, but no ESP.",
  conv=40, cart=25, eng=45, followup=50, ci=30,
  ev_conv="has_cart=True likely false-positive for a practitioner-listings directory", ev_cart="product_count_visible=0",
  ev_eng="booking and reviews already present, cta_count_above_fold=6", ev_followup="has_email_form=True but no ESP automation",
  open_gap_count=1),
L(1303, "oriental-queen.sk", "Oriental-Queen", primary="Cart Recovery Opportunity", secondary="Follow-up Opportunity", confidence="low",
  summary="Slovak dates (fruit) WooCommerce store with an active bulk-discount offer but no ESP.",
  conv=40, cart=55, eng=30, followup=45, ci=30,
  ev_conv="has_cart=True, no ESP", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="no chat/reviews/popup", ev_followup="has_email_form=True but no ESP automation",
  open_gap_count=2),
L(1304, "a25.fr", "A25", primary="Follow-up Opportunity", confidence="low",
  summary="French architecture/urban-design agency (B2B) with no lead-capture form or ESP.",
  conv=35, cart=20, eng=30, followup=40, ci=25,
  ev_conv="has_cart=True likely false-positive for a B2B architecture agency", ev_cart="product_count_visible=0",
  ev_eng="generic popup only, no chat/reviews", ev_followup="no email or contact form detected",
  open_gap_count=1),
L(1305, "udcfa.org", "Udcfa", primary="Follow-up Opportunity", confidence="low",
  summary="US disability-awareness non-profit with both email and contact forms and booking already offered, but no ESP.",
  conv=35, cart=20, eng=40, followup=45, ci=25,
  ev_conv="has_cart=True likely false-positive for a donation-driven non-profit", ev_cart="product_count_visible=0",
  ev_eng="booking already offered, cta_count_above_fold=3", ev_followup="has_email_form=True and has_contact_form=True but no ESP automation for donor/volunteer follow-up",
  open_gap_count=1),
L(1306, "safariasilia.com", "Safariasilia", primary="Follow-up Opportunity", confidence="low",
  summary="Tanzanian safari-tour operator with no lead-capture form or ESP.",
  conv=40, cart=20, eng=30, followup=50, ci=30,
  ev_conv="has_cart=True likely false-positive for a tour-package business", ev_cart="product_count_visible=0",
  ev_eng="no chat/reviews/popup", ev_followup="no email or contact form detected for high-value safari inquiries",
  open_gap_count=1),
L(1307, "loudncleardigital.com", "Loudncleardigital", primary="Insufficient Data", confidence="low",
  summary="Domain resolved but page_text is empty and platform is unknown.",
  conv=50, cart=50, eng=50, followup=50, ci=50,
  ev_conv="page_text empty", ev_cart="has_cart=False (undetermined)",
  ev_eng="no signals extractable", ev_followup="no signals extractable",
  open_gap_count=0, disqualifier="empty/undetermined signals — cannot assess"),
L(1308, "almohma.com", "Almohma", primary="Follow-up Opportunity", confidence="low",
  summary="UAE VAT/corporate-tax/accounting B2B firm with reviews already live but no lead-capture form or ESP.",
  conv=40, cart=20, eng=40, followup=50, ci=30,
  ev_conv="has_cart=True likely false-positive for a B2B accounting firm", ev_cart="product_count_visible=0",
  ev_eng="reviews present, cta_count_above_fold=1", ev_followup="no email or contact form detected",
  open_gap_count=1),
L(1309, "ysto.pl", "Ysto", primary="Cart Recovery Opportunity", secondary="Follow-up Opportunity", confidence="medium",
  summary="Polish collagen-supplements WooCommerce store with an active first-purchase discount but no ESP.",
  conv=45, cart=60, eng=40, followup=50, ci=35,
  ev_conv="has_cart=True, no ESP", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="active discount coupon in copy, no chat/reviews", ev_followup="has_email_form=True but no ESP automation",
  open_gap_count=2),
L(1310, "arteyjardin.mx", "Arteyjardin", primary="Follow-up Opportunity", confidence="medium",
  summary="Mexican landscaping/garden-design service with WhatsApp chat and reviews already live, but no ESP.",
  conv=45, cart=25, eng=50, followup=55, ci=35,
  ev_conv="has_cart=True likely false-positive for a landscaping-design service", ev_cart="product_count_visible=0",
  ev_eng="WhatsApp chat and reviews already present", ev_followup="has_email_form=True but no ESP automation",
  open_gap_count=1),
L(1311, "divarentacar.com", "Divarentacar", primary="Not a Good Fit", confidence="medium",
  summary="Montenegrin car-rental business already running Mailchimp ESP; note its online booking form is currently showing a 'Data form error' bug.",
  conv=25, cart=20, eng=30, followup=20, ci=30,
  ev_conv="Mailchimp ESP already live", ev_cart="has_esp_tag=mailchimp",
  ev_eng="reviews present, cta_count_above_fold=1", ev_followup="email capture and ESP already wired together (though its booking form currently errors)",
  open_gap_count=1, disqualifier="already has ESP in place"),
L(1312, "themarketsurgeon.co.za", "Themarketsurgeon", primary="Cart Recovery Opportunity", secondary="Follow-up Opportunity", confidence="medium",
  summary="South African financial-market-education/digital-products site with tawk chat but no ESP.",
  conv=45, cart=55, eng=45, followup=50, ci=35,
  ev_conv="has_cart=True, no ESP", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="tawk chat already present, cta_count_above_fold=0", ev_followup="has_email_form=True but no ESP automation",
  open_gap_count=2),
L(1313, "gazpachokitchens.com", "Gazpachokitchens", primary="Not a Good Fit", confidence="medium",
  summary="Indian modular-kitchen company already running Mailchimp ESP with WhatsApp chat and reviews.",
  conv=25, cart=15, eng=35, followup=20, ci=30,
  ev_conv="has_cart=False — custom-build B2C services business", ev_cart="has_esp_tag=mailchimp",
  ev_eng="WhatsApp chat and reviews already present", ev_followup="email capture and ESP already wired together",
  open_gap_count=1, disqualifier="already has ESP + chat + reviews stack in place"),
L(1314, "academiedudigital.com", "Academiedudigital", primary="Insufficient Data", confidence="medium",
  summary="French digital academy site whose fetched copy is dominated by raw WordPress prefetch/JSON configuration boilerplate — no readable business content extracted.",
  conv=50, cart=50, eng=50, followup=50, ci=50,
  ev_conv="page_text is JSON/prefetch boilerplate, no readable content", ev_cart="has_cart=False",
  ev_eng="no signals extractable from rendered content", ev_followup="no signals extractable from rendered content",
  open_gap_count=0, disqualifier="page content is unrendered technical boilerplate — cannot assess"),
L(1315, "concordmicro.co.mz", "Concordmicro", primary="Not a Good Fit", confidence="medium",
  summary="Mozambican microloan/finance service already running Mailchimp ESP with booking and reviews.",
  conv=20, cart=15, eng=30, followup=15, ci=25,
  ev_conv="has_cart=True likely false-positive for a financial-services business", ev_cart="has_esp_tag=mailchimp",
  ev_eng="booking and reviews already present", ev_followup="email capture and ESP already wired together",
  open_gap_count=1, disqualifier="already has ESP + booking + reviews stack in place"),
L(1316, "loomifyweb.com", "Loomifyweb", primary="Follow-up Opportunity", confidence="low",
  summary="Tunisian web-development B2B agency with no lead-capture form or ESP.",
  conv=40, cart=20, eng=30, followup=50, ci=30,
  ev_conv="has_cart=True likely false-positive for a B2B web agency", ev_cart="product_count_visible=0",
  ev_eng="no chat/reviews/popup", ev_followup="no email or contact form detected",
  open_gap_count=1),
L(1317, "supernova-iris.ro", "Supernova-Iris", primary="Not a Good Fit", confidence="medium",
  summary="Romanian iris-photography franchise already running Brevo ESP with WhatsApp chat and reviews.",
  conv=25, cart=20, eng=35, followup=20, ci=30,
  ev_conv="has_cart=True but photography-session business, ESP already live", ev_cart="has_esp_tag=brevo",
  ev_eng="WhatsApp chat and reviews already present", ev_followup="email capture and Brevo ESP already wired together",
  open_gap_count=1, disqualifier="already has ESP + chat + reviews stack in place"),
L(1318, "spiritnova.it", "Spiritnova", primary="Cart Recovery Opportunity", secondary="Customer Engagement Opportunity", confidence="low",
  summary="Italian WooCommerce store with mostly unrendered JS boilerplate in fetched copy, no ESP.",
  conv=35, cart=50, eng=30, followup=30, ci=25,
  ev_conv="has_cart=True, no ESP; page content largely unrendered JS boilerplate", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="no chat/reviews/popup", ev_followup="no email capture form detected",
  open_gap_count=2),
L(1319, "hvp.com.pl", "Hvp", primary="Follow-up Opportunity", confidence="low",
  summary="Polish Daikin HVAC installer/dealer with an email form but no ESP.",
  conv=40, cart=20, eng=30, followup=50, ci=30,
  ev_conv="has_cart=True likely false-positive for an HVAC installer/dealer", ev_cart="product_count_visible=0",
  ev_eng="no chat/reviews/popup", ev_followup="has_email_form=True but no ESP automation",
  open_gap_count=1),
L(1320, "elitegym.com.pl", "Elitegym", primary="Follow-up Opportunity", secondary="Cart Recovery Opportunity", confidence="low",
  summary="Polish gym with a small merchandise shop (cups, loungers, vouchers) but no lead-capture form or ESP.",
  conv=35, cart=40, eng=30, followup=40, ci=25,
  ev_conv="has_cart=True but this is primarily a gym-membership business", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="no chat/reviews/popup", ev_followup="no email capture form detected for membership sign-up leads",
  open_gap_count=2),
L(1321, "checkupholiday.com", "Checkupholiday", primary="Follow-up Opportunity", confidence="medium",
  summary="Turkish health-tourism/medical-travel packages business with WhatsApp chat and booking already live, but no ESP.",
  conv=45, cart=20, eng=50, followup=55, ci=35,
  ev_conv="has_cart=True likely false-positive for a medical-tourism packages business", ev_cart="product_count_visible=0",
  ev_eng="WhatsApp chat and booking already present", ev_followup="no email capture form detected despite active chat and booking",
  open_gap_count=1),
L(1322, "techforesight.co", "Techforesight", primary="Not a Good Fit", confidence="medium",
  summary="Digital-transformation consulting firm already running Mailchimp ESP with booking and reviews.",
  conv=25, cart=15, eng=30, followup=20, ci=30,
  ev_conv="has_cart=False — B2B consulting firm", ev_cart="has_esp_tag=mailchimp",
  ev_eng="booking and reviews already present, cta_count_above_fold=1", ev_followup="email capture and ESP already wired together",
  open_gap_count=1, disqualifier="already has ESP + booking + reviews stack in place"),
L(1323, "chamiauto.com", "Chamiauto", primary="Not a Good Fit", confidence="medium",
  summary="Auto body-shop business already running Mailchimp ESP with both email and contact forms.",
  conv=25, cart=20, eng=30, followup=20, ci=30,
  ev_conv="has_cart=True likely false-positive for an auto body-shop service", ev_cart="has_esp_tag=mailchimp",
  ev_eng="cta_count_above_fold=3", ev_followup="email capture and ESP already wired together",
  open_gap_count=1, disqualifier="already has ESP in place"),
L(1324, "etabulky.cz", "Etabulky", primary="Cart Recovery Opportunity", secondary="Follow-up Opportunity", confidence="low",
  summary="Czech Excel-spreadsheet templates (digital products) store with no ESP.",
  conv=40, cart=55, eng=30, followup=45, ci=30,
  ev_conv="has_cart=True, no ESP", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="no chat/reviews/popup", ev_followup="has_email_form=True but no ESP automation",
  open_gap_count=2),
L(1325, "rockwavedigital.com", "Rockwavedigital", primary="Follow-up Opportunity", secondary="Cart Recovery Opportunity", confidence="low",
  summary="Digital-marketing agency with a marketing-templates shop but no ESP.",
  conv=40, cart=40, eng=30, followup=50, ci=30,
  ev_conv="has_cart=True, no ESP", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="no chat/reviews/popup", ev_followup="has_email_form=True but no ESP automation",
  open_gap_count=2),
L(1326, "renaceseguro.com", "Renaceseguro", primary="Follow-up Opportunity", confidence="medium",
  summary="Mexican insurance agency with reviews already live but no ESP.",
  conv=40, cart=20, eng=40, followup=50, ci=30,
  ev_conv="has_cart=True likely false-positive for an insurance-services business", ev_cart="product_count_visible=0",
  ev_eng="reviews present", ev_followup="has_email_form=True but no ESP automation for insurance-quote leads",
  open_gap_count=1),
L(1327, "golfcartwld.net", "Golfcartwld", primary="Cart Recovery Opportunity", secondary="Customer Engagement Opportunity", confidence="medium",
  summary="Golf-cart parts/accessories WooCommerce store (16 products) with no capture form or ESP.",
  conv=40, cart=60, eng=35, followup=30, ci=30,
  ev_conv="has_cart=True, no ESP", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="no chat/reviews/popup, cta_count_above_fold=3", ev_followup="no email capture form detected",
  open_gap_count=2),
L(1328, "tequitamostudeuda.com", "Tequitamostudeuda", primary="Follow-up Opportunity", confidence="medium",
  summary="Spanish debt-relief law firm with WhatsApp chat and both email and contact forms, but no ESP.",
  conv=45, cart=20, eng=45, followup=60, ci=35,
  ev_conv="has_cart=False — legal-services business", ev_cart="has_cart=False",
  ev_eng="WhatsApp chat already present", ev_followup="has_email_form=True and has_contact_form=True but no ESP automation for high-value legal-consult leads",
  open_gap_count=1),
L(1329, "nandicoffee.no", "Nandicoffee", primary="Cart Recovery Opportunity", secondary="Customer Engagement Opportunity", confidence="low",
  summary="Norwegian coffee-roastery WooCommerce store, product_count_visible=0 suggests thin page fetched.",
  conv=40, cart=55, eng=30, followup=30, ci=25,
  ev_conv="has_cart=True, no ESP", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="no chat/reviews/popup", ev_followup="no email capture form detected",
  open_gap_count=2),
L(1330, "maraciju.ro", "Maraciju", primary="Follow-up Opportunity", confidence="low",
  summary="Romanian IP law firm with booking already offered but no email-capture form or ESP.",
  conv=40, cart=20, eng=40, followup=50, ci=30,
  ev_conv="has_cart=True likely false-positive for a law firm", ev_cart="product_count_visible=0",
  ev_eng="booking already offered, cta_count_above_fold=1", ev_followup="has_email_form=True but no ESP automation",
  open_gap_count=1),
L(1331, "longislandcoffee.co.uk", "Longislandcoffee", primary="Cart Recovery Opportunity", secondary="Follow-up Opportunity", confidence="low",
  summary="UK coffee-subscription WooCommerce store (8 products) with no ESP.",
  conv=40, cart=55, eng=30, followup=45, ci=30,
  ev_conv="has_cart=True, no ESP", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="generic popup only, no chat/reviews, cta_count_above_fold=1", ev_followup="has_email_form=True but no ESP automation",
  open_gap_count=2),
L(1332, "apfpoa.org.pl", "Apfpoa", primary="Follow-up Opportunity", confidence="low",
  summary="Polish charity foundation with no lead-capture form or ESP detected.",
  conv=30, cart=15, eng=25, followup=40, ci=25,
  ev_conv="has_cart=False — donation-based non-profit", ev_cart="has_cart=False",
  ev_eng="no chat/reviews/popup", ev_followup="no email or contact form detected for donor follow-up",
  open_gap_count=1),
L(1333, "eduschaler.com", "Eduschaler", primary="Follow-up Opportunity", confidence="medium",
  summary="Indian study-abroad consultancy with both email and contact forms and reviews already live, but no ESP.",
  conv=45, cart=20, eng=45, followup=55, ci=35,
  ev_conv="has_cart=True likely false-positive for a study-abroad consultancy", ev_cart="product_count_visible=0",
  ev_eng="reviews present, 'download free e-book' lead magnet offered", ev_followup="has_email_form=True and has_contact_form=True but no ESP automation",
  open_gap_count=1),
L(1334, "caverosecurity.com", "Caverosecurity", primary="Cart Recovery Opportunity", secondary="Follow-up Opportunity", confidence="low",
  summary="US security-guard training course provider with booking and reviews already live, but no ESP.",
  conv=40, cart=40, eng=45, followup=45, ci=30,
  ev_conv="has_cart=True but this is a training-course business", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="booking and reviews already present, cta_count_above_fold=2", ev_followup="no email capture form detected despite active booking flow",
  open_gap_count=2),
L(1335, "digisankalp.com", "Digisankalp", primary="Follow-up Opportunity", confidence="low",
  summary="Indian digital-marketing agency with an active promo but no ESP.",
  conv=40, cart=20, eng=35, followup=50, ci=30,
  ev_conv="has_cart=True likely false-positive for a B2B marketing agency", ev_cart="product_count_visible=0",
  ev_eng="reviews present, active promo (20% off)", ev_followup="has_email_form=True but no ESP automation",
  open_gap_count=1),
L(1336, "rishikaconsulting.com", "Rishikaconsulting", primary="Follow-up Opportunity", confidence="low",
  summary="Indian Microsoft Dynamics/Power Platform IT-consulting B2B firm with no lead-capture form or ESP.",
  conv=35, cart=20, eng=30, followup=45, ci=25,
  ev_conv="has_cart=True likely false-positive for a B2B IT consulting firm", ev_cart="product_count_visible=0",
  ev_eng="generic popup only, cta_count_above_fold=1", ev_followup="no email or contact form detected",
  open_gap_count=1),
L(1337, "egoshoes.pl", "Egoshoes", primary="Cart Recovery Opportunity", secondary="Follow-up Opportunity", confidence="low",
  summary="Polish shoe WooCommerce store with reviews already live but no ESP.",
  conv=40, cart=55, eng=35, followup=45, ci=30,
  ev_conv="has_cart=True, no ESP", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="reviews present but no chat/popup", ev_followup="has_email_form=True but no ESP automation",
  open_gap_count=2),
L(1338, "fleursdephenix.com", "Fleursdephenix", primary="Follow-up Opportunity", secondary="Cart Recovery Opportunity", confidence="low",
  summary="French energy-healing/coaching-sessions business with reviews already live but no ESP.",
  conv=40, cart=35, eng=40, followup=45, ci=30,
  ev_conv="has_cart=True but this is primarily a booking-driven wellness/coaching service", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="reviews present but no chat/popup", ev_followup="has_email_form=True but no ESP automation for session bookings",
  open_gap_count=2),
L(1339, "boulou-locations.com", "Boulou-Locations", primary="Follow-up Opportunity", confidence="medium",
  summary="French vacation-rental apartments business with both email and contact forms and booking already live, plus reviews, but no ESP.",
  conv=45, cart=20, eng=50, followup=55, ci=35,
  ev_conv="has_cart=True likely false-positive for a vacation-rental business", ev_cart="product_count_visible=0",
  ev_eng="booking and reviews already present", ev_followup="has_email_form=True and has_contact_form=True but no ESP automation",
  open_gap_count=1),
L(1340, "kidsrusclinic.sg", "Kidsrusclinic", primary="Multi-Opportunity", confidence="medium",
  summary="Singapore pediatric clinic with WhatsApp chat, booking, and an exceptionally high above-fold CTA count (16), but no ESP.",
  conv=55, cart=25, eng=60, followup=60, ci=40,
  ev_conv="has_cart=True likely false-positive for a pediatric clinic", ev_cart="product_count_visible=9 (shop tab, secondary to clinical services)",
  ev_eng="WhatsApp chat, booking, and cta_count_above_fold=16 (exceptionally high)", ev_followup="no ESP automation despite very strong engagement infrastructure",
  open_gap_count=2),
L(1341, "unflugged.in", "Unflugged", primary="Not a Good Fit", confidence="medium",
  summary="Indian music-band booking business already running Mailchimp ESP with booking already offered.",
  conv=20, cart=15, eng=30, followup=15, ci=25,
  ev_conv="has_cart=True likely false-positive for a live-performance booking business", ev_cart="has_esp_tag=mailchimp",
  ev_eng="booking already offered", ev_followup="email capture and ESP already wired together",
  open_gap_count=1, disqualifier="already has ESP + booking flow in place"),
L(1342, "mottershead.it", "Mottershead", primary="Follow-up Opportunity", secondary="Cart Recovery Opportunity", confidence="low",
  summary="Italian IT/computer-repair service with an attached shop but no ESP.",
  conv=40, cart=40, eng=30, followup=50, ci=30,
  ev_conv="has_cart=True but this is primarily a repair services business", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="no chat/reviews/popup", ev_followup="has_email_form=True but no ESP automation",
  open_gap_count=2),
L(1343, "truelogcabin.com", "Truelogcabin", primary="Cart Recovery Opportunity", secondary="Customer Engagement Opportunity", confidence="medium",
  summary="US log-cabin-kits retailer (16 products, high-value items) with an active promo but no capture form or ESP.",
  conv=45, cart=65, eng=40, followup=35, ci=35,
  ev_conv="has_cart=True, has_promo_bar=True, no ESP; high-value cart items", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="no chat/reviews/popup despite promo", ev_followup="no email capture form detected",
  open_gap_count=2),
L(1344, "bitsyncdigital.co", "Bitsyncdigital", primary="Cart Recovery Opportunity", secondary="Follow-up Opportunity", confidence="low",
  summary="Digital-marketing agency with a shop (9 products) and tawk chat but no ESP.",
  conv=40, cart=50, eng=40, followup=45, ci=30,
  ev_conv="has_cart=True, no ESP", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="tawk chat already present", ev_followup="has_email_form=True but no ESP automation",
  open_gap_count=2),
L(1345, "headwaterssurgical.com", "Headwaterssurgical", primary="Not a Good Fit", confidence="medium",
  summary="US plastic-surgery clinic already running Mailchimp ESP with booking already offered.",
  conv=20, cart=15, eng=30, followup=15, ci=25,
  ev_conv="has_cart=True likely false-positive for a clinical services provider", ev_cart="has_esp_tag=mailchimp",
  ev_eng="booking already offered, cta_count_above_fold=2", ev_followup="email capture and ESP already wired together",
  open_gap_count=1, disqualifier="already has ESP + booking flow in place"),
L(1346, "quantummuhendislik.com", "Quantummuhendislik", primary="Follow-up Opportunity", confidence="low",
  summary="Turkish HVAC/plumbing engineering B2B firm whose fetched copy includes visible lorem-ipsum placeholder text, no ESP.",
  conv=30, cart=20, eng=25, followup=35, ci=25,
  ev_conv="has_cart=True likely false-positive for a B2B engineering firm; page content includes placeholder filler text", ev_cart="product_count_visible=0",
  ev_eng="no chat/reviews/popup", ev_followup="no email or contact form detected; content quality uncertain",
  open_gap_count=1),
L(1347, "kepykla24.lt", "Kepykla24", primary="Cart Recovery Opportunity", secondary="Customer Engagement Opportunity", confidence="low",
  summary="Lithuanian bakery WooCommerce store, product_count_visible=0 suggests thin page fetched.",
  conv=40, cart=55, eng=30, followup=30, ci=25,
  ev_conv="has_cart=True, no ESP", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="generic popup only, no chat/reviews", ev_followup="no email capture form detected",
  open_gap_count=2),
L(1348, "tlasummitgroup.org", "Tlasummitgroup", primary="Follow-up Opportunity", confidence="low",
  summary="African leadership-education non-profit with Tidio chat and booking already offered, but no ESP.",
  conv=40, cart=20, eng=45, followup=50, ci=30,
  ev_conv="has_cart=True likely false-positive for an education/summit non-profit", ev_cart="product_count_visible=0",
  ev_eng="Tidio chat and booking already present, cta_count_above_fold=3", ev_followup="has_email_form=True but no ESP automation",
  open_gap_count=1),
L(1349, "firstrideon.com", "Firstrideon", primary="Cart Recovery Opportunity", secondary="Follow-up Opportunity", confidence="medium",
  summary="Kids' ride-on toy cars WooCommerce store (15 products) with Tidio chat and reviews already live but no ESP.",
  conv=45, cart=60, eng=50, followup=50, ci=35,
  ev_conv="has_cart=True, no ESP", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="Tidio chat and reviews already present, cta_count_above_fold=2", ev_followup="no email capture form detected despite active chat",
  open_gap_count=2),
L(1350, "publiclandmatters.org", "Publiclandmatters", primary="Follow-up Opportunity", confidence="low",
  summary="US land-conservation non-profit with reviews and a high above-fold CTA count (9), but no ESP.",
  conv=35, cart=20, eng=40, followup=45, ci=25,
  ev_conv="has_cart=True likely false-positive for a donation-driven non-profit", ev_cart="product_count_visible=0",
  ev_eng="reviews present, cta_count_above_fold=9", ev_followup="has_email_form=True but no ESP automation for donor follow-up",
  open_gap_count=1),
L(1351, "fizjodzieciecy.pl", "Fizjodzieciecy", primary="Follow-up Opportunity", secondary="Cart Recovery Opportunity", confidence="medium",
  summary="Polish pediatric-physiotherapy clinic with a newsletter discount offer, booking, and reviews already live, but no ESP.",
  conv=45, cart=35, eng=45, followup=55, ci=35,
  ev_conv="has_cart=True but this is a booking-driven clinical service", ev_cart="has_cart=True, has_esp_tag=none",
  ev_eng="booking and reviews already present", ev_followup="has_email_form=True (newsletter discount offer) but no ESP automation",
  open_gap_count=2),
L(1352, "nikkenmoller.com", "Nikkenmoller", primary="Follow-up Opportunity", confidence="low",
  summary="Saudi interior-design/fit-out B2B firm with WhatsApp chat and a high above-fold CTA count (6), but no lead-capture form or ESP.",
  conv=40, cart=20, eng=40, followup=50, ci=30,
  ev_conv="has_cart=False — B2B interior fit-out firm", ev_cart="has_cart=False",
  ev_eng="WhatsApp chat already present, cta_count_above_fold=6", ev_followup="no email or contact form detected despite active chat channel",
  open_gap_count=1),
L(1353, "kahunachairny.com", "Kahunachairny", primary="Not a Good Fit", confidence="medium",
  summary="Massage-chair retailer (8 products) already running Mailchimp ESP with an active promo and cta_count_above_fold=4.",
  conv=25, cart=20, eng=30, followup=20, ci=30,
  ev_conv="Mailchimp ESP already live, active promo (free shipping over $150)", ev_cart="has_esp_tag=mailchimp",
  ev_eng="cta_count_above_fold=4", ev_followup="email capture and ESP already wired together",
  open_gap_count=1, disqualifier="already has ESP + active promo in place"),
]

n = append_results(RESULTS)
print(f"appended {n} rows (chunk_013)")
